export type Kind='DSA'|'Interview'|'SQL'|'System design';
export type Question={id:string;kind:Kind;topic:string;title:string;prompt:string;difficulty:'Easy'|'Medium'|'Hard';hints:string[];logic:string;summary:string;flow:string[];rubric:string;resource:string;lessonId:string};
export type Lesson={id:string;kind:Kind;title:string;explanation:string;flow:string[];workedExample:string;pitfalls:string;resource:string};
export const questionBank:Question[]=[];export const theory:Lesson[]=[];
export function pack(kind:Kind,id:string,title:string,explanation:string,flow:string[],workedExample:string,pitfalls:string,resource:string,rows:string){
 theory.push({id,kind,title,explanation,flow,workedExample,pitfalls,resource});
 rows.trim().split('\n').filter(Boolean).forEach((line,i)=>{const [raw,prompt,insight]=line.split('|');if(!raw||!prompt||!insight)throw new Error(`Incomplete ${id} row ${i}`);const level=raw.slice(0,2),name=/^[EMH] /.test(raw)?raw.slice(2):raw;
 questionBank.push({id:`${id}-${String(i+1).padStart(2,'0')}`,kind,topic:title,title:name,prompt,difficulty:level==='E '?'Easy':level==='H '?'Hard':'Medium',hints:[kind==='System design'?`Clarify the users, scope and invariant for ${name.toLowerCase()}. Name one requirement before choosing components.`:`First identify the inputs, required output, and invariant for ${name.toLowerCase()}.`,insight,kind==='System design'?`Trace a normal operation and a failed or repeated operation through: ${flow.join(' → ')}. Topic example to adapt: ${workedExample}`:`Trace a small example through: ${flow.join(' → ')}. ${workedExample}`],logic:insight,summary:`${name}: ${insight}`,flow,lessonId:id,resource,rubric:kind==='DSA'?'Give a correct algorithm, explain its invariant, show normal/boundary/adversarial tests, and justify time and auxiliary space including preprocessing.':kind==='SQL'?'Use the supplied PostgreSQL schema. Explain join cardinality, NULL behavior, duplicate handling, boundary dates, and a relevant index; provide the query and expected result shape.':kind==='System design'?'Clarify requirements and scale; define interfaces and data ownership; explain the main flow, consistency, failure recovery, security and observability; justify one alternative.':'Explain the mechanism accurately, show a concrete example, identify a failure mode, and justify a tradeoff. Separate observed evidence from assumptions.'});});
}
