import {test} from 'node:test';
import assert from 'node:assert/strict';
import {questionBank,theory} from '../lib/bank';
import {freshProgress,toggleStep,validateProgress} from '../lib/progress';
import {quests} from '../lib/curriculum';
import {schedule,missionGroups,savePractice,submitAttempt,practicePrompt,brainstorm,dailyPractice} from '../lib/learning';
test('1000 distinct questions have full guidance and matching theory',()=>{assert.equal(questionBank.length,1000);assert.equal(new Set(questionBank.map(q=>q.id)).size,1000);assert.equal(theory.length,60);for(const [kind,count] of Object.entries({DSA:300,Interview:400,SQL:200,'System design':100})){const group=questionBank.filter(q=>q.kind===kind);assert.equal(group.length,count);assert.equal(new Set(group.map(q=>q.prompt)).size,count)}for(const q of questionBank){assert.equal(q.hints.length,3);assert.ok(q.hints.every(h=>h.length>25));assert.ok(q.logic.length>20);assert.ok(q.flow.length>=3);assert.ok(theory.some(t=>t.id===q.lessonId));assert.match(q.resource,/^https:\/\//)}assert.equal(new Set(missionGroups.flatMap(g=>g.steps)).size,7)});
test('all answer versions survive later drafts and feedback changes',()=>{let p=freshProgress();const id=questionBank[0].id;for(let n=0;n<12;n++){p=savePractice(p,id,{draft:`Attempt ${n}`});p=submitAttempt(p,id,'independent',new Date('2026-09-15T12:00:00Z'))}const first=p.practice![id].attempts[0];p=savePractice(p,id,{draft:'',attempts:p.practice![id].attempts.map(a=>a.id===first.id?{...a,feedback:'Check the empty input.'}:a)});assert.equal(p.practice![id].attempts.length,12);assert.equal(p.practice![id].attempts[0].text,'Attempt 0');assert.equal(p.practice![id].attempts[11].text,'Attempt 11');assert.equal(p.practice![id].attempts[11].feedback,'');assert.equal(p.practice![id].reviewDue,'2026-09-16');assert.match(practicePrompt(questionBank[0],first),/Attempt 0/);assert.throws(()=>submitAttempt(p,id));assert.deepEqual(validateProgress(JSON.parse(JSON.stringify(p))),p);assert.throws(()=>validateProgress({...p,practice:{[id]:{...p.practice![id],attempts:[{...first,confidence:'fake'}]}}}))});
function finish(p:ReturnType<typeof freshProgress>,day:number){for(const step of quests[day-1].steps)p=toggleStep(p,day,step.id);return p}
test('schedule distinguishes prestart, backlog, contiguous lead and personal tasks',()=>{let p=freshProgress();assert.equal(p.startDate,'2026-09-15');assert.equal(schedule(p,'2026-09-14').started,false);assert.equal(schedule(p,'2026-09-14').overdue.length,0);assert.equal(schedule(p,'2026-09-16').overdue.length,3);p=finish(p,2);assert.equal(schedule(p,'2026-09-15').ahead,0);p=finish(p,1);assert.equal(schedule(p,'2026-09-15').ahead,1);assert.equal(schedule(p,'2026-09-16').todayTasks.filter(t=>t.done).length,3);p=finish(p,3);p.todos.push({id:'one',text:'Review gap',day:1,done:false,createdAt:'',updatedAt:''});assert.equal(schedule(p,'2026-09-16').ahead,0);assert.equal(schedule(p,'2026-09-16').overdueTodos.length,1);assert.equal(schedule(freshProgress(),'2027-01-01').overdue.length,270)});
test('daily prompt is stable and all suggested questions exist across 90 days',()=>{assert.deepEqual(brainstorm('2026-09-15'),brainstorm('2026-09-15'));assert.notEqual(brainstorm('2026-09-15').id,brainstorm('2026-09-16').id);for(let n=1;n<=90;n++){const daily=dailyPractice(n);assert.equal(daily.length,4);assert.equal(new Set(daily.map(q=>q.kind)).size,4);assert.ok(daily.every(q=>questionBank.includes(q)))}});
