import {test} from 'node:test';
import assert from 'node:assert/strict';
import {freshProgress,toggleStep,saveAnswer,validateProgress} from '../lib/progress';
import {managedTasks,changePlan,moveDueTo,shiftRemaining,submitQuest} from '../lib/planning';
import {schedule} from '../lib/learning';
import {quests} from '../lib/curriculum';
const adjustment={dueDate:'2026-09-18',status:'deferred' as const,reason:'Work commitments',priority:'high' as const,minutes:45};
test('defer a mission: due dates change but answers and completion do not',()=>{let p=saveAnswer(freshProgress(),1,'concept','Keep this answer','Feedback');p=changePlan(p,'quest-1-learn',adjustment);assert.equal(p.days[1].answers.concept.text,'Keep this answer');assert.equal(p.days[1].completedAt,undefined);assert.equal(schedule(p,'2026-09-16').overdue.length,2);assert.equal(schedule(p,'2026-09-18').todayTasks.filter(t=>t.day===1).length,1);assert.equal(schedule(p,'2026-09-19').overdue.filter(t=>t.id==='quest-1-learn').length,1);assert.equal(p.planning?.items['quest-1-learn'].history.length,1);assert.deepEqual(validateProgress(JSON.parse(JSON.stringify(p))),p)});
test('skipping is recoverable and never implies mastery or a lead',()=>{let p=changePlan(freshProgress(),'quest-1-learn',{...adjustment,status:'skipped'});assert.equal(schedule(p,'2026-09-20').overdue.some(t=>t.id==='quest-1-learn'),false);assert.equal(p.days[1],undefined);assert.equal(schedule(p,'2026-09-15').ahead,0);p=changePlan(p,'quest-1-learn',{...adjustment,status:'active',dueDate:'2026-09-15',reason:'Ready to retry'});assert.equal(schedule(p,'2026-09-16').overdue.length,3);assert.equal(p.planning?.items['quest-1-learn'].history.length,2)});
test('time constrained bulk moves preserve completed work and skip records',()=>{let p=freshProgress();for(const step of quests[0].steps)p=toggleStep(p,1,step.id);p=changePlan(p,'quest-2-learn',{...adjustment,status:'skipped'});const moved=moveDueTo(p,'2026-09-18','Busy','2026-09-16');assert.equal(moved.planning?.items['quest-2-practice'].dueDate,'2026-09-18');assert.equal(moved.planning?.items['quest-3-build'],undefined);const shifted=shiftRemaining(moved,3,'Break','2026-09-16');assert.deepEqual(shifted.days,p.days);assert.equal(shifted.planning?.items['quest-2-learn'].status,'skipped');assert.equal(shifted.planning?.items['quest-2-practice'].dueDate,'2026-09-21');assert.equal(managedTasks(shifted).find(t=>t.id==='quest-1-build')?.dueDate,'2026-09-15')});
test('partial submissions retain immutable answer snapshots and truthful completion',()=>{let p=saveAnswer(freshProgress(),1,'concept','First answer','First feedback');p=submitQuest(p,1,'partial','Ran out of time',20);p=saveAnswer(p,1,'concept','Improved answer','New feedback');assert.equal(p.days[1].submissions![0].answers.concept.text,'First answer');assert.equal(p.days[1].submissions![0].answers.concept.feedback,'First feedback');assert.equal(p.days[1].completedAt,undefined);assert.throws(()=>submitQuest(p,1,'complete','',30),/every checklist/);assert.throws(()=>submitQuest(p,1,'not-started','Busy',0),/already has work/);assert.throws(()=>submitQuest(p,1,'partial','',20));for(const step of quests[0].steps)p=toggleStep(p,1,step.id);p=submitQuest(p,1,'complete','Done',90);assert.equal(p.days[1].submissions?.length,2);assert.equal(p.days[1].submissions?.[1].status,'complete');assert.deepEqual(validateProgress(JSON.parse(JSON.stringify(p))),p)});
test('old backups remain valid and malformed planning is rejected',()=>{const old=freshProgress();assert.deepEqual(validateProgress(old),old);assert.throws(()=>changePlan(freshProgress(),'quest-1-learn',{...adjustment,dueDate:'2026-02-31'}));assert.throws(()=>changePlan(freshProgress(),'quest-1-learn',{...adjustment,reason:''}));assert.throws(()=>shiftRemaining(freshProgress(),0,'Break'));assert.throws(()=>validateProgress({...freshProgress(),planning:{items:{},dailyBudget:0}}))});

