import {test} from 'node:test';
import assert from 'node:assert/strict';
import {quests,chapters} from '../lib/curriculum';
import {freshProgress,toggleStep,rateRecall,saveAnswer,validateProgress,reviewPrompt,dayDate,scheduledDay} from '../lib/progress';
test('90 unique missions, 270 complete questions and seven steps per day',()=>{assert.equal(quests.length,90);assert.equal(new Set(quests.map(q=>q.title)).size,90);assert.equal(chapters.length,13);quests.forEach((q,i)=>{assert.equal(q.day,i+1);assert.equal(q.questions.length,3);assert.equal(q.steps.length,7);assert.equal(q.steps.reduce((sum,x)=>sum+x.minutes,0),180);for(const question of q.questions){assert.ok(question.prompt?.length>20);assert.ok(question.hint?.length>20);assert.ok(question.rubric?.length>20)}})});
test('completion and retrieval schedule use real completion date; reopening removes completion',()=>{let p=freshProgress();const now=new Date('2026-09-14T12:00:00');for(const x of quests[0].steps)p=toggleStep(p,1,x.id,now);assert.ok(p.days[1].completedAt);assert.equal(p.days[1].reviewDue,'2026-09-15');p=rateRecall(p,1,'good',new Date('2026-09-15T12:00:00'));assert.equal(p.days[1].reviewDue,'2026-09-18');p=rateRecall(p,1,'again',new Date('2026-09-18T12:00:00'));assert.equal(p.days[1].reviewDue,'2026-09-19');p=toggleStep(p,1,'build',now);assert.equal(p.days[1].completedAt,undefined);assert.equal(p.days[1].reviewDue,undefined);assert.throws(()=>rateRecall(p,1,'good'))});
test('answer changes preserve all history and review prompt includes actual answer',()=>{let p=freshProgress();for(let n=0;n<9;n++)p=saveAnswer(p,1,'concept',`Answer ${n}`,'feedback');assert.equal(p.days[1].answers.concept.history.length,8);assert.ok(reviewPrompt(1,p).includes('Answer 8'));assert.ok(reviewPrompt(1,p).includes('LEARNER SUBMISSION START'));assert.deepEqual(validateProgress(JSON.parse(JSON.stringify(p))),p)});
test('malformed backups cannot introduce invalid days, checks or content',()=>{assert.throws(()=>validateProgress(null));assert.throws(()=>validateProgress({...freshProgress(),startDate:'2026-02-31'}));assert.throws(()=>validateProgress({...freshProgress(),days:{91:{}}}));let p=toggleStep(freshProgress(),1,'recall');assert.throws(()=>validateProgress({...p,days:{1:{...p.days[1],steps:['unknown']}}}));assert.throws(()=>validateProgress({...p,todos:[{id:'bad'}]}));assert.throws(()=>toggleStep(p,91,'recall'))});
test('date offsets cross month boundaries and schedule clamps to 90 days',()=>{assert.equal(dayDate('2026-09-30',1),'2026-10-01');assert.equal(scheduledDay('2026-09-14',new Date('2026-09-14T23:00:00')),1);assert.equal(scheduledDay('2026-09-14',new Date('2026-09-01T12:00:00')),1);assert.equal(scheduledDay('2026-09-14',new Date('2027-01-01T12:00:00')),90)});
