'use client';
import {useEffect,useId,useState} from 'react';
import {labTools,simulateLab,type LabFrame,type LabTool} from '@/lib/adventure-simulators';

export default function AdventureSimulator(){
 const [id,setId]=useState('map'),[filter,setFilter]=useState(''),[limit,setLimit]=useState(6);
 const tool=labTools.find(t=>t.id===id)!;
 const matches=labTools.filter(t=>`${t.name} ${t.when} ${t.methods}`.toLowerCase().includes(filter.toLowerCase()));
 return <section className="adventure"><div className="card"><span className="eyebrow">DATA STRUCTURE EXPEDITIONS</span><h2>Choose a tool. Change the input. Follow the explorer.</h2><p>{labTools.length} additional simulators. Learn the decision behind the technique, then return to your own solution.</p><label>Find a technique<input value={filter} onChange={e=>{setFilter(e.target.value);setLimit(6)}} placeholder="Map, tree, XOR, sorting…"/></label><div className="adventure-grid">{matches.slice(0,limit).map(t=><button className="secondary" key={t.id} aria-pressed={id===t.id} onClick={()=>setId(t.id)}><span aria-hidden="true">{t.emoji}</span><strong>{t.name}</strong></button>)}</div>{matches.length>limit&&<button className="secondary" onClick={()=>setLimit(n=>n+6)}>Show more expeditions ({matches.length-limit} remaining)</button>}{!labTools.some(t=>`${t.name} ${t.when} ${t.methods}`.toLowerCase().includes(filter.toLowerCase()))&&<p>No match. Try a data structure or method name.</p>}</div><Expedition key={id} tool={tool}/></section>;
}
function Expedition({tool:t}:{tool:LabTool}){
 const [input,setInput]=useState(t.example),[goal,setGoal]=useState(t.goal),[frames,setFrames]=useState(()=>simulateLab(t.id,t.example,t.goal)),[step,setStep]=useState(0),[playing,setPlaying]=useState(false),[error,setError]=useState(''),[prediction,setPrediction]=useState('');
 useEffect(()=>{if(!playing)return;if(step>=frames.length-1){setPlaying(false);return}const timer=setTimeout(()=>setStep(i=>i+1),1300);return()=>clearTimeout(timer)},[playing,step,frames.length]);
 function load(text=input,param=goal){try{const next=simulateLab(t.id,text,param);setFrames(next);setStep(0);setPlaying(false);setInput(text);setGoal(param);setError('')}catch(e){setError(e instanceof Error?e.message:'Check your input.')}}
 const f=frames[step],hasGoal=['map','set','bfs','dfs','window','pointers'].includes(t.id);
 return <><section className="card"><span className="eyebrow">{t.emoji} YOUR MISSION</span><h2>{t.name}</h2><p><strong>Choose it when:</strong> {t.when}</p><p><strong>Methods:</strong> <code>{t.methods}</code></p><form onSubmit={e=>{e.preventDefault();load()}} className="adventure-form"><label>{['bfs','dfs','union'].includes(t.id)?'Undirected edges (0–9)':t.id==='trie'?'Words':t.id==='dp'?'Number of steps':'Input values'}<input maxLength={300} value={input} onChange={e=>setInput(e.target.value)}/></label>{hasGoal&&<label>{t.id==='window'?'Window size':['bfs','dfs'].includes(t.id)?'Start vertex':['map','set'].includes(t.id)?'Lookup value':'Target'}<input value={goal} onChange={e=>setGoal(e.target.value)} type="number" step="1"/></label>}<button className="primary">Launch expedition</button><button type="button" className="secondary" onClick={()=>load(t.example,t.goal)}>Reset example</button></form>{error&&<p role="alert" className="error-text">{error} The previous valid walkthrough remains below.</p>}<label>Predict before playing (scratch only)<input maxLength={500} value={prediction} onChange={e=>setPrediction(e.target.value)} placeholder="I think the result will be… because…"/></label><small>Simulator inputs and this scratch prediction reset when switching tools. Use the practice journal to keep an attempt.</small></section>
 <section className="card"><div className="adventure-step"><span key={step} className="adventure-explorer" aria-hidden="true">{t.emoji}</span><div><small>Checkpoint {step+1} / {frames.length}</small><h3>{f.action}</h3></div></div><StatePicture frame={f} heap={t.id==='heap'} tree={['tree','trie'].includes(t.id)}/><p aria-live="polite">{f.why}</p><h4>Memory / variables</h4><pre>{f.memory}</pre>{f.result!==undefined&&<><h4>Return value</h4><pre>{f.result}</pre></>}<div className="button-row"><button className="secondary" disabled={step===0} onClick={()=>{setPlaying(false);setStep(i=>i-1)}}>← Back</button><button className="primary" onClick={()=>{if(step===frames.length-1)setStep(0);setPlaying(v=>!v)}}>{playing?'Pause':'▶ Play'}</button><button className="secondary" disabled={step===frames.length-1} onClick={()=>{setPlaying(false);setStep(i=>i+1)}}>Next →</button><button className="secondary" onClick={()=>{setPlaying(false);setStep(0)}}>Restart</button></div><label>Jump to checkpoint<input type="range" min={0} max={frames.length-1} value={step} onChange={e=>{setPlaying(false);setStep(Number(e.target.value))}}/></label></section>
 <section className="card"><h3>Take this into your interview</h3><p><strong>Cost:</strong> {t.cost}</p><p><strong>Watch out:</strong> {t.trap}</p><details><summary>Read the algorithm sketch</summary><pre>{t.code}</pre><small>Teaching snippets show the core operation; names such as Node, merge, nums, and head refer to the structures explained above. This does not execute submitted code.</small></details><p>Explain: “I chose this because ___. The state I maintain is ___. A boundary case is ___. Its time and space costs are ___.”</p></section>{['map','set','stack','queue'].includes(t.id)&&<MethodBench key={t.id} kind={t.id}/>}
 </>;
}
function StatePicture({frame:f,heap,tree}:{frame:LabFrame;heap:boolean;tree:boolean}){
 const marker=useId().replace(/:/g,'');const edges=f.edges??(heap?f.items.slice(1).map((_,i)=>[Math.floor(i/2),i+1] as [number,number]):[]);
 if(!edges.length)return <div className="adventure-cells">{f.items.length?f.items.map((v,i)=><div className={f.active===i?'active':''} key={i}><small>slot {i}</small><strong>{v}</strong></div>):<p>Empty structure</p>}</div>;
 const width=640;let height=Math.max(250,Math.min(600,f.items.length*26));
 let positions:{x:number;y:number}[]=[];
 if(tree||heap){
  const indegree=f.items.map(()=>0);for(const [,b] of edges)indegree[b]++;
  const roots=indegree.flatMap((n,i)=>n===0?[i]:[]),depth=f.items.map(()=>0),queue=[...roots];
  for(let h=0;h<queue.length;h++)for(const [a,b] of edges)if(a===queue[h]){depth[b]=depth[a]+1;queue.push(b)}
  const levels=Math.max(...depth)+1;height=Math.max(250,levels*90+40);
  positions=f.items.map(()=>({x:0,y:0}));
  for(let d=0;d<levels;d++){
   const row=depth.flatMap((n,i)=>n===d?[i]:[]);
   if(tree)row.sort((a,b)=>f.items[a].localeCompare(f.items[b],undefined,{numeric:true}));
   row.forEach((i,j)=>positions[i]={x:(j+1)*width/(row.length+1),y:40+d*90});
  }
 }else{const radius=Math.min(width/2-65,height/2-45),cx=width/2,cy=height/2;
 positions=f.items.map((_,i)=>({x:cx+radius*Math.cos(i/f.items.length*Math.PI*2-Math.PI/2),y:cy+radius*Math.sin(i/f.items.length*Math.PI*2-Math.PI/2)}));}
 return <div className="adventure-diagram"><svg viewBox={`0 0 ${width} ${height}`} role="img" aria-label={`Node connections. ${edges.map(([a,b])=>`${f.items[a]} points to ${f.items[b]}`).join('; ')}`}><defs><marker id={marker} markerWidth="7" markerHeight="7" refX="20" refY="3.5" orient="auto"><path d="M0,0 L7,3.5 L0,7" fill="currentColor"/></marker></defs>{edges.map(([a,b],i)=><line key={i} x1={positions[a].x} y1={positions[a].y} x2={positions[b].x} y2={positions[b].y} markerEnd={`url(#${marker})`}/>)}{positions.map((pos,i)=><g key={i} className={f.active===i?'active':''}><circle cx={pos.x} cy={pos.y} r={24}/><text x={pos.x} y={pos.y+5} textAnchor="middle">{f.items[i]}</text><text className="node-index" x={pos.x} y={pos.y+40} textAnchor="middle">node {i}</text></g>)}</svg><small>Arrows show references (graph edges are treated as undirected by BFS/DFS). Node positions are for readability, not memory addresses.</small></div>;
}
function MethodBench({kind}:{kind:string}){
 const [key,setKey]=useState('apple'),[value,setValue]=useState('3'),[pairs,setPairs]=useState<[string,string][]>([]),[items,setItems]=useState<string[]>([]),[output,setOutput]=useState('Choose a method.');
 const operations=kind==='map'?['set','get','has','delete','clear','keys','values','entries','size']:kind==='set'?['add','has','delete','clear','values','size']:kind==='stack'?['push','pop','peek','clear','size']:['enqueue','dequeue','peek','clear','size'];
 function apply(op:string){const map=new Map(pairs),set=new Set(items),list=[...items];let result:unknown;
  if(kind==='map'){switch(op){case 'set':map.set(key,value);result='Map updated';break;case 'get':result=map.get(key);break;case 'has':result=map.has(key);break;case 'delete':result=map.delete(key);break;case 'clear':map.clear();result='Map cleared';break;case 'keys':result=[...map.keys()];break;case 'values':result=[...map.values()];break;case 'entries':result=[...map];break;case 'size':result=map.size;}if(map.size>20){setOutput('Maximum 20 entries in this playground.');return}setPairs([...map]);}
  else if(kind==='set'){switch(op){case 'add':set.add(key);result='Set updated';break;case 'has':result=set.has(key);break;case 'delete':result=set.delete(key);break;case 'clear':set.clear();result='Set cleared';break;case 'values':result=[...set];break;case 'size':result=set.size;}if(set.size>20){setOutput('Maximum 20 values.');return}setItems([...set]);}
  else{switch(op){case 'push':case 'enqueue':result=list.push(key);break;case 'pop':result=list.pop();break;case 'dequeue':result=list.shift();break;case 'peek':result=kind==='stack'?list.at(-1):list[0];break;case 'clear':list.length=0;result='Cleared';break;case 'size':result=list.length;}if(list.length>20){setOutput('Maximum 20 values.');return}setItems(list)}setOutput(`${op}: ${JSON.stringify(result)??'undefined'}`);
 }
 return <section className="card"><h3>🧰 Method playground</h3><p>Try individual operations. Keys and values here are strings. This scratch playground is not saved.</p><div className="adventure-form"><label>Key / value<input value={key} maxLength={50} onChange={e=>setKey(e.target.value)}/></label>{kind==='map'&&<label>Associated value<input value={value} maxLength={50} onChange={e=>setValue(e.target.value)}/></label>}</div><div className="button-row">{operations.map(op=><button className="secondary" key={op} onClick={()=>apply(op)}>{op}{op==='size'?'': '()'}</button>)}</div><pre aria-live="polite">{output}</pre><pre>{JSON.stringify(kind==='map'?pairs:items,null,2)}</pre>{kind==='queue'&&<small>This small method demo uses shift() for clarity; the queue expedition above demonstrates an indexed O(1) dequeue.</small>}</section>;
}
