'use client';
import {useEffect,useState} from 'react';
import {arrayExamples,compareArrayApproaches,type ArrayExample,type ArrayTrack} from '@/lib/array-foundations';
import {useStudio,Field,Attempts,copyText} from './studio/StudioContext';

const tracks:{id:ArrayTrack;title:string;emoji:string;keeps:string;when:string;methods:string}[]=[
 {id:'loop',title:'1 · Plain loops',emoji:'🚶',keeps:'Current index, a few variables, and any required output.',when:'Start here to understand the problem. Scans, transforms and running totals often need only a loop.',methods:'for, for…of, while, nums[i], length, push()'},
 {id:'set',title:'2 · Set membership',emoji:'🚪',keeps:'Distinct values: has this appeared before?',when:'Use for membership, uniqueness, intersections and visited values when counts/indices are unnecessary.',methods:'new Set(), add(value), has(value), delete(value), clear(), size, [...set]'},
 {id:'map',title:'3 · Map associations',emoji:'🗃️',keeps:'Key → associated information, such as a count or index.',when:'Use when the question asks how many, where, or which group a value belongs to.',methods:'new Map(), set(key,value), get(key), has(key), delete(key), clear(), size, entries()'},
];
const stretch=new Set(['map-pair-count','map-subarray-count','map-longest-sum','map-window-count','set-consecutive','set-missing-positive']);
const pretty=(v:unknown)=>JSON.stringify(v,null,2);
export default function ArrayFoundations(){
 const {get}=useStudio();const [track,setTrack]=useState<ArrayTrack>('loop'),[selected,setSelected]=useState('loop-sum'),[query,setQuery]=useState(''),[filter,setFilter]=useState('All'),[limit,setLimit]=useState(6);
 const chosen=arrayExamples.find(x=>x.id===selected)!,guide=tracks.find(t=>t.id===track)!;
 const trackExamples=arrayExamples.filter(x=>x.track===track),isLast=selected===trackExamples.at(-1)?.id;
 const nextLabel=isLast?(track==='loop'?'Continue to Set →':track==='set'?'Continue to Map →':'Return to loop foundations →'):'Next example →';
 const filtered=arrayExamples.filter(x=>x.track===track&&`${x.title} ${x.task} ${x.reason}`.toLowerCase().includes(query.toLowerCase())&&(filter==='All'||(filter==='Reviewed'?get(`array-${x.id}`).fields.reviewed==='yes':get(`array-${x.id}`).fields.reviewed!=='yes')));
 function chooseTrack(id:ArrayTrack){setTrack(id);setSelected(arrayExamples.find(x=>x.track===id)!.id);setLimit(6);setQuery('');setFilter('All')}
 return <div className="adventure array-foundations"><section className="card"><span className="eyebrow">START DSA HERE · ARRAYS FIRST</span><h2>One array. Different tools. Understand the choice.</h2><p><strong>60 worked examples:</strong> 20 loops, 20 Set, 20 Map. Start with 3–5 small examples per session and explain each one before moving on. More examples help only when you can transfer the pattern to a new input.</p><div className="array-learning-route">{tracks.map(t=><button key={t.id} className="secondary" aria-pressed={track===t.id} onClick={()=>chooseTrack(t.id)}><span aria-hidden="true">{t.emoji}</span><strong>{t.title}</strong><small>{arrayExamples.filter(x=>x.track===t.id&&get(`array-${x.id}`).fields.reviewed==='yes').length}/20 self-reviewed</small></button>)}</div><div className="array-basics"><h3>Before you begin</h3><p><code>[2,7,11]</code> has indices <code>0,1,2</code> and length <code>3</code>. A value is not its index. A loop visits values; Map and Set usually still need a loop to fill or inspect them.</p><p><strong>Array.map(callback)</strong> transforms an array. <strong>new Map()</strong> creates a key/value collection. They are different tools despite the similar name.</p><p>Unless stated otherwise, numeric lessons use finite integers. “Expected O(n)” for Map/Set uses the usual average hash-lookup model, not a worst-case guarantee from JavaScript. <code>n</code>/<code>m</code> denote input lengths; <code>k</code> denotes distinct values unless a window size is specified.</p></div></section>
 <ComparisonLab/>
 <section className="card"><h2>{guide.emoji} {guide.title} · 20 worked examples</h2><p><strong>What it remembers:</strong> {guide.keeps}</p><p><strong>When to choose it:</strong> {guide.when}</p><p><strong>Tools:</strong> <code>{guide.methods}</code></p><div className="adventure-form"><label>Find an example<input value={query} onChange={e=>{setQuery(e.target.value);setLimit(6)}} placeholder="duplicates, Two Sum, count…"/></label><label>Progress<select value={filter} onChange={e=>{setFilter(e.target.value);setLimit(6)}}>{['All','Unreviewed','Reviewed'].map(x=><option key={x}>{x}</option>)}</select></label></div><div className="adventure-grid">{filtered.slice(0,limit).map(x=><button className="secondary" key={x.id} aria-pressed={selected===x.id} onClick={()=>setSelected(x.id)}><small>{stretch.has(x.id)?'Stretch · return after basics':'Foundation / pattern'}{get(`array-${x.id}`).fields.reviewed==='yes'?' · ✓ Reviewed':''}</small><strong>{x.title}</strong><span className="array-example-preview">{JSON.stringify(x.input)}</span></button>)}</div>{!filtered.length&&<p>No matching examples. Change your search or progress filter.</p>}{filtered.length>limit&&<button className="secondary" onClick={()=>setLimit(n=>n+6)}>Show more ({filtered.length-limit} remaining)</button>}</section>
 <ExampleRoom key={chosen.id} example={chosen} nextLabel={nextLabel} next={()=>{if(isLast){chooseTrack(track==='loop'?'set':track==='set'?'map':'loop');return}setSelected(trackExamples[trackExamples.findIndex(x=>x.id===selected)+1].id)}}/>
 </div>;
}
function ExampleRoom({example:x,next,nextLabel}:{example:ArrayExample;next:()=>void;nextLabel:string}){
 const {get,patch,submit,notice}=useStudio();const id=`array-${x.id}`,record=get(id);
 const [hints,setHints]=useState(false),[reveal,setReveal]=useState(false),[stage,setStage]=useState(0),[playing,setPlaying]=useState(false);
 const story=[['Read the contract',x.task],['Choose what to remember',x.reason],['Trace the given example',x.hint],['Check the result',`Expected return value: ${pretty(x.expected)}`]];
 useEffect(()=>{if(!playing)return;if(stage===story.length-1){setPlaying(false);return}const timer=setTimeout(()=>setStage(n=>n+1),1800);return()=>clearTimeout(timer)},[playing,stage,story.length]);
 return <><section className="card"><span className="eyebrow">WORKED EXAMPLE · {x.track.toUpperCase()}</span><h2>{x.title}</h2><p>{x.task}</p><div className="array-io"><div><h3>Given input</h3><pre>{pretty(x.input)}</pre></div><div><h3>Your prediction</h3><Field id={id} name="prediction" label="What should this return, and why?" rows={3}/></div></div><Field id={id} name="solution" label="Your own code / pseudocode before revealing the solution"/><div className="button-row"><button className="primary" onClick={()=>{if(!get(id).fields.solution?.trim()){notice('Write your attempt first. Incomplete reasoning is okay.');return}patch(id,{question:x.task,title:x.title,input:pretty(x.input),track:x.track});submit(id,'Array solution attempt',hints?1:0)}}>Save my attempt</button><button className="secondary" onClick={()=>setHints(v=>!v)}>{hints?'Hide hint':'Give me a hint'}</button><button className="secondary" onClick={()=>{setPlaying(false);setReveal(v=>!v)}}>{reveal?'Hide reference':'Reveal worked solution'}</button></div>{hints&&<p className="adventure-callout">{x.hint}</p>}
 {reveal&&<><h3>Expected output</h3><pre>{pretty(x.expected)}</pre><h3>Reference JavaScript</h3><pre>{x.code}</pre><p><strong>Why this approach:</strong> {x.reason}</p><p><strong>Time:</strong> {x.time} · <strong>Space:</strong> {x.space}</p><p><strong>Common mistake:</strong> {x.trap}</p><div className="array-story-track" aria-hidden="true"><span style={{left:`${stage/3*100}%`}}>🎒</span></div><div className="adventure-route">{story.map(([label],i)=><button className="secondary" key={label} aria-pressed={stage===i} onClick={()=>{setPlaying(false);setStage(i)}}>{i+1}. {label}</button>)}</div><p className="adventure-callout" aria-live="polite">{story[stage][1]}</p><div className="button-row"><button className="secondary" disabled={!stage} onClick={()=>{setPlaying(false);setStage(n=>n-1)}}>← Back</button><button className="primary" onClick={()=>{if(stage===3)setStage(0);setPlaying(v=>!v)}}>{playing?'Pause':'▶ Walk me through it'}</button><button className="secondary" disabled={stage===3} onClick={()=>{setPlaying(false);setStage(n=>n+1)}}>Next →</button></div><small>This is a narrated worked example. Your submitted code is saved but not executed or graded.</small></>}
 </section><section className="card"><h3>Make the pattern yours</h3><Field id={id} name="notes" label="Change one input. Explain why you chose loops, Map, or Set." placeholder="Try an empty array, repeated values, negative numbers, or no match. English or Hinglish is fine."/><label>My current confidence<select value={record.fields.confidence||'learning'} onChange={e=>patch(id,{confidence:e.target.value})}><option value="learning">Still learning</option><option value="assisted">Solved with help</option><option value="independent">Explained and solved independently</option></select></label><div className="button-row"><button className="secondary" aria-pressed={record.fields.reviewed==='yes'} onClick={()=>patch(id,{reviewed:record.fields.reviewed==='yes'?'no':'yes'})}>{record.fields.reviewed==='yes'?'✓ Reviewed — reopen':'Mark self-reviewed'}</button><button className="secondary" onClick={()=>copyText(`Act as my beginner DSA tutor. Compare my approach with the return-value contract. Give one hint before a full solution. Do not treat saved code as verified.\nExample: ${x.title}\nTask: ${x.task}\nInput: ${pretty(x.input)}\nMy work: ${pretty(get(id).fields)}`,notice)}>Copy question + my work as prompt</button><button className="primary" onClick={next}>{nextLabel}</button></div><Attempts id={id}/></section></>;
}
export function ComparisonLab(){
 const [text,setText]=useState('2,7,11,15'),[target,setTarget]=useState('9'),[mode,setMode]=useState<'duplicates'|'pair'>('pair'),[loaded,setLoaded]=useState({nums:[2,7,11,15],target:9,mode:'pair' as 'duplicates'|'pair'}),[error,setError]=useState('');
 function load(raw=text,goal=target,kind=mode){try{const tokens=raw.trim()?raw.split(',').map(x=>x.trim()):[];if(tokens.some(x=>!/^[-+]?\d+$/.test(x)))throw Error('Use comma-separated whole numbers, without empty entries.');if(kind==='pair'&&!goal.trim())throw Error('Enter a target.');const nums=tokens.map(Number),n=kind==='duplicates'?0:Number(goal);for(const t of tracks)compareArrayApproaches(nums,n,kind,t.id);setLoaded({nums,target:n,mode:kind});setText(raw);setTarget(String(n));setMode(kind);setError('')}catch(e){setError(e instanceof Error?e.message:'Check your input.')}}
 return <section className="card"><span className="eyebrow">SAME INPUT · SAME QUESTION · THREE APPROACHES</span><h2>See the extra memory replace repeated searching.</h2><p>For a fair comparison, all three panels return the same <strong>Boolean</strong>. Two Sum that returns <strong>indices</strong> is a separate worked example in the loop and Map tracks. A Set alone does not preserve indices.</p><form className="adventure-form" onSubmit={e=>{e.preventDefault();load()}}><label>Question<select value={mode} onChange={e=>setMode(e.target.value as typeof mode)}><option value="pair">Does a target-sum pair exist?</option><option value="duplicates">Does any value repeat?</option></select></label><label>Array<input maxLength={120} value={text} onChange={e=>setText(e.target.value)}/></label>{mode==='pair'&&<label>Target<input type="number" step="1" value={target} onChange={e=>setTarget(e.target.value)}/></label>}<button className="primary">Compare approaches</button></form>{error&&<p className="error-text" role="alert">{error} The last valid comparison stays below.</p>}<div className="button-row"><button className="secondary" onClick={()=>load('3,3','6','pair')}>Same value, different indices</button><button className="secondary" onClick={()=>load('1,2,3,4,5','20','pair')}>No pair</button><button className="secondary" onClick={()=>load('4,1,2,4','0','duplicates')}>Duplicate</button><button className="secondary" onClick={()=>load('','0',mode)}>Empty array</button></div><p><strong>Loaded question:</strong> {loaded.mode==='pair'?`Pair sum ${loaded.target}`:'Repeated value'} · input <code>{JSON.stringify(loaded.nums)}</code></p><div className="array-comparison">{tracks.map(t=><CompareWalk key={`${t.id}-${JSON.stringify(loaded)}`} nums={loaded.nums} target={loaded.target} mode={loaded.mode} track={t.id}/>)}</div><small>Counts describe this implementation’s pair comparisons or has() calls, not measured runtime or equivalent CPU instructions. Map also performs maintenance lookups not counted here. Map/Set use additional storage and average-lookup assumptions.</small></section>;
}
function CompareWalk({nums,target,mode,track}:{nums:number[];target:number;mode:'duplicates'|'pair';track:ArrayTrack}){
 const result=compareArrayApproaches(nums,target,mode,track),[step,setStep]=useState(0),[play,setPlay]=useState(false),f=result.frames[step],guide=tracks.find(t=>t.id===track)!;
 useEffect(()=>{if(!play)return;if(step===result.frames.length-1){setPlay(false);return}const t=setTimeout(()=>setStep(n=>n+1),1000);return()=>clearTimeout(t)},[play,step,result.frames.length]);
 return <article><h3>{guide.emoji} {track==='loop'?'Nested loops':track==='map'?'Map':'Set'}</h3><p>{track==='loop'?'Worst O(n²), O(1) auxiliary space':'Expected O(n), O(n) auxiliary space'}</p><div className="array-mini-cells">{nums.map((n,i)=><span className={f.active.includes(i)?'active':''} key={i}><small>{i}</small><b>{n}</b></span>)}</div><p className="array-live-step" aria-live="polite">{f.action}</p><pre>{f.memory}</pre><div className="button-row"><button className="secondary" aria-label={`Previous ${track} step`} disabled={!step} onClick={()=>{setPlay(false);setStep(n=>n-1)}}>←</button><button className="secondary" onClick={()=>{if(step===result.frames.length-1)setStep(0);setPlay(v=>!v)}}>{play?'Pause':'Play'}</button><button className="secondary" aria-label={`Next ${track} step`} disabled={step===result.frames.length-1} onClick={()=>{setPlay(false);setStep(n=>n+1)}}>→</button></div><small>Step {step+1}/{result.frames.length}</small>{step===result.frames.length-1&&<p><strong>Result: {String(result.result)}</strong><br/>{result.checks} {track==='loop'?'pair checks':'main membership checks'} · {result.stored} stored lookup entries</p>}</article>;
}
