'use client';
import {cartoonLessons} from '@/lib/cartoon-lessons';
import {useRouteQuery,updateRouteQuery,routePage} from '@/lib/workspace-location';
import CartoonPlayer from './CartoonPlayer';
import Pagination from './Pagination';
import {useStudio} from './studio/StudioContext';

export default function CartoonClassroom(){
 const query=useRouteQuery(),movie=query.get('movie'),search=query.get('search')||'',category=query.get('category')||'All',selected=cartoonLessons.find(l=>l.id===movie),{get,read}=useStudio();
 const filtered=cartoonLessons.filter(l=>(category==='All'||l.category===category)&&`${l.title} ${l.category} ${l.why}`.toLowerCase().includes(search.toLowerCase())),page=Math.min(Math.max(1,Math.ceil(filtered.length/12)),routePage(query.get('page')));
 if(selected)return <div className="cartoon-classroom"><div className="cartoon-controls"><button className="secondary" onClick={()=>updateRouteQuery({movie:null})}>← All cartoon stories</button><button className="secondary" onClick={()=>read(`cartoon-${selected.id}`)}>Open in Commute · notes & screenshots</button><span>{selected.category}</span></div><h2>{selected.title}</h2><CartoonPlayer key={selected.id} lesson={selected}/></div>;
 return <div className="cartoon-classroom"><section className="card cartoon-welcome"><span className="eyebrow">Small stories. Real developer concepts.</span><h2>Learn with Pip, your curious robot guide</h2><p>{cartoonLessons.length} original animated stories. First understand the simple picture, then connect it to code. Predict, watch, explain, and take a captioned video with you.</p><p>SQL, DSA, JavaScript, React, system design, OOP, .NET, Python, Docker, cloud, Linux, AI and communication.</p></section>{movie&&!selected&&<p role="status">That story was not found. Choose one below.</p>}<div className="cartoon-filters"><label>Find a concept<input type="search" value={search} placeholder="Try Redis, queue, closure…" onChange={e=>updateRouteQuery({search:e.target.value,page:null},true)}/></label><label>Topic<select value={category} onChange={e=>updateRouteQuery({category:e.target.value,page:null})}><option>All</option>{[...new Set(cartoonLessons.map(l=>l.category))].map(c=><option key={c}>{c}</option>)}</select></label></div><div className="cartoon-grid">{filtered.slice((page-1)*12,page*12).map(l=><article key={l.id} className="card cartoon-tile"><span className={`cartoon-world cartoon-world-${l.world}`} aria-hidden="true">{{table:'▦',city:'⇄',queue:'→',stack:'▤',tree:'⑂',array:'[ ]',stage:'✦',factory:'⚙'}[l.world]}</span><small>{l.category} · {l.scenes.length} scenes</small><h3>{l.title}</h3><p>{l.why}</p><small>{get(`cartoon-${l.id}`).attempts.length?`${get(`cartoon-${l.id}`).attempts.length} saved learning checkpoints`:'New story · about 3 minutes with practice'}</small><a className="secondary" href={`/cartoons/?movie=${encodeURIComponent(l.id)}`} onClick={e=>{if(e.ctrlKey||e.metaKey||e.shiftKey||e.altKey)return;e.preventDefault();updateRouteQuery({movie:l.id});window.scrollTo({top:0,behavior:'auto'})}}>Watch & explore →</a></article>)}</div>{!filtered.length&&<div className="card"><p>No stories match this search.</p><button className="secondary" onClick={()=>updateRouteQuery({search:null,category:null,page:null})}>Clear filters</button></div>}<Pagination page={page} total={filtered.length} pageSize={12} label="Cartoon stories" onChange={page=>{updateRouteQuery({page});document.querySelector('.cartoon-filters')?.scrollIntoView({block:'start'})}}/></div>;
}
