'use client';
import {COACH_SETTINGS,readCoachPack} from '@/lib/auto-coach';
import {useStudio,Field,Attempts} from './studio/StudioContext';
import CartoonPlayer from './CartoonPlayer';
import TopicChat from './TopicChat';

export function CoachAISettings(){
 const {get,patch}=useStudio(),settings=get(COACH_SETTINGS).fields;
 return <section className="card"><span className="eyebrow">OPTIONAL · GEMINI CONNECTION</span><h3>Flexible feedback after each answer</h3><p>First add <code>GEMINI_API_KEY</code> to Supabase → Edge Functions → Secrets, apply the setup SQL, and deploy the function. Never paste your key into this page or chat.</p><a className="secondary" href="/auto-coach-setup.md" download>Download the one-time setup guide</a><p>Enabling this sends the submission, question and previous-answer excerpt to Google. Free-tier content may be used to improve Google products; omit private work code. Quotas apply. Use an unbilled Google project if you want to stay within the free tier.</p><label className="auto-toggle"><input type="checkbox" checked={settings.aiAuto==='yes'} onChange={e=>patch(COACH_SETTINGS,{aiAuto:e.target.checked?'yes':'no'})}/>Send new submissions to Gemini automatically</label><label className="auto-toggle"><input type="checkbox" checked={settings.research==='yes'} onChange={e=>patch(COACH_SETTINGS,{research:e.target.checked?'yes':'no'})}/>Fetch a matching official documentation page when available</label><p className="muted">Local follow-ups must also be enabled above. Existing packs are not sent automatically. App limits: 10 requests per account and 100 across the project per UTC day. Provider limits may be lower. There is no paid-model fallback.</p><a href="https://ai.google.dev/gemini-api/docs/pricing" target="_blank" rel="noreferrer">Gemini pricing and data-use details →</a></section>;
}
export default function CoachAIControls({id}:{id:string}){
 const {get,patch,submit,notice}=useStudio(),r=get(id),settings=get(COACH_SETTINGS).fields,ai=readCoachPack(r.fields.aiPack),responseId=`auto-ai-response-${id.slice(10)}`;
 function request(){patch(id,{cloudStatus:'pending',requestId:crypto.randomUUID(),research:settings.research==='yes'?'yes':'no',cloudError:''});notice('AI request queued. The local lesson and original answer are kept.')}
 return <><section className="card"><span className="eyebrow">OPTIONAL · A SECOND EXPLANATION</span><h3>AI tutor feedback</h3>{ai?<><p>Generated with Gemini · {new Date(ai.createdAt).toLocaleString()}. AI feedback can be wrong; verify the code and reasoning.</p><ul>{ai.observations.map((x,i)=><li key={i}>{x}</li>)}</ul><h4>Your AI follow-up</h4><p>{ai.challenge}</p><Field id={responseId} name="answer" label="My AI follow-up answer"/><details><summary>Hint</summary><p>{ai.hint}</p></details><details><summary>Watch the AI-generated cartoon</summary><CartoonPlayer key={ai.createdAt} lesson={{...ai.lesson,id:`${id}-ai`}}/></details><button className="primary" onClick={()=>{if(!get(responseId).fields.answer?.trim()){notice('Write your answer first.');return}submit(responseId,'AI follow-up · self-reviewed')}}>Save follow-up answer</button><Attempts id={responseId}/>{ai.sources.length?<div><h4>Documentation fetched for this explanation</h4>{ai.sources.map(s=><p key={s.url}><a href={s.url} target="_blank" rel="noreferrer">{new URL(s.url).hostname}{new URL(s.url).pathname}</a><small> · Retrieved {new Date(s.checkedAt).toLocaleString()}</small></p>)}<small>Sources informed generation; they do not independently verify every AI claim.</small></div>:<p className="muted">No fresh web reference was available for this response.</p>}</>:<><p>Send this submission and the previous-answer excerpt to Gemini for feedback, a new challenge, reference code and a cartoon storyboard. Your key stays on the server. Free-tier data may be used to improve Google products.</p>{r.fields.cloudStatus==='pending'?<p role="status">Generating… You can continue studying. The result will be saved to this account.</p>:<button className="secondary" onClick={request}>{r.fields.cloudStatus==='failed'?'Retry sending to Gemini':'Send this answer to Gemini'}</button>}{r.fields.cloudError&&<p role="alert">{r.fields.cloudError}</p>}<p><a href="/auto-coach-setup.md" download>Download connection instructions</a></p></>}</section>{readCoachPack(r.fields.pack)&&<TopicChat id={id} pack={readCoachPack(r.fields.pack)!}/>}</>;
}
