'use client';
import {useState} from 'react';
import {makeSpeakingPlan,readSpeakingPlan,speakingRecommendation,speakingTracks,type SpeakingTrack} from '@/lib/communication-coach';
import {saveCommunication,validateProgress,hasCommunicationRep,type Progress} from '@/lib/progress';
import {blankStudio} from '@/lib/studio-state';
import {LearningProgressBar} from './ProgressOverview';
import Pagination from './Pagination';
const trackLabels={balanced:'All areas · balanced rotation',interview:'Interview answers',workplace:'Workplace English',everyday:'Everyday conversations'};
export default function CommunicationPractice({p,day,commit,notice,openDay}:{p:Progress;day:number;commit:(p:Progress)=>void;notice:(s:string)=>void;openDay:(day:number)=>void}){
 const id=`communication-coach-${day}`,record=p.studio?.[id]||blankStudio(),fields=record.fields,plan=readSpeakingPlan(fields.plan),finished=fields.sessionStatus==='submitted',recommendation=speakingRecommendation(p),[historyPage,setHistoryPage]=useState(1);
 const track=speakingTracks.includes(fields.track as SpeakingTrack)?fields.track as SpeakingTrack:'balanced',minutes=[5,10,20].includes(Number(fields.minutes))?Number(fields.minutes):10,audience=fields.audience||'Private rehearsal',variant=Number(fields.variant)||0,preview=plan||makeSpeakingPlan(p,day,track,minutes,audience,variant),log=p.communication?.[day],reps=Object.values(p.communication||{}).filter(hasCommunicationRep).length;
 function write(changes:Record<string,string>){const at=new Date().toISOString(),next={...p,updatedAt:at,studio:{...p.studio,[id]:{...record,fields:{...fields,...changes},updatedAt:at}}};try{validateProgress(next);commit(next)}catch(e){notice(e instanceof Error?e.message:'Could not save this change.')}}
 function submit(){if(!plan||finished)return;if(!fields.answer?.trim()||!fields.improvement?.trim()){notice('Add what you said and one improvement before submitting. Private rehearsal counts.');return}if(!fields.confidenceAfter||!fields.outcome){notice('Choose your confidence and session outcome.');return}if(record.attempts.length>=200){notice('Export your saved work before adding more than 200 attempts for this day.');return}const at=new Date().toISOString(),snapshot={...fields,sessionStatus:'submitted',submittedAt:at},next=saveCommunication({...p,studio:{...p.studio,[id]:{fields:snapshot,updatedAt:at,attempts:[...record.attempts,{id:crypto.randomUUID(),at,fields:snapshot,outcome:`${plan.track} · ${fields.outcome}`,hints:fields.showExample==='yes'?1:0}]}}},day,{status:fields.outcome==='done'?'done':'attempted',notes:`${plan.title}\n${fields.answer}\nImprovement: ${fields.improvement}`,reply:fields.followupAnswer||'Private rehearsal; no listener reply recorded.'});try{validateProgress(next);commit(next);notice('Speaking session recorded. Check the account save status for cloud confirmation.')}catch(e){notice(e instanceof Error?e.message:'Unable to save session.')}}
 const doneSteps=[!!fields.answer?.trim(),!!fields.followupAnswer?.trim(),!!fields.improvement?.trim(),finished].filter(Boolean).length;
 return <section className="card communication-practice"><div className="section-heading"><div><span className="eyebrow">COMMUNICATION COACH · DAY {day}</span><h2>{preview.title}</h2></div><label>Choose course day<select value={day} onChange={e=>openDay(Number(e.target.value))}>{Array.from({length:90},(_,i)=><option key={i} value={i+1}>Day {i+1}{hasCommunicationRep(p.communication?.[i+1])?' · rep recorded':''}</option>)}</select></label></div><p>{reps}/90 speaking reps recorded · This day: {log?.status||'not submitted'}. Attempted and Done both count as one daily rep; extra attempts do not inflate the count.</p><LearningProgressBar value={Math.round(reps/90*100)} label="90-day speaking progress"/>
 {!plan&&<><div className="communication-options"><label>Focus<select value={track} onChange={e=>write({track:e.target.value})}>{speakingTracks.map(t=><option key={t} value={t}>{trackLabels[t]}</option>)}</select></label><label>Available time<select value={minutes} onChange={e=>write({minutes:e.target.value})}>{[5,10,20].map(n=><option key={n} value={n}>{n} minutes</option>)}</select></label><label>Practice setting<select value={audience} onChange={e=>write({audience:e.target.value})}>{['Private rehearsal','Willing friend or teammate','Willing person in a public setting'].map(a=><option key={a}>{a}</option>)}</select></label></div><p><strong>Suggested level: {recommendation.level}.</strong> {recommendation.reason}</p><button className="secondary" onClick={()=>write({variant:String(variant+1)})}>Try another scenario</button><button className="primary" onClick={()=>write({plan:JSON.stringify(preview),sessionStatus:'active'})}>Start this speaking session</button><small>Starting freezes your task so later progress cannot change it while you practise.</small></>}
 <div className="communication-plan"><p><strong>{preview.track} · {preview.minutes} min · {preview.audience}</strong></p><p>{preview.prompt}</p><ol>{preview.steps.map(s=><li key={s}>{s}</li>)}</ol><div className="communication-flow">{preview.structure.split(' → ').map((s,i)=><span key={i}>{i+1}. {s}</span>)}</div><p><strong>Start with:</strong> {preview.opener}</p><p><strong>If you freeze:</strong> {preview.rescue}</p><p>{preview.audience==='Private rehearsal'?'Play both roles yourself. No message or recording is sent to anyone.':'Ask whether the person has a moment. If they decline or seem busy, thank them and use private rehearsal instead. Do not record another person without permission.'}</p><p>{preview.level==='Foundation'?'Keep one idea per sentence. Rehearse once before answering.':preview.level==='Stretch'?'Answer the follow-up without the script, then give a shorter version in two sentences.':'Give one concrete example, then practise a follow-up without reading.'}</p></div>
 {plan&&<><div className="section-heading"><h3>Prepare → respond → reflect → submit</h3><span>{doneSteps}/4 stages</span></div><LearningProgressBar value={doneSteps*25} label="Current speaking session stages"/><label>Your answer or what you said<textarea rows={5} maxLength={10000} readOnly={finished} value={fields.answer||''} onChange={e=>write({answer:e.target.value})} placeholder="Write your own sentences. Your draft saves without marking the rep complete."/></label><button className="secondary" onClick={()=>write({showExample:fields.showExample==='yes'?'no':'yes'})}>Show / hide an example</button>{fields.showExample==='yes'&&<p className="info-box">{preview.example}</p>}<details open={fields.followupOpen==='yes'} onToggle={e=>{if(!finished&&e.currentTarget.open!==(fields.followupOpen==='yes'))write({followupOpen:e.currentTarget.open?'yes':'no'})}}><summary>Practise the follow-up</summary><p>{preview.followup}</p><label>Your reply / listener feedback<textarea rows={3} maxLength={8000} readOnly={finished} value={fields.followupAnswer||''} onChange={e=>write({followupAnswer:e.target.value})}/></label></details><label>One clearer sentence or improvement<textarea rows={3} maxLength={6000} readOnly={finished} value={fields.improvement||''} onChange={e=>write({improvement:e.target.value})} placeholder="Original sentence → simpler version. Or record the exact point you want to improve."/></label><div className="communication-options"><label>Confidence after practice<select disabled={finished} value={fields.confidenceAfter||''} onChange={e=>write({confidenceAfter:e.target.value})}><option value="">Choose honestly</option>{[1,2,3,4,5].map(n=><option key={n} value={n}>{n} / 5{n===1?' · need support':n===5?' · comfortable':''}</option>)}</select></label><label>Next focus<select disabled={finished} value={fields.nextFocus||'clarity'} onChange={e=>write({nextFocus:e.target.value})}>{['clarity','structure','listening','nerves'].map(f=><option key={f}>{f}</option>)}</select></label><label>Outcome<select disabled={finished} value={fields.outcome||''} onChange={e=>write({outcome:e.target.value})}><option value="">Choose outcome</option><option value="attempted">Attempted · needs more practice</option><option value="done">Done · finished the exercise</option></select></label></div><p>Confidence is your self-rating. The app does not grade pronunciation, fluency or grammar automatically.</p>{finished?<><p role="status">Submitted {new Date(fields.submittedAt).toLocaleString()}. Your previous attempt is preserved below.</p><button className="primary" onClick={()=>write({plan:'',sessionStatus:'',answer:'',followupAnswer:'',improvement:'',confidenceAfter:'',outcome:'',showExample:'',followupOpen:'',variant:String(variant+1)})}>Start another session</button></>:<button className="primary" onClick={submit}>Submit communication</button>}</>}
 {log&&<details><summary>Existing day log & earlier saved versions</summary><p>{log.notes}</p><p>{log.reply}</p>{[...log.history].reverse().map((h,i)=><article key={i}><small>{h.status} · {new Date(h.savedAt).toLocaleString()}</small><p>{h.notes}</p><p>{h.reply}</p></article>)}</details>}
 {!!record.attempts.length&&<section><h3>Speaking session history · {record.attempts.length}</h3>{[...record.attempts].reverse().slice((historyPage-1)*5,historyPage*5).map(a=>{const saved=readSpeakingPlan(a.fields.plan);return <details key={a.id}><summary>{saved?.title||'Saved session'} · {new Date(a.at).toLocaleString()}</summary><p>{saved?.prompt}</p><p className="preserve-lines">{a.fields.answer}</p><p><strong>Follow-up:</strong> {a.fields.followupAnswer||'Not recorded'}</p><p><strong>Improvement:</strong> {a.fields.improvement}</p><small>Confidence {a.fields.confidenceAfter}/5 · Next focus {a.fields.nextFocus||'clarity'}</small></details>})}<Pagination page={historyPage} total={record.attempts.length} pageSize={5} onChange={setHistoryPage} label="Speaking attempts"/></section>}
 <div className="pagination"><button className="secondary" disabled={day===1} onClick={()=>openDay(day-1)}>← Previous day</button><span>Day {day} of 90</span><button className="secondary" disabled={day===90} onClick={()=>openDay(day+1)}>Next day →</button></div></section>;
}
