'use client';
import {useState} from 'react';
import {dateKey,dayDate,hasCommunicationRep,saveCommunication,type Progress} from '@/lib/progress';
import {communicationMission} from '@/lib/course';
import {quests} from '@/lib/curriculum';

export default function CommunicationHistory({p,commit,open}:{p:Progress;commit:(p:Progress)=>void;open:(day:number)=>void}){
 const [selected,setSelected]=useState<number[]>([]),[message,setMessage]=useState('');
 const days=quests.filter(q=>dayDate(p.startDate,q.day-1)<=dateKey()||p.communication?.[q.day]||p.days[q.day]?.completedAt);
 const attempted=days.filter(q=>p.communication?.[q.day]?.status==='attempted').length,done=days.filter(q=>p.communication?.[q.day]?.status==='done').length;
 function record(){let next=p;for(const day of selected){if(next.communication?.[day]?.status!=='done')next=saveCommunication(next,day,{status:'done'});}commit(next);setMessage(`Recorded ${selected.length} selected day(s) as done. Check the account save status for cloud confirmation.`);setSelected([]);}
 return <section className="card"><h2>Your communication history</h2><p><strong>{attempted+done} speaking reps recorded:</strong> {done} Done · {attempted} Attempted. Both earn the daily rep; Planned or an unsaved draft does not count. Finishing a course checklist alone does not record communication.</p><details><summary>Review days or record practice you already completed</summary><p>Select only the days when you actually did the communication practice. This saves Done while keeping existing notes, replies and earlier statuses.</p><div className="button-row"><button className="secondary" onClick={()=>setSelected(days.filter(q=>p.days[q.day]?.completedAt&&p.communication?.[q.day]?.status!=='done').map(q=>q.day))}>Select completed course days</button><button className="secondary" disabled={!selected.length} onClick={()=>setSelected([])}>Clear selection</button></div>{days.map(q=>{const log=p.communication?.[q.day];return <div className="list-row" key={q.day}><label style={{display:'flex',alignItems:'center',gap:12}}><input type="checkbox" style={{width:18,height:18,flexShrink:0}} disabled={log?.status==='done'} checked={selected.includes(q.day)} onChange={e=>setSelected(old=>e.target.checked?[...old,q.day]:old.filter(n=>n!==q.day))}/><span><strong>Day {q.day} · {dayDate(p.startDate,q.day-1)}</strong><small>{communicationMission(q.day).title} · {log?.status==='done'?'Done':log?.status==='attempted'?'Attempted · rep recorded':log?'Planned':'No saved communication record'}{hasCommunicationRep(log)?' ✓':''}</small></span></label><button className="text-btn" onClick={()=>open(q.day)}>Open day →</button></div>})}{!days.length&&<p>Your course has not started yet. Communication tasks appear on each course day.</p>}<button className="primary" disabled={!selected.length} onClick={record}>Record {selected.length||''} selected days as done</button></details>{message&&<p role="status">{message}</p>}</section>;
}
