'use client';
import type {ReadingLesson} from '@/lib/commute';

// Illustrated states come from the lesson, not a code execution engine.
export default function ConceptVisual({lesson:l,step}:{lesson:ReadingLesson;step:number}){
 const id=l.id;
 if(id.includes('map-basics')||id.includes('map-counting'))return <figure className="concept-visual"><figcaption>Map: keys point to values</figcaption><div className="concept-map"><span>Key</span><span>Value</span>{(id.includes('counting')?(step===0?[['a','1']]:[['a',step===2?'2':'1'],['b','1']]):(step===0?[]:[['2','0']])).map(([k,v])=><div key={k}><code>{k}</code><b>→</b><code>{v}</code></div>)}</div><p><code>has(key)</code> checks presence. <code>get(key)</code> reads the value. Even <code>false</code> can be a stored value.</p><small>Illustrated entries at the selected walkthrough step.</small></figure>;
 if(id.includes('set-basics'))return <figure className="concept-visual"><figcaption>Set: repeated values occupy one membership slot</figcaption><div className="concept-chips">{['3','1','3'].map((n,i)=><code key={i}>{n}</code>)}<span>→</span><div className="concept-set"><code>3</code><code>1</code></div></div><p><code>has(3) → true</code> · <code>size → 2</code></p><small>Objects use identity, not deep value equality.</small></figure>;
 if(id.includes('micro-macro'))return <figure className="concept-visual"><figcaption>Browser scheduling: finish the stack, drain microtasks</figcaption><div className="concept-lanes"><div><strong>Current script</strong><code>sync work → stack empty</code></div><div><strong>Microtask queue</strong><code>Promise callbacks → newly queued microtasks</code></div><div><strong>Later task</strong><code>timer callback when eligible</code></div></div><p>Rendering may occur between tasks. A zero-delay timer cannot interrupt the running script.</p></figure>;
 if(id.includes('virtual-dom'))return <figure className="concept-visual"><figcaption>Render computes; commit applies DOM changes</figcaption><div className="concept-lanes"><div><strong>Previous description</strong><code>button → 1</code></div><div><strong>Next description</strong><code>button → 2</code></div><div><strong>DOM commit</strong><code>update text; retain matching node</code></div></div><p>Component type, position and keys affect identity. A render does not imply replacing the entire DOM.</p></figure>;
 if(id.includes('react-context'))return <figure className="concept-visual"><figcaption>Context flows down to consuming descendants</figcaption><div className="concept-tree"><strong>Theme provider: dark</strong><span>↓</span><div><span>Layout (passes no theme prop)</span><span>↓</span><strong>Button → useContext(ThemeContext)</strong></div></div><p>A nearer provider overrides the value for its subtree.</p></figure>;
 if(id.includes('redis-cache-aside'))return <figure className="concept-visual"><figcaption>Cache-aside read: hits and misses follow different paths</figcaption><div className="concept-tree"><strong>Request → application → Redis GET</strong><span>↓</span><div className="concept-branches"><div><b>Hit</b><span>Return cached value</span></div><div><b>Miss</b><span>Read database → SET with TTL → return</span></div></div></div><p>The database remains authoritative. A write needs an explicit invalidation policy.</p></figure>;
 if(l.format==='Design answer'||id.includes('serverless')||id.includes('redis')||id.includes('sql-where')||id.includes('acid')||id.includes('react-'))return <figure className="concept-visual"><figcaption>{l.format==='Design answer'?'Scenario flow and responsibilities':'Concept trace'}</figcaption><ol className="concept-pipeline">{l.steps.map((s,i)=><li key={i} aria-current={i===step?'step':undefined}><b>{s.title}</b><span>{s.state}</span>{i<l.steps.length-1&&<i aria-hidden>↓</i>}</li>)}</ol><small>Illustration only. Use the step controls to inspect each boundary.</small></figure>;
 return null;
}
