'use client';
import {useEffect,useState} from 'react';
import {architectureCases,commandLessons,previewCommand,computeModel,inspectOrder,initialOrders,constraintDDL,techRadar,radarReviewed,type SampleOrder} from '@/lib/foundation-labs';
import {useStudio,Field,Attempts} from './studio/StudioContext';

const areas=[['design','🏙️','HLD ↔ LLD'],['linux','🐧','Linux command camp'],['compute','🧠','CPU ↔ GPU'],['postgres','🐘','PostgreSQL gates'],['radar','📡','Tech radar']] as const;
const related:Record<string,[string,string][]>= {
 design:[['hld','What is HLD?'],['lld','What is LLD?'],['composition','OOP or composition?']],
 linux:[['linux-basics','Linux versus shell'],['linux-files','Files and paths'],['linux-pipes','Pipes'],['linux-permissions','Permissions'],['linux-processes','Processes']],
 compute:[['cpu','CPU fundamentals'],['gpu','GPU fundamentals'],['memory-storage','Memory and storage']],
 postgres:[['pg-types','Data types'],['pg-constraints','Constraints'],['pg-relations','Foreign keys'],['pg-transactions','Transactions / ACID'],['pg-indexes','Indexes'],['sql-flow','WHERE and HAVING']],
 radar:[['docker-foundations','Docker'],['cicd-foundations','CI/CD'],['rag-foundations','RAG'],['observability','Observability']],
};
export default function FoundationWorkshops({read}:{read:(id:string)=>void}){
 const [area,setArea]=useState('design');
 return <div className="adventure foundation-workshops"><section className="card"><span className="eyebrow">SYSTEMS EXPEDITION BASE CAMP</span><h2>Understand the system around your code.</h2><p>Choose a mission, make a prediction, and watch the steps. Then explain what you would use and why.</p><div className="foundation-tabs">{areas.map(([id,icon,name])=><button key={id} className="secondary" aria-pressed={area===id} onClick={()=>setArea(id)}>{icon} {name}</button>)}</div></section>{area==='design'?<ArchitectureZoom/>:area==='linux'?<LinuxCamp/>:area==='compute'?<ComputeRace/>:area==='postgres'?<ConstraintCamp/>:<TechRadar/>}<section className="card"><h3>Explore the concepts behind this mission</h3><div className="button-row">{related[area].map(([id,name])=><button key={id} className="secondary" onClick={()=>read(id)}>{name} →</button>)}</div></section><WorkshopReflection key={area} area={area}/></div>;
}
function Journey({steps,emoji='📦'}:{steps:readonly(readonly[string,string])[];emoji?:string}){
 const [step,setStep]=useState(0),[playing,setPlaying]=useState(false);
 useEffect(()=>{if(!playing)return;if(step===steps.length-1){setPlaying(false);return}const t=setTimeout(()=>setStep(i=>i+1),1600);return()=>clearTimeout(t)},[playing,step,steps.length]);
 return <><div className="foundation-track" aria-hidden="true"><span style={{left:`${step/Math.max(1,steps.length-1)*100}%`}}>{emoji}</span></div><div className="adventure-route">{steps.map(([name],i)=><button className="secondary" key={`${name}-${i}`} aria-pressed={i===step} onClick={()=>{setPlaying(false);setStep(i)}}><small>{i+1}</small><strong>{name}</strong>{i<steps.length-1&&<span aria-hidden="true">→</span>}</button>)}</div><div className="adventure-callout" aria-live="polite"><h3>{steps[step][0]}</h3><p>{steps[step][1]}</p></div><div className="button-row"><button className="secondary" disabled={!step} onClick={()=>{setPlaying(false);setStep(i=>i-1)}}>← Back</button><button className="primary" onClick={()=>{if(step===steps.length-1)setStep(0);setPlaying(v=>!v)}}>{playing?'Pause':'▶ Animate flow'}</button><button className="secondary" disabled={step===steps.length-1} onClick={()=>{setPlaying(false);setStep(i=>i+1)}}>Next →</button><button className="secondary" onClick={()=>{setPlaying(false);setStep(0)}}>Restart</button></div></>;
}
function ArchitectureZoom(){
 const [selected,setSelected]=useState('booking'),[level,setLevel]=useState('hld');const example=architectureCases.find(x=>x.id===selected)!;
 return <section className="card"><h2>🏙️ High-level design ↔ 🧱 Low-level design</h2><div className="foundation-compare"><div><h3>HLD: the system view</h3><p>Components, responsibilities, storage, data flow, capacity, reliability and tradeoffs. Use it to agree on the overall approach.</p></div><div><h3>LLD: the implementation view</h3><p>Interfaces, functions/classes, schemas, state transitions, algorithms and error cases. Use it to turn the approach into implementable behavior.</p></div></div><p>Both describe the same system at different detail levels. LLD can use OOP or functional modules.</p><label>Choose a design<select value={selected} onChange={e=>setSelected(e.target.value)}>{architectureCases.map(x=><option value={x.id} key={x.id}>{x.name}</option>)}</select></label><p><strong>Requirement:</strong> {example.requirement}</p><div className="button-row"><button className="secondary" aria-pressed={level==='hld'} onClick={()=>setLevel('hld')}>HLD: zoom out</button><button className="secondary" aria-pressed={level==='lld'} onClick={()=>setLevel('lld')}>LLD: zoom in</button></div><Journey key={`${selected}-${level}`} steps={level==='hld'?example.hld:example.lld} emoji={level==='hld'?'📨':'🔧'}/>{level==='lld'&&<><h3>Implementation contract</h3><pre>{example.code}</pre></>}<p><strong>Interview route:</strong> requirements → assumptions → data/API → flow → failures → tradeoffs. Explain why each component exists before adding another one.</p></section>;
}
function LinuxCamp(){
 const {patch,submit}=useStudio();const [query,setQuery]=useState(''),[command,setCommand]=useState('pwd'),[cwd,setCwd]=useState('/home/learner/app'),[history,setHistory]=useState<string[]>([]);
 const matches=commandLessons.filter(x=>`${x.command} ${x.meaning} ${x.use}`.toLowerCase().includes(query.toLowerCase()));
 function run(text=command){const result=previewCommand(text,cwd);setHistory(h=>[...h,`${cwd} $ ${text}\n${result.output}`].slice(-20));setCwd(result.cwd)}
 return <><section className="card"><h2>🐧 Linux command practice</h2><p>Linux is the kernel; a distribution adds tools and services. A terminal displays a shell session, and the shell interprets commands.</p><p><strong>Practice fixture:</strong> commands below return teaching output. No local shell, network connection, file change or installed service is accessed. Only listed command forms and fixture paths are supported.</p><Journey steps={[["Terminal","You enter text and receive output."],["Shell","A real shell parses syntax and launches programs; this lab only previews supported examples."],["Process + kernel","A real program asks the OS for resources."],["Output + status","Read output and check whether the operation succeeded."]]} emoji="🐧"/><form className="adventure-form" onSubmit={e=>{e.preventDefault();run()}}><label>Command<input maxLength={200} value={command} onChange={e=>setCommand(e.target.value)} autoComplete="off" spellCheck={false}/></label><button className="primary">Preview command</button><button type="button" className="secondary" onClick={()=>{setCwd('/home/learner/app');setHistory([])}}>Reset fixture</button></form><pre className="foundation-terminal" aria-live="polite">{history.join('\n\n')||'Try pwd, ls, cd logs, cd .., or grep ERROR app.log.'}</pre><small>Current fixture directory: {cwd}. Session output resets when leaving this camp unless you save it.</small><button className="secondary" disabled={!history.length} onClick={()=>{patch('foundation-linux',{transcript:history.join('\n\n')});submit('foundation-linux','Linux command transcript')}}>Save transcript checkpoint</button></section><section className="card"><h3>{commandLessons.length} command cards</h3><label>Find a command<input value={query} onChange={e=>setQuery(e.target.value)} placeholder="permissions, process, grep…"/></label><div className="foundation-command-grid">{matches.map(x=><article key={x.command}><code>{x.command}</code><h4>{x.meaning}</h4><p>{x.use}</p><button className="secondary" onClick={()=>{setCommand(x.command);run(x.command)}}>Preview</button></article>)}</div>{!matches.length&&<p>No matching command. Clear the search to see the full list.</p>}<p><a href="https://www.gnu.org/software/coreutils/manual/coreutils.html" target="_blank" rel="noreferrer">GNU command reference ↗</a></p></section></>;
}
function ComputeRace(){
 const [jobs,setJobs]=useState(32),[independent,setIndependent]=useState(true),[overhead,setOverhead]=useState(2),[tick,setTick]=useState(0),[running,setRunning]=useState(false);
 const model=computeModel(jobs,independent,overhead),duration=Math.max(model.cpuTime,model.gpuTime);
 useEffect(()=>{if(!running)return;if(tick>=duration){setRunning(false);return}const t=setTimeout(()=>setTick(i=>i+1),550);return()=>clearTimeout(t)},[running,tick,duration]);
 function reset(){setTick(0);setRunning(false)}
 return <section className="card"><h2>🧠 CPU or 🎨 GPU: what changes the result?</h2><p>A CPU handles diverse general-purpose work. A GPU can accelerate suitable parallel numeric work. They often work together.</p><p><strong>Toy model:</strong> four CPU lanes, sixteen GPU lanes, one unit per job, plus GPU setup/transfer overhead. Units and lanes are illustrative, not hardware timings or benchmark results. Dependent jobs use one lane on either side.</p><div className="adventure-form"><label>Jobs: {jobs}<input type="range" min={1} max={64} value={jobs} onChange={e=>{reset();setJobs(Number(e.target.value))}}/></label><label>GPU setup units: {overhead}<input type="range" min={0} max={10} value={overhead} onChange={e=>{reset();setOverhead(Number(e.target.value))}}/></label><label>Work shape<select value={independent?'parallel':'dependent'} onChange={e=>{reset();setIndependent(e.target.value==='parallel')}}><option value="parallel">Independent jobs</option><option value="dependent">Each job depends on the previous one</option></select></label></div><div className="foundation-compare">{[{name:'CPU',done:Math.min(jobs,tick*model.cpuWidth),time:model.cpuTime,icon:'🧠'},{name:'GPU',done:Math.min(jobs,Math.max(0,tick-overhead)*model.gpuWidth),time:model.gpuTime,icon:'🎨'}].map(x=><div key={x.name}><h3>{x.icon} {x.name} · {x.done}/{jobs}</h3><p>{x.time} modeled time units{x.name==='GPU'&&tick<overhead?' · preparing/transferring':''}</p><div className="foundation-jobs" aria-label={`${x.name}: ${x.done} of ${jobs} jobs finished`}>{Array.from({length:jobs},(_,i)=><span key={i} className={i<x.done?'done':''} aria-hidden="true">{i<x.done?'✓':'·'}</span>)}</div></div>)}</div><div className="button-row"><strong>Time: {tick}</strong><button className="primary" onClick={()=>{if(tick===duration)setTick(0);setRunning(v=>!v)}}>{running?'Pause':'▶ Run comparison'}</button><button className="secondary" disabled={tick===duration} onClick={()=>{setRunning(false);setTick(n=>n+1)}}>One time step</button><button className="secondary" onClick={reset}>Reset</button></div><p>Try 4 jobs, then 64. Then make the jobs dependent. Explain why overhead or a dependency can erase the benefit of more parallel lanes.</p><p><a href="https://aws.amazon.com/compare/the-difference-between-gpus-cpus/" target="_blank" rel="noreferrer">CPU/GPU background from AWS ↗</a></p></section>;
}
function ConstraintCamp(){
 const [rows,setRows]=useState<SampleOrder[]>(()=>initialOrders.map(x=>({...x}))),[draft,setDraft]=useState({id:'3',userId:'1',code:'BOOK-C',quantity:'2'}),[report,setReport]=useState<ReturnType<typeof inspectOrder>|null>(null),[message,setMessage]=useState('');
 function inspect(){setReport(inspectOrder(draft,rows));setMessage('Preview ready. Inspect the gates before attempting insertion.')}
 function insert(){const result=inspectOrder(draft,rows);setReport(result);if(result.row){if(rows.length>=20){setMessage('The fixture is limited to 20 rows. Reset it to continue.');return}setRows([...rows,result.row]);setMessage('Accepted into this temporary fixture. Your real database was not changed.')}else setMessage('Rejected by this model. Fix the failing values and try again.')}
 return <section className="card"><h2>🐘 PostgreSQL constraint gates</h2><p>Change a proposed row and predict whether it is accepted. The sample learner table contains IDs 1 (Asha) and 2 (Ravi).</p><p><strong>Teaching model:</strong> this JavaScript checker illustrates the displayed schema; it is not a PostgreSQL engine. Blank fields stand for SQL NULL here, and code equality is case-sensitive. It does not model concurrent transactions, collation variants, or every SQL behavior.</p><details><summary>Read the corresponding SQL schema</summary><pre>{constraintDDL}</pre></details><div className="adventure-form">{([['id','Primary-key ID'],['userId','Learner ID'],['code','Unique code'],['quantity','Positive quantity']] as const).map(([key,label])=><label key={key}>{label}<input value={draft[key]} maxLength={60} onChange={e=>{setReport(null);setMessage('');setDraft({...draft,[key]:e.target.value})}}/></label>)}</div><div className="button-row"><button className="primary" onClick={inspect}>Inspect gates</button><button className="secondary" onClick={insert}>Try inserting row</button><button className="secondary" onClick={()=>{setRows(initialOrders.map(x=>({...x})));setReport(null);setMessage('Fixture reset. No account data was changed.')}}>Reset fixture</button></div><div className="button-row"><span>Try a failure:</span><button className="secondary" onClick={()=>{setDraft({...draft,id:'1'});setReport(null);setMessage('')}}>Duplicate ID</button><button className="secondary" onClick={()=>{setDraft({...draft,userId:'99'});setReport(null);setMessage('')}}>Missing parent</button><button className="secondary" onClick={()=>{setDraft({...draft,quantity:'0'});setReport(null);setMessage('')}}>Invalid quantity</button><button className="secondary" onClick={()=>{setDraft({...draft,code:''});setReport(null);setMessage('')}}>NULL code</button></div>{report&&<Journey key={JSON.stringify(report.gates)+message} steps={report.gates.map(g=>[`${g.pass?'✓':'✕'} ${g.name}`,`${g.detail} ${g.pass?'This proposed row satisfies this gate.':'Not satisfied; later checks also require valid typed inputs.'}`] as [string,string])} emoji="📦"/>}{message&&<p role="status">{message}</p>}<div className="foundation-table"><table><caption>Temporary orders · {rows.length} rows</caption><thead><tr><th>ID</th><th>Learner</th><th>Code</th><th>Quantity</th></tr></thead><tbody>{rows.map(r=><tr key={r.id}><td>{r.id}</td><td>{r.userId}</td><td>{r.code}</td><td>{r.quantity}</td></tr>)}</tbody></table></div><p>Refresh or leave this camp to discard fixture edits. Save what you learned in the reflection below.</p><p><a href="https://www.postgresql.org/docs/current/ddl-constraints.html" target="_blank" rel="noreferrer">PostgreSQL constraint reference ↗</a></p></section>;
}
function TechRadar(){
 const {get,patch}=useStudio();
 return <section className="card"><span className="eyebrow">EVIDENCE, THEN PRACTICE</span><h2>📡 Technology radar</h2><p>Sources reviewed <strong>{radarReviewed}</strong>. These cards summarize the cited <strong>2025</strong> reports available in this review; they are not live rankings or claims about 2026 hiring demand.</p><p>GitHub activity and developer surveys measure different things. Neither guarantees interview selection. The practice actions below are learning suggestions based on those signals, not findings reported by the surveys.</p><div className="foundation-radar">{techRadar.map(t=>{const id=`foundation-radar-${t.id}`,chosen=get(id).fields.selected==='yes';return <article key={t.id}><small>{t.period}</small><h3>{t.name}</h3><p><strong>Evidence:</strong> {t.evidence}</p><a href={t.source} target="_blank" rel="noreferrer">Read the primary source ↗</a><p><strong>Practice mission:</strong> {t.mission}</p><button className="secondary" aria-pressed={chosen} onClick={()=>patch(id,{selected:chosen?'no':'yes',mission:t.mission,reviewedSourceDate:radarReviewed})}>{chosen?'✓ Added to my interests':'Add to my learning interests'}</button></article>})}</div><p>For your next interview, explain one project end to end: UI → API → data → deployment → failures. Add a new technology when it helps solve a concrete problem. The radar is a dated snapshot and does not update automatically.</p></section>;
}
function WorkshopReflection({area}:{area:string}){
 const {get,patch,submit,notice}=useStudio(),id=`foundation-${area}`;
 return <section className="card"><h3>🏁 Bring back your understanding</h3><Field id={id} name="explanation" label="What is it, when would I use it, and what could go wrong?" placeholder="English or Hinglish: I would choose this when… My example is… The tradeoff is…"/><Field id={id} name="nextPractice" label="My next implementation or interview practice task" rows={3}/><button className="primary" onClick={()=>{if(!get(id).fields.explanation?.trim()){notice('Add your explanation before submitting.');return}patch(id,{topic:area});submit(id,'Foundation workshop reflection')}}>Submit reflection</button><Attempts id={id}/></section>;
}
