'use client';
import {useState} from 'react';
import {puzzleCatalog,type PuzzleMode} from '@/lib/studio-puzzles';
import type {Progress} from '@/lib/progress';
import {StudioProvider} from './studio/StudioContext';
import {PuzzleLab,SqlPlayground,RenderExplorer,RequestJourney,IncidentRoom,CompareLab} from './studio/TechnicalLabs';
import {DesignBuilder,DecisionJournal,StackLab} from './studio/DesignStudio';
import {ExplainLevels,VoiceRecorder,StoryStudio,SentenceWorkshop,ListeningLab,InterviewTree,ConversationLadder} from './studio/SpeakingStudio';
import {DailyCoach,CommuteBridge,MistakeNotebook,Glossary,Portfolio,WeeklyReport} from './studio/PersonalCoach';
import UnderstandingCoach from './studio/UnderstandingCoach';
const modules=[
['bug','Experiment','Bug detective','Find a root cause and record the correction.'],['predict','Experiment','Predict before playing','Commit to an output and explain your reasoning.'],['change','Experiment','Change one thing','See how an altered assumption changes behavior.'],['hints','Experiment','Hint ladder','Clue → approach → pseudocode → explanation.'],['trace','Experiment','Code to picture','Follow references, callbacks and state transitions.'],['sql','Experiment','SQL playground','Run queries against an isolated sample database.'],['react','Experiment','React render explorer','Observe actual memoized and normal child commits.'],['request','Experiment','Backend request journey','Trace validation, identity, data and failures.'],['incidents','Experiment','Production incident room','Investigate logs and defend a recovery action.'],
['design','Design','System-design builder','Connect components and explore failure paths.'],['requirements','Design','Requirement cards','Adapt a design as scale and constraints change.'],['decisions','Design','Decision journal','Capture a choice, its cost and when to revisit it.'],['stacks','Design','One feature, three stacks','Compare Node, .NET and Python implementations.'],['compare','Design','Compare concepts','Choose between alternatives using concrete examples.'],
['levels','Speak','Explain at three levels','Adapt an idea for a beginner, teammate and interviewer.'],['record','Speak','Explain it aloud','Record 60 seconds and listen to your own explanation.'],['story','Speak','Project storytelling','Build honest STAR stories and architecture narratives.'],['sentences','Speak','Sentence workshop','Use local clarity checks and preserve your meaning.'],['listen','Speak','Listening practice','Summarize a spoken question before answering.'],['interview','Speak','Follow-up tree','Answer one question and then face a deeper follow-up.'],['conversation','Speak','Conversation ladder','Take a manageable step with a willing listener.'],['interrupt','Speak','Interruption practice','Pause, acknowledge and adapt under challenge.'],
['energy','Your coach','Energy-based plan','Choose a 10-, 30- or 60-minute session.'],['return','Your coach','Return after a break','Resume from saved work without erasing your backlog.'],['bridge','Your coach','Commute to practice','Link reading, evening application and morning recall.'],['mistakes','Your coach','Mistake notebook','Save causes, corrections and retry dates.'],['glossary','Your coach','Personal glossary','Build your own definitions, examples and pronunciation notes.'],['portfolio','Your coach','Evidence portfolio','Collect and export work you can explain.'],['weekly','Your coach','Weekly report','Inspect recorded practice without inflated readiness scores.'],['understand','Your coach','I don’t understand','Try a simpler explanation and one guiding question.'],
] as const;
type Module=typeof modules[number][0];
export default function GrowthStudio({p,commit,notice,sync,userKey,openDay,practice,read}:{p:Progress;commit:(p:Progress)=>void;notice:(text:string)=>void;sync:string;userKey:string;openDay:(day:number)=>void;practice:(id:string)=>void;read:(id?:string)=>void}){
 const [group,setGroup]=useState('Experiment'),[selected,setSelected]=useState<Module|null>(null),[search,setSearch]=useState('');const current=modules.find(m=>m[0]===selected);const visible=modules.filter(m=>(search||m[1]===group)&&(m[2]+' '+m[3]).toLowerCase().includes(search.toLowerCase()));
 let content;switch(selected){case 'bug':case 'predict':case 'change':case 'hints':case 'trace':content=<PuzzleLab mode={selected}/>;break;case 'sql':content=<SqlPlayground/>;break;case 'react':content=<RenderExplorer/>;break;case 'request':content=<RequestJourney/>;break;case 'incidents':content=<IncidentRoom/>;break;case 'design':case 'requirements':content=<DesignBuilder/>;break;case 'decisions':content=<DecisionJournal/>;break;case 'stacks':content=<StackLab/>;break;case 'compare':content=<CompareLab/>;break;case 'levels':content=<ExplainLevels/>;break;case 'record':content=<VoiceRecorder/>;break;case 'story':content=<StoryStudio/>;break;case 'sentences':content=<SentenceWorkshop/>;break;case 'listen':content=<ListeningLab/>;break;case 'interview':content=<InterviewTree/>;break;case 'conversation':content=<ConversationLadder/>;break;case 'interrupt':content=<InterviewTree interrupt/>;break;case 'energy':content=<DailyCoach/>;break;case 'return':content=<DailyCoach returning/>;break;case 'bridge':content=<CommuteBridge/>;break;case 'mistakes':content=<MistakeNotebook/>;break;case 'glossary':content=<Glossary/>;break;case 'portfolio':content=<Portfolio/>;break;case 'weekly':content=<WeeklyReport/>;break;case 'understand':content=<UnderstandingCoach/>;break}
 return <StudioProvider p={p} commit={commit} notice={notice} userKey={userKey} openDay={openDay} practice={practice} read={read}><div className="growth-studio"><div className="studio-banner"><div><span className="eyebrow">PRACTISE. OBSERVE. EXPLAIN.</span><h2>{current?current[2]:'Your interview practice studio'}</h2><p>{current?current[3]:'Hands-on labs, speaking exercises and a personal learning routine. Pick one useful action.'}</p></div><div className="studio-banner-actions"><a href="/practice-studio.md" download>Download studio guide</a>{current&&<button className="secondary" onClick={()=>setSelected(null)}>← All studio tools</button>}</div></div><p className="studio-save-status" role="status">{sync} · Drafts and text checkpoints use your existing account.</p>{!selected?<><div className="studio-category-nav">{['Experiment','Design','Speak','Your coach'].map(g=><button className="secondary" aria-pressed={group===g} key={g} onClick={()=>{setGroup(g);setSearch('')}}>{g}</button>)}<input aria-label="Search studio tools" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Find a tool…"/></div><div className="studio-module-grid">{visible.map(m=><button className="card" key={m[0]} onClick={()=>{setSelected(m[0]);setGroup(m[1]);window.scrollTo({top:0,behavior:'smooth'})}}><small>{m[1]}</small><h3>{m[2]}</h3><p>{m[3]}</p><span>{m[0] in puzzleCatalog?`${puzzleCatalog[m[0] as PuzzleMode].length} exercises · `:''}Open tool →</span></button>)}</div>{!visible.length&&<p>No matching tool. Try SQL, speaking, design, or a different search.</p>}</>:<div key={selected}>{content}</div>}</div></StudioProvider>;
}
