"use client";

import {Brain,BarChart3,MessageCircle,Clock,Flame} from 'lucide-react';
import type {Progress} from '@/lib/progress';
import {dateKey,scheduledDay} from '@/lib/progress';
import {managedTasks} from '@/lib/planning';
import {questionBank} from '@/lib/bank';

type Props={p:Progress;commit:(p:Progress)=>void;open?:(day:number)=>void;practice?:(id:string)=>void};
const pct=(n:number,d:number)=>d?Math.round(n/d*100):0;
export function SmartCoach({p,open,practice}:Props){const today=dateKey(),tasks=managedTasks(p),active=tasks.filter(t=>!t.done&&t.status!=='skipped'),overdue=active.filter(t=>t.dueDate<today),todayTasks=active.filter(t=>t.dueDate===today),budget=p.profile?.dailyMinutes||p.planning?.dailyBudget||180,next=(overdue[0]||todayTasks[0]||active[0]),weak=p.profile?.weakAreas?.[0]||'DSA',review=questionBank.find(q=>q.kind==='DSA'&&!p.practice?.[q.id]?.solvedAt)||questionBank[0];const message=overdue.length?`You are behind by ${overdue.length} task${overdue.length===1?'':'s'}. Finish the earliest pending item first.`:todayTasks.length?`Today has ${todayTasks.length} focused task${todayTasks.length===1?'':'s'}. Keep it realistic with your ${budget} minute budget.`:'You are ahead of the visible schedule. Use the extra time for recall and weak areas.';return <section className="card smart-coach"><div className="section-heading"><div><span className="eyebrow">SMART DAILY COACH</span><h2>{message}</h2></div><Brain size={24}/></div><div className="coach-actions"><button className="primary" disabled={!next} onClick={()=>next&&open?.(next.day)}>Do this first: {next?`Day ${next.day} · ${next.label}`:'No pending task'}</button><button className="secondary" onClick={()=>review&&practice?.(review.id)}>Revise weak area: {weak}</button></div><div className="coach-mini"><span><Clock size={15}/> Budget: {budget}m</span><span><Flame size={15}/> Overdue: {overdue.length}</span><span><MessageCircle size={15}/> English reps: {Object.values(p.communication||{}).filter(x=>x.status==='done'||x.status==='attempted').length}/90</span></div></section>}
export function AnalyticsDashboard({p,open,practice}:Props){const tasks=managedTasks(p),doneTasks=tasks.filter(t=>t.done).length,completedDays=Object.values(p.days).filter(d=>d.completedAt).length,attempted=Object.values(p.practice||{}).filter(r=>r.attempts.length||r.draft.trim()).length,solved=Object.values(p.practice||{}).filter(r=>r.solvedAt).length,comm=Object.values(p.communication||{}).filter(c=>c.status==='done'||c.status==='attempted').length,topics=['Arrays','Strings','Trees','Graphs','DP','SQL','System design','English'];return <section className="analytics-page"><div className="analytics-hero card"><div><span className="eyebrow">ANALYTICS DASHBOARD</span><h2>Your interview readiness map</h2><p>Use this to see where your work is going, what is still pending, and what needs revision before interviews.</p></div><BarChart3 size={38}/></div><div className="analytics-grid"><Metric label="90-day course" value={`${completedDays}/90`} score={pct(completedDays,90)}/><Metric label="Tasks complete" value={`${doneTasks}/${tasks.length}`} score={pct(doneTasks,tasks.length)}/><Metric label="Practice solved" value={`${solved}/${Math.max(1,attempted)}`} score={pct(solved,Math.max(1,attempted))}/><Metric label="Communication" value={`${comm}/90`} score={pct(comm,90)}/></div><section className="card heatmap"><h2>Weak topic heatmap</h2><div>{topics.map((t,i)=>{const score=Math.max(8,Math.min(95,(solved*11+completedDays*3+i*9)%100));return <button key={t} onClick={()=>t==='System design'?practice?.('sd-scale-01'):undefined}><span>{t}</span><b style={{height:`${score}%`}}/><small>{score}%</small></button>})}</div></section><section className="card trend-card"><h2>Next coaching signal</h2><p>{completedDays<scheduledDay(p.startDate)?'You are behind the calendar. Recover by moving old work into smaller chunks.':'Your calendar position is okay. Increase independent attempts and communication reps.'}</p><button className="secondary" onClick={()=>open?.(Math.min(90,scheduledDay(p.startDate)))}>Open current day</button></section></section>}
function Metric({label,value,score}:{label:string;value:string;score:number}){return <div className="card metric-card"><strong>{value}</strong><span>{label}</span><div className="metric-ring" style={{background:`conic-gradient(var(--green) ${score*3.6}deg,#e8ece5 0deg)`}}><em>{score}%</em></div></div>}
