'use client';
import {Field,copyText,useStudio} from './studio/StudioContext';
const scripts=[
 {title:'1. Tell me about yourself',structure:'Present role → actual experience → one relevant contribution → why this role',sample:'I am a full-stack developer with about three years of experience. My main work has been with [your actual technologies]. In [real project], I owned [specific feature or responsibility]. One challenge was [real problem], and I addressed it by [your action]. I am now looking for a role where I can deepen my backend skills and contribute across the application.',why:'Keep this to 60–90 seconds. Replace every bracket with a truthful detail. Do not list every technology you have only read about.'},
 {title:'2. Explain your project',structure:'User problem → request flow → your ownership → decision → result',sample:'The application helps [users] achieve [goal]. The frontend handles [workflow], the API validates and authorizes requests, and the database stores [entities]. I was responsible for [your part]. I chose [approach] because [reason], with [trade-off]. We checked the result through [actual verification or evidence].',why:'Start with a feature the interviewer can picture. Distinguish what the team did from what you personally did.'},
 {title:'3. Explain React with an example',structure:'Definition → state-driven UI → concrete example → limitation',sample:'React is a library for building UI from components. A component uses props and state to describe what should be shown. For example, a search component stores the query and renders matching results. I keep the render pure, manage external synchronization with effects when needed, and use stable keys for results. React does not automatically solve network races or backend authorization.',why:'This is a technical model answer, not a claim that you built a specific production search feature.'},
 {title:'4. Explain a MERN request end to end',structure:'React → HTTP → Express/Node → business rules → MongoDB → response',sample:'For creating a note, React sends the text to an Express endpoint running on Node. The backend verifies the session, validates the text and derives the owner from the verified identity. It writes the document to MongoDB and returns the saved ID. React updates the screen only after confirmation or shows an explicit pending state. On failure, I preserve the draft and offer retry.',why:'Then discuss a real trade-off: document shape, duplicate requests, database indexing or retry behavior.'},
 {title:'5. Answer a basic .NET question',structure:'Distinguish terms → role → example → ownership detail',sample:'C# is the language, .NET supplies the runtime and libraries, and ASP.NET Core is the web framework. For example, an ASP.NET Core endpoint can call a service through dependency injection and use EF Core to query storage. I would keep HTTP concerns in the endpoint and business rules in an appropriate service. The exact lifetime and transaction boundaries depend on the use case.',why:'If you have not used .NET professionally, say that clearly and connect it to backend concepts you genuinely understand.'},
 {title:'6. Explain SQL with reasoning',structure:'State result → describe clauses in order → example → edge case',sample:'To find customers with at least three paid orders, I first filter paid rows with WHERE, group by customer, and use HAVING COUNT(*) >= 3. WHERE filters individual rows; HAVING filters groups. This does not include customers with no orders. If those customers were required, I would start from the customers table and consider a LEFT JOIN.',why:'Ask about nulls, ties and duplicate rows before assuming the requested result.'},
 {title:'7. Talk through a coding problem',structure:'Clarify → brute force → repeated work → invariant → code → complexity',sample:'For Two Sum, I need two different indices whose values add to the target. A pairwise scan is O(n squared). To avoid rescanning earlier values, I keep a Map from value to index. Before inserting the current value, I look for its complement. The invariant is that the Map contains only earlier indices. I would check duplicates, no match and negative values. Hashing gives average O(n) time with O(n) extra space.',why:'A useful explanation reconstructs the logic. You do not need to remember a memorized speech.'},
 {title:'8. Explain a system design',structure:'Requirements → simple flow → data model → failures → scale → trade-off',sample:'For a URL shortener, I would clarify traffic, custom aliases and expiry first. A create endpoint validates a URL, generates a key and stores it under a unique constraint. The redirect path looks up the key, checks expiry and redirects. I would handle collisions and abuse, then consider caching if reads justify it. The cache improves latency but adds invalidation and expiry concerns.',why:'State assumptions instead of presenting guessed capacity numbers as requirements.'},
 {title:'9. Answer a behavioral question',structure:'Situation → task → your action → result → learning',sample:'In [real situation], we needed to [goal]. My responsibility was [task]. I investigated [evidence], discussed [trade-off] with [team], and implemented [action]. The result was [actual outcome]. Afterward, we added [real prevention or learning].',why:'If you lack a metric, explain an observable outcome honestly. Never invent an incident or a numerical improvement.'},
 {title:'10. Recover when you do not know',structure:'Acknowledge → clarify → reason from known facts → verification plan',sample:'I have not used that feature in production. My understanding is [what you know]. Could I clarify whether you mean [distinction]? I would first try [bounded approach] and verify [specific behavior] with a small example and the official documentation.',why:'It is better to reason transparently than to guess confidently. Pause, then answer one point at a time.'},
];
export default function InterviewAnswerGuide(){
 const {notice}=useStudio();
 return <section className="card"><span className="eyebrow">START HERE · SPEAK BEFORE YOU MEMORIZE</span><h2>How to answer, from the basics</h2><p>For a technical question, use <strong>definition → purpose → example → trade-off</strong>. Give the first clear answer in 30–60 seconds, then let the interviewer choose where to go deeper.</p><ol><li><strong>Listen and clarify.</strong> Restate the question when its scope is unclear.</li><li><strong>Answer directly.</strong> Give one accurate definition or decision.</li><li><strong>Show it.</strong> Use a small input/output example or a real project detail.</li><li><strong>Explain why.</strong> Name the benefit, edge case and limitation.</li><li><strong>Stop and invite a follow-up.</strong> “Would you like me to show the code or the request flow?”</li></ol><p>Sample scripts are practice templates. Bracketed details must come from your own experience. You may draft notes in Hinglish and rehearse the final answer in clear English.</p>{scripts.map((s,i)=><details key={s.title}><summary>{s.title}</summary><h4>Answer structure</h4><p>{s.structure}</p><h4>Sample spoken answer</h4><p>{s.sample}</p><p><strong>Why this works:</strong> {s.why}</p><button className="secondary" onClick={()=>copyText(`${s.title}\n${s.structure}\n${s.sample}\n${s.why}`,notice)}>Copy practice script</button><Field id={`interview-speaking-${i+1}`} name="draft" label="My truthful version"/></details>)}<details><summary>Self-check after every practice answer</summary><ul><li>Did I answer the actual question within the first two sentences?</li><li>Did I explain one concrete example?</li><li>Did I distinguish facts, assumptions and personal experience?</li><li>Did I explain a limitation instead of claiming my approach is always best?</li><li>Could a teammate understand me without reading my code?</li></ul></details></section>;
}
