'use client';
import type {MouseEvent} from 'react';
import {interviewTopics} from '@/lib/interview-topics';
import {materialQuestions,workedExamples,materialSources} from '@/lib/interview-materials';
import {useWorkspaceLocation,navigateWorkspace,updateRouteQuery,routePage} from '@/lib/workspace-location';
import {useStudio,Field,copyText} from './studio/StudioContext';
import Pagination from './Pagination';

function follow(e:MouseEvent<HTMLAnchorElement>,href:string){if(e.ctrlKey||e.metaKey||e.shiftKey||e.altKey)return;e.preventDefault();navigateWorkspace(href);window.scrollTo({top:0,behavior:'auto'})}
export default function InterviewMaterials(){
 const {get,patch,notice}=useStudio(),location=useWorkspaceLocation(),url=new URL(location,'https://quest90.local');
 const slug=url.pathname.split('/').filter(Boolean)[1],topic=interviewTopics.find(t=>t.slug===slug);
 const key=(id:string)=>`interview-material-${id}`;
 if(!topic)return <section className="interview-materials"><div className="card"><span className="eyebrow">YOUR INTERVIEW SHELF</span><h2>One topic. A clear revision path.</h2><p>130 curated questions for around three years of full-stack experience. These are useful interview themes, not a guaranteed list of what a company will ask.</p><p>Choose a topic → answer aloud → reveal the explanation → save what you missed. Your revision markers are self-assessments, separate from course completion.</p></div><div className="materials-grid">{interviewTopics.map(t=>{const qs=materialQuestions(t.slug),done=qs.filter(q=>get(key(q.id)).fields.rating==='ready').length,href=`/interview-materials/${t.slug}/`;return <a key={t.slug} href={href} onClick={e=>follow(e,href)} className="card materials-topic"><span className="eyebrow">{qs.length} QUESTIONS</span><h2>{t.name}</h2><p>{t.summary}</p><progress aria-label={`${t.name} self-rated readiness`} value={done} max={qs.length}/><small>{done}/{qs.length} can explain</small><strong>Open revision guide →</strong></a>})}</div></section>;
 const questions=materialQuestions(topic.slug),search=url.searchParams.get('q')||'',filter=url.searchParams.get('filter')||'all';
 const filtered=questions.filter(q=>(`${q.group} ${q.question} ${q.answer} ${q.example}`.toLowerCase().includes(search.toLowerCase()))&&(filter==='all'||get(key(q.id)).fields.rating===filter));
 const pageSize=6,page=Math.min(routePage(url.searchParams.get('page')),Math.max(1,Math.ceil(filtered.length/pageSize))),visible=filtered.slice((page-1)*pageSize,page*pageSize);
 const done=questions.filter(q=>get(key(q.id)).fields.rating==='ready').length;
 return <section className="interview-materials"><nav aria-label="Interview topics" className="materials-tabs"><a href="/interview-materials/" onClick={e=>follow(e,'/interview-materials/')}>← All materials</a>{interviewTopics.map(t=>{const href=`/interview-materials/${t.slug}/`;return <a key={t.slug} href={href} aria-current={slug===t.slug?'page':undefined} onClick={e=>follow(e,href)}>{t.name}</a>})}</nav>
 <div className="card"><span className="eyebrow">{questions.length} QUESTIONS · ANSWER → EXAMPLE → TRADE-OFF</span><h2>{topic.name} interview revision</h2><p>{topic.summary}</p><progress aria-label="Questions you can explain" value={done} max={questions.length}/><p>{done}/{questions.length} can explain · Self-rated, not an interview score.</p>{slug==='dotnet'&&<a className="secondary" href="/interview-materials-dotnet.pdf" download>Download the 32-page .NET PDF</a>}<details><summary>Your four-hour revision plan</summary><ol><li>40 minutes: explain fundamentals aloud; mark uncertain answers.</li><li>40 minutes: connect the topic to a feature you actually built.</li><li>40 minutes: rehearse failure cases, trade-offs and security.</li><li>10 minutes: take a break, then recall five points without looking.</li><li>45 minutes: write and explain the worked examples below.</li><li>30 minutes: practise your project story using situation, action and result.</li><li>35 minutes: mock round and revisit only weak areas.</li></ol></details><details><summary>Last-minute speaking checklist</summary><ul><li>State the definition, purpose, example and one trade-off.</li><li>Clarify assumptions before coding or designing.</li><li>Explain a normal case, an edge case and a failure.</li><li>Be honest about what you have used in production.</li><li>If unsure, explain what you know and how you would verify the rest.</li></ul></details></div>
 <div className="card materials-filters"><label>Find a question<input type="search" value={search} placeholder="Search questions and explanations" onChange={e=>updateRouteQuery({q:e.target.value,page:null},true)}/></label><label>Show<select value={filter} onChange={e=>updateRouteQuery({filter:e.target.value,page:null})}><option value="all">All questions</option><option value="revise">Needs revision</option><option value="ready">Can explain</option></select></label></div>
 {!filtered.length&&<div className="card"><p>No questions match these filters.</p><button className="secondary" onClick={()=>updateRouteQuery({q:null,filter:null,page:null})}>Clear filters</button></div>}
 {visible.map(q=>{const id=key(q.id),record=get(id);return <article className="card material-question" key={q.id}><span className="eyebrow">{q.id.toUpperCase()} · {q.group}</span><h3>{q.question}</h3><p className="muted">Try a 30–60 second answer before revealing the explanation.</p><details><summary>Reveal answer and explanation</summary><h4>Say this</h4><p>{q.answer}</p><h4>Example and why it matters</h4><p>{q.example}</p><h4>Common mistake</h4><p>{q.mistake}</p><button className="secondary" onClick={()=>copyText(`${q.question}\n\nAnswer: ${q.answer}\nExample: ${q.example}\nAvoid: ${q.mistake}`,notice)}>Copy Q&amp;A</button></details><details><summary>My answer and revision notes</summary><Field id={id} name="notes" label="My explanation, example or question"/></details><div className="materials-actions"><button className={record.fields.rating==='revise'?'primary':'secondary'} aria-pressed={record.fields.rating==='revise'} onClick={()=>patch(id,{rating:'revise'})}>Needs revision</button><button className={record.fields.rating==='ready'?'primary':'secondary'} aria-pressed={record.fields.rating==='ready'} onClick={()=>patch(id,{rating:'ready'})}>I can explain this</button>{record.fields.rating&&<button className="secondary" onClick={()=>patch(id,{rating:''})}>Clear marker</button>}</div>{record.updatedAt&&<small>Modified {new Date(record.updatedAt).toLocaleString()} · Check the account sync indicator for cloud save.</small>}</article>})}
 <Pagination page={page} total={filtered.length} pageSize={pageSize} label={`${topic.name} questions`} onChange={n=>{updateRouteQuery({page:n});window.scrollTo({top:0,behavior:'auto'})}}/>
 <div className="card"><h2>Worked examples</h2>{workedExamples[topic.slug]?.map(ex=><details key={ex.title}><summary>{ex.title}</summary><pre><code>{ex.code}</code></pre><p>{ex.explanation}</p><p><strong>Interview follow-up:</strong> {ex.followUp}</p><button className="secondary" onClick={()=>copyText(`${ex.title}\n${ex.code}\n${ex.explanation}\n${ex.followUp}`,notice)}>Copy example</button></details>)}</div>
 <div className="card"><h2>Mini mock round</h2><p>Choose one question from this page. Explain it in one minute, apply it to a real feature in two minutes, then describe one failure and how you would diagnose it. Revisit your “Needs revision” list afterward.</p>{!!materialSources[slug]?.length&&<><h3>Official reference reading</h3><ul>{materialSources[slug].map(([label,href])=><li key={href}><a href={href} target="_blank" rel="noreferrer">{label} ↗</a></li>)}</ul><small>Check version-specific behavior against your interview company’s stack.</small></>}</div>
 </section>;
}
