'use client';
import {useEffect,useMemo,useRef,useState} from 'react';
import {Command,Search,X,Focus,Orbit,ArrowUpRight,Pause,Play} from 'lucide-react';
import {chapters,quests} from '@/lib/curriculum';
import {questionBank} from '@/lib/bank';
import {interviewTopics} from '@/lib/interview-topics';
import {workspacePaths,workspaceUrl,type WorkspaceView} from '@/lib/workspace-routes';
import {navigateWorkspace} from '@/lib/workspace-location';
import {scheduledDay,type Progress} from '@/lib/progress';

const names:Record<WorkspaceView,string>={materials:'Interview materials',autoCoach:'Auto coach',dashboard:'Today',challenges:'My challenges',studio:'Practice studio',commute:'Commute library',cartoons:'Cartoon classroom',visual:'Visual lab',profile:'My profile',timeline:'DSA learning path',planner:'My schedule',bank:'Question bank',theory:'Theory studio',brain:'Daily brainstorm',interview:'Mock interview',analytics:'Analytics',oops:'OOP studio',journey:'Course journey',quest:'Daily quest',recall:'Recall room',library:'Skill library',tasks:'Tasks and notes',settings:'Settings',communication:'Communication coach'};
const shortcuts:Partial<Record<WorkspaceView,WorkspaceView[]>>={commute:['visual','bank','recall'],bank:['visual','studio','recall'],materials:['interview','communication','recall'],visual:['bank','commute','challenges'],analytics:['planner','recall','journey'],communication:['interview','materials','quest'],oops:['visual','materials','studio'],quest:['commute','bank','communication'],cartoons:['commute','visual','bank']};
export default function LearningCockpit({p,view,focus,onFocus}:{p:Progress;view:WorkspaceView;focus:boolean;onFocus:()=>void}){
 const dialog=useRef<HTMLDialogElement>(null),input=useRef<HTMLInputElement>(null),trigger=useRef<HTMLButtonElement>(null);
 const [query,setQuery]=useState(''),[map,setMap]=useState(false),[motion,setMotion]=useState(false),[chapter,setChapter]=useState(1);
 const current=scheduledDay(p.startDate),finished=quests.filter(q=>p.days[q.day]?.completedAt).length;
 const launch=()=>{setQuery('');if(!dialog.current?.open)dialog.current?.showModal();input.current?.focus();};
 const close=()=>{dialog.current?.close();trigger.current?.focus();};
 useEffect(()=>{try{setMotion(localStorage.getItem('quest90-cockpit-motion')==='on'&&!matchMedia('(prefers-reduced-motion: reduce)').matches)}catch{};const handler=(e:KeyboardEvent)=>{if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==='k'){e.preventDefault();if(dialog.current?.open)dialog.current.close();else{setQuery('');dialog.current?.showModal();input.current?.focus();}}};window.addEventListener('keydown',handler);return()=>window.removeEventListener('keydown',handler)},[]);
 const toggleMotion=()=>{setMotion(!motion);try{localStorage.setItem('quest90-cockpit-motion',!motion?'on':'off')}catch{}};
 const entries=useMemo(()=>[
  ...Object.keys(workspacePaths).map(v=>({label:names[v as WorkspaceView],kind:'Page',path:workspaceUrl(v as WorkspaceView,current),keywords:''})),
  ...interviewTopics.map(t=>({label:`${t.name} interview guide`,kind:'Interview',path:`/interview-materials/${t.slug}/`,keywords:t.summary})),
  ...quests.map(q=>({label:`Day ${q.day} · ${q.title}`,kind:'Course',path:workspaceUrl('quest',q.day),keywords:q.mission})),
  ...questionBank.map(q=>({label:q.title,kind:q.kind,path:`/questions/?question=${encodeURIComponent(q.id)}`,keywords:q.topic}))
 ],[current]);
 const words=query.trim().toLowerCase().split(/\s+/).filter(Boolean),matches=entries.filter(e=>words.every(w=>`${e.label} ${e.kind} ${e.keywords}`.toLowerCase().includes(w))),results=matches.slice(0,30);
 const visit=(path:string)=>{close();navigateWorkspace(path);window.scrollTo({top:0,behavior:'instant'});};
 const c=chapters.find(c=>c.id===chapter)||chapters[0],chapterQuests=quests.filter(q=>q.chapter===c.id),done=chapterQuests.filter(q=>p.days[q.day]?.completedAt).length;
 return <section className={`learning-cockpit ${motion?'cockpit-motion':''}`} aria-label="Learning cockpit">
  <div className="cockpit-rail"><div className="cockpit-location"><span className="cockpit-beacon" aria-hidden="true"/><span><small>LEARNING COCKPIT</small><strong>{names[view]}</strong></span></div><div className="cockpit-actions"><button ref={trigger} onClick={launch}><Search size={16}/><span>Find anything</span><kbd>Ctrl / ⌘ K</kbd></button><button onClick={()=>setMap(!map)} aria-expanded={map} aria-controls="course-constellation"><Orbit size={16}/><span>Course map</span></button><button onClick={onFocus} aria-pressed={focus}><Focus size={16}/><span>{focus?'Exit focus':'Focus'}</span></button><button onClick={toggleMotion} aria-pressed={motion} aria-label={motion?'Pause decorative animation':'Enable decorative animation'}>{motion?<Pause size={16}/>:<Play size={16}/>}</button></div></div>
  <div className="cockpit-connections"><small>CONNECT THIS SESSION</small>{(shortcuts[view]||['commute','challenges','analytics'] as WorkspaceView[]).map((v,i)=><a key={v} href={workspaceUrl(v,current)} onClick={e=>{if(e.metaKey||e.ctrlKey||e.shiftKey||e.altKey)return;e.preventDefault();navigateWorkspace(workspaceUrl(v,current));window.scrollTo(0,0);}}><span>{String(i+1).padStart(2,'0')}</span>{names[v]}<ArrowUpRight size={13}/></a>)}</div>
  {map&&<div id="course-constellation" className="cockpit-map"><div className="cockpit-map-heading"><div><span className="eyebrow">YOUR COURSE CONSTELLATION</span><h2>Every chapter connects to the next.</h2><p>{finished} of 90 days completed. Select a chapter to find your next mission.</p></div><div className="cockpit-planet" aria-hidden="true"><Orbit size={55}/></div></div><div className="cockpit-nodes">{chapters.map((ch,i)=>{const qs=quests.filter(q=>q.chapter===ch.id),n=qs.filter(q=>p.days[q.day]?.completedAt).length;return <button key={ch.id} onClick={()=>setChapter(ch.id)} aria-pressed={chapter===ch.id} className={n===qs.length?'node-complete':''}><span className="cockpit-node">{String(i+1).padStart(2,'0')}</span><strong>{ch.name}</strong><small>{n}/{qs.length} days</small><progress value={n} max={qs.length} aria-label={`${ch.name} completed days`}/></button>})}</div><div className="cockpit-chapter"><div><h3>{c.name}</h3><p>{c.description}</p><small>{done}/{chapterQuests.length} course days completed · all missions stay unlocked</small></div><div>{chapterQuests.map(q=><a key={q.day} className={p.days[q.day]?.completedAt?'is-complete':''} href={workspaceUrl('quest',q.day)} onClick={e=>{if(e.metaKey||e.ctrlKey||e.shiftKey||e.altKey)return;e.preventDefault();navigateWorkspace(workspaceUrl('quest',q.day));window.scrollTo(0,0);}} title={q.title}>Day {q.day}{p.days[q.day]?.completedAt?' ✓':''}</a>)}</div></div></div>}
  <dialog ref={dialog} className="cockpit-dialog" aria-label="Search learning destinations" onCancel={()=>trigger.current?.focus()} onClick={e=>{if(e.target===e.currentTarget)close()}}><div className="cockpit-search-top"><Command size={22}/><h2>Where do you want to learn?</h2><button onClick={close} aria-label="Close search"><X size={20}/></button></div><label htmlFor="cockpit-search">Search pages, course missions and question titles</label><input id="cockpit-search" ref={input} value={query} onChange={e=>setQuery(e.target.value)} placeholder="Try: React, Two Sum, Day 10, SQL…" onKeyDown={e=>{if(e.key==='Enter'&&results[0])visit(results[0].path)}}/><p className="cockpit-result-count">{matches.length} results{matches.length>30?' · showing first 30; add another word to narrow':''}. Tab to choose, Enter to open.</p><div className="cockpit-results">{results.map(r=><a key={r.path} href={r.path} onClick={e=>{if(e.metaKey||e.ctrlKey||e.shiftKey||e.altKey)return;e.preventDefault();visit(r.path)}}><span><small>{r.kind}</small><strong>{r.label}</strong><code>{r.path}</code></span><ArrowUpRight size={18}/></a>)}{!results.length&&<p>No match. Try a topic name or a day number.</p>}</div></dialog>
 </section>;
}
