'use client';
import {useRef,useState} from 'react';
import type {SupabaseClient,User} from '@supabase/supabase-js';
import {imageRecords} from './Screenshots';
import {localImages,localImageSave,Screenshot} from '@/lib/local-db';
export function MediaBackup({client,user}:{client:SupabaseClient|null;user:User|null}){
 const [message,setMessage]=useState(''),[busy,setBusy]=useState(false),input=useRef<HTMLInputElement>(null);
 async function run(fn:()=>Promise<void>){setBusy(true);setMessage('');try{await fn()}catch(e){setMessage((e as Error).message)}finally{setBusy(false)}}
 async function save(images:Screenshot[]){for(const image of images){const record={...image,user_id:user?.id||'guest'};if(client&&user){const {error}=await client.from('training_images').upsert(record);if(error)throw new Error(`Import stopped: ${error.message}. Already imported images remain saved; retrying is safe.`)}else await localImageSave(record)}setMessage(`${images.length} screenshots imported.`)}
 async function restore(file?:File){if(!file)return;await run(async()=>{if(file.size>150000000)throw new Error('Use a screenshot backup below 150 MB.');const data=JSON.parse(await file.text());if(data.app!=='Quest90-media'||!Array.isArray(data.images))throw new Error('This is not a screenshot backup.');const counts=new Map<string,number>();for(const x of data.images){if(!x||!/^\w{8}-\w{4}-\w{4}-\w{4}-\w{12}$/.test(x.id)||typeof x.context_id!=='string'||x.context_id.length>160||typeof x.name!=='string'||x.name.length>300||typeof x.data_url!=='string'||x.data_url.length>3000000||!/^data:image\/(png|jpeg|webp);base64,[A-Za-z0-9+/=]+$/.test(x.data_url)||!Number.isFinite(Date.parse(x.created_at)))throw new Error('Invalid screenshot record.');counts.set(x.context_id,(counts.get(x.context_id)||0)+1);if(counts.get(x.context_id)!>10)throw new Error('A context contains more than 10 images.');}if(confirm(`Import ${data.images.length} screenshots into ${user?'your account':'this device'}? Matching image IDs will be replaced.`))await save(data.images)});if(input.current)input.current.value=''}
 return <section className="card"><h2>Screenshot backups</h2><p>Images are separate base64 records. Keep this backup together with your progress export.</p><div className="button-stack"><button className="secondary" disabled={busy} onClick={()=>void run(async()=>{const images=await imageRecords(client,user),url=URL.createObjectURL(new Blob([JSON.stringify({app:'Quest90-media',exportedAt:new Date().toISOString(),images})],{type:'application/json'})),a=document.createElement('a');a.href=url;a.download='quest90-screenshots.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);setMessage(`Exported ${images.length} screenshots.`)})}>Export screenshots</button><button className="secondary" disabled={busy} onClick={()=>input.current?.click()}>Import screenshot backup</button>{user&&<button className="secondary" disabled={busy} onClick={()=>void run(async()=>{const images=await localImages();if(confirm(`Copy ${images.length} guest screenshots to your account?`))await save(images)})}>Copy guest screenshots to account</button>}</div><input ref={input} type="file" hidden accept="application/json,.json" onChange={e=>void restore(e.target.files?.[0])}/>{(busy||message)&&<p role="status">{busy?'Working…':message}</p>}</section>
}
