'use client';
import {useState} from 'react';
import {questionBank} from '@/lib/bank';
import {useStudio,Field,Attempts,copyText,saveFile} from './studio/StudioContext';

function safeUrl(raw:string){try{const u=new URL(raw);return ['https:','http:'].includes(u.protocol)&&!u.username&&!u.password?u.href:null}catch{return null}}
export default function PracticePassport(){
 const {p,get,patch,submit,notice,practice}=useStudio();const records=Object.entries(p.studio||{}).filter(([id])=>id.startsWith('passport-')).sort((a,b)=>b[1].updatedAt.localeCompare(a[1].updatedAt));
 const [selected,setSelected]=useState(records[0]?.[0]||''),[kind,setKind]=useState('problem'),[title,setTitle]=useState('Two Sum');
 const r=get(selected),f=r.fields,isContest=f.kind==='contest',savedHere=r.attempts.some(a=>a.outcome==='Portal attempt saved'),linked=questionBank.find(q=>q.kind==='DSA'&&q.title.toLowerCase()===(f.title||'').toLowerCase());
 const portalAttempts=records.filter(([,r])=>r.attempts.some(a=>a.outcome==='Portal attempt saved')).length,external=records.filter(([,r])=>r.attempts.some(a=>a.outcome==='External practice reflection')).length;
 function create(){if(!title.trim()){notice('Give this entry a problem or contest name.');return}const id=`passport-${crypto.randomUUID()}`;patch(id,{title:title.trim(),kind,createdAt:new Date().toISOString(),portal:'LeetCode',status:'Attempted'});if(get(id).fields.kind)setSelected(id)}
 function finish(){if(!isContest&&!savedHere){notice('Save your portal attempt first.');return}if(!f.reflection?.trim()){notice('Write one thing you learned before submitting.');return}if(f.url&&!safeUrl(f.url)){notice('Use a complete HTTP(S) link without embedded credentials.');return}if(f.minutes&&(!Number.isInteger(Number(f.minutes))||Number(f.minutes)<0||Number(f.minutes)>1440)){notice('Minutes must be a whole number from 0 to 1440.');return}if(isContest){const rank=f.rank?Number(f.rank):null,total=f.participants?Number(f.participants):null;if((rank!==null&&(!Number.isSafeInteger(rank)||rank<1))||(total!==null&&(!Number.isSafeInteger(total)||total<1))||(rank!==null&&total!==null&&rank>total)){notice('Use a positive whole-number rank and participant count; rank cannot exceed participants. Leave unknown values blank.');return}}submit(selected,isContest?'Contest reflection':'External practice reflection')}
 return <div className="adventure"><section className="card"><span className="eyebrow">YOUR PRACTICE PASSPORT</span><h2>Practice here. Try it elsewhere. Bring back what you learned.</h2><p>{portalAttempts} entries with portal attempts · {external} with external reflections · {records.filter(([,r])=>r.fields.kind==='contest').length} contest journals. Counts describe your records, not verified platform results.</p><div className="adventure-form"><label>Entry type<select value={kind} onChange={e=>setKind(e.target.value)}><option value="problem">Problem practice</option><option value="contest">Contest / tournament</option></select></label><label>Problem or contest name<input maxLength={160} value={title} onChange={e=>setTitle(e.target.value)} list="passport-problems"/></label><datalist id="passport-problems">{questionBank.filter(q=>q.kind==='DSA').map(q=><option key={q.id} value={q.title}/>)}</datalist><button className="primary" onClick={create}>Start a new entry</button></div><p>External results and ranks are self-reported. This does not sign in to, fetch, or submit answers to another website.</p></section>
 {!!records.length&&<section className="card"><label>Continue or review an entry<select value={selected} onChange={e=>setSelected(e.target.value)}><option value="" disabled>Select an entry</option>{records.map(([id,r])=><option key={id} value={id}>{r.fields.title} · {r.fields.kind} · {r.attempts.length} checkpoints</option>)}</select></label></section>}
 {selected&&<><section className="card"><span className="eyebrow">{isContest?'CONTEST LOG':'01 · SOLVE IN YOUR PORTAL'}</span><h2>{f.title}</h2>{!isContest&&<><p>Attempt the problem here before checking an external solution. A saved attempt can be incomplete; record the point where you got stuck.</p>{linked&&<button className="secondary" onClick={()=>practice(linked.id)}>Open {linked.title} in the question bank →</button>}<Field id={selected} name="internalAnswer" label="My portal solution / pseudocode"/><Field id={selected} name="complexity" label="Approach, time/space costs, and edge cases" rows={3}/><button className="primary" onClick={()=>{if(!f.internalAnswer?.trim()){notice('Write your attempt first, even if incomplete.');return}submit(selected,'Portal attempt saved')}}>Save portal attempt</button><p>{savedHere?'✓ Portal checkpoint saved. Continue to external practice below.':'External submission unlocks after you save this attempt.'}</p>{linked&&(p.practice?.[linked.id]?.attempts?.length||0)>0&&<p>You also have {p.practice?.[linked.id]?.attempts.length} saved question-bank attempts. They remain in the question bank.</p>}</>}</section>
 <section className="card"><h3>{isContest?'🏆 Record your contest experience':'02 · Practice on another platform'}</h3><fieldset disabled={!isContest&&!savedHere}><div className="adventure-form"><label>Platform<select value={f.portal||'LeetCode'} onChange={e=>patch(selected,{portal:e.target.value})}>{['LeetCode','Codeforces','HackerRank','GeeksforGeeks','Quest90 solo tournament','Other'].map(x=><option key={x}>{x}</option>)}</select></label>{f.portal==='Other'&&<label>Platform name<input maxLength={100} value={f.platformName||''} onChange={e=>patch(selected,{platformName:e.target.value})}/></label>}<label>Date<input type="date" value={f.date||''} onChange={e=>patch(selected,{date:e.target.value})}/></label><label>Minutes spent<input type="number" min={0} max={1440} value={f.minutes||''} onChange={e=>patch(selected,{minutes:e.target.value})}/></label></div><label>Problem / submission / contest URL<input maxLength={2000} value={f.url||''} onChange={e=>patch(selected,{url:e.target.value})} placeholder="https://…"/></label>{safeUrl(f.url||'')&&<a target="_blank" rel="noreferrer" href={safeUrl(f.url!)!}>Open your saved link ↗</a>}{!isContest&&savedHere&&f.title?.toLowerCase()==='two sum'&&<p><a href="https://leetcode.com/problems/two-sum/" target="_blank" rel="noreferrer">Try Two Sum on LeetCode ↗</a> — record your own result here afterward.</p>}<label>Outcome<select value={f.status||'Attempted'} onChange={e=>patch(selected,{status:e.target.value})}>{['Attempted','Solved independently','Solved with hints','Read solution, retry needed','Not finished'].map(x=><option key={x}>{x}</option>)}</select></label>{isContest&&<><div className="adventure-form"><label>Rank (leave blank if unknown)<input type="number" min="1" step="1" value={f.rank||''} onChange={e=>patch(selected,{rank:e.target.value})}/></label><label>Total participants (optional)<input type="number" min="1" step="1" value={f.participants||''} onChange={e=>patch(selected,{participants:e.target.value})}/></label></div><Field id={selected} name="solvedQuestions" label="Which questions did I solve? Titles, links, and approaches"/><Field id={selected} name="unsolvedQuestions" label="Which questions remain? Where did I lose time?"/></>}<Field id={selected} name="stuck" label="Where did I get stuck? What hint changed my thinking?"/><Field id={selected} name="reflection" label="What did I learn? Compare with my earlier attempt."/><Field id={selected} name="nextAction" label="My next concrete action" rows={3}/><label>Retry on<input type="date" value={f.retryOn||''} onChange={e=>patch(selected,{retryOn:e.target.value})}/></label><button className="primary" onClick={finish}>Submit {isContest?'contest':'external practice'} reflection</button></fieldset><small>Each submission preserves a snapshot; edits do not rewrite older checkpoints. Retry dates are planning notes, not automatic notifications.</small></section>
 <section className="card"><h3>03 · Keep your learning trail</h3><div className="button-row"><button className="secondary" onClick={()=>copyText(`Review my ${isContest?'contest reflection':'problem-solving progression'}. Compare attempts, find the main learning gap, and suggest one next exercise. Do not infer a verified rank or result.\n${JSON.stringify(r,null,2)}`,notice)}>Copy all as a coaching prompt</button><button className="secondary" onClick={()=>saveFile(`quest90-${selected}.json`,JSON.stringify(r,null,2),'application/json')}>Export entry</button></div><Attempts id={selected}/></section></>}
 </div>;
}
