'use client';
import {useRouteQuery,updateRouteQuery,routePage} from '@/lib/workspace-location';
import {dayProgress,weekProgress} from '@/lib/course-progress';
import {dayDate,type Progress} from '@/lib/progress';
export function LearningProgressBar({value,label}:{value:number;label:string}){return <div className="progress-track" role="progressbar" aria-label={label} aria-valuemin={0} aria-valuemax={100} aria-valuenow={value}><span style={{width:`${value}%`}}/></div>}
export default function ProgressOverview({p,day,open}:{p:Progress;day:number;open:(day:number)=>void}){
 const params=useRouteQuery(),week=params.has('progressWeek')?Math.min(13,routePage(params.get('progressWeek'))):Math.ceil(day/7),setWeek=(week:number)=>updateRouteQuery({progressWeek:week}),current=dayProgress(p,day),selected=weekProgress(p,week),weeks=Array.from({length:13},(_,i)=>weekProgress(p,i+1)),done=weeks.reduce((n,w)=>n+w.done,0),total=weeks.reduce((n,w)=>n+w.total,0);
 return <section className="card progress-overview"><div className="section-heading"><div><span className="eyebrow">DAY → WEEK → COURSE</span><h2>Your recorded progress</h2></div><strong>{Math.round(done/total*100)}% overall</strong></div><LearningProgressBar value={Math.round(done/total*100)} label="Overall learning progress"/><p>Checklist steps + assigned DSA marked solved + speaking reps. These record your work, not an interview-readiness score. Skipped work is not counted as complete.</p><div className="progress-summary-grid"><article><h3>Day {day} · {current.percent}%</h3><LearningProgressBar value={current.percent} label={`Day ${day} learning progress`}/><p>{current.steps}/{current.stepTotal} steps · {current.dsa}/{current.dsaTotal} DSA · {current.speaking}/1 speaking</p><button className="secondary" onClick={()=>open(day)}>Continue Day {day}</button></article><article><label>Course week<select value={week} onChange={e=>setWeek(Number(e.target.value))}>{weeks.map(w=><option key={w.week} value={w.week}>Week {w.week} · Days {w.start}–{w.end} · {w.percent}%</option>)}</select></label><h3>Week {week} · {selected.percent}%</h3><LearningProgressBar value={selected.percent} label={`Week ${week} learning progress`}/><p>{selected.done}/{selected.total} recorded requirements · {dayDate(p.startDate,selected.start-1)} to {dayDate(p.startDate,selected.end-1)}</p></article></div><div className="week-progress-days">{selected.days.map(d=><button key={d.day} className="secondary" onClick={()=>open(d.day)}><strong>Day {d.day}</strong><LearningProgressBar value={d.percent} label={`Day ${d.day} progress`}/><span>{d.percent}% · {d.done}/{d.total}</span></button>)}</div><div className="pagination"><button className="secondary" disabled={week===1} onClick={()=>setWeek(week-1)}>← Previous week</button><span>Week {week} of 13</span><button className="secondary" disabled={week===13} onClick={()=>setWeek(week+1)}>Next week →</button></div></section>;
}
