import {ArrowRight} from 'lucide-react';
export default function ReadingDataView({id,step}:{id:string;step:number}){
  if(id==='guide-closures')return <figure className="reading-data-view"><figcaption>Two separate lexical environments</figcaption><div className="closure-environments">{['A','B'].map((label,i)=><div key={label}><strong>Counter {label}</strong><span>{i===1&&step===0?'Not created yet':`count = ${i===0?(step>=3?2:step>=2?1:0):0}`}</span><small>increment() / read()</small><ArrowRight size={17}/><span>Own count binding</span></div>)}</div></figure>;
  if(id==='guide-event-loop'){
    const outputs=[['A'],['A'],['A'],['A','D'],['A','D','C'],['A','D','C','B']][step];
    return <figure className="reading-data-view"><figcaption>Browser execution lanes · illustrated snapshot</figcaption><div className="event-lanes"><div><strong>Call stack</strong><span>{step<=3?'Current script':step===4?'Promise reaction C':'Timer callback B'}</span></div><div><strong>Microtasks</strong><span>{step===2||step===3?'C waiting':'Empty'}</span></div><div><strong>Timer</strong><span>{step===0?'Not registered':step<5?'B scheduled; waits for a task turn':'B runs'}</span></div><div><strong>Console</strong><span>{outputs.join(' → ')}</span></div></div></figure>;
  }
  if(id==='guide-two-sum')return <figure className="reading-data-view"><figcaption>Scan once; remember earlier values</figcaption><div className="reading-array">{[2,7,11].map((n,i)=><div key={i} className={(step===3&&i===1||step>0&&step<3&&i===0)?'active':''}><small>index {i}</small><strong>{n}</strong><span>{step===3&&i<2?'Found pair':step>0&&i===(step===3?1:0)?'Current':' '}</span></div>)}</div><div className="reading-map"><strong>Earlier values → indices</strong><span>{step>=2?'2 → 0':'Empty map'}</span><span>Need: {step===0?'not calculated':step===3?'9 − 7 = 2':'9 − 2 = 7'}</span></div></figure>;
  if(id==='guide-sql-where')return <figure className="reading-data-view"><figcaption>Filter salary ≥ 50,000; only TRUE passes</figcaption><div className="reading-table-scroll"><table><thead><tr><th>Name</th><th>Salary</th><th>Predicate</th><th>Result</th></tr></thead><tbody>{[['Asha','70000','TRUE'],['Ravi','45000','FALSE'],['Mina','NULL','UNKNOWN']].map(([name,salary,predicate],i)=><tr key={name} className={step>=2&&i>0?'excluded':''}><td>{name}</td><td>{salary}</td><td>{step>0?predicate:'Pending'}</td><td>{step>=2?(i===0?'Keep':'Exclude'):'Evaluate next'}</td></tr>)}</tbody></table></div></figure>;
  if(id==='guide-usememo')return <figure className="reading-data-view"><figcaption>Memo dependency check · conceptual model</figcaption><div className="memo-model"><div><strong>Dependencies</strong><span>items: same reference</span><span>query: {step===3?'a → ab':'a'}</span></div><ArrowRight aria-hidden/><div><strong>{step===0||step===3?'Calculate':'Compare / reuse'}</strong><span>{step===0?'First render: filter items':step===3?'Changed dependency: filter again':'Unchanged: reuse prior result'}</span></div></div><small>The memo is local to this component instance and hook. React may discard cached values.</small></figure>;
  return null;
}
