'use client';
import {useEffect,useRef,useState} from 'react';
import {Clock3,Trophy,ArrowLeft,ArrowRight,Download} from 'lucide-react';
import {visualScenarios} from '@/lib/visual-scenarios';
import {gradeRound,readProblems,readStringMap,readResults,snapshotProblems} from '@/lib/scenario-tournaments';
import {validateProgress,type Progress} from '@/lib/progress';
import type {StudioRecord} from '@/lib/studio-state';
import {saveFile} from './studio/StudioContext';

type Props={p:Progress;commit:(p:Progress)=>void;notice:(s:string)=>void};
const prefix='solo-round-';
export default function ScenarioTournament({p,commit,notice}:Props){
 const latest=useRef(p);latest.current=p;
 const rounds=Object.entries(p.studio||{}).filter(([id,r])=>id.startsWith(prefix)&&r.fields.type==='scenario-tournament').sort((a,b)=>(b[1].fields.startedAt||'').localeCompare(a[1].fields.startedAt||''));
 const active=rounds.find(([,r])=>r.fields.status==='active');
 const [selected,setSelected]=useState(active?.[0]||''),[index,setIndex]=useState(0),[size,setSize]=useState(4),[minutes,setMinutes]=useState(20),[topic,setTopic]=useState('All'),[difficulty,setDifficulty]=useState('All'),[now,setNow]=useState(()=>Date.now());
 useEffect(()=>{const timer=setInterval(()=>setNow(Date.now()),1000);return()=>clearInterval(timer)},[]);
 function write(id:string,r:StudioRecord){const next={...latest.current,updatedAt:new Date().toISOString(),studio:{...latest.current.studio,[id]:r}};try{validateProgress(next);latest.current=next;commit(next);return true}catch(e){notice(e instanceof Error?e.message:'Round could not be saved.');return false}}
 function finish(id:string,reason:string){const r=latest.current.studio?.[id];if(!r||r.fields.status!=='active')return;const problems=readProblems(r.fields.problems),savedAnswers=readStringMap(r.fields.answers);if(!problems||!savedAnswers){notice('This round has no readable problem snapshot. Export your data before making changes.');return}const result=gradeRound(problems,savedAnswers),at=new Date().toISOString(),score=result.reduce((sum,q)=>sum+q.points,0),fields={...r.fields,status:'finished',finishedAt:at,finishReason:reason,result:JSON.stringify(result),score:String(score),maximum:String(result.length*100)};if(write(id,{fields,updatedAt:at,attempts:[...r.attempts,{id:crypto.randomUUID(),at,fields:{...fields},outcome:`${score}/${result.length*100} · ${reason}`,hints:0}]}))notice(reason==='Time expired'?'Time is up. Your saved answers have been scored.':'Round submitted. Review the explanations below.')}
 useEffect(()=>{if(active&&readProblems(active[1].fields.problems)&&readStringMap(active[1].fields.answers)&&Number.isFinite(Number(active[1].fields.deadline))&&Date.now()>=Number(active[1].fields.deadline))finish(active[0],'Time expired')},[now,active?.[0],active?.[1].fields.deadline]);
 const eligible=visualScenarios.filter(q=>(topic==='All'||q.topic===topic)&&(difficulty==='All'||q.difficulty===difficulty));
 function start(){if(Object.values(latest.current.studio||{}).some(r=>r.fields.type==='scenario-tournament'&&r.fields.status==='active')){notice('Resume and finish your active round first.');return}if(eligible.length<size)return;const problems=snapshotProblems(eligible,size),at=new Date().toISOString(),id=prefix+crypto.randomUUID(),fields={type:'scenario-tournament',rulesVersion:'1',status:'active',startedAt:at,deadline:String(Date.now()+minutes*60000),duration:String(minutes),topic,difficulty,problems:JSON.stringify(problems),answers:'{}',scratch:'{}'};if(write(id,{fields,attempts:[],updatedAt:at})){setSelected(id);setIndex(0);setNow(Date.now())}}
 const record=p.studio?.[selected],fields=record?.fields,problems=readProblems(fields?.problems)||[],answers=readStringMap(fields?.answers)||{},scratch=readStringMap(fields?.scratch)||{},results=readResults(fields?.result)||[],invalid=!!fields&&(!readProblems(fields.problems)||!readStringMap(fields.answers)||!readStringMap(fields.scratch)||!fields.deadline||!Number.isFinite(Number(fields.deadline))||Number(fields.deadline)<=0||(fields.status==='finished'&&!readResults(fields.result))),running=fields?.status==='active'&&!invalid,q=problems[Math.min(index,Math.max(0,problems.length-1))],remaining=Math.max(0,Math.ceil((Number(fields?.deadline||0)-now)/1000));
 function edit(name:'answers'|'scratch',value:string){const r=latest.current.studio?.[selected];if(!r||r.fields.status!=='active'||!q)return;if(Date.now()>=Number(r.fields.deadline)){finish(selected,'Time expired');return}const values=readStringMap(r.fields[name]);if(!values){notice('The saved round needs recovery. Export it first.');return}write(selected,{...r,updatedAt:new Date().toISOString(),fields:{...r.fields,[name]:JSON.stringify({...values,[q.id]:value})}})}
 const completed=rounds.filter(([,r])=>r.fields.status==='finished'&&Number.isFinite(Number(r.fields.score))&&Number(r.fields.maximum)>0);
 return <div className="scenario-tournament"><section className="card tournament-hero"><Trophy size={30}/><div><span className="eyebrow">SOLO SCENARIO TOURNAMENTS</span><h2>Race the clock. Review the reasoning.</h2><p>Timed input/output challenges with saved drafts and a personal score history. These are output-prediction rounds, not a coding judge or public multiplayer contest.</p></div></section>
 <section className="card"><h3>Round rules</h3><ul><li>100 points per exact JSON result. No speed bonus or partial credit. Object key order is ignored; array order and value types matter.</li><li>Examples: <code>[0,1]</code>, <code>3</code>, <code>null</code>, or the object required by the problem. Do not add Markdown fences.</li><li>Answers can change until submission or the deadline. Correct answers and explanations appear after the round.</li><li>The timer continues while you leave the page and is checked on return using your device clock. Only saved drafts can be recovered on another device; check the account save status.</li></ul><p>{completed.length} rounds completed · best accuracy {completed.length?Math.max(...completed.map(([,r])=>Math.round(Number(r.fields.score)/Number(r.fields.maximum)*100))):0}% · self-practice, no global rating</p></section>
 {invalid&&record&&<section className="card"><h3>This saved round needs recovery</h3><p>Its stored fields are incomplete or invalid. Export them before starting a replacement; existing work will be kept.</p><button className="secondary" onClick={()=>saveFile(`quest90-round-recovery-${selected}.json`,JSON.stringify(record,null,2),'application/json')}>Export saved round</button><button className="secondary" onClick={()=>write(selected,{...record,updatedAt:new Date().toISOString(),fields:{...record.fields,status:'invalid'}})}>Archive invalid round</button></section>}{!running&&<section className="card"><h3>Create a round</h3>{active?<button className="primary" onClick={()=>{setSelected(active[0]);setIndex(0)}}>Resume active round</button>:<><div className="tournament-config"><label>Topic<select value={topic} onChange={e=>setTopic(e.target.value)}><option>All</option>{[...new Set(visualScenarios.map(q=>q.topic))].map(t=><option key={t}>{t}</option>)}</select></label><label>Difficulty<select value={difficulty} onChange={e=>setDifficulty(e.target.value)}>{['All',...new Set(visualScenarios.map(q=>q.difficulty))].map(d=><option key={d}>{d}</option>)}</select></label><label>Questions<select value={size} onChange={e=>setSize(Number(e.target.value))}>{[4,6,8].map(n=><option key={n}>{n}</option>)}</select></label><label>Minutes<select value={minutes} onChange={e=>setMinutes(Number(e.target.value))}>{[10,20,30,45].map(n=><option key={n}>{n}</option>)}</select></label></div><p>{eligible.length} matching scenarios. A round contains no duplicate IDs and mixes topics where possible.</p><button className="primary" disabled={eligible.length<size} onClick={start}>Start {minutes}-minute round</button></>}</section>}
 {running&&q&&<section className="card"><div className="tournament-status"><strong><Clock3 size={19}/> {Math.floor(remaining/60)}:{String(remaining%60).padStart(2,'0')} remaining</strong><span>{Object.values(answers).filter(a=>a.trim()).length}/{problems.length} answers drafted</span><button className="primary" onClick={()=>finish(selected,Date.now()>=Number(fields?.deadline)?'Time expired':'Submitted early')}>Submit round</button></div><div className="tournament-question-nav" aria-label="Round questions">{problems.map((problem,i)=><button className="secondary" aria-pressed={q.id===problem.id} key={problem.id} onClick={()=>setIndex(i)}>{i+1}{answers[problem.id]?.trim()?' · drafted':''}</button>)}</div><span className="eyebrow">{q.topic} · {q.difficulty} · 100 points</span><h3>{q.title}</h3><p>{q.prompt}</p><h4>Input</h4><pre>{JSON.stringify(q.input,null,2)}</pre><label className="field-label">Your predicted result (JSON)<textarea rows={4} value={answers[q.id]||''} maxLength={2000} disabled={remaining===0} onChange={e=>edit('answers',e.target.value)} placeholder="Enter the return value specified by this question"/></label><label className="field-label">Scratch code / reasoning (saved, not graded)<textarea rows={6} value={scratch[q.id]||''} maxLength={2000} disabled={remaining===0} onChange={e=>edit('scratch',e.target.value)} placeholder="Trace values or write your own algorithm here. This editor does not execute code."/></label><div className="button-row"><button className="secondary" disabled={index===0} onClick={()=>setIndex(i=>i-1)}><ArrowLeft size={16}/>Previous</button><button className="secondary" disabled={index===problems.length-1} onClick={()=>setIndex(i=>i+1)}>Next<ArrowRight size={16}/></button></div></section>}
 {fields?.status==='finished'&&!invalid&&<section className="card"><span className="eyebrow">ROUND REVIEW</span><h2>{fields.score} / {fields.maximum} points</h2><p>{fields.finishReason} · {new Date(fields.startedAt).toLocaleString()} · {fields.duration} minute budget</p><button className="secondary" onClick={()=>saveFile(`quest90-round-${selected}.json`,JSON.stringify({rules:fields.rulesVersion,startedAt:fields.startedAt,finishedAt:fields.finishedAt,results,scratch,snapshots:record?.attempts},null,2),'application/json')}><Download size={16}/>Export round</button>{results.map(result=><details className={`tournament-result ${result.correct?'correct':'review'}`} key={result.id}><summary>{result.correct?'✓':'Review'} {result.title} · {result.points}/100</summary><p>{result.prompt}</p><h4>Input</h4><pre>{JSON.stringify(result.input)}</pre><h4>Your answer</h4><pre>{result.submitted||'(unanswered)'}</pre>{!result.validJson&&<p>Answer was missing or was not valid finite JSON.</p>}<h4>Expected result</h4><pre>{JSON.stringify(result.expected,null,2)}</pre><p>{result.explanation}</p>{scratch[result.id]&&<><h4>Your scratch work</h4><pre>{scratch[result.id]}</pre></>}</details>)}</section>}
 {record&&record.attempts.some(a=>a.outcome==='Recovered tournament snapshot')&&<section className="card"><h3>Recovered draft history</h3><p>Work recovered from another save is kept here without reopening your submitted round.</p>{record.attempts.filter(a=>a.outcome==='Recovered tournament snapshot').map(a=><details className="tournament-result" key={a.id}><summary>{new Date(a.at).toLocaleString()} · recovered draft</summary><h4>Answers</h4><pre>{JSON.stringify(readStringMap(a.fields.answers)||{},null,2)}</pre><h4>Scratch work</h4><pre>{JSON.stringify(readStringMap(a.fields.scratch)||{},null,2)}</pre><button className="secondary" onClick={()=>saveFile(`quest90-snapshot-${a.id}.json`,JSON.stringify(a,null,2),'application/json')}>Export snapshot</button></details>)}</section>}
 {!!rounds.length&&<section className="card"><h3>Your round history</h3><p>Personal results only. Different problem selections and difficulty settings are not directly comparable ratings.</p><div className="tournament-history">{rounds.map(([id,r])=><button className="secondary" key={id} onClick={()=>{setSelected(id);setIndex(0)}}><span>{new Date(r.fields.startedAt).toLocaleString()}</span><strong>{r.fields.status==='finished'?`${r.fields.score}/${r.fields.maximum}`:r.fields.status==='active'?'Resume':'View saved record'}</strong><small>{r.fields.topic} · {r.fields.difficulty} · {r.fields.duration} min</small></button>)}</div></section>}
 </div>;
}
