'use client';
import {useEffect,useRef,useState} from 'react';
import type {SupabaseClient,User} from '@supabase/supabase-js';
import {ImagePlus,Trash2,Download,X} from 'lucide-react';
import {localImages,localImageSave,localImageDelete,Screenshot} from '@/lib/local-db';
export async function imageRecords(client:SupabaseClient|null,user:User|null,context?:string){if(!client||!user)return localImages(context);const all:Screenshot[]=[];for(let offset=0;;offset+=100){let query=client.from('training_images').select('*').eq('user_id',user.id).order('id').range(offset,offset+99);if(context)query=query.eq('context_id',context);const {data,error}=await query;if(error)throw new Error(error.message);all.push(...data as Screenshot[]);if(data.length<100)return all;}}
export async function encodeScreenshot(file:File){if(!['image/png','image/jpeg','image/webp'].includes(file.type))throw new Error('Use PNG, JPEG, or WebP screenshots.');if(file.size>2*1024*1024)throw new Error('Each screenshot must be 2 MB or smaller.');const bitmap=await createImageBitmap(file);const pixels=bitmap.width*bitmap.height;bitmap.close();if(pixels>25000000)throw new Error('Use an image below 25 megapixels.');return new Promise<string>((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(String(r.result));r.onerror=()=>reject(new Error('The image could not be read.'));r.readAsDataURL(file)})}
export function Screenshots({context,client,user}:{context:string;client:SupabaseClient|null;user:User|null}){
 const [images,setImages]=useState<Screenshot[]>([]),[error,setError]=useState(''),[busy,setBusy]=useState(false),[preview,setPreview]=useState<Screenshot|null>(null);const fileRef=useRef<HTMLInputElement>(null),generation=useRef(0);
 useEffect(()=>{const g=++generation.current;setImages([]);setError('');void imageRecords(client,user,context).then(x=>{if(g===generation.current)setImages(x)}).catch(e=>{if(g===generation.current)setError(e.message)});return()=>{generation.current++}},[client,user?.id,context]);
 async function upload(files:FileList|null){if(!files)return;const g=generation.current;setBusy(true);setError('');try{if(images.length+files.length>10)throw new Error('Up to 10 screenshots per question, lesson or quest. Export and remove an image to make room.');for(const file of Array.from(files)){const data_url=await encodeScreenshot(file);if(g!==generation.current)return;const record:Screenshot={id:crypto.randomUUID(),user_id:user?.id||'guest',context_id:context,name:file.name.slice(0,300),data_url,created_at:new Date().toISOString()};if(client&&user){const {error:e}=await client.from('training_images').insert(record);if(e)throw new Error(e.message)}else await localImageSave(record);if(g===generation.current)setImages(old=>[...old,record]);}}catch(e){if(g===generation.current)setError(e instanceof Error?e.message:'Image save failed.')}finally{if(g===generation.current)setBusy(false);if(fileRef.current)fileRef.current.value=''}}
 async function remove(img:Screenshot){if(!confirm(`Delete ${img.name}? Download it first if you want to keep a copy.`))return;setError('');try{if(client&&user){const {error:e}=await client.from('training_images').delete().eq('id',img.id).eq('user_id',user.id);if(e)throw e}else await localImageDelete(img.id);setImages(old=>old.filter(x=>x.id!==img.id));}catch(e){setError(e instanceof Error?e.message:'Delete failed.')}}
 return <section className="screenshot-section"><div className="section-heading"><div><h3>Your screenshots</h3><small>Saved reference images for this topic · {images.length}/10</small></div><button className="secondary" disabled={busy} onClick={()=>fileRef.current?.click()}><ImagePlus size={17}/>{busy?'Saving…':'Add image'}</button></div><input ref={fileRef} hidden type="file" multiple accept="image/png,image/jpeg,image/webp" onChange={e=>void upload(e.target.files)}/><small>PNG, JPEG or WebP · 2 MB each · stored as base64 {user?'in your Supabase account':'on this device'}</small>{error&&<p className="error-text" role="alert">{error}</p>}<div className="image-grid">{images.map(img=><figure key={img.id}><button className="image-preview" onClick={()=>setPreview(img)} aria-label={`Preview ${img.name}`}><img src={img.data_url} alt={img.name}/></button><figcaption><span>{img.name}</span><small>{new Date(img.created_at).toLocaleString()}</small><div><a className="icon-btn" href={img.data_url} download={img.name} aria-label={`Download ${img.name}`}><Download size={15}/></a><button className="icon-btn" onClick={()=>void remove(img)} aria-label={`Delete ${img.name}`}><Trash2 size={15}/></button></div></figcaption></figure>)}</div>{preview&&<ImageDialog image={preview} close={()=>setPreview(null)}/>}</section>
}
function ImageDialog({image,close}:{image:Screenshot;close:()=>void}){const ref=useRef<HTMLDialogElement>(null);useEffect(()=>{ref.current?.showModal();return()=>ref.current?.close()},[]);return <dialog className="image-dialog" ref={ref} onCancel={close} aria-label={image.name}><div className="flex-between"><strong>{image.name}</strong><button className="icon-btn" aria-label="Close image preview" onClick={close}><X size={22}/></button></div><img src={image.data_url} alt={image.name}/></dialog>}
