"use client";
import {useState} from 'react';
import {ArrowRight,Eye,Clock,CalendarDays} from 'lucide-react';
import {dateKey,type Progress} from '@/lib/progress';
import {managedTasks} from '@/lib/planning';
export default function StartHere({p,open,visual,planner}:{p:Progress;open:(day:number)=>void;visual:()=>void;planner:()=>void}){
 const [short,setShort]=useState(false),today=dateKey();
 const tasks=managedTasks(p).filter(t=>!t.done&&t.status!=='skipped').sort((a,b)=>a.dueDate.localeCompare(b.dueDate)||a.day-b.day);
 const next=tasks[0],overdue=tasks.filter(t=>t.dueDate<today).length,scheduledToday=tasks.filter(t=>t.dueDate===today).length;
 return <section className="card start-here"><div className="section-heading"><div><span className="eyebrow">START HERE</span><h2>{next?`One next step: ${next.label}`:'Your planned work is complete'}</h2></div><button className="secondary" aria-pressed={short} onClick={()=>setShort(!short)}><Clock size={16}/>{short?'Show full session':'I only have 10 minutes'}</button></div>{next?<><p className="start-task-title">Day {next.day} · {next.title}</p><p>{next.dueDate>today?`Scheduled for ${next.dueDate}. You can explore early or return on that date.`:short?'Spend 2 minutes recalling the idea, 6 minutes on one small attempt, and 2 minutes noting your next step. Submit partial work in the quest when you finish.':'Open this task, attempt it, and save your work before moving to the next one.'}</p><div className="start-actions"><button className="primary" onClick={()=>next.personal?planner():open(next.day)}>{short?'Start a small attempt':'Continue this task'} <ArrowRight size={17}/></button><button className="secondary" onClick={visual}><Eye size={17}/>Learn with a picture</button><button className="secondary" onClick={planner}><CalendarDays size={17}/>Manage my time</button></div><div className="start-steps">{tasks.slice(0,3).map((t,i)=><button key={t.id} onClick={()=>t.personal?planner():open(t.day)}><span>{i+1}</span><div><small>{i===0?'FIRST':'THEN'} · Day {t.day} · {t.dueDate}</small><strong>{t.label}</strong></div></button>)}</div></>:<><p>Revisit a visual lesson and explain it without hints to check what you remember.</p><button className="primary" onClick={visual}>Open Visual lab <Eye size={17}/></button></>}<div className="start-counts"><span>{scheduledToday} tasks due today</span><span>{overdue} pending from earlier</span><small>The 10-minute option does not change deadlines or mark work complete.</small></div></section>;
}
