'use client';
import {dateKey,scheduledDay,hasCommunicationRep,type Progress} from '@/lib/progress';
import {dayAssignments,communicationMission} from '@/lib/course';
import {patternCases} from '@/lib/patterns';
export default function TodayFocus({p,commit,practice,read,open,tool}:{p:Progress;commit:(p:Progress)=>void;practice:(id:string)=>void;read:(id:string)=>void;open:(day:number)=>void;tool:(id:string)=>void}){
 const today=dateKey(),day=scheduledDay(p.startDate),id=`today-focus-${today}`,r=p.studio?.[id],minutes=r?.fields.minutes==='30'?30:60,assigned=dayAssignments(day),q=assigned.dsa.find(q=>!p.practice?.[q.id]?.solvedAt)||assigned.dsa[0],lesson=patternCases[(day-1)%patternCases.length],comm=communicationMission(day);
 const mistakes=Object.entries(p.studio||{}).filter(([id,r])=>id.startsWith('mistake-')&&r.fields.deleted!=='yes'&&r.fields.resolved!=='yes'&&r.fields.retry&&r.fields.retry<=today),recalls=Object.entries(p.studio||{}).filter(([id,r])=>id.startsWith('bridge-')&&r.fields.due&&r.fields.due<=today&&r.fields.recalled!=='yes');
 const times=minutes===30?[15,10,5]:[30,20,10];
 return <section className="card today-focus"><span className="eyebrow">YOUR THREE FOCUSED ACTIONS</span><div className="section-heading"><h2>{today<p.startDate?`Preview Day 1 · starts ${p.startDate}`:`Day ${day}: solve, understand, speak`}</h2><div className="button-row">{[30,60].map(n=><button className="secondary" key={n} aria-pressed={minutes===n} onClick={()=>{const at=new Date().toISOString();commit({...p,updatedAt:at,studio:{...p.studio,[id]:{fields:{...r?.fields,minutes:String(n)},attempts:r?.attempts||[],updatedAt:at}}})}}>{n===30?'Busy day · 30 min':'Focused · 60 min'}</button>)}</div></div><div className="today-focus-grid"><article><small>01 · SOLVE · {times[0]} MIN</small><h3>{q.title}</h3><p>{p.practice?.[q.id]?.solvedAt?'Recorded solved · revisit without hints':q.prompt}</p><button className="primary" onClick={()=>practice(q.id)}>Open DSA problem</button></article><article><small>02 · UNDERSTAND · {times[1]} MIN</small><h3>{lesson.title}</h3><p>Predict the pattern, justify it, and trace an example.</p><button className="primary" onClick={()=>read(`pattern-reading-${lesson.id}`)}>Read / listen on my commute</button></article><article><small>03 · SPEAK · {times[2]} MIN</small><h3>{comm.title}</h3><p>{hasCommunicationRep(p.communication?.[day])?'Speaking rep already recorded. You can revisit it.':comm.prompt}</p><button className="primary" onClick={()=>open(day)}>Open daily speaking task</button></article></div><p>Time limits make the session manageable. Save partial work when needed; these suggestions do not change deadlines or complete tasks automatically.{assigned.dsa.length>1?' This milestone day has a second DSA assignment in your daily quest.':''}</p><div className="button-row"><button className="secondary" onClick={()=>tool('patterns')}>Pattern detective</button><button className="secondary" onClick={()=>tool('solution')}>Explain my solution</button><button className="secondary" onClick={()=>tool('mistakes')}>{mistakes.length} mistakes due</button><button className="secondary" onClick={()=>tool('bridge')}>{recalls.length} reading recalls due</button><button className="secondary" onClick={()=>tool('checkpoint')}>Weekly checkpoint</button><button className="secondary" onClick={()=>tool('story-bank')}>My story bank</button></div></section>;
}
