export type LabFrame={action:string;why:string;items:string[];memory:string;active?:number;edges?:[number,number][];result?:string};
export type LabTool={id:string;name:string;emoji:string;when:string;methods:string;cost:string;trap:string;example:string;goal:string;code:string};
export const labTools:LabTool[]=[
 {id:'xor-pairs',name:'XOR pair cancellation',emoji:'🧦',when:'Every integer appears exactly twice except one, and you need the unpaired value.',methods:'x ^ x = 0; x ^ 0 = x; XOR is associative and commutative.',cost:'O(n) time / O(1) accumulator; this lab additionally validates the input contract using a frequency map.',trap:'This trick does not solve arbitrary duplicate counts. The lab rejects inputs that do not contain exactly one singleton and pairs for all others.',example:'4,1,2,1,2',goal:'0',code:'let answer=0;\nfor(const value of nums) answer ^= value;\nreturn answer; // only under the singleton + pairs contract'},
 {id:'prefix',name:'Prefix-sum mile markers',emoji:'📏',when:'Answer many range-sum queries on an unchanged array.',methods:'prefix[0]=0; prefix[i+1]=prefix[i]+nums[i]; sum of [l,r) = prefix[r]-prefix[l].',cost:'O(n) preprocessing, O(1) per range query, O(n) storage.',trap:'The right boundary is exclusive here. An updated input makes this prefix table stale.',example:'2,-1,4,3',goal:'0',code:'const prefix=[0];\nfor(const x of nums) prefix.push(prefix.at(-1)+x);\n// [1,3): prefix[3]-prefix[1]'},
 {id:'recursion',name:'Recursion call-stack climb',emoji:'🪜',when:'A problem can be reduced to a smaller version with a terminating base case.',methods:'Call frame, base case, recursive call, return; factorial(n)=n*factorial(n-1).',cost:'O(n) calls and O(n) stack. Iteration can use O(1) extra space.',trap:'Without a reachable base case recursion does not terminate. JavaScript has finite call-stack depth and Number precision; this lab caps n at 12.',example:'5',goal:'0',code:'function factorial(n){\n if(n===0) return 1;\n return n*factorial(n-1);\n}'},
 {id:'map',name:'Map frequency detective',emoji:'🕵️',when:'Remember a value’s count, index, or associated record: Two Sum, grouping, frequency problems.',methods:'set(key,value), get(key), has(key), delete(key), clear(), keys(), values(), entries(), size',cost:'Typical hash-map reasoning: expected O(n) time / O(k) space for k distinct keys. JavaScript does not promise worst-case O(1) lookup.',trap:'has(k) distinguishes a missing key from a stored undefined; object keys compare by identity. Map is not Array.map().',example:'4,2,4,7,2',goal:'4',code:'const counts = new Map();\nfor (const x of nums) {\n  counts.set(x, (counts.get(x) ?? 0) + 1);\n}\ncounts.has(target); counts.get(target);'},
 {id:'set',name:'Set duplicate gate',emoji:'🚪',when:'Ask whether you have seen a value, deduplicate values, or mark visited graph nodes.',methods:'add(value), has(value), delete(value), clear(), values(), size',cost:'Expected O(n) time / O(k) space with hash-set reasoning.',trap:'A Set stores values, not frequencies. Two separate {id:1} objects are distinct entries.',example:'3,1,3,2,1',goal:'3',code:'const seen = new Set();\nfor (const x of nums) {\n  if (!seen.has(x)) seen.add(x);\n}\n[...seen]; // first insertion order'},
 {id:'stack',name:'Stack undo tower',emoji:'📚',when:'Undo, balanced brackets, expression parsing, DFS, and monotonic-stack problems.',methods:'Array.push(value), Array.pop(), stack.at(-1), length',cost:'Amortized O(1) push, O(1) pop; O(n) stored values.',trap:'LIFO: the most recently inserted value leaves first. pop() on an empty array returns undefined.',example:'1,2,3',goal:'0',code:'const stack=[];\nfor (const x of nums) stack.push(x);\nwhile (stack.length) console.log(stack.pop());'},
 {id:'queue',name:'Queue boarding gate',emoji:'🚌',when:'FIFO work, breadth-first traversal, or scheduling requests fairly.',methods:'enqueue: push(); dequeue: queue[head++]; size: length-head',cost:'O(1) indexed dequeue; O(n) total storage in this bounded example.',trap:'shift() moves indices and is generally O(n). A long-lived indexed queue must compact or use a ring buffer.',example:'8,4,6',goal:'0',code:'const queue=[...nums];\nlet head=0;\nwhile (head<queue.length) {\n  const next=queue[head++];\n}'},
 {id:'linked',name:'Linked-list pointer rescue',emoji:'🔗',when:'Reverse a chain or splice nodes when you already hold the necessary node references.',methods:'Node {value,next}; head, prev, current, next; no native JavaScript LinkedList class.',cost:'Reverse: O(n) time / O(1) auxiliary pointers. Index lookup is O(n).',trap:'Save current.next before rewiring it or you lose the remainder. Repeated values still represent separate nodes.',example:'1,2,3,4',goal:'0',code:'let prev=null, current=head;\nwhile (current) {\n const next=current.next;\n current.next=prev;\n prev=current; current=next;\n}\nhead=prev;'},
 {id:'tree',name:'Binary-search-tree orchard',emoji:'🌳',when:'Ordered lookup and range queries. A general binary tree has at most two children but need not be ordered.',methods:'insert, search, inorder traversal; implemented with left/right references.',cost:'O(h) per insert/search, O(n) traversal; an unbalanced tree can have h=n.',trap:'This simulator ignores duplicate keys and does not balance the tree. Inorder is sorted only for a BST.',example:'5,3,8,1,4,7,9',goal:'0',code:'function insert(node,x) {\n if (!node) return {value:x,left:null,right:null};\n if(x<node.value) node.left=insert(node.left,x);\n if(x>node.value) node.right=insert(node.right,x);\n return node;\n}\n// inorder: left → node → right'},
 {id:'bfs',name:'Graph BFS rescue',emoji:'🗺️',when:'Find reachability or shortest paths in an unweighted graph, level by level.',methods:'Adjacency Map, visited Set, queue with head index; mark visited when enqueueing.',cost:'O(V+E) time / O(V) auxiliary space.',trap:'A graph may contain cycles. BFS is not a weighted shortest-path algorithm.',example:'0-1,0-2,1-3,2-3,3-4',goal:'0',code:'const queue=[start], seen=new Set([start]);\nfor(let head=0;head<queue.length;head++){\n for(const v of adj.get(queue[head]) ?? []) {\n  if(!seen.has(v)){seen.add(v);queue.push(v);}\n }\n}'},
 {id:'dfs',name:'Graph DFS cave explorer',emoji:'🔦',when:'Explore components, detect structures, and search deeply before returning.',methods:'Adjacency Map, visited Set, explicit stack or recursion.',cost:'O(V+E) time / O(V+E) stack storage in this simple push-neighbors implementation.',trap:'A visited set prevents cycles; DFS visit order depends on neighbor order. DFS does not guarantee shortest paths.',example:'0-1,0-2,1-3,2-3,3-4',goal:'0',code:'const stack=[start], seen=new Set();\nwhile(stack.length){\n const u=stack.pop();\n if(seen.has(u)) continue;\n seen.add(u);\n for(const v of [...adj.get(u)].reverse())\n  if(!seen.has(v)) stack.push(v);\n}'},
 {id:'bits',name:'XOR and NOR bit workshop',emoji:'💡',when:'XOR toggles bits and cancels pairs; bit masks represent compact flags. NOR is useful for Boolean logic and digital circuits.',methods:'a ^ b: XOR; a | b: OR; ~(a | b): bitwise NOR; !(a || b): logical NOR.',cost:'O(1) for fixed 32-bit Number bitwise operations.',trap:'XOR is not exponentiation (**). Number bitwise operations use signed 32-bit integers. Here NOR is masked to 8 bits; NOT otherwise flips all 32 bits.',example:'5,3',goal:'0',code:'const xor = a ^ b;\nconst nor8 = (~(a | b)) & 255;\nconst logicalNor = !(a || b);\n// 5 ^ 3 = 6; 8-bit NOR = 248'},
 {id:'heap',name:'Min-heap priority camp',emoji:'⛺',when:'Repeatedly retrieve the smallest item: schedulers, top-k, and priority queues.',methods:'push + sift-up; peek root; pop root + sift-down (not shown here). parent=(i-1)>>1.',cost:'O(log n) insert, O(1) peek, O(n) stored values.',trap:'A heap is partially ordered, not a sorted array. Parent ≤ children does not order siblings.',example:'9,3,7,1,5',goal:'0',code:'heap.push(x);\nlet i=heap.length-1;\nwhile(i>0){\n const p=Math.floor((i-1)/2);\n if(heap[p]<=heap[i]) break;\n [heap[p],heap[i]]=[heap[i],heap[p]]; i=p;\n}'},
 {id:'insertion',name:'Insertion-sort card table',emoji:'🃏',when:'Sort a small or almost sorted sequence while keeping a sorted prefix.',methods:'Compare, shift right, insert; operate on a copy to preserve the input.',cost:'Worst O(n²), best O(n), O(1) auxiliary space beyond the copy.',trap:'Use > rather than >= while shifting to preserve the order of equal values.',example:'5,2,4,1,3',goal:'0',code:'const a=[...nums];\nfor(let i=1;i<a.length;i++){\n const x=a[i]; let j=i-1;\n while(j>=0 && a[j]>x){a[j+1]=a[j];j--;}\n a[j+1]=x;\n}'},
 {id:'merge',name:'Merge-sort river branches',emoji:'🏞️',when:'Need predictable O(n log n) sorting by dividing then merging sorted halves.',methods:'slice, recurse, two read pointers, merge output.',cost:'O(n log n) time; O(n) peak auxiliary data plus recursion for this implementation.',trap:'The merge step is linear, not constant. Taking from the left on ties preserves stability.',example:'8,2,6,1,5,3',goal:'0',code:'function sort(a){\n if(a.length<2) return a;\n const m=Math.floor(a.length/2);\n return merge(sort(a.slice(0,m)),sort(a.slice(m)));\n}\n// merge: repeatedly take the smaller head'},
 {id:'dp',name:'Dynamic-programming stepping stones',emoji:'🪨',when:'Subproblems overlap and their answers can be reused. Count ways to climb n steps using jumps of 1 or 2.',methods:'Base cases ways[0]=1, ways[1]=1; transition ways[i]=ways[i-1]+ways[i-2].',cost:'O(n) time / O(n) table; two variables reduce space to O(1).',trap:'Define what the state means before writing a recurrence. Here zero steps has one empty way.',example:'7',goal:'0',code:'const ways=[1,1];\nfor(let i=2;i<=n;i++) ways[i]=ways[i-1]+ways[i-2];\nreturn ways[n];'},
 {id:'backtrack',name:'Subset treasure expedition',emoji:'🎒',when:'Explore choices with choose → explore → undo: subsets, combinations, puzzles.',methods:'path.push(), recursive visit(), path.pop(); copy path at each leaf.',cost:'O(n·2^n) output time and storage; O(n) recursion/path excluding output.',trap:'Backtracking is exponential. This lab caps input at 6 values and treats equal values at different indices as separate choices.',example:'1,2,3',goal:'0',code:'function visit(i,path){\n if(i===nums.length){out.push([...path]);return;}\n visit(i+1,path); // exclude\n path.push(nums[i]); visit(i+1,path); path.pop();\n}'},
 {id:'trie',name:'Trie word trail',emoji:'🪧',when:'Prefix lookup, autocomplete, and dictionaries with shared prefixes.',methods:'children Map<char,node>, terminal flag; insert(word), startsWith(prefix), search(word).',cost:'O(L) insert/search per word of length L; storage proportional to inserted characters.',trap:'A prefix node is not necessarily a complete word; check terminal. This lab normalizes ASCII words to lowercase.',example:'car,cat,care,dog',goal:'0',code:'let node=root;\nfor(const char of word){\n if(!node.children.has(char)) node.children.set(char,new Node());\n node=node.children.get(char);\n}\nnode.terminal=true;'},
 {id:'union',name:'Union-find island bridges',emoji:'🌉',when:'Track connected components as undirected edges are added; cycle detection and Kruskal’s algorithm.',methods:'find root, union roots; path compression flattens future finds.',cost:'This simple unranked implementation has O(V) worst-case operations. Add union by rank/size with compression for amortized near-constant operations.',trap:'Union-find answers connectivity, not the actual path between vertices. Repeated connections do not join new components.',example:'0-1,2-3,1-2,0-3',goal:'0',code:'function find(x){\n if(parent[x]!==x) parent[x]=find(parent[x]);\n return parent[x];\n}\nparent[find(a)]=find(b);'},
 {id:'window',name:'Sliding-window supply wagon',emoji:'🚃',when:'Compute an aggregate over every contiguous block of a fixed size without re-reading all elements.',methods:'Add incoming value, subtract outgoing value, update best.',cost:'O(n) time / O(1) auxiliary state.',trap:'Window size must be between 1 and n. Variable windows need an invariant; arbitrary negatives break some shrinking strategies.',example:'2,1,5,1,3,2',goal:'3',code:'let sum=0,best=-Infinity;\nfor(let i=0;i<nums.length;i++){\n sum+=nums[i];\n if(i>=k) sum-=nums[i-k];\n if(i>=k-1) best=Math.max(best,sum);\n}'},
 {id:'pointers',name:'Two-pointer meeting trail',emoji:'🤝',when:'Find a target pair in sorted input by moving inward from opposite ends.',methods:'left++, right--; compare a[left]+a[right] with target.',cost:'O(n) scan / O(1) auxiliary space for already sorted input.',trap:'Unsorted input cannot justify discarding a side. Sorting first changes original indices and costs O(n log n).',example:'1,2,4,6,9',goal:'10',code:'let l=0,r=nums.length-1;\nwhile(l<r){\n const sum=nums[l]+nums[r];\n if(sum===target) return [l,r];\n if(sum<target) l++; else r--;\n}\nreturn [];'},
];
export function simulateLab(id:string,text:string,goal:string):LabFrame[]{
 const frames:LabFrame[]=[];
 const add=(action:string,why:string,items:unknown[],memory:unknown,active?:number,edges?:[number,number][])=>frames.push({action,why,items:items.map(String),memory:typeof memory==='string'?memory:JSON.stringify(memory),active,edges});
 const end=(result:unknown)=>{const last=frames.at(-1)!;frames.push({...last,action:'Checkpoint reached',why:'Explain this result before trying a different input.',result:JSON.stringify(result)});return frames};
 if(text.length>300)throw Error('Keep your example under 300 characters.');
 if(id==='trie'){
  const words=text.toLowerCase().split(',').map(w=>w.trim());if(words.length>8||words.some(w=>!(/^[a-z]{1,8}$/).test(w)))throw Error('Use 1–8 comma-separated words, each 1–8 ASCII letters.');
  const prefixes=['∅'],links:[number,number][]=[],terminal=new Set<string>();
  for(const word of words){let parent=0;for(let i=1;i<=word.length;i++){const prefix=word.slice(0,i);let idx=prefixes.indexOf(prefix);if(idx<0){idx=prefixes.length;prefixes.push(prefix);links.push([parent,idx])}parent=idx;add(`Follow “${prefix}”`,'Reuse a shared prefix or create a missing child.',prefixes,[...terminal],idx,[...links])}terminal.add(word);add(`Mark “${word}” as a word`,'A terminal flag separates complete words from prefixes.',prefixes,[...terminal],parent,[...links])}return end([...terminal]);
 }
 if(['bfs','dfs','union'].includes(id)){
  const parts=text.split(',').map(s=>s.trim());if(parts.length>18||parts.some(s=>!/^\d-\d$/.test(s)))throw Error('Use up to 18 undirected edges such as 0-1,1-2. Vertex IDs are digits 0–9.');
  const edges=parts.map(s=>s.split('-').map(Number) as [number,number]);const vertices=[...new Set(edges.flat())].sort((a,b)=>a-b),links=edges.map(([a,b])=>[vertices.indexOf(a),vertices.indexOf(b)] as [number,number]);
  if(id==='union'){const parent=Object.fromEntries(vertices.map(v=>[v,v]));const find=(x:number):number=>parent[x]===x?x:(parent[x]=find(parent[x]));for(const [a,b] of edges){const x=find(a),y=find(b);parent[x]=y;add(`Connect ${a} ↔ ${b}`,x===y?'Already connected; component count stays the same.':'Join the roots, not arbitrary internal nodes.',vertices,parent,vertices.indexOf(a),links)}return end(vertices.map(v=>({vertex:v,root:find(v)})))}
  const start=Number(goal);if(!goal.trim()||!vertices.includes(start))throw Error('Start vertex must appear in the edges.');
  const adj=new Map(vertices.map(v=>[v,[] as number[]]));for(const [a,b] of edges){adj.get(a)!.push(b);adj.get(b)!.push(a)}
  const work=[start],seen=new Set<number>(id==='bfs'?[start]:[]),order:number[]=[];let head=0;
  while(id==='bfs'?head<work.length:work.length>0){const u=id==='bfs'?work[head++]:work.pop()!;if(id==='dfs'&&seen.has(u))continue;seen.add(u);order.push(u);for(const v of id==='dfs'?[...adj.get(u)!].reverse():adj.get(u)!){if(!seen.has(v)){if(id==='bfs')seen.add(v);work.push(v)}}add(`Visit ${u}`,id==='bfs'?'Take the earliest discovered vertex; enqueue unseen neighbors.':'Take the most recent frontier vertex; explore deeply.',vertices,{frontier:id==='bfs'?work.slice(head):work,visited:order},vertices.indexOf(u),links)}return end(order);
 }
 const tokens=text.trim()?text.split(',').map(s=>s.trim()):[];
 if(tokens.length>12||tokens.some(x=>!/^[-+]?\d+$/.test(x)||!Number.isSafeInteger(Number(x))||Math.abs(Number(x))>1000))throw Error('Use up to 12 comma-separated integers from -1000 to 1000. Empty input is allowed where meaningful.');
 const nums=tokens.map(Number),target=Number(goal);if(!Number.isSafeInteger(target)||Math.abs(target)>10000)throw Error('Parameter must be a whole number from -10000 to 10000.');
 add('Pack your input','Predict the final result, then follow the state changes.',nums,{});
 if(id==='xor-pairs'){const counts=new Map<number,number>();for(const x of nums)counts.set(x,(counts.get(x)??0)+1);if([...counts.values()].filter(n=>n===1).length!==1||[...counts.values()].some(n=>n!==1&&n!==2))throw Error('Use exactly one unpaired value and exactly two occurrences of every other value.');let acc=0;for(let i=0;i<nums.length;i++){const before=acc;acc^=nums[i];add(`${before} XOR ${nums[i]} = ${acc}`,'Equal paired values cancel regardless of their order.',nums,{accumulator:acc},i)}return end(acc);}
 if(id==='prefix'){const prefix=[0];for(let i=0;i<nums.length;i++){prefix.push(prefix[i]+nums[i]);add(`prefix[${i+1}]=${prefix[i+1]}`,'Each marker is the total before its index; marker zero starts at 0.',prefix,{input:nums,through:i},i+1)}return end(prefix);}
 if(id==='recursion'){if(nums.length!==1||nums[0]<0||nums[0]>12)throw Error('Use a single integer from 0 to 12.');const stack:number[]=[];const factorial=(n:number):number=>{stack.push(n);add(`Call factorial(${n})`,'Pause this frame while a smaller call works.',stack,{n});if(n===0){add('Base case: return 1','The smallest subproblem ends the descent.',stack,{});stack.pop();return 1}const answer=n*factorial(n-1);add(`Return ${answer}`,'Resume the waiting frame and multiply the returned value.',stack,{answer});stack.pop();return answer};return end(factorial(nums[0]));}
 if(id==='map'){const map=new Map<number,number>();for(const x of nums){map.set(x,(map.get(x)??0)+1);add(`set(${x}, ${map.get(x)})`,'get() reads the old count; set() stores the new count.',[...map].map(([k,v])=>`${k} → ${v}`),{hasTarget:map.has(target),targetCount:map.get(target)??0})}return end([...map]);}
 if(id==='set'){const set=new Set<number>();for(const x of nums){const had=set.has(x);set.add(x);add(`add(${x})`,had?'Already present: adding it again changes nothing.':'New value: the gate lets it enter.',[...set],{size:set.size,hasTarget:set.has(target)})}return end([...set]);}
 if(id==='stack'||id==='queue'){const a:number[]=[],out:number[]=[];for(const x of nums){a.push(x);add(`Push ${x}`,'Store the incoming value.',a,{output:out})}let head=0;while(id==='stack'?a.length>0:head<a.length){const x=id==='stack'?a.pop()!:a[head++];out.push(x);add(`${id==='stack'?'Pop':'Dequeue'} ${x}`,id==='stack'?'Last in, first out.':'First in, first out.',id==='stack'?a:a.slice(head),{output:out})}return end(out);}
 if(id==='linked'){const next=nums.map((_,i)=>i+1<nums.length?i+1:-1);let prev=-1,cur=nums.length?0:-1;while(cur!==-1){const following=next[cur];next[cur]=prev;add(`Rewire node ${cur}`,'Keep next safe, reverse one arrow, then advance both pointers.',nums,{prev,current:cur,savedNext:following},cur,next.flatMap((to,from)=>to<0?[]:[[from,to] as [number,number]]));prev=cur;cur=following}return end([...nums].reverse());}
 if(id==='tree'){const values:number[]=[],left:number[]=[],right:number[]=[],edges=()=>values.flatMap((_,i)=>[left[i],right[i]].filter(v=>v>=0).map(v=>[i,v] as [number,number]));for(const x of nums){if(values.includes(x)){add(`Skip duplicate ${x}`,'This BST stores unique keys.',values,{},values.indexOf(x),edges());continue}let parent=-1,pos=values.length?0:-1;while(pos>=0){parent=pos;pos=x<values[pos]?left[pos]:right[pos]}const idx=values.length;values.push(x);left.push(-1);right.push(-1);if(parent>=0)(x<values[parent]?left:right)[parent]=idx;add(`Insert ${x}`,'Smaller keys go left; larger keys go right.',values,{root:values[0]},idx,edges())}const out:number[]=[];const visit=(i:number)=>{if(i<0)return;visit(left[i]);out.push(values[i]);add(`Inorder visit ${values[i]}`,'Left subtree → current node → right subtree.',values,{output:out},i,edges());visit(right[i])};if(values.length)visit(0);return end(out);}
 if(id==='bits'){if(nums.length!==2||nums.some(n=>n<0||n>255))throw Error('Use exactly two integers from 0 to 255.');const [a,b]=nums;let xor='',nor='';for(let bit=7;bit>=0;bit--){const x=(a>>bit)&1,y=(b>>bit)&1;xor+=x^y;nor+=1-(x|y);add(`Inspect bit ${bit}`,`${x} XOR ${y} = ${x^y}; NOR = ${1-(x|y)}.`,[a.toString(2).padStart(8,'0'),b.toString(2).padStart(8,'0')],{xor,nor})}return end({xor:a^b,nor8:(~(a|b))&255,logicalNor:!(a||b)});}
 if(id==='heap'){const heap:number[]=[];for(const x of nums){heap.push(x);let i=heap.length-1;add(`Insert ${x}`,'Attach at the end to preserve the complete-tree shape.',heap,{},i);while(i>0){const parent=Math.floor((i-1)/2);if(heap[parent]<=heap[i])break;[heap[parent],heap[i]]=[heap[i],heap[parent]];i=parent;add('Sift upward','Swap with a larger parent until heap order holds.',heap,{},i)}}return end(heap);}
 if(id==='insertion'){const a=[...nums];for(let i=1;i<a.length;i++){const x=a[i];let j=i-1;while(j>=0&&a[j]>x){a[j+1]=a[j];j--;add('Shift right',`Make room for ${x} in the sorted prefix.`,a,{held:x},j+1)}a[j+1]=x;add(`Place ${x}`,'The prefix through this position is now sorted.',a,{prefixEnd:i},j+1)}return end(a);}
 if(id==='merge'){const sort=(a:number[]):number[]=>{if(a.length<2)return a;const m=Math.floor(a.length/2);add('Split the river','Solve two smaller sorting problems.',a,{left:a.slice(0,m),right:a.slice(m)});const l=sort(a.slice(0,m)),r=sort(a.slice(m)),out:number[]=[];let i=0,j=0;while(i<l.length||j<r.length){out.push(j===r.length||(i<l.length&&l[i]<=r[j])?l[i++]:r[j++]);add('Merge sorted heads','Choose the smaller remaining head; take left on ties.',out,{left:l.slice(i),right:r.slice(j)})}return out};return end(sort(nums));}
 if(id==='dp'){if(nums.length!==1||nums[0]<0||nums[0]>30)throw Error('Enter one step count from 0 to 30.');const n=nums[0],ways=[1];if(n>=1)ways.push(1);add('Establish base cases','There is one empty way for n=0, and one way for n=1.',ways,{n});for(let i=2;i<=n;i++){ways[i]=ways[i-1]+ways[i-2];add(`ways[${i}]=${ways[i]}`,'The final jump came from i−1 or i−2; add those disjoint possibilities.',ways,{i},i)}return end(ways[n]);}
 if(id==='backtrack'){if(nums.length>6)throw Error('Subset exploration is capped at 6 values (64 subsets).');const out:number[][]=[];const visit=(i:number,path:number[])=>{if(i===nums.length){out.push([...path]);add('Collect a subset','Copy the path; do not store its mutable reference.',path,{count:out.length});return}visit(i+1,path);path.push(nums[i]);add(`Choose index ${i}`,'Explore the branch containing this value.',path,{i});visit(i+1,path);path.pop();add(`Undo index ${i}`,'Restore the path for the next branch.',path,{i})};visit(0,[]);return end(out);}
 if(id==='window'){const k=target;if(k<1||k>nums.length)throw Error('Window size must be from 1 through the input length.');let sum=0,best=-Infinity;for(let i=0;i<nums.length;i++){sum+=nums[i];if(i>=k)sum-=nums[i-k];if(i>=k-1)best=Math.max(best,sum);add(`Advance to ${i}`,'Add the new value; remove the value that left the fixed-size window.',nums,{window:nums.slice(Math.max(0,i-k+1),i+1),sum,best:Number.isFinite(best)?best:'not full'},i)}return end(best);}
 if(id==='pointers'){if(nums.some((n,i)=>i>0&&n<nums[i-1]))throw Error('Two pointers requires ascending sorted input.');let l=0,r=nums.length-1;while(l<r){const sum=nums[l]+nums[r];add(`Compare indices ${l} and ${r}`,sum<target?'Sum too small: increase the left value.':sum>target?'Sum too large: decrease the right value.':'A pair reaches the target.',nums,{l,r,sum,target});if(sum===target)return end([l,r]);if(sum<target)l++;else r--}return end([]);}
 throw Error('Unknown simulator.');
}
