export type ArrayTrack='loop'|'map'|'set';
export type ArrayExample={id:string;track:ArrayTrack;title:string;input:Record<string,unknown>;expected:unknown;task:string;code:string;reason:string;hint:string;time:string;space:string;trap:string};
function e(track:ArrayTrack,id:string,title:string,input:Record<string,unknown>,expected:unknown,task:string,code:string,reason:string,hint:string,time:string,space:string,trap:string):ArrayExample{return {track,id:`${track}-${id}`,title,input,expected,task,code,reason,hint,time,space,trap}}
export const arrayExamples:ArrayExample[]=[
 e('loop','sum','Sum every value',{nums:[3,-2,7]},8,'Return the sum; an empty array returns 0.',"function solve({ nums }) {\n  let total = 0;\n  for (let i = 0; i < nums.length; i++) total += nums[i];\n  return total;\n}",'A running total summarizes the prefix already visited.','The total changes 0 → 3 → 1 → 8.','O(n)','O(1)','Do not reset total inside the loop.'),
 e('loop','maximum','Find the maximum',{nums:[-8,-3,-12]},-3,'Return the maximum, or null for empty input.',"function solve({ nums }) {\n  if (!nums.length) return null;\n  let best = nums[0];\n  for (let i = 1; i < nums.length; i++) if (nums[i] > best) best = nums[i];\n  return best;\n}",'Keep the largest value seen so far; sorting is unnecessary.','Start at -8, improve to -3, ignore -12.','O(n)','O(1)','Starting at zero gives the wrong answer for all-negative inputs.'),
 e('loop','minimum','Find the minimum',{nums:[5,2,9,-1]},-1,'Return the minimum, or null for empty input.',"function solve({ nums }) {\n  if (!nums.length) return null;\n  let best = nums[0];\n  for (let i = 1; i < nums.length; i++) if (nums[i] < best) best = nums[i];\n  return best;\n}",'The current minimum is enough to summarize the prefix.','Only 2 and -1 improve the initial minimum of 5.','O(n)','O(1)','Handle empty input before reading nums[0].'),
 e('loop','find','Find the first matching index',{nums:[4,9,4],target:4},0,'Return the first target index, or -1 if missing.',"function solve({ nums, target }) {\n  for (let i = 0; i < nums.length; i++) if (nums[i] === target) return i;\n  return -1;\n}",'Left-to-right traversal makes the first match the earliest index.','Stop at index 0 even though index 2 also matches.','O(n)','O(1)','A value and its index are different outputs.'),
 e('loop','count','Count a target',{nums:[2,3,2,2],target:2},3,'Return how many times the target occurs.',"function solve({ nums, target }) {\n  let count = 0;\n  for (const x of nums) if (x === target) count++;\n  return count;\n}",'Only one target matters, so one counter is sufficient.','Increment for indices 0, 2 and 3.','O(n)','O(1)','A Map is unnecessary when counting only one known target.'),
 e('loop','reverse','Reverse into a new array',{nums:[1,2,3]},[3,2,1],'Return a reversed copy without changing the input.',"function solve({ nums }) {\n  const out = [];\n  for (let i = nums.length - 1; i >= 0; i--) out.push(nums[i]);\n  return out;\n}",'Read from the last index to the first and append to a separate output.','The first read is nums[2], not nums[3].','O(n)','O(n) output','nums.reverse() mutates the array; this contract requires a copy.'),
 e('loop','double','Transform each value',{nums:[2,-1,0]},[4,-2,0],'Return a new array containing each value doubled.',"function solve({ nums }) {\n  const out = [];\n  for (const x of nums) out.push(x * 2);\n  return out;\n}",'This is a transformation: one output value per input value.','Each element is processed independently.','O(n)','O(n) output','Array.map(callback) could express this; new Map() is a different data structure.'),
 e('loop','evens','Keep only even values',{nums:[1,2,-4,7,0]},[2,-4,0],'Return even values in their original order.',"function solve({ nums }) {\n  const out = [];\n  for (const x of nums) if (x % 2 === 0) out.push(x);\n  return out;\n}",'Append only values that satisfy the predicate.','Both -4 and 0 are even.','O(n)','O(n) output','Do not use x%2===1 to identify all odd negative numbers.'),
 e('loop','duplicates','Find duplicates with nested loops',{nums:[3,1,3]},true,'Return whether any two distinct positions hold the same value.',"function solve({ nums }) {\n  for (let j = 0; j < nums.length; j++) for (let i = 0; i < j; i++) if (nums[i] === nums[j]) return true;\n  return false;\n}",'Compare the current value only with earlier positions.','At j=2, index 0 already contains 3.','O(n²) worst case','O(1)','Comparing a position with itself would always report a duplicate.'),
 e('loop','two-sum','Two Sum: inspect every earlier pair',{nums:[2,7,11,15],target:9},[0,1],'Return indices [i,j] with i<j and the target sum. Choose the earliest j, then earliest i; return [] if absent.',"function solve({ nums, target }) {\n  for (let j = 0; j < nums.length; j++) for (let i = 0; i < j; i++) if (nums[i] + nums[j] === target) return [i, j];\n  return [];\n}",'Trying pairs gives a correct baseline before optimizing lookups.','At j=1, 2+7 equals 9.','O(n²)','O(1), excluding result','Return indices, not [2,7], and never reuse one position.'),
 e('loop','prefix','Build prefix sums',{nums:[2,-1,4]},[0,2,1,5],'Return prefix sums with a leading 0. prefix[i] sums values before index i.',"function solve({ nums }) {\n  const prefix = [0];\n  for (let i = 0; i < nums.length; i++) prefix.push(prefix[i] + nums[i]);\n  return prefix;\n}",'A reusable total at every boundary supports fast later range sums.','The sum for indices [1,3) is prefix[3]-prefix[1]=3.','O(n) construction','O(n) output','Be explicit about inclusive versus exclusive boundaries.'),
 e('loop','running-max','Maximum after each step',{nums:[3,1,5,2]},[3,3,5,5],'Return the maximum of every prefix; empty input returns [].',"function solve({ nums }) {\n  const out = [];\n  let best = -Infinity;\n  for (const x of nums) {\n    best = Math.max(best, x);\n    out.push(best);\n  }\n  return out;\n}",'A running maximum changes only when a larger value arrives.','The value 1 does not lower the maximum.','O(n)','O(n) output','The output has one value per input, not only the final maximum.'),
 e('loop','rotate','Rotate left by one',{nums:[1,2,3,4]},[2,3,4,1],'Return a new array with the first value moved to the end.',"function solve({ nums }) {\n  if (!nums.length) return [];\n  const out = [];\n  for (let i = 1; i < nums.length; i++) out.push(nums[i]);\n  out.push(nums[0]);\n  return out;\n}",'Copy the suffix, then append the saved first value.','A one-element input is unchanged.','O(n)','O(n) output','Rotating is not reversing.'),
 e('loop','second-largest','Second-largest distinct value',{nums:[5,5,2,4]},4,'Return the second-largest distinct number, or null if fewer than two distinct values exist.',"function solve({ nums }) {\n  let first = -Infinity, second = -Infinity;\n  for (const x of nums) {\n    if (x > first) {\n      second = first;\n      first = x;\n    } else if (x < first && x > second) second = x;\n  }\n  return second === -Infinity ? null : second;\n}",'Keep the best two distinct candidates; duplicates of first do not become second.','The second 5 must be ignored.','O(n)','O(1)','This example assumes finite numbers, so -Infinity can be a sentinel.'),
 e('loop','merge','Merge sorted arrays',{a:[1,4,8],b:[2,4,9]},[1,2,4,4,8,9],'Merge two ascending arrays into a sorted output, retaining duplicates.',"function solve({ a, b }) {\n  const out = [];\n  let i = 0, j = 0;\n  while (i < a.length || j < b.length) {\n    if (j === b.length || i < a.length && a[i] <= b[j]) out.push(a[i++]);\n    else out.push(b[j++]);\n  }\n  return out;\n}",'Take the smaller unconsumed head and advance only that pointer.','After a side is exhausted, copy the other side.','O(n+m)','O(n+m) output','This requires sorted inputs; merging arbitrary arrays does not sort them.'),
 e('loop','sorted','Check ascending order',{nums:[1,2,2,5]},true,'Return whether each value is at least the previous value.',"function solve({ nums }) {\n  for (let i = 1; i < nums.length; i++) if (nums[i] < nums[i - 1]) return false;\n  return true;\n}",'Only adjacent comparisons are needed to detect a descent.','Equal neighbors are allowed.','O(n)','O(1)','Do not sort first: that destroys evidence of the original order.'),
 e('loop','remove','Remove a chosen value',{nums:[2,1,2,3],target:2},[1,3],'Return a new array omitting every target occurrence.',"function solve({ nums, target }) {\n  const out = [];\n  for (const x of nums) if (x !== target) out.push(x);\n  return out;\n}",'Copy retained values instead of splicing while traversing.','Both 2s are excluded; order of 1 and 3 stays unchanged.','O(n)','O(n) output','Deleting during a forward loop can skip shifted values.'),
 e('loop','positive','Count positive, negative and zero',{nums:[-2,0,4,7,-1]},{positive:2,negative:2,zero:1},'Return three counts.',"function solve({ nums }) {\n  const out = { positive: 0, negative: 0, zero: 0 };\n  for (const x of nums) {\n    if (x > 0) out.positive++;\n    else if (x < 0) out.negative++;\n    else out.zero++;\n  }\n  return out;\n}",'The categories partition the finite-number input.','Exactly one counter changes for each value.','O(n)','O(1)','Zero is neither positive nor negative.'),
 e('loop','flatten','Flatten exactly one level',{groups:[[1,2],[],[3]]},[1,2,3],'Flatten an array of numeric arrays by one level.',"function solve({ groups }) {\n  const out = [];\n  for (const group of groups) for (const x of group) out.push(x);\n  return out;\n}",'The outer loop selects a group and the inner loop visits its elements.','An empty group contributes nothing.','O(g+n), g groups / n values','O(n) output','This is not arbitrary-depth recursive flattening.'),
 e('loop','unique','Deduplicate without a Set',{nums:[3,1,3,2,1]},[3,1,2],'Return unique values in first-appearance order.',"function solve({ nums }) {\n  const out = [];\n  for (const x of nums) {\n    let found = false;\n    for (const y of out) if (x === y) {\n      found = true;\n      break;\n    }\n    if (!found) out.push(x);\n  }\n  return out;\n}",'The output doubles as the list of values already retained.','Before appending a value, scan the smaller retained list.','O(n²) worst case','O(k) output','This trades repeated scanning for avoiding a membership structure.'),

 e('map','duplicates','Duplicate detection with a Map',{nums:[3,1,3]},true,'Return whether a value has appeared before.',"function solve({ nums }) {\n  const seen = /* @__PURE__ */ new Map();\n  for (const x of nums) {\n    if (seen.has(x)) return true;\n    seen.set(x, true);\n  }\n  return false;\n}",'A Map can store presence, but a Set is simpler if no associated value is needed.','Check has before storing.','Expected O(n)','O(k)','Do not mistake Map.get returning undefined for proof the key is absent.'),
 e('map','two-sum','Two Sum: remember earlier indices',{nums:[2,7,11,15],target:9},[0,1],'Return the earliest finishing pair of indices, breaking ties by earliest earlier index; [] if absent.',"function solve({ nums, target }) {\n  const seen = /* @__PURE__ */ new Map();\n  for (let j = 0; j < nums.length; j++) {\n    const needed = target - nums[j];\n    if (seen.has(needed)) return [seen.get(needed), j];\n    if (!seen.has(nums[j])) seen.set(nums[j], j);\n  }\n  return [];\n}",'Store value → earliest index so a complement lookup also gives the required index.','For 7, look for 9−7=2; the Map stores 2→0.','Expected O(n)','O(k)','Check before storing to prevent pairing an element with itself.'),
 e('map','frequency','Count every value',{nums:[4,2,4,7,2]},[[4,2],[2,2],[7,1]],'Return [value,count] entries in first-appearance order.',"function solve({ nums }) {\n  const counts = /* @__PURE__ */ new Map();\n  for (const x of nums) counts.set(x, (counts.get(x) ?? 0) + 1);\n  return [...counts];\n}",'Unlike a Set, a Map associates each key with its count.','get(4) changes from missing to 1, then 2.','Expected O(n)','O(k)','Updating an existing key does not move its original insertion position.'),
 e('map','first-unique','First value appearing once',{nums:[4,2,4,7,2]},7,'Return the first singleton value, or null if none.',"function solve({ nums }) {\n  const counts = /* @__PURE__ */ new Map();\n  for (const x of nums) counts.set(x, (counts.get(x) ?? 0) + 1);\n  for (const x of nums) if (counts.get(x) === 1) return x;\n  return null;\n}",'A counting pass separates global frequency from first-position selection.','Only 7 has count 1.','Expected O(n)','O(k)','A value seen once so far may appear again later; wait for full counts.'),
 e('map','mode','Most frequent, earliest on a tie',{nums:[2,1,1,2,3]},2,'Return the most frequent value; tie by first appearance. Empty input returns null.',"function solve({ nums }) {\n  const counts = /* @__PURE__ */ new Map();\n  for (const x of nums) counts.set(x, (counts.get(x) ?? 0) + 1);\n  let best = null, max = 0;\n  for (const [x, n] of counts) if (n > max) {\n    best = x;\n    max = n;\n  }\n  return best;\n}",'Iterate final counts in insertion order and replace the winner only for a larger count.','2 and 1 both occur twice; 2 appeared first.','Expected O(n)','O(k)','Updating the winner while counting can accidentally choose the wrong tie winner.'),
 e('map','same-bag','Compare values with multiplicity',{a:[1,2,2],b:[2,1,2]},true,'Return whether both arrays contain identical values with identical counts. Order does not matter.',"function solve({ a, b }) {\n  if (a.length !== b.length) return false;\n  const counts = /* @__PURE__ */ new Map();\n  for (const x of a) counts.set(x, (counts.get(x) ?? 0) + 1);\n  for (const x of b) {\n    const n = counts.get(x) ?? 0;\n    if (n === 0) return false;\n    counts.set(x, n - 1);\n  }\n  return true;\n}",'Subtract the second array’s demand from the first array’s counts.','Two copies of 2 must be available.','Expected O(n+m)','O(k)','Equal Sets cannot distinguish [1,1,2] from [1,2,2].'),
 e('map','parity','Group by a computed key',{nums:[1,2,3,4]},[['odd',[1,3]],['even',[2,4]]],'Group values as odd/even; order groups by first appearance.',"function solve({ nums }) {\n  const groups = /* @__PURE__ */ new Map();\n  for (const x of nums) {\n    const key = x % 2 === 0 ? \"even\" : \"odd\";\n    if (!groups.has(key)) groups.set(key, []);\n    groups.get(key).push(x);\n  }\n  return [...groups];\n}",'A key can be derived from each value rather than being the value itself.','The odd group is created first because 1 arrives first.','Expected O(n)','O(n)','Do not share the same array object between group keys.'),
 e('map','positions','Store every occurrence index',{nums:[5,2,5,5]},[[5,[0,2,3]],[2,[1]]],'Return each value mapped to its list of indices.',"function solve({ nums }) {\n  const pos = /* @__PURE__ */ new Map();\n  for (let i = 0; i < nums.length; i++) {\n    if (!pos.has(nums[i])) pos.set(nums[i], []);\n    pos.get(nums[i]).push(i);\n  }\n  return [...pos];\n}",'Use value → index list when one index is not enough.','The key 5 retains three distinct positions.','Expected O(n)','O(n)','Replacing an existing list loses earlier positions.'),
 e('map','last-index','Keep the last index',{nums:[5,2,5]},[[5,2],[2,1]],'Return value → last index entries in key insertion order.',"function solve({ nums }) {\n  const last = /* @__PURE__ */ new Map();\n  for (let i = 0; i < nums.length; i++) last.set(nums[i], i);\n  return [...last];\n}",'Overwriting is intentional when the newest position is the desired information.','5 is updated from index 0 to 2, but remains the first key.','Expected O(n)','O(k)','This overwrite policy is different from earliest-index Two Sum.'),
 e('map','pair-count','Count all target-sum index pairs',{nums:[1,1,2,2],target:3},4,'Count all pairs i<j that sum to target.',"function solve({ nums, target }) {\n  const counts = /* @__PURE__ */ new Map();\n  let pairs = 0;\n  for (const x of nums) {\n    pairs += counts.get(target - x) ?? 0;\n    counts.set(x, (counts.get(x) ?? 0) + 1);\n  }\n  return pairs;\n}",'Every earlier complement produces a distinct index pair.','Each of the two 2s matches both earlier 1s.','Expected O(n)','O(k)','A Set would remember presence but lose the number of earlier complements.'),
 e('map','subarray-count','Count contiguous target-sum ranges',{nums:[1,-1,1],target:1},3,'Count nonempty contiguous subarrays with the target sum.',"function solve({ nums, target }) {\n  const seen = /* @__PURE__ */ new Map([[0, 1]]);\n  let sum = 0, count = 0;\n  for (const x of nums) {\n    sum += x;\n    count += seen.get(sum - target) ?? 0;\n    seen.set(sum, (seen.get(sum) ?? 0) + 1);\n  }\n  return count;\n}",'Two prefix sums differing by target identify a matching range.','Count [0,0], [0,2], and [2,2].','Expected O(n)','O(n)','Seed prefix sum 0 once so ranges starting at index 0 are counted.'),
 e('map','longest-sum','Longest contiguous target-sum range',{nums:[1,-1,5,-2,3],target:3},4,'Return the maximum length of a contiguous range with target sum, or 0.',"function solve({ nums, target }) {\n  const first = /* @__PURE__ */ new Map([[0, -1]]);\n  let sum = 0, best = 0;\n  for (let i = 0; i < nums.length; i++) {\n    sum += nums[i];\n    if (first.has(sum - target)) best = Math.max(best, i - first.get(sum - target));\n    if (!first.has(sum)) first.set(sum, i);\n  }\n  return best;\n}",'Keep the earliest index for each prefix sum to maximize future lengths.','The range [1,-1,5,-2] has sum 3 and length 4.','Expected O(n)','O(n)','Overwriting an earlier prefix index can shorten the best range.'),
 e('map','intersection-bag','Intersection with repeated values',{a:[1,2,2,3],b:[2,2,2,4]},[2,2],'Return common values with minimum multiplicity, in the second array’s order.',"function solve({ a, b }) {\n  const counts = /* @__PURE__ */ new Map();\n  for (const x of a) counts.set(x, (counts.get(x) ?? 0) + 1);\n  const out = [];\n  for (const x of b) {\n    const n = counts.get(x) ?? 0;\n    if (n > 0) {\n      out.push(x);\n      counts.set(x, n - 1);\n    }\n  }\n  return out;\n}",'Each successful match consumes one available copy.','Only two 2s are available in a, so the third 2 in b is skipped.','Expected O(n+m)','O(k) plus output','A Set-based intersection returns distinct values instead.'),
 e('map','join','Join records by ID',{users:[{id:1,name:'Asha'},{id:2,name:'Ravi'}],orders:[{userId:2,total:9},{userId:3,total:5}]},[{name:'Ravi',total:9},{name:null,total:5}],'Attach each order’s user name, or null if the user ID is missing. User IDs are unique.',"function solve({ users, orders }) {\n  const byId = /* @__PURE__ */ new Map();\n  for (const u of users) byId.set(u.id, u.name);\n  const out = [];\n  for (const o of orders) out.push({ name: byId.get(o.userId) ?? null, total: o.total });\n  return out;\n}",'Build an index once rather than scanning all users for every order.','userId 2 resolves to Ravi; userId 3 has no match.','Expected O(u+o)','O(u) plus output','Duplicate IDs would overwrite earlier entries; define that policy first.'),
 e('map','merge-counts','Combine frequency summaries',{a:[[1,2],[2,1]],b:[[2,3],[3,1]]},[[1,2],[2,4],[3,1]],'Add count entries from two summaries. Preserve first key insertion order.',"function solve({ a, b }) {\n  const counts = /* @__PURE__ */ new Map();\n  for (const [key, n] of [...a, ...b]) counts.set(key, (counts.get(key) ?? 0) + n);\n  return [...counts];\n}",'Keys represent values; associated numbers represent counts, not array indices.','The two entries for key 2 contribute 1+3=4.','Expected O(n+m)','O(k+n+m) including concatenation','Replacing with n instead of adding would discard one summary.'),
 e('map','window-count','Distinct values per fixed window',{nums:[1,2,1,3],k:3},[2,3],'Return the distinct count for each length-k window. k is an integer from 1 to n.',"function solve({ nums, k }) {\n  const counts = /* @__PURE__ */ new Map(), out = [];\n  for (let i = 0; i < nums.length; i++) {\n    counts.set(nums[i], (counts.get(nums[i]) ?? 0) + 1);\n    if (i >= k) {\n      const x = nums[i - k], n = counts.get(x) - 1;\n      if (n === 0) counts.delete(x);\n      else counts.set(x, n);\n    }\n    if (i >= k - 1) out.push(counts.size);\n  }\n  return out;\n}", 'A frequency Map can remove one occurrence without forgetting other copies still in the window.','Windows [1,2,1] and [2,1,3] contain 2 and 3 distinct values.','Expected O(n)','O(k) plus output','Deleting a value immediately when it leaves is wrong if another copy remains.'),
 e('map','nearby','Duplicate within k positions',{nums:[1,2,3,1],k:3},true,'Return whether equal values appear at different indices no farther than k apart. k is nonnegative.',"function solve({ nums, k }) {\n  const last = /* @__PURE__ */ new Map();\n  for (let i = 0; i < nums.length; i++) {\n    if (last.has(nums[i]) && i - last.get(nums[i]) <= k) return true;\n    last.set(nums[i], i);\n  }\n  return false;\n}", 'The most recent occurrence gives the smallest distance to the current index.','The two 1s are three positions apart.','Expected O(n)','O(d), d distinct input values','Do not keep only the earliest index when you need the nearest occurrence.'),
 e('map','first-repeat','First repeat event and its indices',{nums:[4,2,4,2]},{value:4,first:0,again:2},'Return the earliest repeat encountered, including its first and repeated indices; null if absent.',"function solve({ nums }) {\n  const first = /* @__PURE__ */ new Map();\n  for (let i = 0; i < nums.length; i++) {\n    if (first.has(nums[i])) return { value: nums[i], first: first.get(nums[i]), again: i };\n    first.set(nums[i], i);\n  }\n  return null;\n}",'The stored index explains where the repetition began.','4 repeats at index 2 before 2 repeats at index 3.','Expected O(n)','O(k)','“First duplicate” must specify first repeated event versus earliest original duplicate.'),
 e('map','remainder','Group by remainder modulo three',{nums:[-1,0,1,2,4]},[[2,[-1,2]],[0,[0]],[1,[1,4]]],'Group by mathematical remainder 0,1,2, preserving first group and element order.',"function solve({ nums }) {\n  const groups = /* @__PURE__ */ new Map();\n  for (const x of nums) {\n    const key = (x % 3 + 3) % 3;\n    if (!groups.has(key)) groups.set(key, []);\n    groups.get(key).push(x);\n  }\n  return [...groups];\n}",'Normalize JavaScript’s negative remainder when a nonnegative bucket is required.','-1 belongs to remainder bucket 2.','Expected O(n)','O(n)','JavaScript -1 % 3 is -1, not 2.'),
 e('map','record-update','Keep the latest record per ID',{records:[{id:1,score:3},{id:2,score:5},{id:1,score:9}]},[{id:1,score:9},{id:2,score:5}],'Return the last record for each ID, with IDs in first-appearance order.',"function solve({ records }) {\n  const latest = /* @__PURE__ */ new Map();\n  for (const r of records) latest.set(r.id, r);\n  return [...latest.values()];\n}",'Map keys let you replace one logical entity without adding a duplicate entry.','ID 1 is updated to score 9 but stays before ID 2.','Expected O(n)','O(k) references','This returns original record references, not deep clones.'),

 e('set','duplicates','Duplicate detection with a Set',{nums:[3,1,3]},true,'Return whether any value repeats.',"function solve({ nums }) {\n  const seen = /* @__PURE__ */ new Set();\n  for (const x of nums) {\n    if (seen.has(x)) return true;\n    seen.add(x);\n  }\n  return false;\n}",'Only membership is needed, so no associated index/count is stored.','On the last 3, has(3) is already true.','Expected O(n)','O(k)','Adding before checking would make every value appear repeated.'),
 e('set','unique','Keep unique values in order',{nums:[3,1,3,2,1]},[3,1,2],'Return distinct values in first-appearance order.',"function solve({ nums }) {\n  const seen = /* @__PURE__ */ new Set();\n  for (const x of nums) seen.add(x);\n  return [...seen];\n}",'Repeated add() leaves one stored value.','The first insertion order is 3, then 1, then 2.','Expected O(n)','O(k)','Deduplication does not sort the values.'),
 e('set','membership','Answer several membership queries',{nums:[2,4,8],queries:[4,5,8]},[true,false,true],'Return whether each query value is in nums.',"function solve({ nums, queries }) {\n  const values = new Set(nums), out = [];\n  for (const q of queries) out.push(values.has(q));\n  return out;\n}",'Building membership once is useful for repeated lookups.','4 and 8 exist; 5 does not.','Expected O(n+q)','O(k) plus output','For a single tiny lookup, the cost of building a Set may not be worthwhile.'),
 e('set','intersection','Distinct intersection',{a:[1,2,2,3],b:[2,3,4]},[2,3],'Return common distinct values, in first-array order.',"function solve({ a, b }) {\n  const other = new Set(b), out = /* @__PURE__ */ new Set();\n  for (const x of a) if (other.has(x)) out.add(x);\n  return [...out];\n}",'One Set checks membership; another prevents repeated output.','Both occurrences of 2 produce only one output entry.','Expected O(n+m)','O(k+m)','This ignores multiplicity; use counts when copies matter.'),
 e('set','difference','Values only in the first array',{a:[1,2,2,3],b:[2,4]},[1,3],'Return distinct values in a but not b, in a order.',"function solve({ a, b }) {\n  const blocked = new Set(b), out = /* @__PURE__ */ new Set();\n  for (const x of a) if (!blocked.has(x)) out.add(x);\n  return [...out];\n}",'Negated membership expresses exclusion.','2 is blocked; 1 and 3 remain.','Expected O(n+m)','O(k+m)','a−b and b−a are different operations.'),
 e('set','union','Combine distinct values',{a:[1,2],b:[2,3]},[1,2,3],'Return distinct values, processing a before b.',"function solve({ a, b }) {\n  const out = new Set(a);\n  for (const x of b) out.add(x);\n  return [...out];\n}",'A Set removes duplicate membership across both inputs.','Adding 2 again does not create another element.','Expected O(n+m)','O(k)','A union does not preserve duplicate counts.'),
 e('set','symmetric','Values belonging to exactly one side',{a:[1,2,2],b:[2,3]},[1,3],'Return distinct values present in exactly one input; a-only first, then b-only.',"function solve({ a, b }) {\n  const A = new Set(a), B = new Set(b), out = [];\n  for (const x of A) if (!B.has(x)) out.push(x);\n  for (const x of B) if (!A.has(x)) out.push(x);\n  return out;\n}",'Compute both directional differences.','2 exists on both sides and is excluded.','Expected O(n+m)','O(n+m)','Counting odd total occurrences is not the same as symmetric difference.'),
 e('set','subset','Check whether one collection is contained',{a:[1,1,2],b:[1,2,3]},true,'Return whether every distinct value of a occurs in b.',"function solve({ a, b }) {\n  const values = new Set(b);\n  for (const x of a) if (!values.has(x)) return false;\n  return true;\n}",'Membership containment deliberately ignores multiplicity.','Both occurrences of 1 ask the same membership question.','Expected O(n+m)','O(m)','This does not check whether b contains enough copies to fulfill a multiset.'),
 e('set','disjoint','Check that collections do not overlap',{a:[1,3],b:[2,4]},true,'Return true if the arrays share no value.',"function solve({ a, b }) {\n  const values = new Set(b);\n  for (const x of a) if (values.has(x)) return false;\n  return true;\n}",'A single shared member disproves disjointness.','Neither 1 nor 3 occurs in b.','Expected O(n+m)','O(m)','An empty collection is disjoint from every collection.'),
 e('set','equal','Compare distinct contents',{a:[1,1,2],b:[2,1]},true,'Return whether both arrays have the same distinct values; ignore order and counts.',"function solve({ a, b }) {\n  const A = new Set(a), B = new Set(b);\n  if (A.size !== B.size) return false;\n  for (const x of A) if (!B.has(x)) return false;\n  return true;\n}",'Compare sizes and membership, not Set object identity.','The repeated 1 does not affect distinct contents.','Expected O(n+m)','O(n+m)','A===B compares object references, not their members.'),
 e('set','three-way','Common to three arrays',{a:[1,2,3],b:[2,3,4],c:[3,5]},[3],'Return distinct common values in a order.',"function solve({ a, b, c }) {\n  const B = new Set(b), C = new Set(c), out = /* @__PURE__ */ new Set();\n  for (const x of a) if (B.has(x) && C.has(x)) out.add(x);\n  return [...out];\n}",'Each candidate must pass membership checks against both other inputs.','2 fails the third-array check; 3 passes both.','Expected O(n+m+p)','O(m+p+k)','Intersection requires all conditions, not any one condition.'),
 e('set','two-sum','Does a target-sum pair exist?',{nums:[2,7,11,15],target:9},true,'Return a Boolean for whether two distinct positions sum to target. This does not return indices.',"function solve({ nums, target }) {\n  const seen = /* @__PURE__ */ new Set();\n  for (const x of nums) {\n    if (seen.has(target - x)) return true;\n    seen.add(x);\n  }\n  return false;\n}",'Membership is sufficient only because the requested result is yes/no.','For 7, the earlier complement 2 is present.','Expected O(n)','O(k)','For LeetCode-style indices, a Map can retain the missing positional information.'),
 e('set','first-repeat','First value that repeats',{nums:[4,2,4,2]},4,'Return the first repeat encountered, or null.',"function solve({ nums }) {\n  const seen = /* @__PURE__ */ new Set();\n  for (const x of nums) {\n    if (seen.has(x)) return x;\n    seen.add(x);\n  }\n  return null;\n}",'The scan stops at the first failed uniqueness check.','4 repeats before the second 2 arrives.','Expected O(n)','O(k)','This returns a value, not its repeated index.'),
 e('set','missing-positive','Smallest missing positive integer',{nums:[3,4,-1,1]},2,'Return the smallest positive integer not present.',"function solve({ nums }) {\n  const values = new Set(nums);\n  for (let candidate = 1; candidate <= nums.length + 1; candidate++) if (!values.has(candidate)) return candidate;\n}",'Among n numbers, at least one value in 1..n+1 must be missing.','1 exists, but 2 is absent.','Expected O(n)','O(n)','Zero and negative numbers do not count as positive candidates.'),
 e('set','consecutive','Longest consecutive-value run',{nums:[100,4,200,1,3,2,2]},4,'Return the longest run of consecutive distinct integer values, regardless of input positions.',"function solve({ nums }) {\n  const values = new Set(nums);\n  let best = 0;\n  for (const x of values) {\n    if (values.has(x - 1)) continue;\n    let y = x;\n    while (values.has(y)) y++;\n    best = Math.max(best, y - x);\n  }\n  return best;\n}",'Start counting only where the previous value is absent, so each run is scanned once.','The run 1,2,3,4 has length 4.','Expected O(n)','O(n)','This is consecutive values, not a contiguous subarray.'),
 e('set','absolute','Distinct absolute magnitudes',{nums:[-2,2,-3,0,3]},[2,3,0],'Return distinct absolute values in first transformed appearance order.',"function solve({ nums }) {\n  const values = /* @__PURE__ */ new Set();\n  for (const x of nums) values.add(Math.abs(x));\n  return [...values];\n}",'Transform before applying the equality rule.','-2 and 2 both map to magnitude 2.','Expected O(n)','O(k)','Changing the order to deduplicate before transforming can leave duplicates.'),
 e('set','blocked','Filter against blocked values',{nums:[1,2,1,3,4],blocked:[2,4]},[1,1,3],'Remove blocked values while preserving all other occurrences and order.',"function solve({ nums, blocked }) {\n  const deny = new Set(blocked), out = [];\n  for (const x of nums) if (!deny.has(x)) out.push(x);\n  return out;\n}",'The membership structure is for blocked values, not output deduplication.','Both unblocked 1s must remain.','Expected O(n+b)','O(b) plus output','Using a Set for output would wrongly discard the second 1.'),
 e('set','tags','Collect unique tags',{groups:[['js','react'],['js','sql'],[]]},['js','react','sql'],'Return distinct exact tag strings in first-appearance order.',"function solve({ groups }) {\n  const tags = /* @__PURE__ */ new Set();\n  for (const group of groups) for (const tag of group) tags.add(tag);\n  return [...tags];\n}",'A nested traversal flattens groups while Set enforces membership.','The repeated js is stored once.','Expected O(g+n)','O(k)','Strings are case-sensitive: JS and js are different tags unless normalized.'),
 e('set','duplicate-ids','Detect duplicate record IDs',{records:[{id:1,name:'A'},{id:2,name:'B'},{id:1,name:'C'}]},true,'Return whether record IDs repeat; records themselves are different objects.',"function solve({ records }) {\n  const ids = /* @__PURE__ */ new Set();\n  for (const r of records) {\n    if (ids.has(r.id)) return true;\n    ids.add(r.id);\n  }\n  return false;\n}",'Extract the logical key before checking uniqueness.','The third record repeats ID 1.','Expected O(n)','O(k)','A Set of entire objects compares identities and would miss this logical duplicate.'),
 e('set','complete-range','Does the array contain every number 1..n?',{nums:[3,1,2,2],n:3},true,'Return whether all integers from 1 to n are present. Extra values and duplicates are allowed; n is nonnegative.',"function solve({ nums, n }) {\n  const values = new Set(nums);\n  for (let x = 1; x <= n; x++) if (!values.has(x)) return false;\n  return true;\n}",'Check each required member instead of relying on array length or sum.','1, 2 and 3 exist even though 2 appears twice.','Expected O(length+n)','O(k)','A matching sum alone does not prove every required value is present.'),
];

export type CompareFrame={action:string;memory:string;active:number[]};
export function compareArrayApproaches(nums:number[],target:number,mode:'duplicates'|'pair',track:ArrayTrack){
 if(nums.length>12||nums.some(x=>!Number.isInteger(x)||Math.abs(x)>1000)||!Number.isInteger(target)||Math.abs(target)>2000)throw Error('Use up to 12 integers from -1000 to 1000 and a target from -2000 to 2000.');
 const frames:CompareFrame[]=[{action:'Begin with no earlier values inspected.',memory:track==='loop'?'No lookup structure':'Empty '+track,active:[]}];let checks=0,result=false;
 const map=new Map<number,number>(),set=new Set<number>();
 outer:for(let j=0;j<nums.length;j++){
  if(track==='loop'){for(let i=0;i<j;i++){checks++;const match=mode==='duplicates'?nums[i]===nums[j]:nums[i]+nums[j]===target;frames.push({action:mode==='duplicates'?`Compare ${nums[i]} and ${nums[j]}: ${match}`:`${nums[i]} + ${nums[j]} = ${nums[i]+nums[j]}: ${match?'matches':'does not match'} ${target}`,memory:'Only i and j are needed.',active:[i,j]});if(match){result=true;break outer}}}
  else{const needed=mode==='duplicates'?nums[j]:target-nums[j];checks++;const found=track==='map'?map.has(needed):set.has(needed);frames.push({action:`has(${needed}) → ${found}`,memory:JSON.stringify(track==='map'?[...map]:[...set]),active:[j]});if(found){result=true;break}if(track==='map'){if(!map.has(nums[j]))map.set(nums[j],j)}else set.add(nums[j]);frames.push({action:track==='map'?`Remember value ${nums[j]} → index ${map.get(nums[j])}`:`Remember value ${nums[j]}`,memory:JSON.stringify(track==='map'?[...map]:[...set]),active:[j]})}
 }
 frames.push({action:`Return ${result}`,memory:track==='loop'?'No lookup structure':JSON.stringify(track==='map'?[...map]:[...set]),active:[]});return {frames,result,checks,stored:track==='loop'?0:track==='map'?map.size:set.size};
}
