import type {ReadingLesson} from './commute-guides';
import {cartoonPatterns} from './cartoon-patterns';
import {patternReferences} from './pattern-references';
export type CartoonScene={title:string;say:string;technical:string;code:string;items:string[];active:number[]};
export type CartoonLesson={id:string;category:string;title:string;world:'table'|'city'|'queue'|'stack'|'tree'|'array'|'stage'|'factory';why:string;limit:string;scenes:CartoonScene[];quiz:{question:string;choices:string[];answer:number;why:string}};
const s=(title:string,say:string,technical:string,code:string,items:string[],active:number[]):CartoonScene=>({title,say,technical,code,items,active});
const m=(id:string,category:string,title:string,world:CartoonLesson['world'],why:string,limit:string,scenes:CartoonScene[],question:string,choices:string[],answer:number,explanation:string):CartoonLesson=>({id,category,title,world,why,limit,scenes,quiz:{question,choices,answer,why:explanation}});
export const cartoonLessons:CartoonLesson[]=[
 ...cartoonPatterns,
 m('sql-where','SQL & PostgreSQL','The WHERE gate','table','Ask the database for just the rows you need.','The gate is an analogy for logical filtering, not the database’s physical execution plan.',[
 s('Meet the team','Three friends bring their scores. We only want scores of at least ten.','Each row has a name and a score.','SELECT name FROM scores WHERE points >= 10;', ['Asha | 12','Ben | 7','Chen | 10'],[]),
 s('Check the rule','Asha and Chen pass our gate. Ben does not meet this rule.','The predicate is true for 12 and 10. SQL WHERE keeps true, not false or unknown.', '12 >= 10 → true; 7 >= 10 → false; 10 >= 10 → true',['Asha | 12','Ben | 7','Chen | 10'],[0,2]),
 s('Show the answer','We asked for names, so the answer shows names, not every column.','Projection selects name. Add ORDER BY when output order matters.','Result names: Asha, Chen (order unspecified)',['Asha','Chen'],[0,1])
 ],'How do you keep only rows whose city is Pune?',['WHERE city = \'Pune\'','ORDER BY city','SELECT city only'],0,'WHERE chooses rows. SELECT chooses columns; ORDER BY sorts.'),
 m('sql-join','SQL & PostgreSQL','Match the lunch tickets','table','Combine related data using a shared key.','A join can produce multiple matches. A key is not automatically unique.',[
 s('Two lists','One list knows each child. Another list knows who ordered lunch.','Customers and orders are separate tables.','customers: (1,Asha),(2,Ben); orders: (9,1)',['Customer 1: Asha','Customer 2: Ben','Order 9: customer 1'],[]),
 s('Match the number','Ticket number one matches Asha. Ben has no lunch ticket in this example.','Join on the foreign-key relationship, not row position.','SELECT c.name,o.id FROM customers c LEFT JOIN orders o ON o.customer_id=c.id;',['Asha ↔ order 9','Ben ↔ no match'],[0]),
 s('Keep unmatched friends','A LEFT JOIN keeps Ben too, with an empty order value.','Unmatched right-side columns are SQL NULL. An INNER JOIN would omit Ben.','Asha | 9; Ben | NULL',['Asha | 9','Ben | NULL'],[0,1])
 ],'What happens if Asha has two matching orders?',['Only one appears','Two joined rows appear','The database rejects the join'],1,'Each matching pair produces a row unless you explicitly aggregate or deduplicate.'),
 m('sql-group','SQL & PostgreSQL','Team baskets and HAVING','table','Summarize many rows into one result per group.','WHERE filters individual rows; HAVING filters groups after aggregation.',[
 s('Collect fruit','Red team brings three apples, then two more. Blue brings one.','Each delivery is a row.','deliveries: (Red,3),(Red,2),(Blue,1)',['Red | 3','Red | 2','Blue | 1'],[]),
 s('One basket per team','Put each team’s apples in its own basket. Red now has five.','GROUP BY creates result groups; SUM adds each group’s values.','SELECT team,SUM(apples) FROM deliveries GROUP BY team;',['Red | 5','Blue | 1'],[0,1]),
 s('Choose big baskets','Only keep baskets containing at least four apples.','HAVING applies to the aggregate result.','... GROUP BY team HAVING SUM(apples) >= 4;',['Red | 5'],[0])
 ],'Where does SUM(apples) >= 4 belong?',['HAVING','WHERE on the input rows','ORDER BY only'],0,'HAVING can filter grouped aggregates.'),
 m('acid','SQL & PostgreSQL','The all-or-nothing coin swap','city','Use transactions to protect changes that belong together.','Isolation levels vary; a transaction is not automatically serializable.',[
 s('Make a promise','Asha gives Ben five coins. We must not lose the coins halfway through.','Debit and credit should be one transaction.','BEGIN; -- Asha=20, Ben=10',['Asha: 20','Transfer: 5','Ben: 10'],[0]),
 s('Keep both changes together','If the second step fails, undo the first instead of keeping half a swap.','Atomicity means all-or-nothing. Constraints enforce rules such as valid balances.','UPDATE accounts SET balance=balance-5 WHERE id=1; -- credit next',['Debit pending','Credit pending','ROLLBACK on error'],[0,1]),
 s('Finish the promise','When both steps succeed, save the result. Other swaps still need sensible rules.','COMMIT makes the transaction durable under the database’s guarantees; isolation governs concurrent visibility.','COMMIT; -- Asha=15, Ben=15',['Asha: 15','Committed','Ben: 15'],[0,2])
 ],'If credit fails, should the debit remain?',['Yes','No: roll back the transaction','Only rename the account'],1,'Atomicity prevents a half-completed transfer.'),
 m('indexes','SQL & PostgreSQL','The library’s index cards','tree','An index can avoid scanning every row for a selective lookup.','Indexes use space and add write work. The planner may prefer a scan.',[
 s('A long shelf','Finding one book by opening every book is slow on a huge shelf.','A sequential scan examines table rows.','SELECT * FROM books WHERE isbn = $1;',['Book shelf','Every row','Target ISBN'],[1]),
 s('Follow the index','Sorted index cards point us toward the right book.','A B-tree index supports ordered key lookup; actual plans depend on data and selectivity.','CREATE INDEX ON books(isbn);',['Root keys','Branch keys','Matching key'],[0,1,2]),
 s('Pay for the helper','When books change, the index cards must change too.','Measure plans with EXPLAIN; extra indexes make writes more expensive.','EXPLAIN SELECT * FROM books WHERE isbn = $1;',['Read benefit','Storage cost','Write maintenance'],[0,2])
 ],'Should every column always get an index?',['Yes','No: measure the query and write costs','Only names can be indexed'],1,'Useful indexes depend on queries, selectivity and write workload.'),
 m('redis','System design','Redis snack cupboard','city','Cache repeated reads near your application.','Redis is not automatically synchronized with your database; expiration and invalidation need a policy.',[
 s('An empty cupboard','The robot wants a snack recipe. Its quick cupboard is empty.','A cache-aside read first checks Redis.','GET product:42 → miss',['Client','App','Redis: empty','Database'],[2]),
 s('Visit the big library','Fetch the recipe from the big library and keep a copy nearby.','On a miss, read the database and cache the result with a chosen TTL.','DB read → SET product:42 value EX 60',['Client','App','Redis: copy','Database: source'],[3,2]),
 s('A recipe changes','The library updates the recipe. An old cupboard copy can now be wrong.','Invalidate or update cached data on writes; choose acceptable staleness explicitly.','UPDATE product; DEL product:42;',['Database: new','Redis: invalidate','Next read: refill'],[0,1])
 ],'Does a database update magically refresh every cached copy?',['Yes','No','Only at midnight'],1,'Your application needs an invalidation, update or expiration strategy.'),
 m('load-balancer','System design','The busy pizza city','city','Spread requests over healthy application servers.','Adding servers does not remove shared database bottlenecks or solve session state automatically.',[
 s('A crowd arrives','One pizza counter cannot serve everyone quickly.','Clients send requests to a load balancer.','Client → load balancer',['Customers','Balancer','Server A','Server B'],[0,1]),
 s('Choose a counter','The helper sends different customers to available counters.','Routing can use round robin, least connections or another policy.','request 1 → A; request 2 → B',['Balancer','Server A: busy','Server B: ready','Database'],[0,2]),
 s('One counter closes','If a counter becomes unhealthy, send new work elsewhere.','Health checks remove unhealthy targets; in-flight requests may still need safe retries.','health(A)=fail → route to B',['Server A: unhealthy','Balancer','Server B: healthy'],[1,2])
 ],'Will more app servers always fix a slow database?',['Yes','No','Only if they have the same name'],1,'A shared bottleneck can remain after scaling the app tier.'),
 m('message-queue','System design','The parcel waiting room','queue','Decouple accepting work from doing it.','Delivery guarantees vary; duplicate delivery is possible, so consumers need safe handling.',[
 s('Leave a parcel','You leave your parcel with a ticket instead of waiting for the whole delivery.','A producer enqueues a job for asynchronous processing.','POST /orders → enqueue(orderId)',['Order 41','Order 42','Worker'],[0]),
 s('Worker takes a job','A worker picks up a parcel. Other customers can keep leaving parcels.','Consumers process jobs at their own pace; queues absorb bursts within capacity.','receive → process → acknowledge',['Worker: 41','Waiting: 42','Ack: pending'],[0]),
 s('A worker drops out','If a worker disappears before confirming delivery, the parcel may be tried again.','Make the side effect idempotent before acknowledging a retryable message.','if processed(orderId) return;',['Retry: 41','Already processed?','Ack safely'],[0,1,2])
 ],'Why remember processed job IDs?',['To make retries safe','To sort customer names','To remove every job before processing'],0,'A repeated message should not repeat an irreversible side effect.'),
 m('idempotency','System design','One ticket, one purchase','city','Make repeating a request safe for the intended operation.','Checking a key and performing a side effect must be coordinated; a simple non-atomic check is not enough.',[
 s('The reply gets lost','You press Buy. The shop completes it, but the reply never reaches you.','A client timeout does not prove the server failed.','POST /purchase; Idempotency-Key: abc',['Client: waiting','Purchase: saved','Reply: lost'],[1,2]),
 s('Try the same ticket','Try again with the same ticket number, not a new one.','The server recognizes the same operation key and checks request compatibility.','retry with key abc',['Retry abc','Saved result abc','No second purchase'],[0,1]),
 s('Return the saved result','The shop returns the original result. You get one purchase, not two.','Use a unique key plus a transactional design, retaining the operation result.','return savedResult(abc)',['One purchase','Same result','Client informed'],[0,2])
 ],'Should a retry use a fresh key for the same purchase?',['Yes','No','The key should be the password'],1,'Use the same operation key to identify a retry of that operation.'),
 m('websocket','System design','The open walkie-talkie','city','Keep a two-way channel for timely updates.','WebSocket alone does not guarantee application-level delivery, replay or exactly-once processing.',[
 s('Open the channel','Instead of asking for news repeatedly, open a channel with the server.','A WebSocket connection begins with a handshake.','Browser ↔ server',['Browser','Handshake','Server'],[0,1,2]),
 s('Talk both ways','Now either side can send a message while the channel is open.','Useful for chat, collaboration and live updates.','socket.send(message)',['Browser: message','Open channel','Server: update'],[0,2]),
 s('The channel breaks','If the connection breaks, reconnect and ask what you missed.','Use authentication, heartbeats and application message IDs/replay where required.','reconnect → request messages after lastSeenId',['Disconnected','Reconnect','Resume from ID'],[1,2])
 ],'Does reconnecting automatically replay every missed chat message?',['Yes','No: the app needs a replay design','Messages cannot be lost'],1,'Connection transport and durable message delivery are separate concerns.'),
 m('hld-lld','System design','City map and house blueprint','city','Use HLD for system responsibilities and LLD for component details.','A diagram should answer requirements and trade-offs, not just list fashionable services.',[
 s('Draw the city','First show where the school, homes and roads belong.','HLD describes services, data stores, communication and scale boundaries.','Client → API → service → database',['Client','API','Service','Database'],[0,1,2,3]),
 s('Draw one house','Now choose how the rooms, doors and switches fit together.','LLD details interfaces, classes or functions, state transitions and error handling.','OrderService.placeOrder(input)',['Input contract','Validation','State change','Error result'],[0,1,2,3]),
 s('Walk through a failure','Explain what happens if a door sticks, not only when everything works.','Start with requirements, trace a request, choose contracts, then examine failures and costs.','What if payment times out?',['Requirement','Normal flow','Failure flow','Trade-off'],[2,3])
 ],'Which is usually an LLD concern?',['Method contracts and state transitions','Only the number of regions','The company logo'],0,'LLD explains the internal responsibilities and behavior of a component.'),
 m('map-set','DSA','The guest book and locker desk','array','Choose Set for membership and Map for associated information.','JavaScript object keys compare by identity, not by equal-looking fields.',[
 s('Who has arrived?','A guest book only needs to say whether a name has appeared.','A Set stores distinct values.','seen.add("Asha"); seen.has("Asha");',['Asha','Ben','Asha again'],[0,2]),
 s('Which locker is theirs?','A locker desk also needs to remember each guest’s locker number.','A Map stores key → value pairs.','lockers.set("Asha", 0); lockers.get("Asha");',['Asha → 0','Ben → 7'],[0]),
 s('Choose the information','If you need a count or an index, keep that information too.','Use has for existence: a stored index of 0 is still valid.','counts.set(x, (counts.get(x) ?? 0) + 1)',['Membership: Set','Index/count: Map'],[0,1])
 ],'For Two Sum’s original indices, which extra information matters?',['Value → earlier index','Only unique values','Only the array length'],0,'A Map can return the earlier partner’s index.'),
 m('stack','DSA','The pancake stack','stack','Handle the most recent unfinished item first.','A stack is LIFO, not the FIFO order used by a queue.',[
 s('Put down a pancake','Put A on a plate, then B on top of A.','push adds to the top of a stack.','stack.push("A"); stack.push("B");',['A','B'],[1]),
 s('Take the top one','You take B first because it is on top.','pop removes the latest item.','stack.pop() → "B"',['A'],[0]),
 s('Match nested brackets','When an inner bracket closes, match the latest opening bracket first.','This last-opened-first-closed rule validates nesting.','([)] → invalid, even though counts match',['Open (','Open [','Wrong close )'],[1,2])
 ],'After push A, push B, pop, what remains?',['A','B','A and B'],0,'The last pushed item B is removed.'),
 m('queue','DSA','The ticket counter','queue','Process arrivals in first-in-first-out order.','Priority queues use a different rule; this lesson shows a normal FIFO queue.',[
 s('Join the line','Asha arrives, then Ben, then Chen.','Enqueue appends to the waiting line.','queue.push("Asha","Ben","Chen");',['Asha','Ben','Chen'],[0]),
 s('Serve the first arrival','Asha gets served first. Ben moves to the front.','A head index avoids repeatedly shifting a JavaScript array.','const next = queue[head++];',['Ben','Chen'],[0]),
 s('Keep the order','New arrivals join behind everyone already waiting.','FIFO is useful for BFS frontiers and ordered work.','queue.push("Diya");',['Ben','Chen','Diya'],[2])
 ],'Who is served next after Asha?',['Chen','Ben','The newest arrival'],1,'FIFO serves the earliest remaining arrival.'),
 m('trees-bfs','DSA','Explore the treehouse','tree','BFS explores nearby nodes before farther ones.','Fewest hops means shortest path only when every edge has equal cost.',[
 s('Start at the root','Stand at treehouse A. Its next rooms are B and C.','A tree is a graph without cycles; BFS uses a queue.','queue = [A]',['A','B','C','D','E'],[0]),
 s('Visit one level','Visit B and C before exploring rooms farther away.','Process the frontier in FIFO order.','visit A → enqueue B,C',['A','B','C','D','E'],[1,2]),
 s('Then go deeper','Now visit D and E. You have explored level by level.','Mark visited when enqueueing in a general graph to avoid cycles.','levels = [[A],[B,C],[D,E]]',['A','B','C','D','E'],[3,4])
 ],'Which structure keeps BFS in level order?',['Stack','Queue','An unsorted bag'],1,'The FIFO frontier keeps shallower discoveries ahead of deeper ones.'),
 m('binary-search','DSA','Guess the hidden number','array','Discard half the candidates using an ordered comparison.','The input must be ordered or the yes/no condition must be monotonic.',[
 s('Look in the middle','Find seven in this sorted row. The middle value is five.','Compare target with the midpoint.','mid=2; nums[mid]=5',['1','3','5','7','9'],[2]),
 s('Cross out the small half','Seven is bigger than five. Everything to the left is too small too.','Move past mid so the candidate interval strictly shrinks.','lo = mid + 1; // lo=3',['1','3','5','7','9'],[3,4]),
 s('Find the answer','The next middle value is seven. Return its position.','The target is at index 3. Binary search uses O(log n) comparisons.','return 3',['1','3','5','7','9'],[3])
 ],'Can the same elimination rule search an arbitrary unsorted row?',['Yes','No','Only if the numbers are odd'],1,'Without order, discarding a half may discard the answer.'),
 m('sliding-window','DSA','The moving picture frame','array','Reuse work when adjacent contiguous ranges overlap.','A fixed-size sum works with negatives; some variable-size sum rules require positive values.',[
 s('Frame three numbers','Put a frame around two, one and five. Their sum is eight.','A window is a contiguous range.','sum = 2+1+5 = 8',['2','1','5','1','3','2'],[0,1,2]),
 s('Slide one place','Remove the old two and add the new one. Do not add everything again.','Subtract outgoing and add incoming values.','sum = 8-2+1 = 7',['2','1','5','1','3','2'],[1,2,3]),
 s('Keep the best','The next frame has five, one and three. Nine is our best so far.','Maintain the best complete window, not only the final sum.','sum = 7-1+3 = 9',['2','1','5','1','3','2'],[2,3,4])
 ],'Does a window skip numbers in the middle?',['Yes','No, it is contiguous','Only when the sum is large'],1,'A subsequence may skip positions; a window does not.'),
 m('closure','JavaScript','The function’s little backpack','stage','A returned function can retain access to variables from its creation scope.','The backpack is an analogy for lexical bindings, not necessarily a copied snapshot.',[
 s('Pack a counter','Make a counter with its own number starting at zero.','Each call to createCounter creates a new binding.','function createCounter(){ let n=0; return () => ++n; }',['Counter A: n=0','Counter B: n=0'],[]),
 s('Open the same backpack','Call A twice. It remembers its number: one, then two.','The closure retains access to A’s n.','const a=createCounter(); a(); a();',['Counter A: n=2','Counter B: n=0'],[0]),
 s('A different backpack','B starts at one on its first call. A’s number does not change.','Independent factory calls create independent state.','const b=createCounter(); b() → 1',['Counter A: n=2','Counter B: n=1'],[1])
 ],'Does calling createCounter twice share the same n binding?',['Yes','No','Only on Tuesdays'],1,'Each invocation creates a separate lexical binding.'),
 m('event-loop','JavaScript','The event-loop kitchen','queue','Understand why promises and timers run after synchronous work.','This simplified story describes browser scheduling; Node has additional phases.',[
 s('Finish the current recipe','The chef finishes the current job before reading waiting notes.','Synchronous JavaScript runs to completion on this call stack.','log("A"); queueMicrotask(()=>log("B")); setTimeout(()=>log("C"),0); log("D");',['Stack: A, D','Microtask: B','Timer task: C'],[0]),
 s('Read the little notes','When the stack is empty, handle the microtask note.','Microtasks are drained before the next task; newly queued microtasks also matter.','Output so far: A, D, B',['Stack: empty','Microtask: B','Timer task: C'],[1]),
 s('Take the next task','The timer can run later. Zero delay did not mean right now.','A zero-delay timer becomes eligible for a later task; it cannot interrupt the script.','Final output: A, D, B, C',['A','D','B','C'],[3])
 ],'Can a zero-delay timer interrupt the running script?',['Yes','No','Only after a console.log'],1,'The current synchronous work must finish first.'),
 m('react-render','React','The stage director','stage','Separate describing the UI from changing the actual DOM.','A render does not mean rebuilding the whole DOM; identity depends on type, position and keys.',[
 s('The scene says one','The director reads state and describes a button showing one.','Rendering calculates the next UI description.','const [count,setCount] = useState(1);',['State: 1','Render description','DOM: 1'],[0,1]),
 s('Ask for a new scene','A click asks for count plus one. React schedules another render.','Use an updater when the next state depends on previous state.','setCount(c => c + 1)',['State update','Render: button 2','DOM: still old'],[0,1]),
 s('Update the stage','React applies the needed changes. The button now shows two.','Commit updates the DOM. Effects run according to their lifecycle after a commit.','DOM text: 1 → 2',['Render description','Commit','DOM: 2'],[1,2])
 ],'Is calculating a new render the same as replacing the whole page?',['Yes','No','Only with buttons'],1,'React reconciles descriptions and commits necessary DOM changes.'),
 m('react-context-memo','React','The noticeboard and saved homework','stage','Context shares a value; memoization may avoid repeated calculation.','useMemo is a performance optimization, not a persistence guarantee or a fix for impure rendering.',[
 s('Read the noticeboard','A theme provider puts a color on a noticeboard for its descendants.','useContext reads the nearest matching provider.','const theme = useContext(ThemeContext);',['Theme provider','Layout','Button consumer'],[0,2]),
 s('Keep useful homework','If a calculation is costly and its inputs stay the same, a saved result may help.','useMemo caches a calculated value between renders when dependencies compare equal.','const total = useMemo(()=>sum(items), [items]);',['items reference','Calculate total','Cached value'],[1,2]),
 s('Check what changed','New inputs mean new homework. Measure before adding extra caching.','Mutating an array in place can make reference-based assumptions incorrect.','setItems(old => [...old, newItem]);',['New items','Recalculate','New total'],[0,1,2])
 ],'Does useMemo guarantee permanent storage?',['Yes','No','It writes to the database'],1,'It is a render-time optimization, not durable storage.'),
 m('oop','OOP & design','The toy workshop','factory','Protect state and vary behavior behind a clear contract.','Inheritance is one tool. Composition is often better when behavior changes independently.',[
 s('Protect the toy’s battery','The toy exposes a safe button instead of letting everyone pull its wires.','Encapsulation protects internal state behind deliberate operations.','class Counter { #n=0; increment(){ return ++this.#n; } }',['Private state','Public method','Caller'],[0,1]),
 s('One command, different toys','Say move to a car and a boat. Each moves in its own way.','Polymorphism lets different implementations satisfy the same contract.','for (const toy of toys) toy.move();',['move() contract','Car: drive','Boat: sail'],[1,2]),
 s('Give each helper a job','Separate payment from sending receipts. Replace one helper without rebuilding everything.','Single responsibility and dependency inversion encourage focused components and abstractions.','Checkout(paymentGateway, receiptSender)',['Checkout','Payment contract','Receipt contract'],[0,1,2])
 ],'Must Checkout know every payment provider’s internal code?',['Yes','No: depend on a suitable contract','Only when using React'],1,'A clear interface separates policy from provider details.'),
 m('mern','MERN & APIs','The request delivery team','city','Trace a request across React, Node/Express and MongoDB.','Never trust browser input just because the UI checked it; authorization belongs on the server.',[
 s('Write an order','The React screen sends a request containing the user’s intended action.','The frontend is a client, not the source of authorization.','fetch("/api/orders", {method:"POST", body:JSON.stringify(input)})',['React','HTTP request','Express','MongoDB'],[0,1]),
 s('Check the parcel','Express checks who sent it and whether the contents are allowed.','Authenticate, authorize, validate and call business logic before storing.','identity → permission → schema → service',['Identity','Permission','Validation','Service'],[0,1,2,3]),
 s('Save and reply','Store the accepted order, then send a useful response to the screen.','Handle errors deliberately and avoid leaking private data.','insertOne(order) → response 201',['MongoDB','Safe response','React update'],[0,1,2])
 ],'Can client-side validation replace server authorization?',['Yes','No','Only for logged-in users'],1,'A caller can bypass the browser UI entirely.'),
 m('dotnet','C# & .NET','The .NET helper team','factory','Follow middleware, endpoints and injected services.','Service lifetimes matter; a singleton should not capture request-scoped state.',[
 s('Enter the hallway','A request walks through middleware helpers before reaching its endpoint.','Middleware can inspect a request and pass it to the next component.','app.UseAuthentication(); app.UseAuthorization();',['Request','Middleware','Endpoint'],[0,1]),
 s('Get the right helper','The endpoint asks for an order service instead of building every helper itself.','Dependency injection resolves registered services with configured lifetimes.','builder.Services.AddScoped<IOrderService, OrderService>();',['Endpoint','IOrderService','Scoped instance'],[1,2]),
 s('Do the job asynchronously','The service can await database work while the request awaits its result.','Use async I/O and cancellation appropriately; async does not mean unlimited parallel work.','await service.FindAsync(id, cancellationToken);',['Service','Database I/O','Response'],[0,1,2])
 ],'Is a request-scoped service intended to hold every user’s shared mutable state?',['Yes','No','Only in C#'],1,'Request-scoped lifetime and singleton shared state have different responsibilities.'),
 m('flask','Python','The Flask small café','city','Understand a small route-driven Python web app.','Flask’s development server is not your production deployment plan.',[
 s('Read the address','A small café has a counter for each kind of request.','Flask maps a route to a view function.','@app.get("/orders/<int:id>")',['HTTP request','Route','View function'],[1]),
 s('Check before serving','The helper checks the request and looks up the correct order.','Validate inputs and enforce authorization in server-side code.','order = service.find_authorized(user, id)',['User identity','Permission','Order service'],[0,1,2]),
 s('Return a response','Send JSON and a meaningful status code. Run behind a suitable production server.','WSGI servers host Flask apps; production needs configuration, logging and timeouts.','return jsonify(order), 200',['Flask app','WSGI server','Client JSON'],[0,2])
 ],'Is the debug server a complete production setup?',['Yes','No','Only for small JSON'],1,'Use a production server and operational configuration.'),
 m('django','Python','The Django organized school','factory','Connect URLs, views, models and migrations.','The ORM does not remove the need to understand query costs and authorization.',[
 s('Find the classroom','A URL rule sends the request to the right view.','Django URL patterns dispatch requests.','path("orders/", views.orders)',['URL pattern','View','Request user'],[0,1]),
 s('Ask for records','The view uses a model query to ask for allowed data.','QuerySets describe database queries; avoid N+1 access patterns.','Order.objects.filter(owner=request.user)',['View','QuerySet','Database'],[1,2]),
 s('Change the school safely','When the model changes, plan how the database changes too.','Migrations version schema changes; review their impact on existing data.','makemigrations → review → migrate',['Model change','Migration','Existing data'],[0,1,2])
 ],'Does using an ORM make every query efficient?',['Yes','No','It avoids all SQL'],1,'Inspect query counts, indexes and access patterns.'),
 m('docker','Docker & CI/CD','Pack the tiny workshop','factory','Package an app environment consistently.','Containers share the host kernel; they are not complete virtual machines, and images must not contain secrets.',[
 s('Write the recipe','A Dockerfile describes how to prepare the app’s workshop.','Build instructions create an image.','Dockerfile → docker build',['Source','Dockerfile','Image'],[0,1]),
 s('Make a running copy','Start a container from the image, like opening one prepared workshop.','An image is a template; a container is a running or stopped instance.','docker run image-name',['Image','Container A','Container B'],[1,2]),
 s('Keep important files safe','A workshop can disappear. Put lasting data in a suitable external place.','Container writable layers are ephemeral; volumes or managed stores hold durable data.','database volume; runtime secret injection',['Container','Volume','Runtime configuration'],[1,2])
 ],'Should a database’s only durable copy live in an ephemeral container layer?',['Yes','No','Only on weekends'],1,'Use a storage design that survives container replacement.'),
 m('cicd','Docker & CI/CD','The careful delivery conveyor','factory','Automate repeatable checks and deployment steps.','Passing checks lowers risk but does not prove every behavior correct; releases need observation and rollback.',[
 s('Inspect the parcel','A code change enters the delivery line. Check it before sending it onward.','CI can run linting, type checks and appropriate tests.','commit → checks',['Code change','Checks','Result'],[0,1]),
 s('Build one package','Create a versioned package that you can identify later.','Build an artifact and promote that same artifact through environments.','artifact: app@commit-sha',['Verified source','Artifact','Staging'],[1,2]),
 s('Deliver and watch','Deploy, watch for trouble, and have a safe way back.','Use health checks, monitoring and a rollback or roll-forward plan.','deploy → observe → rollback if needed',['Release','Metrics','Rollback option'],[0,1,2])
 ],'Do passing tests guarantee a problem-free release?',['Yes','No','Only with a green button'],1,'Real traffic, dependencies and configuration still need observation.'),
 m('serverless','AWS & cloud','Rent a helper for an event','city','Run event-triggered work without managing individual servers yourself.','Servers still exist. Time limits, concurrency, cold starts and service costs matter.',[
 s('An event arrives','A new file arrives, so ask a helper to make its thumbnail.','An event can trigger a function such as AWS Lambda.','Object upload → function invocation',['Upload','Event','Function'],[0,1]),
 s('Do a small job','The helper runs the job, then finishes. Keep lasting results elsewhere.','Treat local invocation state as non-durable. Use external storage for persistence.','read object → resize → write output',['Function','Input object','Output object'],[0,2]),
 s('Plan for repeats','An event may be delivered again. Make the repeated job safe.','Use idempotency, bounded concurrency, permissions and observability.','output key = deterministic source version',['Retry','Same output key','Metrics'],[0,1])
 ],'Does serverless mean there are no servers?',['Yes','No','It means no database'],1,'The provider manages servers; application responsibilities remain.'),
 m('linux','Linux','Walk through the folder town','tree','Use the terminal to inspect files and navigate deliberately.','Commands shown are examples, not executed by this lesson. Always understand a command before running it.',[
 s('Where am I?','First find your current street before trying to visit another one.','pwd prints the current working directory.','pwd',['/home','/home/sam','/home/sam/app'],[1]),
 s('Look before moving','List what is here. Move into the app folder when it is the one you want.','ls lists entries; cd changes the shell’s working directory.','ls; cd app',['app/','notes.txt','images/'],[0]),
 s('Read a useful clue','Read a small file or the last lines of a log to investigate a problem.','cat shows file contents; tail limits output. Paths and permissions matter.','tail -n 20 app.log',['app.log','Last 20 lines','Observation'],[0,1])
 ],'Which command tells you the current directory?',['pwd','cd alone as a print command','A SQL query'],0,'pwd prints the current working directory.'),
 m('cpu-gpu','Computer fundamentals','One clever chef and many helpers','factory','Choose hardware based on the shape of the work.','A GPU is not faster for every task; transfer cost, memory and branching can dominate.',[
 s('A complicated recipe','A chef handles varied steps and changing decisions.','CPUs are optimized for general-purpose work and low-latency control flow.','Branching application logic',['CPU core','Decision','Next instruction'],[0,1]),
 s('Many similar slices','Many helpers can cut many similar pieces at once.','GPUs execute large amounts of parallel numerical work effectively.','Many vector/matrix operations',['Data batch','Parallel workers','Results'],[0,1,2]),
 s('Count the travel time','Sending one tiny carrot to a huge workshop can cost more than cutting it nearby.','Benchmark end-to-end work, including data transfer and launch overhead.','total time = transfer + compute + return',['Transfer','Compute','Return'],[0,2])
 ],'Will moving every small task to a GPU always help?',['Yes','No','Only if it has more lights'],1,'Parallelism helps suitable workloads, not every workload.'),
 m('rag','AI & RAG','The open-book answering robot','city','Retrieve relevant material before generating an answer.','Retrieved text can be wrong or hostile. RAG does not guarantee truth or remove the need for evaluation.',[
 s('Find useful pages','Before answering, the robot looks for pages related to your question.','Index document chunks and retrieve relevant passages using search.','question → retrieval',['Question','Search index','Relevant passages'],[0,1]),
 s('Read with boundaries','Give the robot those pages as evidence, not as commands to obey.','Pass retrieved context with source identifiers and clear instruction boundaries.','context = retrieved passages + source IDs',['Instructions','Untrusted documents','Model'],[0,1,2]),
 s('Answer and check','The robot answers with references. Check whether the pages really support it.','Evaluate relevance, groundedness and access control; say when evidence is missing.','answer + citations + uncertainty',['Draft answer','Source support','User'],[0,1])
 ],'Does retrieving a page prove the generated answer is correct?',['Yes','No','Only when the answer is long'],1,'Retrieval and generation can both fail; evidence must support the claim.'),
 m('communication','English & interviews','The clear-speaking adventure','stage','Make an explanation easy to follow with one idea and one example.','A speaking framework supports your own truthful experience; it should not invent accomplishments.',[
 s('Choose one message','Our robot wants to explain everything at once. Help it choose one point.','State the problem before implementation details.','The problem was repeated database reads.',['Problem','Many details','Listener'],[0]),
 s('Give a small example','Show one example, like using a nearby cupboard for a repeated request.','Connect the mechanism to a concrete input or scenario.','We cached frequently requested product data.',['Problem','Example','Trade-off'],[1]),
 s('Pause and check','Mention one trade-off, pause, and ask whether the listener wants more detail.','Adapt the explanation to the audience and invite clarification.','The trade-off was stale data, so we chose an expiry policy.',['Clear point','Concrete example','Follow-up question'],[0,1,2])
 ],'What should you do if you do not understand a question?',['Pretend you understand','Ask for clarification','Answer faster'],1,'Clarifying a question is part of clear communication.')
];
export const cartoonReadingLessons:ReadingLesson[]=cartoonLessons.map(l=>({id:`cartoon-${l.id}`,title:l.title,category:'Cartoon classroom',topic:l.category,format:'Visual guide',minutes:3,explanation:`${l.why}\n\nA simple story first, then the technical explanation. These are authored illustrations, not live execution.`,example:l.scenes[0].say,steps:l.scenes.map(s=>({title:s.title,detail:s.say,state:s.technical+'\n'+s.code})),pitfall:l.limit,interview:l.scenes.map(s=>s.technical).join(' '),recall:l.quiz.question,answer:l.quiz.why,resource:patternReferences.find(r=>r.story===l.id&&r.url)?.url,questions:[{question:l.quiz.question,answer:l.quiz.choices[l.quiz.answer]+'. '+l.quiz.why}]}));
