import type {CartoonLesson,CartoonScene} from './cartoon-lessons';
const s=(title:string,say:string,technical:string,code:string,items:string[],active:number[]):CartoonScene=>({title,say,technical,code,items,active});
const m=(id:string,title:string,world:CartoonLesson['world'],why:string,limit:string,scenes:CartoonScene[],question:string,choices:string[],answer:number,explanation:string):CartoonLesson=>({id,category:'DSA patterns',title,world,why,limit,scenes,quiz:{question,choices,answer,why:explanation}});
// Original examples for the topics in the learner's reference collection.
export const cartoonPatterns:CartoonLesson[]=[
 m('two-pointers','Two friends find a pair','array','Use opposing pointers when a sorted order tells you which side can be eliminated.','Sorting an unsorted input changes original positions. Preserve indices if the contract needs them.',[
 s('Meet at opposite ends','Two friends stand at opposite ends of a sorted row. They want a total of nine.','Start left=0 and right=3. Both pointers refer to distinct positions.','values=[1,2,4,7]; target=9',['1: left','2','4','7: right'],[0,3]),
 s('Too small: move left','One plus seven is eight. Move the left friend to a larger number.','With a fixed left value, moving right inward cannot increase the sum. Discard that left candidate.','1+7=8 < 9 → left++',['1: discarded','2: left','4','7: right'],[1,3]),
 s('Meet the target','Two plus seven is nine. We found the pair without checking every pair.','Sorted pair search is O(n) time and O(1) extra space. Sorting first adds cost.','while(l<r){const sum=a[l]+a[r]; if(sum===target)return [l,r]; if(sum<target)l++;else r--;}',['2 + 7','Indices: [1,3]','Stop'],[0,1])
 ],'If the sorted pair sum is too large, which move helps?',['Move right inward','Move left to a larger value','Stop immediately'],0,'Decrease the larger endpoint. Sorted order justifies eliminating candidates.'),
 m('substring-window','The no-repeat train carriage','array','Use a variable sliding window when validity can be maintained as its endpoints move.','Different substring contracts need different counts. This no-repeat rule is not a universal substring template.',[
 s('Let two passengers in','Passengers a and b enter. Our carriage allows only one passenger of each name.','The invariant is that every character in the current window is unique.','text="abba"; window="ab"; best=2',['a','b','b waiting','a waiting'],[0,1]),
 s('A duplicate arrives','Another b arrives. Move the left door until the old b is outside.','Deleting only a does not remove the duplicate b; continue shrinking while the new character is present.','while(seen.has(c)) seen.delete(text[left++]);',['a: out','old b: out','new b: in','a: waiting'],[2]),
 s('Grow again','Now a can enter. The biggest valid carriage we saw held two passengers.','Each character enters and leaves the Set at most once: expected O(n) time. This example uses ASCII.','seen.add(c); best=Math.max(best,right-left+1); // result: 2',['Final window: ba','Best length: 2'],[0,1])
 ],'Why is one left++ sometimes insufficient?',['The duplicate may still be inside','Windows must always have length two','Set sorts the text'],0,'Shrink until the invariant is restored, not just once.'),
 m('string-counts','The letter tile shop','array','Use a frequency map when a string question needs multiplicity, such as anagrams.','Set loses repeated counts. Normalize case and decide how to handle Unicode if the contract requires it.',[
 s('Count every tile','The word aab brings two a tiles and one b tile.','Store character → count, not just membership.','aab → Map{a:2,b:1}',['a: 2','b: 1'],[0,1]),
 s('Spend matching tiles','The word aba takes one a, one b, and the last a. Nothing is missing.','For equal-length strings, every requested tile must have a positive remaining count.','aba: a 2→1; b 1→0; a 1→0',['a: 0','b: 0'],[0,1]),
 s('Watch a near miss','The word abb wants a second b. Our shop has none, so it is not an anagram.','Counts distinguish aab from abb even though both have the same unique letters.','if((counts.get(c)??0)===0)return false; counts.set(c,counts.get(c)-1);',['Need b','b remaining: 0','Reject'],[0,1])
 ],'Can Set alone distinguish aab and abb?',['Yes','No','Only when sorted'],1,'Both contain the unique letters a and b. Their frequencies differ.'),
 m('graph-visited','The town with a loop','city','Use graph traversal plus visited state to explore reachable nodes without repeating cycles.','Directed edges differ from undirected edges. BFS gives fewest edges, not cheapest weighted travel.',[
 s('Choose a starting house','A leads to B. B leads back to A and onward to C.','Represent outgoing neighbors explicitly in an adjacency list.','A:[B], B:[A,C], C:[]',['A','B','C'],[0]),
 s('Leave a visited sticker','Visit A, then B. B sees A again, but A already has a sticker.','Mark nodes when you discover/enqueue them, preventing repeated work.','seen={A,B}; queue=[B] → skip A; discover C',['A: visited','B: processing','C: discovered'],[1,2]),
 s('Finish the reachable town','Visit C. No unexplored houses remain in our waiting line.','With adjacency lists, BFS costs O(V+E) time over the explored graph and O(V) space.','const queue=[start], seen=new Set([start]); for(let h=0;h<queue.length;h++){for(const n of graph[queue[h]])if(!seen.has(n)){seen.add(n);queue.push(n)}}',['Visited: A,B,C','Queue exhausted'],[0])
 ],'Why mark a node before placing it in the queue?',['To avoid multiple pending copies','To sort all houses','To remove every edge'],0,'Two neighbors could discover the same node before it is processed.'),
 m('dfs','The explorer and the return rope','stack','Use depth-first search to finish one branch before returning to another; useful for tree walks and connectivity.','Deep recursion can overflow the language call stack. An explicit stack is an alternative.',[
 s('Follow one branch','The explorer leaves A for B, then goes deeper to D.','Preorder DFS visits a node, then its children. Tree: A→B,C; B→D.','visit order begins A,B,D',['A','B','D'],[2]),
 s('Use the return rope','D has no child. Return to B, then A, where C is still waiting.','The call stack remembers unfinished recursive work.','D returns; B returns; continue A with child C',['A: C pending','B: finished','D: finished'],[0]),
 s('Finish the other branch','Visit C. Every room has now been explored in a depth-first order.','For this ordered tree the traversal is A,B,D,C; unlike BFS A,B,C,D.','function walk(n){if(!n)return;visit(n);for(const child of n.children)walk(child)}',['A','B','D','C'],[3])
 ],'Does DFS always find the fewest-edge path first?',['Yes','No','Only when recursive'],1,'DFS prioritizes depth. Use BFS for shortest paths in unweighted graphs.'),
 m('backtracking','Try a badge, then undo it','stage','Use backtracking to enumerate choices while maintaining a partial candidate; prune only when a branch cannot work.','Generating all subsets is exponential. Save a copy of the current path, not the same mutable array.',[
 s('Choose or skip a sticker','We have A and B stickers. Every badge can choose or skip each one.','Each position offers two branches: exclude or include.','items=[A,B]; begin with path=[]',['Skip A','Choose A'],[0,1]),
 s('Undo before another choice','After trying B, remove it before exploring the next badge.','push → recurse → pop restores the parent state.','path.push(items[i]); visit(i+1); path.pop();',['Parent path','Choose','Explore','Undo'],[1,2,3]),
 s('Keep four distinct badges','Our badges are empty, B, A, and AB. Each is a separate saved copy.','Copying all subset outputs costs O(n·2^n); the active path uses O(n) space.','function subsets(a){const out=[],path=[];function visit(i){if(i===a.length){out.push([...path]);return}visit(i+1);path.push(a[i]);visit(i+1);path.pop()}visit(0);return out}',['[]','[B]','[A]','[A,B]'],[0,1,2,3])
 ],'Why do we pop after exploring a choice?',['Restore the parent path','Delete every valid answer','Sort the items'],0,'Sibling branches must start from the same parent state.'),
 m('monotonic-stack','Waiting for a warmer day','stack','Use a monotonic stack for nearest greater/smaller candidates that can be resolved by a new value.','Strict versus non-strict comparisons matter. Equal temperatures do not satisfy strictly warmer.',[
 s('Two days are waiting','Seventy-three degrees waits for warmth. Seventy-one joins the waiting pile.','Keep unresolved indices with non-increasing temperatures from bottom to top.','temps=[73,71,74]; stack=[0,1]',['Day 0: 73','Day 1: 71'],[0,1]),
 s('A warm day helps both','Seventy-four arrives. It is warmer than both waiting days, so resolve each one.','Pop while current temperature is greater. Index differences give waiting days.','day1: 2-1=1; day0: 2-0=2',['Day 1 waits: 1','Day 0 waits: 2'],[0,1]),
 s('One day remains unanswered','Seventy-four has no later warmer day here. Its wait stays zero.','Each index is pushed and popped at most once: O(n) time, O(n) space.','function waits(t){const out=Array(t.length).fill(0),st=[];for(let i=0;i<t.length;i++){while(st.length&&t[i]>t[st[st.length-1]]){const j=st.pop();out[j]=i-j}st.push(i)}return out}',['Result [2,1,0]','Unresolved: day 2'],[0])
 ],'Should another 73 resolve a waiting 73 for strictly warmer?',['Yes','No','Only on Mondays'],1,'Equal is not greater. Choose the comparator to match the question.'),
 m('bitwise','The switchboard puzzle','array','Use bit operations for compact flags or algebraic properties such as pair cancellation under precise input guarantees.','JavaScript Number bitwise operations use 32-bit integers. XOR is not a general duplicate-removal algorithm.',[
 s('Look at tiny switches','Each bit is a tiny switch: zero is off and one is on.','AND keeps bits on in both operands; OR keeps bits on in either.','0101 & 0011 = 0001; 0101 | 0011 = 0111',['AND: both','OR: either','XOR: different'],[0,1,2]),
 s('Matching pairs cancel','XOR switches on differences. Two equal numbers cancel to zero.','For numbers paired exactly twice except one, XOR of all values isolates the single value.','5 ^ 2 ^ 5 = 2',['5','2','5'],[0,2]),
 s('Read one feature flag','A bit mask can ask whether a feature’s switch is on.','Check (flags & mask) !== 0. NOR means NOT OR; mask the width if only four bits matter.','(0b0101 & 0b0100)!==0 // true\n(~(0b0101|0b0011)) & 0b1111 // 8',['flags: 0101','mask: 0100','enabled: true'],[0,1])
 ],'Will XOR isolate one value if arbitrary counts are allowed?',['Always','No','Only for sorted input'],1,'The pair-cancellation shortcut depends on the specified multiplicities.'),
 m('dp-ways','Remember the ways up the stairs','array','Use dynamic programming when repeated subproblems share a complete state and a valid recurrence.','Define state, base cases, transition and order before coding. This example only permits steps of one or two.',[
 s('Name a smaller question','How many ways reach step three? First remember how many reach each smaller step.','ways[i] counts ordered sequences of 1/2 steps reaching i.','ways[0]=1; ways[1]=1',['Step 0: 1','Step 1: 1'],[0,1]),
 s('Add the last-step choices','To reach step three, come from step two or step one. These choices do not overlap.','ways[i]=ways[i-1]+ways[i-2]; sum because we count distinct paths.','ways[2]=2; ways[3]=2+1=3',['0: 1','1: 1','2: 2','3: 3'],[1,2,3]),
 s('Reuse your notes','The three routes are 111, 12, and 21. No need to solve the same smaller question again.','A table takes O(n) time and O(n) space; two rolling values reduce auxiliary space to O(1).','function ways(n){let prev=1,cur=1;for(let i=2;i<=n;i++){[prev,cur]=[cur,prev+cur]}return cur}',['111','12','21'],[0,1,2])
 ],'Why add the two previous counts?',['They count disjoint last-step choices','The array is sorted','Addition is always DP'],0,'Every route ends with either a one-step move or a two-step move.'),
 m('dp-choices','Pick prizes without neighbors','array','Use decision DP when taking or skipping an item changes which future or earlier choices are valid.','A greedy choice of the largest single reward can fail. State must capture the restriction that affects later decisions.',[
 s('Read the rule','Prize boxes hold two, seven, nine, and three coins. You cannot take neighboring boxes.','best[i] is the maximum total from the first i boxes, allowing the empty selection.','values=[2,7,9,3]; best[0]=0',['2','7','9','3'],[]),
 s('Take or skip nine','Taking nine can join two for eleven. Skipping nine leaves the earlier best of seven.','best[i]=max(best[i-1], best[i-2]+value[i-1]).','best[1]=2; best[2]=7; best[3]=max(7,2+9)=11',['Take 2','Skip 7','Take 9','3 pending'],[0,2]),
 s('Keep the best plan','Adding three to seven gives ten. Keeping eleven is better, so skip the last box.','A rolling implementation uses O(n) time and O(1) space; reconstructing the chosen indices needs extra bookkeeping.','function reward(a){let two=0,one=0;for(const x of a){[two,one]=[one,Math.max(one,two+x)]}return one}',['Skip 3','Best total: 11','Chosen values: 2,9'],[1,2])
 ],'Is taking the largest value and deleting its neighbors always safe?',['Yes','No','Only for long arrays'],1,'Try [4,5,4]: taking 5 loses the better total 4+4=8.')
];
