export type ReadingStep={title:string;detail:string;state:string;line?:number};
export type ReadingLesson={id:string;title:string;category:string;topic:string;format:'Visual guide'|'Scenario note'|'Question & answer'|'Design answer';minutes:number;explanation:string;example:string;code?:string;output?:string;steps:ReadingStep[];pitfall:string;interview:string;recall:string;answer:string;resource?:string;practiceId?:string;hinglish?:string;useWhen?:string;methods?:{name:string;use:string;example:string}[];questions?:{question:string;answer:string}[]};
type Guide=Omit<ReadingLesson,'format'|'minutes'|'topic'>;
const guides:Guide[]=[
{id:'guide-closures',title:'Closures: a function remembers its environment',category:'JavaScript',explanation:'A closure lets a function access bindings from where it was created, even after the outer call has returned. It keeps access to the binding, not a frozen copy of its value. Use closures for private state, factories and callbacks.',example:'Create two counters. Increment the first twice: its result is 2, while the second remains 0. Each factory call creates a separate environment.',code:`function createCounter() {
  let count = 0;
  return { increment: () => ++count, read: () => count };
}
const a = createCounter();
const b = createCounter();
a.increment();
a.increment();
console.log(a.read(), b.read());`,output:'2 0',steps:[{title:'Create A',detail:'The returned functions refer to A’s lexical environment.',state:'A → { count: 0 }',line:5},{title:'Create B',detail:'A second call creates a different binding.',state:'A → { count: 0 }\nB → { count: 0 }',line:6},{title:'Increment A',detail:'Only A’s binding changes.',state:'A.count = 1; B.count = 0',line:7},{title:'Read both',detail:'The bindings remain independent.',state:'A.count = 2; B.count = 0\nOutput: 2 0',line:9}],pitfall:'A long-lived callback can keep referenced objects reachable. Remove subscriptions when they are no longer needed.',interview:'A closure is a function with access to its lexical environment. I can use a factory to give each counter private, independent state.',recall:'If two functions come from the same factory call, do they share its count?',answer:'Yes. The increment and read functions from one call share that call’s binding; functions from another call have a different binding.',resource:'https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Closures'},
{id:'guide-event-loop',title:'Event loop: predict the output before running',category:'JavaScript',explanation:'In this browser example, the current script finishes before queued callbacks run. Promise reactions run as microtasks at a checkpoint; the timer callback runs in a later task. A zero-delay timer does not mean immediate execution.',example:'Predict A, D, C, B. Registering a callback is different from executing it.',code:`console.log('A');
setTimeout(() => console.log('B'), 0);
Promise.resolve().then(() => console.log('C'));
console.log('D');`,output:'A\nD\nC\nB',steps:[{title:'Run script',detail:'The first synchronous log executes.',state:'Stack: script\nOutput: A',line:1},{title:'Schedule timer',detail:'The host tracks the timer; its callback cannot interrupt this script.',state:'Timer: B waiting\nOutput: A',line:2},{title:'Queue reaction',detail:'The fulfilled Promise schedules its reaction as a microtask.',state:'Microtasks: [C]\nTimer: B',line:3},{title:'Finish script',detail:'D logs before the stack becomes empty.',state:'Output: A D',line:4},{title:'Drain microtasks',detail:'C runs before taking the later timer task.',state:'Output: A D C',line:3},{title:'Run timer task',detail:'B now logs. Rendering opportunities are host-controlled.',state:'Output: A D C B',line:2}],pitfall:'CPU loops still block the main thread. An endlessly growing microtask queue can also starve other work. Do not apply this simple ordering to every Node.js scheduling case.',interview:'The event loop coordinates tasks and microtasks after synchronous work. Promises are not background threads.',recall:'Does wrapping a huge synchronous loop in an async function make it nonblocking?',answer:'No. The synchronous loop still occupies the executing thread until it yields or finishes.',resource:'https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Execution_model'},
{id:'guide-usememo',title:'React useMemo: what is cached and when?',category:'React',explanation:'useMemo can reuse a calculation result between renders when every dependency compares equal with Object.is. The calculation still happens on the initial render. It is a performance optimization, not persistent storage or a correctness guarantee.',example:'Changing a theme can reuse the filtered list when items and query keep their identities/values. Changing query recomputes it.',code:`const visible = useMemo(() => {
  return items.filter(item => item.name.includes(query));
}, [items, query]);`,output:'Same items + same query → reuse result\nChanged query → recalculate',steps:[{title:'Initial render',detail:'No previous memo exists; calculate the result.',state:'query = "a"\nvisible = matching items',line:2},{title:'Unrelated update',detail:'Compare dependencies with Object.is.',state:'items: same identity\nquery: "a" → "a"',line:3},{title:'Reuse',detail:'The existing result can be returned without filtering.',state:'visible: cached reference',line:1},{title:'Dependency changes',detail:'A new query requires a new calculation.',state:'query: "a" → "ab"\nvisible: recalculated',line:2}],pitfall:'Creating a dependency object on every render defeats reuse. Mutating an array in place can produce stale results. Include all reactive dependencies; never use memoization to hide an impure calculation.',interview:'I measure the expensive work first, then memoize a pure calculation with complete dependencies. The application must stay correct if React recalculates it.',recall:'Will useMemo prevent its component from rendering?',answer:'No. It reuses a calculation result within rendering; it does not itself prevent the component render.',resource:'https://react.dev/reference/react/useMemo'},
{id:'guide-react-render',title:'React render, commit, and state snapshots',category:'React',explanation:'A state update requests another render. Rendering calculates the next UI; committing applies the needed DOM changes. Event handlers observe the state snapshot from the render that created them.',example:'Calling setCount(count + 1) twice in one handler uses the same captured count. Functional updates express two successive increments.',code:`function incrementTwice() {
  setCount(current => current + 1);
  setCount(current => current + 1);
}`,output:'Starting at 0 → queued transformations → 2',steps:[{title:'Event',detail:'The handler requests updates.',state:'Current snapshot: 0',line:1},{title:'Queue',detail:'Apply the first updater and then the second.',state:'0 → 1 → 2',line:3},{title:'Render',detail:'Calculate UI using the next state.',state:'Next snapshot: 2'},{title:'Commit',detail:'Update changed DOM properties.',state:'Displayed count: 2'}],pitfall:'Do not mutate state directly or perform network writes during render.',interview:'I separate calculating UI from committing it. Functional updaters are useful when new state depends on previous state.',recall:'Does every render necessarily change the DOM?',answer:'No. React can render and find that no DOM change is needed.',resource:'https://react.dev/learn/render-and-commit'},
{id:'guide-react-effects',title:'Effects, cleanup, and stale requests',category:'React',explanation:'An effect synchronizes a component with an external system. Cleanup stops or invalidates the previous synchronization before the next setup or unmount. Values captured by a callback belong to the render that created it.',example:'Searching for A and then B can produce replies in reverse order. Ignore A after its effect has been cleaned up.',code:`useEffect(() => {
  let ignore = false;
  load(query).then(result => {
    if (!ignore) setResult(result);
  }).catch(error => { if (!ignore) setError(error); });
  return () => { ignore = true; };
}, [query]);`,output:'Only the currently active effect may update this result.',steps:[{title:'Search A',detail:'First effect starts loading.',state:'A.ignore = false',line:2},{title:'Search B',detail:'Cleanup invalidates A.',state:'A.ignore = true\nB.ignore = false',line:6},{title:'A resolves late',detail:'The guard rejects the stale update.',state:'A result ignored',line:4},{title:'B resolves',detail:'The current request updates the view.',state:'UI shows B',line:4}],pitfall:'Ignoring a result does not cancel its network request. Use AbortController when cancellation is supported. Derived values often belong in render rather than an effect.',interview:'I identify the external system, declare dependencies, and make cleanup symmetrical with setup.',recall:'Why is an empty dependency array wrong when the effect uses a changing query?',answer:'The synchronization would retain the initial query instead of following query changes.',resource:'https://react.dev/reference/react/useEffect'},
{id:'guide-sql-where',title:'WHERE: keep only rows that satisfy a condition',category:'SQL',explanation:'WHERE filters input rows before grouping. Only TRUE passes; FALSE and UNKNOWN do not. Use IS NULL for missing values. Bind user input as parameters instead of concatenating SQL.',example:'Asha earns 70,000; Ravi earns 45,000; Mina has an unknown salary. A threshold of 50,000 keeps only Asha.',code:`WITH employees(name, salary) AS (
  VALUES ('Asha', 70000), ('Ravi', 45000), ('Mina', NULL)
)
SELECT name FROM employees WHERE salary >= 50000;`,output:'name\nAsha',steps:[{title:'Input rows',detail:'Evaluate the condition separately for each row.',state:'Asha: 70000\nRavi: 45000\nMina: NULL',line:2},{title:'Predicate',detail:'Compare each salary with 50000.',state:'Asha: TRUE\nRavi: FALSE\nMina: UNKNOWN',line:4},{title:'Filter',detail:'Only TRUE survives.',state:'Asha: 70000',line:4},{title:'Project',detail:'Return the selected name column.',state:'Asha',line:4}],pitfall:'salary = NULL does not check for missing salary. Use salary IS NULL. Parenthesize mixed AND/OR conditions.',interview:'WHERE filters rows with a predicate. HAVING filters grouped results; the distinction affects aggregates and query meaning.',recall:'How do you include employees whose salary is unknown?',answer:'Use WHERE salary >= 50000 OR salary IS NULL.',resource:'https://www.postgresql.org/docs/current/tutorial-select.html'},
{id:'guide-sql-having',title:'WHERE versus HAVING: rows before groups',category:'SQL',explanation:'WHERE filters individual rows. GROUP BY forms groups and computes aggregates. HAVING keeps or removes groups based on conditions such as their total.',example:'Paid orders of 40 and 70 for user 1 total 110. A pending order is excluded before summing.',code:`WITH orders(user_id, amount, status) AS (
  VALUES (1,40,'paid'),(1,70,'paid'),(2,200,'pending')
)
SELECT user_id, SUM(amount) AS total FROM orders
WHERE status = 'paid'
GROUP BY user_id HAVING SUM(amount) >= 100;`,output:'user_id | total\n1       | 110',steps:[{title:'Filter',detail:'Keep paid rows.',state:'(1,40), (1,70)',line:5},{title:'Group',detail:'Collect rows with the same user_id.',state:'user 1 → [40,70]',line:6},{title:'Aggregate',detail:'Compute the group total.',state:'user 1 → 110',line:4},{title:'HAVING',detail:'Keep groups whose total reaches 100.',state:'1 | 110',line:6}],pitfall:'Filtering individual orders by amount >= 100 would wrongly discard both smaller orders.',interview:'I decide whether a condition concerns one row or an aggregate group before choosing WHERE or HAVING.',recall:'Can SUM(amount) normally be used in this query’s WHERE?',answer:'No. This group aggregate is not available at the row-filtering stage; use HAVING.',resource:'https://www.postgresql.org/docs/current/tutorial-agg.html'},
{id:'guide-acid',title:'ACID transactions: four guarantees',category:'SQL',explanation:'The common acronym is ACID, not ACIDT: Atomicity, Consistency, Isolation and Durability. Atomicity groups changes together. Consistency means preserving declared invariants. Isolation governs concurrent observations. Durability concerns committed data surviving failures within the database’s guarantees.',example:'Transfer 20 from account A (100) to B (50). Either both balance changes commit, or neither does. Concurrency still needs an appropriate isolation/locking strategy.',code:`BEGIN;
UPDATE accounts SET balance = balance - 20 WHERE id = 'A';
UPDATE accounts SET balance = balance + 20 WHERE id = 'B';
COMMIT;`,output:'Successful transfer: A=80, B=70; combined balance remains 150.',steps:[{title:'Begin',detail:'Start a transaction.',state:'A=100, B=50',line:1},{title:'Debit',detail:'A change is part of an uncommitted transaction.',state:'Transaction view: A=80, B=50',line:2},{title:'Credit',detail:'Restore the transfer invariant within the transaction.',state:'Transaction view: A=80, B=70',line:3},{title:'Commit or rollback',detail:'Commit the pair; on failure roll the transaction back.',state:'Committed: 80,70\nRolled back: 100,50',line:4}],pitfall:'A transaction does not invent business rules. Validate account existence, sufficient funds and concurrency behavior. Isolation is not identical at every isolation level.',interview:'I explain each guarantee using one transfer and state which anomalies my chosen isolation level permits.',recall:'Does database consistency mean replicas instantly have identical data?',answer:'Not in the ACID acronym. ACID consistency refers to preserving invariants; replica consistency is a separate distributed-systems concern.',resource:'https://www.postgresql.org/docs/current/tutorial-transactions.html'},
{id:'guide-two-sum',title:'Two Sum: how to recognize the hash-map approach',category:'DSA',explanation:'The brute-force method checks every pair. Notice the repeated question: have I seen target minus the current number? A hash map turns that repeated scan into an expected constant-time lookup. Lookup before insertion prevents reusing the current index.',example:'nums=[2,7,11], target=9. At 2, remember index 0. At 7, the needed value is 2, already at index 0.',code:`function twoSum(nums, target) {
  const seen = new Map();
  for (let i = 0; i < nums.length; i++) {
    const need = target - nums[i];
    if (seen.has(need)) return [seen.get(need), i];
    seen.set(nums[i], i);
  }
  return [];
}`,output:'twoSum([2,7,11],9) → [0,1]\ntwoSum([3,3],6) → [0,1]',steps:[{title:'Start',detail:'No earlier indices exist.',state:'seen = {}',line:2},{title:'Visit 2',detail:'Need 7, which is not in the map.',state:'i=0, need=7\nseen={}',line:4},{title:'Remember 2',detail:'The map stores values from earlier indices.',state:'seen={2:0}',line:6},{title:'Visit 7',detail:'Need 2; it exists at index 0.',state:'i=1, need=2\nreturn [0,1]',line:5}],pitfall:'Do not return values when indices are requested. Do not reuse one index. Expected O(n) time and O(n) space assume normal hash-map operation costs.',interview:'My invariant is that the map contains only earlier values. Each lookup finds a valid distinct-index complement. I trade O(n) memory for avoiding O(n²) pair checks.',recall:'What hint distinguishes this from a sliding-window problem?',answer:'The pair need not be contiguous, and I need membership of a complement. Sliding windows address contiguous ranges under an appropriate monotonic condition.',practiceId:'dsa-arrays-01'},
{id:'guide-dsa-patterns',title:'Choose a DSA pattern from the constraints',category:'DSA',explanation:'Start with the required output and a correct baseline. Look for repeated work and structure: sorted search suggests binary search, contiguous ranges suggest windows or prefix sums, connectivity suggests graph traversal, overlapping states suggest dynamic programming. These are clues, not proofs.',example:'For a sorted list of 1 million numbers, checking the middle and discarding half needs about 20 comparisons. The same elimination is invalid on arbitrary unsorted input.',code:`lo = 0; hi = length - 1
while lo <= hi:
  mid = lo + floor((hi - lo) / 2)
  compare target with values[mid]
  keep only the half that can contain target`,output:'Each valid elimination halves the remaining search interval.',steps:[{title:'Contract',detail:'State input, output, constraints and duplicate policy.',state:'Sorted ascending array; find a target index'},{title:'Baseline',detail:'Linear search is correct but repeats comparisons.',state:'O(n) scan'},{title:'Exploit structure',detail:'Sorted order rules out half the interval.',state:'n → n/2 → n/4'},{title:'Prove and check',detail:'Keep the target in the retained interval if present.',state:'O(log n), empty interval means absent'}],pitfall:'Do not memorize a pattern name and skip its invariant. Negative numbers can break common sum-window rules.',interview:'I propose a baseline, identify a usable property, explain why no valid answer is discarded, then analyze time and space.',recall:'Is dynamic programming appropriate merely because a problem asks for a maximum?',answer:'No. You need a meaningful state, a recurrence and repeated subproblems or another reason to store intermediate answers.'},
{id:'guide-design-types',title:'System design types: HLD, LLD, and architecture styles',category:'System design',explanation:'There is no universal fixed number of system-design types. HLD describes services, data ownership and infrastructure. LLD describes contracts, components and their internal responsibilities. Monolith, microservices, event-driven and layered are architectural styles, not levels of detail.',example:'For a parking system, HLD covers gate devices, payment service and storage. LLD covers Ticket, PricingPolicy and interfaces between payment and entry decisions.',steps:[{title:'Clarify the level',detail:'Ask whether the interviewer expects service architecture or component internals.',state:'HLD ↔ LLD'},{title:'Choose boundaries',detail:'Put each business responsibility somewhere explicit.',state:'Gate → Ticket service → Payment → Store'},{title:'Choose a style',detail:'A small modular monolith may satisfy the requirements.',state:'Deployment style ≠ quality score'},{title:'Zoom in',detail:'Define an interface and its data contract.',state:'price(ticket, exitTime) → amount'}],pitfall:'OOP is one implementation approach. Functional and procedural modules can implement the same service architecture.',interview:'I clarify the design level first, then choose the simplest style that meets scale, team and reliability constraints.',recall:'Are HLD and microservices alternative answers to the same question?',answer:'No. One is a level of detail; the other is an architectural style. A high-level design can describe a monolith or microservices.',resource:'https://docs.aws.amazon.com/wellarchitected/latest/framework/welcome.html'},
{id:'guide-design-approach',title:'Approach a system-design interview in seven steps',category:'System design',explanation:'Begin with requirements and constraints, not a list of services. Establish a baseline architecture and examine the most demanding path. Estimates should drive decisions; state assumptions and units.',example:'For a URL shortener, 10 million reads/day averages about 116 requests/second. A hypothetical 10× peak is about 1,160/second. These are assumptions for this exercise, not observed traffic.',steps:[{title:'Requirements',detail:'Ask about expiry, custom aliases, privacy and latency.',state:'Create link; redirect; optionally expire'},{title:'Estimate',detail:'Separate averages, peaks and storage growth.',state:'10,000,000 / 86,400 ≈ 116 reads/s'},{title:'API and data',detail:'Define request/response and unique key ownership.',state:'POST /links → code\nGET /:code → redirect'},{title:'Baseline',detail:'Start with a service and durable store.',state:'Client → Service → Database'},{title:'Bottleneck',detail:'Read-heavy hot keys may benefit from cache.',state:'Read → Cache → DB on miss'},{title:'Failure and safety',detail:'Consider expiry, malicious links, rate limits and monitoring.',state:'Timeout / miss / abuse / stale cache'},{title:'Implementation',detail:'Build a small vertical slice, then measure it.',state:'Contract → schema → endpoint → evidence'}],pitfall:'Do not claim that adding queues or microservices automatically increases reliability.',interview:'I will confirm scope, estimate load, design contracts and storage, trace a request, then discuss failure modes and tradeoffs.',recall:'What is the purpose of a capacity estimate?',answer:'To justify a decision such as caching or partitioning, not to produce precise-looking numbers from unstated assumptions.'},
{id:'guide-cache-aside',title:'Cache-aside: trace a hit, miss, and stale value',category:'System design',explanation:'In cache-aside, application code reads the cache first. On a miss it loads the source of truth, stores a temporary copy, and returns it. A cached copy can be stale; define acceptable staleness and invalidation behavior.',example:'A product costs 100. A cache serves 100 after the database changes to 120 unless invalidated or expired. Decide whether this is acceptable for browsing versus checkout.',code:`value = cache.get(key)
if value is missing:
  value = database.read(key)
  cache.set(key, value, ttl)
return value`,output:'Hit → fast cached read\nMiss → database read then cache fill',steps:[{title:'Lookup',detail:'Use a key that includes relevant identity/tenant context.',state:'cache[product:42] = missing',line:1},{title:'Load',detail:'Read the authoritative record.',state:'database price = 100',line:3},{title:'Fill',detail:'Store a copy with an expiry policy.',state:'cache[product:42] = 100',line:4},{title:'Next read',detail:'Return cached data until policy refreshes it.',state:'cache hit → 100',line:5}],pitfall:'TTL does not prevent stale reads before expiry. Concurrent misses can overwhelm the database without coordination.',interview:'I define the source of truth, key, expiry, invalidation and miss behavior. Checkout may revalidate the authoritative price.',recall:'Can a cache be permanently correct just because it has a TTL?',answer:'No. TTL only bounds a particular cached entry’s lifetime; freshness also depends on writes and refresh races.'},
{id:'guide-waterfall',title:'Waterfall versus iterative delivery',category:'Engineering',explanation:'A Waterfall-style process organizes work into sequential phases such as requirements, design, implementation, verification and maintenance. Iterative delivery revisits learning in smaller increments. Real projects may combine practices; neither label removes the need for feedback.',example:'For a stable reporting contract, document fields and acceptance criteria before implementation. For an uncertain search experience, prototype one flow and gather feedback early.',steps:[{title:'Requirements',detail:'Agree what success means.',state:'Report fields + acceptance criteria'},{title:'Design',detail:'Choose schema, interfaces and UI structure.',state:'Reviewed design'},{title:'Implement',detail:'Build against the agreed contract.',state:'Working software'},{title:'Verify',detail:'Check requirements and report discrepancies.',state:'Acceptance evidence'},{title:'Maintain',detail:'Fix defects and manage changes.',state:'Changes feed back into planning'}],pitfall:'Discovering a misunderstood requirement late can make sequential handoffs expensive. Agile does not mean no documentation or no planning.',interview:'I compare requirement stability, feedback timing and cost of change. I describe the actual team practices rather than only naming a methodology.',recall:'Does Waterfall mean a project can never revisit an earlier decision?',answer:'No. Rework can happen; the concern is how late feedback and formal phase dependencies affect its cost.',resource:'https://www.ibm.com/think/topics/agile-vs-waterfall'},
{id:'guide-oop-composition',title:'OOP and composition: depend on a capability',category:'OOP & .NET',explanation:'Encapsulation protects state and invariants. Abstraction exposes a useful contract. Polymorphism allows different implementations behind that contract. Composition combines collaborators instead of forcing an inheritance hierarchy.',example:'An order service needs a way to charge. Inject a payment interface so a fake implementation can exercise failure behavior without charging a real card.',code:`public interface IPaymentGateway {
    Task<bool> ChargeAsync(decimal amount);
}
public class Checkout(IPaymentGateway gateway) {
    public Task<bool> PayAsync(decimal amount) {
        if (amount <= 0) throw new ArgumentOutOfRangeException();
        return gateway.ChargeAsync(amount);
    }
}`,output:'Checkout → IPaymentGateway → real gateway or fake',steps:[{title:'Contract',detail:'Define the capability checkout needs.',state:'ChargeAsync(amount) → outcome',line:2},{title:'Compose',detail:'Supply the collaborator from the outside.',state:'Checkout has a gateway',line:4},{title:'Protect invariant',detail:'Reject invalid input before the side effect.',state:'amount must be positive',line:6},{title:'Dispatch',detail:'Call the chosen implementation.',state:'Fake for local exercise; real in deployment',line:7}],pitfall:'This simplified bool omits decline reasons, idempotency and uncertainty after timeouts; a production payment contract needs them.',interview:'I use interfaces where implementations vary, while keeping business rules in the service that owns them.',recall:'Does every class need an interface?',answer:'No. Introduce abstractions around useful contracts and variation, not mechanically around every class.',resource:'https://learn.microsoft.com/en-us/dotnet/csharp/fundamentals/object-oriented/'},
{id:'guide-python-generator',title:'Python generators: produce values on demand',category:'Python',explanation:'A generator yields one value and suspends its local state until the next request. It can avoid materializing a whole sequence, but does not make a slow computation parallel or automatically faster.',example:'Consume three squares without first building a list of every square.',code:`def squares(limit):
    for n in range(limit):
        yield n * n
values = squares(3)
print(next(values))
print(next(values))
print(list(values))`,output:'0\n1\n[4]',steps:[{title:'Create',detail:'The function body has not been consumed.',state:'Generator ready',line:4},{title:'First next',detail:'Run until the first yield.',state:'n=0 → yield 0',line:5},{title:'Second next',detail:'Resume the loop.',state:'n=1 → yield 1',line:6},{title:'Consume rest',detail:'Only the remaining value is collected.',state:'[4], then exhausted',line:7}],pitfall:'A generator is generally single-pass. Converting it to a list materializes the remaining values.',interview:'I use generators for incremental processing and discuss resource cleanup if the generator owns a file or connection.',recall:'What would list(values) return if called again after the example?',answer:'An empty list because this generator is exhausted.',resource:'https://docs.python.org/3/tutorial/classes.html#generators'},
{id:'guide-cicd',title:'CI/CD: follow one change into production',category:'AWS & DevOps',explanation:'Continuous integration checks changes frequently. Continuous delivery keeps a releasable artifact ready, often with a release approval. Continuous deployment automatically releases changes that satisfy the pipeline’s gates.',example:'A commit triggers dependency installation, checks, artifact creation, staging deployment and a health check. Promote the same artifact to avoid environment-specific rebuild drift.',steps:[{title:'Source',detail:'Identify the exact revision.',state:'commit abc123'},{title:'Check',detail:'Install locked dependencies and run relevant validation.',state:'Failures stop promotion'},{title:'Package',detail:'Produce an immutable artifact.',state:'image digest sha256:…'},{title:'Deploy',detail:'Provide environment configuration separately.',state:'Same artifact + environment config'},{title:'Observe',detail:'Check health and business signals; keep a rollback route.',state:'Healthy → proceed\nRegression → rollback'}],pitfall:'An HTTP process being up does not prove dependencies or user flows are healthy. Database migrations may require compatibility across two application versions.',interview:'I separate build, release and operations, explain secrets handling, and describe how we detect and recover from a bad release.',recall:'What differs between continuous delivery and deployment?',answer:'Delivery maintains release readiness; deployment also automates the actual production release when gates pass.',resource:'https://docs.github.com/en/actions'},
];

// Original speaking exercises: practical scripts, not diagnoses or promised outcomes.
const speaking:[string,string,string,string,string,string][]=[
['introduce-yourself','Introduce yourself in 30 seconds','Structure your introduction as present role, evidence and next goal. Choose one specific project rather than listing every technology.','I am a full-stack developer with 2.6 years of experience. I build React interfaces and backend APIs. Recently, I improved a slow reporting flow. I am now looking for a role where I can own features end to end.','Replace the reporting claim with something you actually did.','Say your introduction once in 30 seconds, then remove one unnecessary sentence.'],
['ask-time-to-think','Ask for thinking time without apologizing','A short pause lets you organize an answer. State that you are thinking, choose a structure, then begin with a concrete point.','Let me take a moment to organize my thoughts. I will start with a simple approach and then improve it.','You do not need to fill every pause with sorry or actually.','Pause for three seconds before answering a familiar question.'],
['sentence-structure','Build clear English sentences','Use a subject, a precise verb and a concrete object. Add a reason or result in a second sentence if the first becomes too long.','Before: In that this API having issue.\nAfter: This API returns an error when the token expires. I will check the refresh flow.','Prefer a clear short sentence over a long sentence with uncertain grammar.','Describe one bug using: The system does X when Y. I will check Z.'],
['clarify-question','Clarify an interview question','Restate the goal and ask about the assumption that changes your solution. One focused question is easier to answer than a list of ten.','When you say duplicates, should I return every repeated value or only whether a duplicate exists?','Do not silently solve a different interpretation.','Ask one clarification for: design a notification system.'],
['dont-know','Say you do not know and still reason','Separate what you know from what you would verify. Acknowledge the missing detail without inventing an answer.','I have not used that feature in production. My understanding is that it handles retries. I would verify its delivery guarantees before choosing it.','Do not imply professional experience from a tutorial.','Answer a question about an unfamiliar tool using known / uncertain / next check.'],
['star-story','Tell a specific STAR story','Use situation, task, action and result. Spend most of the answer on what you personally did and what evidence showed the result.','Our report page was slow. I owned the API investigation. I traced repeated queries and batched the reads. We measured the latency again after release.','Do not invent percentages. If you lack a metric, describe an observed outcome honestly.','Prepare a 60-second story about one bug you resolved.'],
['disagree','Disagree with a teammate constructively','Acknowledge the goal, explain your concern and propose a way to compare options. Discuss the idea rather than the person.','I agree that faster delivery matters. My concern is losing retries after a restart. Could we compare a durable queue with the in-memory approach?','Avoid always, never and accusations about intentions.','Rewrite: Your design is wrong, as a concern plus a question.'],
['status-update','Give a useful daily update','State completed work, the next action and a blocker with a specific request. A status update should help someone decide whether to assist.','Yesterday I finished validation. Today I am connecting the save API. I am blocked on the response format; could we confirm the error fields?','Do not bury the blocker in a long chronological story.','Give a 20-second update about your current practice task.'],
['stranger-small-talk','Start a low-pressure conversation','Choose a suitable public moment, ask a simple question, and give the other person an easy way to decline. Listen to the actual response.','Excuse me, is this the queue for the bus to the station? Thank you—that helps.','Do not interrupt someone wearing headphones or continue if they seem uninterested. Practise only when stationary or a passenger.','Try one brief practical question in an appropriate setting, then note the reply without personal details.'],
['follow-up','Keep a conversation going with a follow-up','Pick one detail from the other person’s answer and ask a related question. Share a brief relevant detail yourself rather than conducting an interrogation.','They say: I am learning Python.\nYou say: What are you building with it? I have been using it for small API exercises.','Avoid a rapid sequence of unrelated questions.','Practise one follow-up with a teammate or willing friend.'],
['nervous-speaking','Make a nervous speaking task smaller','Choose a manageable speaking action: one sentence to yourself, then a short recording, then a question with a willing person. The target is completing the action, not eliminating every nervous feeling.','I only need to ask one clear question today. I can speak slowly, pause, and end politely.','Do not treat one uncomfortable conversation as proof that you cannot communicate. Progress varies.','Record a 20-second explanation. Notice one clear sentence and improve just one thing.'],
['repair-sentence','Recover when you lose your words','Restart with a shorter sentence. Name the main idea first and then add detail. Correcting yourself is a normal part of conversation.','Let me say that more clearly. The cache stores a temporary copy. If the original changes, we need a refresh policy.','Avoid starting over repeatedly to achieve a perfect accent or sentence.','Explain a closure, deliberately pause, and restart once clearly.'],
['explain-tradeoff','Explain a technical tradeoff aloud','State the option, benefit, cost and condition for choosing it. Compare against a concrete alternative.','I would cache frequent reads to reduce database load. The cost is possible staleness, so checkout will still verify the current price.','A tool name without the cost does not explain a decision.','Compare SQL and a document database for one specific data model.'],
['interview-close','Close an interview with useful questions','Ask about actual responsibilities, team practices and success expectations. Pick questions whose answers help you judge the role.','What would successful ownership look like in the first three months? How does the team review production incidents?','Avoid asking questions only to sound impressive; listen and follow up.','Choose two questions you honestly want answered about your next role.'],
['listen-back','Reflect on a conversation without judging yourself','Record what you tried, what the person actually said and one next improvement. Separate observation from guesses about their opinion of you.','I asked for clarification. They gave an example. Next time I will summarize the example before proposing a solution.','Do not store a stranger’s private details. Keep the reflection about your own practice.','Write: I tried __. I observed __. Next time I will __.'],
];
export const commuteGuides:ReadingLesson[]=[...guides.map(g=>({...g,format:'Visual guide' as const,minutes:5,topic:g.category})),...speaking.map(([id,title,explanation,example,pitfall,recall])=>({id:`guide-speak-${id}`,title,category:'English & confidence',topic:'Communication practice',format:'Visual guide' as const,minutes:3,explanation,example,pitfall,recall,answer:'There is no single correct script. Check that your message is clear, truthful, brief and suitable for the listener.',interview:example,steps:[{title:'Prepare',detail:explanation,state:'Choose one small message'},{title:'Say it',detail:example,state:'Speak slowly; allow a pause'},{title:'Listen',detail:'Let the other person finish. Clarify if needed.',state:'Notice the actual reply'},{title:'Reflect',detail:recall,state:'One useful next step'}]}))];
