import {quests} from './curriculum';
import type {Progress} from './progress';
export const speakingTracks=['balanced','interview','workplace','everyday'] as const;
export type SpeakingTrack=typeof speakingTracks[number];
export type SpeakingPlan={version:1;day:number;track:string;level:string;minutes:number;audience:string;title:string;prompt:string;opener:string;structure:string;example:string;followup:string;rescue:string;steps:string[];reason:string};
const scenarios={
 interview:[
 ['Explain your approach','Explain a solution from today’s course to an interviewer.','I will clarify the input first, describe a simple solution, then discuss an improvement.','Problem → baseline → improvement → edge case','Why is this approach better, and when would you choose differently?'],
 ['Tell your ownership story','Use a real project where you took responsibility.','One feature I owned was… My responsibility was…','Situation → task → your actions → observed result','Which decision was yours, and what would you change now?'],
 ['Handle an unfamiliar question','Practise admitting what you do not know while reasoning aloud.','I have not used that directly. May I clarify the requirement and explain how I would investigate?','Known facts → uncertainty → investigation → verification','How would you verify your assumption before shipping?'],
 ['Explain a trade-off','Compare two approaches you studied, with a concrete constraint.','Given this requirement, I would choose… The cost is…','Requirement → options → choice → cost','What change in requirements would reverse your choice?'],
 ['Recover from an interruption','Answer a question, then practise a polite pause and restart.','Let me address that point first, then return to the example.','Acknowledge → clarify → answer → reconnect','Can you give the short version in two sentences?'],
 ['Introduce your experience','Introduce yourself using only your real work and learning.','I am a full-stack developer. Recently I worked on…','Role → contribution → strength → next goal','What is one technical problem you personally solved?']
 ],
 workplace:[
 ['Give a useful standup','Report progress, the next action and one blocker.','Yesterday I completed… Today I will… I need help with…','Done → next → blocker → specific request','What exactly do you need from the team, and by when?'],
 ['Ask for clarification','Turn an unclear feature request into two concrete questions.','To make sure I implement this correctly, can we clarify…?','Restate → ask → example → confirm','What should happen for an empty or invalid input?'],
 ['Explain a delay early','Explain a realistic risk without blaming someone else.','I found a risk that may affect the delivery date. Here is what I know…','Risk → impact → options → next update','What smaller part can we still deliver first?'],
 ['Disagree respectfully','Raise a technical concern and propose an alternative.','I understand the goal. My concern is… Could we compare…?','Shared goal → evidence → concern → alternative','What evidence would change your opinion?'],
 ['Explain a production issue','Give a calm, factual incident update.','We observed… The affected behavior is… Our next check is…','Observation → impact → action → next update','What is confirmed, and what is still a hypothesis?'],
 ['Review a teammate’s code','Practise one specific, respectful code-review comment.','Could we consider…? In this input, the current code may…','Observation → example → suggestion → question','How would you explain the same feedback to a beginner?']
 ],
 everyday:[
 ['Start a short conversation','Ask a willing person a simple question about a shared setting.','Hi, is this a good time for a quick question?','Greeting → permission → question → thanks','Ask one relevant follow-up based on their answer.'],
 ['Ask for help clearly','Practise asking for directions or help with a service.','Excuse me, could you help me find…?','Context → specific request → confirm → thanks','Repeat the instruction in your own words to confirm it.'],
 ['Listen and summarize','Listen to a willing person or a short audio clip and summarize the main point.','If I understood correctly, you mean…','Listen → summarize → confirm → follow-up','Which detail did you initially miss?'],
 ['Explain your day simply','Describe one useful thing you learned without technical jargon.','Today I learned a way to… Here is a simple example…','Event → simple explanation → example → question','How would you say it without using framework names?'],
 ['Recover when you miss a word','Practise asking someone to repeat or rephrase.','Sorry, I missed the last part. Could you say that again a little more slowly?','Acknowledge → request → paraphrase → continue','How can you confirm the meaning without pretending to understand?'],
 ['End a conversation politely','Practise a friendly closing without feeling trapped in a conversation.','Thank you, that was helpful. I need to get going, but it was nice speaking with you.','Acknowledge → appreciation → close','What would you say if the person is busy or declines?']
 ]
} as const;
export function speakingRecommendation(p:Progress){const attempts=Object.entries(p.studio||{}).filter(([id])=>id.startsWith('communication-coach-')).flatMap(([,r])=>r.attempts).sort((a,b)=>b.at.localeCompare(a.at)),recent=attempts.slice(0,3),scores=recent.map(a=>Number(a.fields.confidenceAfter)).filter(n=>n>=1&&n<=5),average=scores.length?scores.reduce((n,s)=>n+s,0)/scores.length:0;return {level:!scores.length||average<3?'Foundation':average>=4?'Stretch':'Practice',focus:recent[0]?.fields.nextFocus||'clarity',reason:!scores.length?'Start with a short private rehearsal. Your later self-ratings will guide the suggested difficulty.':`Based on ${scores.length} recent self-rating${scores.length===1?'':'s'}, not an automatic language assessment. Next focus: ${recent[0]?.fields.nextFocus||'clarity'}.`}}
export function makeSpeakingPlan(p:Progress,day:number,track:SpeakingTrack,minutes:number,audience:string,variant:number):SpeakingPlan{const chosen=track==='balanced'?(['interview','workplace','everyday'] as const)[(day-1+variant)%3]:track,pool=scenarios[chosen],s=pool[(Math.floor((day-1)/3)+variant)%pool.length],recommendation=speakingRecommendation(p),topic=quests[day-1].title;return {version:1,day,track:chosen,minutes,audience,...recommendation,title:s[0],prompt:`${s[1]} ${chosen==='everyday'?'Use a comfortable everyday setting or a private role-play.':`Use your Day ${day} work, “${topic}”, or a real work example you can explain truthfully.`}`,opener:s[2],structure:s[3],example:chosen==='interview'?'Example structure: “The repeated scan does extra work. I can remember earlier values in a Map. For each value I check its complement before storing it.” Adapt this only if it matches your actual solution.':chosen==='workplace'?'Example: “The input validation is complete. I am checking the empty-input behavior next. Could you confirm whether we should return an empty list or an error?”': 'Example: “Excuse me, is this the queue for the information desk?” Listen, then say: “Thank you. So I should wait here, right?”',followup:s[4],rescue:({clarity:'Use familiar words and replace one vague sentence with an example. ',structure:'Use the answer structure in order and keep one point per sentence. ',listening:'Repeat the other person’s main point before responding. ',nerves:'Start privately and practise just the opening sentence first. '}[recommendation.focus as 'clarity'|'structure'|'listening'|'nerves']||'')+'Pause once. Say: “Let me think for a moment.” Use one short sentence. If a word is missing, explain it with simpler words.',steps:minutes===5?['1 min: choose one point and rehearse the opener','2 min: say or write a 30–60 second answer','2 min: answer one follow-up and record one improvement']:minutes===10?['2 min: plan with the structure below','3 min: rehearse a 60–90 second answer','3 min: respond to a follow-up or willing listener','2 min: shorten one sentence and reflect']:['3 min: prepare and rehearse','7 min: practise privately or with a willing listener','5 min: respond to follow-ups and clarify one misunderstanding','5 min: compare your first and improved answer'],level:recommendation.level}}
export function readSpeakingPlan(value?:string):SpeakingPlan|null{try{const p=JSON.parse(value||'');return p?.version===1&&Number.isInteger(p.day)&&p.day>=1&&p.day<=90&&[5,10,20].includes(p.minutes)&&['interview','workplace','everyday'].includes(p.track)&&['title','prompt','opener','structure','example','followup','rescue','reason','level','audience'].every(k=>typeof p[k]==='string')&&Array.isArray(p.steps)&&p.steps.every((s:unknown)=>typeof s==='string')?p:null}catch{return null}}
