import {arrayExamples,type ArrayTrack} from './array-foundations';
import type {ReadingLesson} from './commute-guides';

export const arrayReadingTracks:{id:ArrayTrack;title:string;emoji:string;idea:string;methods:NonNullable<ReadingLesson['methods']>}[]=[
 {id:'loop',title:'Loops first',emoji:'🚶',idea:'Visit each position and keep only the information the answer needs. A sum needs one total; comparing every pair needs two indices.',methods:[{name:'for / for…of',use:'Use an index when position matters, or a value when it does not.',example:'for (const x of nums) total += x;'},{name:'length / nums[i]',use:'Read the array size and a zero-based position.',example:'[4,9][1] // 9'},{name:'push(value)',use:'Append to an output array.',example:'out.push(x * 2)'}]},
 {id:'set',title:'Set: have I seen it?',emoji:'🚪',idea:'Store distinct values when membership is enough. A Set does not store a count or the original array index. Usually you still use a loop around it.',methods:[{name:'add(value)',use:'Remember a value; repeating it does not increase size.',example:'seen.add(3); seen.add(3); // size 1'},{name:'has(value)',use:'Ask whether a value is present.',example:'seen.has(3) // true'},{name:'delete / clear / size',use:'Remove one value, remove all values, or count distinct entries.',example:'seen.delete(3); seen.size // 0'},{name:'[...set]',use:'Convert distinct values into an array in insertion order.',example:'[...new Set([3,1,3])] // [3,1]'}]},
 {id:'map',title:'Map: remember extra information',emoji:'🗃️',idea:'Associate each key with information: a count, index, object, or group. Array.map(callback) transforms an array; new Map() is a different collection.',methods:[{name:'set(key, value)',use:'Insert or replace information for a key.',example:'positions.set(7, 1)'},{name:'has(key)',use:'Check presence even if the stored value is 0 or false.',example:'positions.has(7) // true'},{name:'get(key)',use:'Read information; missing keys return undefined.',example:'positions.get(7) // 1'},{name:'delete / clear / size / entries',use:'Remove entries, empty the collection, count entries, or iterate pairs.',example:'[...positions.entries()] // [[7,1]]'}]},
];
const primers:ReadingLesson[]=arrayReadingTracks.map(t=>({
 id:`array-reading-${t.id}-start`,title:t.title,category:'Array foundations',topic:t.id==='loop'?'Arrays & loops':t.id==='set'?'Set membership':'Map associations',format:'Visual guide',minutes:3,
 explanation:t.idea+'\n\nAn array value is not its index. In [2,7,11], the value 7 is at index 1. Read the return-value contract before choosing a tool. Numeric examples use finite integers unless their contract says otherwise.',
 example:t.id==='loop'?'Sum [3,-2,7]: start at 0 → add 3 → add -2 → add 7 → return 8.':t.id==='set'?'Check [3,1,3]: empty Set → remember 3 → remember 1 → the next 3 is already present.': 'Two Sum [2,7,11], target 9: at 2, need 7 but it is absent; store 2 → index 0. At 7, need 2; get(2) returns 0, so return [0,1].',
 steps:[{title:'Read the question',detail:'Decide whether the answer requires values, indices, counts, or a Boolean.',state:'Input → required output'},{title:'Choose memory',detail:t.idea,state:t.id==='loop'?'index + running variables':t.id==='set'?'value → present / absent':'key → count / index / group'},{title:'Walk through',detail:'Inspect the current value, update memory, and maintain the meaning of that memory.',state:t.methods[0].example},{title:'Explain the choice',detail:'Say what you remember and why that is enough.',state:t.id==='loop'?'Running totals: O(n) time, O(1) extra space': 'Typical hash-lookup model: expected O(n) scan, O(n) extra space'}],
 methods:t.methods,pitfall:t.id==='loop'?'Nested loops may inspect O(n²) pairs. A single scan often needs no Map or Set.':'Expected constant-time lookup is a hash-model assumption, not a JavaScript worst-case guarantee. Objects are compared by identity.',
 interview:`I first identify the output contract. ${t.idea}`,recall:'Would you use a Set or Map when you must return the original index, and why?',answer:'Use a Map from value to index. A Set answers membership but does not retain the original index. A plain loop can also find indices by scanning.',
 hinglish:t.id==='loop'?'Har element ko visit karo. Jo answer ke liye zaroori hai, bas wahi yaad rakho.':t.id==='set'?'Bas yeh jaan-na hai ki value pehle aayi thi? Set use karo. Count ya index chahiye toh Map dekho.':'Key ke saath count ya index yaad rakhna hai toh Map use karo. has presence check karta hai, get stored value deta hai.',
}));
export const arrayReadingLessons:ReadingLesson[]=[...primers,...arrayExamples.map((x):ReadingLesson=>({
 id:`array-reading-${x.id}`,title:`${x.track==='loop'?'Loops':x.track==='map'?'Map':'Set'} · ${x.title}`,category:'Array foundations',topic:x.track==='loop'?'Arrays & loops':x.track==='set'?'Set membership':'Map associations',format:'Visual guide',minutes:4,
 explanation:`${x.reason}\n\nTime: ${x.time}. Space: ${x.space}. Expected lookup costs use the usual hash-table model. Read the precise input and return-value contract below.`,
 useWhen:x.task,example:`${x.task}\n\nInput:\n${JSON.stringify(x.input,null,2)}`,code:x.code,output:JSON.stringify(x.expected,null,2),
 steps:[{title:'Input & contract',detail:x.task,state:JSON.stringify(x.input,null,2)},{title:'Choose the memory',detail:x.reason,state:x.track==='loop'?'Loop indices / running variables / required output':x.track==='set'?'Distinct values: membership, not counts or indices':'Keys associated with information: inspect the code for this problem'},{title:'Trace the example',detail:x.hint,state:x.hint},{title:'Result & cost',detail:`Time: ${x.time}. Space: ${x.space}.`,state:JSON.stringify(x.expected,null,2)}],
 pitfall:x.trap,interview:`${x.reason} For the given input, the result is ${JSON.stringify(x.expected)}. Time is ${x.time}; space is ${x.space}.`,recall:`Without looking at the code, explain this approach: ${x.task}`,answer:`${x.hint} ${x.reason}`,methods:arrayReadingTracks.find(t=>t.id===x.track)!.methods,
 questions:[{question:'What is the key idea?',answer:x.reason},{question:'Give me a hint before the answer.',answer:x.hint},{question:'What mistake should I avoid?',answer:x.trap}],
})),{
 id:'array-reading-compare',title:'Same question, three tools: animated comparisons',category:'Array foundations',topic:'Loops vs Set vs Map',format:'Visual guide',minutes:5,
 explanation:'Compare nested loops, a Set, and a Map using the same Boolean question. Watch the active indices and lookup memory change. The worked Two Sum lessons that return indices have a different contract from this membership comparison.',example:'Input [3,3], target 6: two different positions form a pair. Input [3], target 6: one position cannot pair with itself.',
 steps:[{title:'Choose a contract',detail:'Does a pair exist? Or does a duplicate exist?',state:'Return true / false'},{title:'Choose a tool',detail:'Nested loops try earlier pairs. Set remembers earlier values. Map also keeps an index.',state:'Pairs ↔ membership ↔ key/value lookup'},{title:'Check before storing',detail:'Look up the needed earlier value before adding the current value.',state:'Check → match? → otherwise store'},{title:'Explain the tradeoff',detail:'Lookups trade additional memory for fewer pair comparisons.',state:'O(n²), O(1) extra → expected O(n), O(n) extra'}],pitfall:'Comparisons and has() calls are not equivalent CPU instructions; the display is not a runtime benchmark.',interview:'I use nested loops as a baseline, then remember earlier values. I need a Map if the output requires the associated index.',recall:'Why check before storing the current value?',answer:'To prevent a value from matching itself when the target is twice that value.'
}];
export function arrayReadingPath(track:ArrayTrack){return [`array-reading-${track}-start`,...arrayExamples.filter(x=>x.track===track).map(x=>`array-reading-${x.id}`)];}
