import {questionBank,theory} from './bank';
import {quests} from './curriculum';
import {Progress,dateKey,dayDate,scheduledDay} from './progress';
import {managedTasks} from './planning';
// Stable question IDs: five foundations from each of the twenty DSA topic packs.
export const requiredDSA=theory.filter(t=>t.kind==='DSA').flatMap(t=>questionBank.filter(q=>q.lessonId===t.id).slice(0,5));
const courseLessons=['int-js','int-react','int-node','int-mongo','sql-select','int-next','int-python','int-pg','int-delivery','int-cloud','sd-product','int-behavior','int-testing'];
export function dayAssignments(day:number){if(!Number.isInteger(day)||day<1||day>90)throw new Error('Choose day 1–90.');const offset=day-1+Math.floor((day-1)/9),count=day%9===0?2:1,q=quests[day-1],pool=questionBank.filter(x=>x.lessonId===courseLessons[q.chapter-1]);return {dsa:requiredDSA.slice(offset,offset+count),companion:pool[(day-1)%7%pool.length]};}
export function dsaDueDate(p:Progress,day:number){return p.planning?.items[`quest-${day}-practice`]?.dueDate||dayDate(p.startDate,day-1)}
export function courseStats(p:Progress,today=dateKey()){const end=dayDate(p.startDate,89),started=today>=p.startDate,day=scheduledDay(p.startDate,new Date(today+'T12:00:00'));const entries=quests.flatMap(q=>dayAssignments(q.day).dsa.map(question=>({question,day:q.day,dueDate:dsaDueDate(p,q.day),solved:!!p.practice?.[question.id]?.solvedAt}))),solved=entries.filter(x=>x.solved),due=entries.filter(x=>!x.solved&&x.dueDate<today),assigned=entries.filter(x=>x.dueDate<=today),remaining=100-solved.length,daysLeft=today>end?0:started?91-day:90;const weak=entries.filter(x=>!x.solved&&!!p.practice?.[x.question.id]?.attempts.length),next=due[0]||weak[0]||entries.find(x=>!x.solved);return {entries,solved:solved.length,due,assigned:assigned.length,remaining,daysLeft,end,day,started,next,pace:daysLeft?Number((remaining/daysLeft).toFixed(1)):remaining,extended:entries.filter(x=>x.dueDate>end&&!x.solved).length,completeDays:quests.filter(q=>p.days[q.day]?.completedAt&&dayAssignments(q.day).dsa.every(x=>p.practice?.[x.id]?.solvedAt)).length};}
export function changeCourseStart(p:Progress,startDate:string,shiftOverrides=true):Progress{if(!/^\d{4}-\d{2}-\d{2}$/.test(startDate)||dateKey(new Date(startDate+'T12:00:00'))!==startDate)throw new Error('Choose a valid course start date.');const difference=Math.round((Date.parse(startDate+'T00:00:00Z')-Date.parse(p.startDate+'T00:00:00Z'))/86400000),at=new Date().toISOString();if(!difference)return p;const items={...p.planning?.items};if(shiftOverrides&&p.planning){const tasks=managedTasks(p);for(const [id,item] of Object.entries(items)){if(tasks.find(t=>t.id===id)?.done)continue;const dueDate=dayDate(item.dueDate,difference),reason=`Course start changed from ${p.startDate} to ${startDate}`;items[id]={...item,dueDate,updatedAt:at,history:[...item.history,{at,dueDate,status:item.status,reason}]}}}return {...p,startDate,updatedAt:at,...(p.planning?{planning:{...p.planning,items}}:{})};}
export function markQuestionSolved(p:Progress,id:string):Progress{const r=p.practice?.[id];if(!r?.attempts.length)throw new Error('Submit an answer before marking the question solved.');return {...p,updatedAt:new Date().toISOString(),practice:{...p.practice,[id]:{...r,solvedAt:r.solvedAt?undefined:new Date().toISOString(),updatedAt:new Date().toISOString()}}};}
