// Authored scenario examples. Order matches the stable IDs in bank/design.ts.
// These are learning designs, not throughput guarantees or executed systems.
export type DesignCase={example:string;contract:string;data:string;nodes:string[];risk:string};
export const designCases:Record<string,DesignCase>={};
function cases(topic:string,rows:string){
 rows.trim().split('\n').forEach((row,i)=>{const [example,contract,data,path,risk]=row.split('|');if(!risk)throw Error(`Incomplete design case ${topic}-${i+1}`);designCases[`${topic}-${String(i+1).padStart(2,'0')}`]={example,contract,data,nodes:path.split(' > '),risk};});
}
cases('sd-routing',`
A mobile request carries an expired access token; reject it before spending the downstream request budget.|GET /orders/42; propagate request-id and remaining deadline.|Route(path, upstream, timeout_ms); request logs omit tokens.|Mobile client > TLS gateway > Token verifier > Order service|Authentication success does not authorize access to order 42.
A versioned app.js is served near the user; a cache miss fetches the same version from origin.|GET /assets/app.a31.js with immutable versioned URL.|Asset(path, content_hash); cache key includes the required representation dimensions.|Browser > DNS / edge selection > CDN cache > Asset origin|An unversioned file may remain stale after deployment.
One backend misses several readiness checks; remove it, drain connections, then reintroduce only after recovery.|GET /ready; proxy tracks consecutive successes and failures.|Target(address, readiness, failures, drain_until).|Health checker > Target registry > Reverse proxy > Ready backend|A single failed probe should not produce continuous removal and reentry.
User 42 makes requests through different API instances; all instances must enforce the same bucket.|allow(userId, cost, now) returns allowed and retryAfter.|Bucket(user_id, tokens, last_refill); refill plus consume is atomic.|User > API instance > Shared bucket operation > Allow / 429|A read-then-write counter allows concurrent requests through the same last token.
A short code abc resolves to a destination; repeated reads should avoid unnecessary writes.|POST /links; GET /abc returns redirect or expiry result.|Link(code UNIQUE, destination, expires_at, owner_id).|Browser > Redirect handler > Mapping cache > Link store|Cached links must respect revocation and expiry requirements.
A CPU-heavy report saturates one process; compare a larger machine with splitting independent jobs.|POST /reports returns job identity and status.|Job(id, workload_partition, state); record per-core utilization and queue wait.|Report queue > Scheduler > Compute workers > Result store|Adding instances will not speed one indivisible single-threaded computation.
A user changes search terms; cancellation should stop obsolete work where supported.|GET /search?q=new with deadline and cancellation signal.|Request(id, deadline, cancelled); durable side effects retain their operation ID.|Browser abort > Gateway deadline > Service cancellation > Downstream work|Stopping the client wait does not prove a downstream write stopped.
An employee can read only their department's internal records, even on the corporate network.|GET /internal/records/7; authenticate user and authorize department.|Employee(id, department); Grant(subject, resource, action).|Employee device > Private ingress > Identity verifier > Resource authorization|Network access alone is not permission to every internal object.
An authorized user uploads a private 100 MB file directly to object storage.|POST /uploads returns scoped upload target; POST /uploads/{id}/complete verifies metadata.|Upload(id, owner, object_key, expected_size, state).|Upload authorization > Scoped storage upload > Completion verification > Private object metadata|A client-supplied completion flag cannot establish that the expected object exists.
Region A stops serving requests; route users to B only after checking data and capacity readiness.|Failover runbook defines health trigger, RTO, RPO and failback gates.|Region(role, health, replica_position, spare_capacity).|Outage detection > Traffic controller > Ready region B > Recoverable data|Failing over traffic without available data or capacity can widen the outage.
`);
cases('sd-storage',`
Adding node D transfers its assigned ranges rather than rehashing every key by server count.|locate(key, ringVersion) returns owner plus replicas.|RingToken(token, node_id, version); Migration(range, source, destination, state).|Key hash > Versioned ring > Range owner > Range migration|Virtual nodes improve average balance but do not split one hot key.
A leader accepts a write but fails before the client receives its acknowledgment.|write(key,value,operationId) returns committed version or uncertain outcome.|LogEntry(term, index, key, value); durable replica acknowledgment positions.|Client > Current leader > Replicated log > Commit acknowledgment|The acknowledgment rule determines which writes survive failover.
One tenant generates 60% of requests; move it to dedicated capacity while ordinary tenants share shards.|route(tenantId, partitionVersion); move tenant under a versioned routing plan.|TenantRoute(tenant_id, shard_id, version); migration checkpoints.|Tenant request > Tenant router > Shared / dedicated shard > Migration verifier|A tenant key preserves locality but can create an oversized hot partition.
Customer names and orders are on different shards; a monthly report still needs their join.|StartReport(snapshotId) returns asynchronous report ID.|Order(customer_id, shard); Customer(id, version); report snapshot watermark.|Shard extracts > Versioned analytics staging > Join processor > Report|Joining snapshots from different times can produce a misleading report.
A session key expires at 12:00; a read at 12:01 must not return it even before physical deletion.|get(key,now) returns absent when expires_at is passed.|Entry(key,value,expires_at); expiry index or sampling metadata.|Read key > Check logical expiry > Return / miss > Reclaim memory|Memory cleanup timing and the promised read-expiry behavior are different.
A private document is revised three times, then deleted under a retention policy.|PUT /documents/{id}/versions; DELETE returns deletion workflow ID.|Document(owner,current_version); BlobVersion(hash,retention_until); deletion state.|Owner authorization > Version metadata > Immutable blob versions > Retention worker|Deleting the current pointer does not remove old blobs, indexes or retained backups.
Rename a required field while old mobile clients still send the original field.|Accept old/new contracts during an explicit compatibility window.|Migration(version,backfill_cursor); both fields until all clients migrate.|Expand schema > Backfill > Compatible readers / writers > Contract old field|Dropping the old field before old clients leave breaks requests.
A user edits their profile in region A and immediately reads from B.|GET /profile with minVersion; route to a source that can satisfy it.|Profile(id,version); session's last-seen write version.|Profile write > Session version token > Replica version check > Primary fallback|Low-latency local reads may not satisfy read-your-writes during replication lag.
Restore a deleted database into an isolated environment within one hour.|Restore(backupId,targetTime) followed by application validation.|Backup(id,snapshot_time,log_range,key_reference,restore_verified_at).|Snapshot + logs > Isolated restore > Integrity checks > Controlled cutover|A backup file is not evidence that the full application can be restored in time.
An analytics query reads two columns from a billion-row table while OLTP updates single records.|Aggregate selected columns over a declared snapshot.|Column segments, dictionary encoding and row identity; track update cost.|Column projection > Segment pruning > Vector / batch scan > Aggregation|A scan-friendly format may impose higher cost on frequent small row updates.
`);
cases('sd-consistency',`
A feed may show an older like count; selling the same seat twice is unacceptable.|GET /feed permits defined lag; reserve(seatId) must atomically claim ownership.|FeedProjection(version); Seat(id,owner,state,version).|Operation requirement > Consistency choice > Read / atomic claim > Observable result|Use separate guarantees for operations rather than one label for the entire product.
Two editors load version 5 and both submit an update; only one can replace that version.|PATCH /record/7 with expectedVersion=5 returns new version or 409.|Record(id,payload,version); optional conflict history.|Read version > Prepare edit > Conditional update > Conflict resolution|Blind last-write-wins can erase another editor's changes.
Inventory reserves successfully but the payment service declines the order.|CreateOrder(operationId); each saga step returns a durable outcome.|OrderState; Reservation; PaymentOperation; outbox; compensation records.|Order coordinator > Inventory reservation > Payment operation > Release / fulfillment|A compensation is a business action and may itself fail or need reconciliation.
A charge succeeds at the provider but its response is lost; the client retries with the same key.|POST /payments with scoped idempotency key; reject different payload under that key.|PaymentOperation(tenant,key,payload_hash,state,provider_id,result).|Stable client key > Durable operation claim > Provider call > Reconciliation|A local key alone cannot make an unsupported external side effect exactly once.
Two buyers compete for the last seat; one hold expires while payment confirmation is delayed.|HoldSeat(seatId,operationId); ConfirmHold(holdId,paymentId).|Seat; Hold(owner,expires_at,state,version); confirmed reservation uniqueness.|Atomic seat hold > Payment attempt > Expiry / confirmation race > Reconcile|Comparing the clock in application code without an atomic state transition permits overselling.
A user edits a shared profile while another editor has a long-lived lock.|UpdateProfile(expectedVersion) or acquire bounded editing lease.|Profile(version); Lease(owner,expires_at,fence); preserved draft.|Load profile > Choose coordination > Commit / reject > Preserve losing draft|Abandoned locks block work; optimistic edits require explicit conflict UX.
Shipping may have accepted a request before the order service timed out.|StartShipment(operationId); QueryShipment(operationId).|WorkflowStep(state,request_id,external_id,last_checked_at).|Persist intent > Send request > Timeout / unknown > Query and reconcile|Immediately compensating an unknown outcome can conflict with a successful side effect.
Two machines produce events with skewed wall clocks; a later causal action has an earlier timestamp.|Append(entityId,expectedSequence,event); declare ordering scope.|Event(entity_id,sequence,causation_id,wall_time).|Causal action > Assign entity sequence > Persist event > Ordered consumer|Wall-clock timestamps do not establish a universal causal order.
Two buyers each request three units when only five remain.|Reserve(sku,quantity) uses atomic available>=quantity predicate.|Inventory(sku,available,version); Reservation(id,quantity,state).|Validate quantity > Atomic decrement > Reservation record > Commit / release|Reading stock and decrementing later can allow both requests.
An order says paid while the payment service says pending; decide which evidence is authoritative.|Reconcile(operationId) records diagnosis and approved repair.|Discrepancy(entity_id,source_versions,evidence,repair_state).|Detect mismatch > Fetch authoritative evidence > Choose repair > Audit result|Blindly copying the latest timestamp can spread incorrect state.
`);
cases('sd-messaging',`
A user opts out of email after a notification is queued but before it is sent.|POST /notifications; GET /deliveries/{id} exposes provider-confirmed states.|Notification; ChannelDelivery(attempts,state); Preference(user,channel).|Durable intent > Delivery queue > Preference-aware worker > Channel provider|Provider acceptance is not proof that a human read the notification.
An order event is consumed by billing, analytics and inventory at different speeds.|Publish(eventId,type,schemaVersion,payload); subscribe with independent checkpoint.|EventEnvelope; Subscription; consumer checkpoint and dedup key.|Order outbox > Event broker > Independent consumers > Owned projections|A slow subscriber should not force every service to stop processing.
Kafka production remains 5,000/s while consumers process 3,000/s.|Observe lag by partition and age; plan replay within capacity.|PartitionOffset(produced,committed); handler latency and failure samples.|Partition backlog > Diagnose handler > Scale / repair consumers > Controlled catch-up|More consumers than useful partitions may not add processing parallelism.
Workers have very different processing speeds; compare pushed jobs with lease-based polling.|claim(maxJobs,leaseDuration) or push with bounded acknowledgment deadline.|Job(lease_owner,lease_until,attempt); worker capacity.|Pending jobs > Push / pull admission > Worker capacity > Acknowledge / retry|Unbounded delivery to slow workers creates memory pressure and duplicate work.
A reminder must still run after every worker restarts before its due time.|ScheduleReminder(dueAt,recipient,operationId); atomically claim due jobs.|Reminder(id,due_at,state,lease_until,operation_key).|Persistent schedule > Due-job claim > Reminder sender > Outcome record|An in-memory timer disappears with its process.
A broker delivers the same invoice event twice but only one ledger entry should be added.|ApplyInvoice(eventId) within a transaction that records deduplication and the effect.|ProcessedEvent(event_id UNIQUE); LedgerEntry(source_event UNIQUE).|Repeated delivery > Transactional dedup check > Business write > Acknowledge|Deduplication and the effect must share a boundary or retain a failure window.
A poison message exhausts retries; an operator fixes its schema and requests replay.|Replay(deadLetterId,reason) requires authorization and preserves original identity.|DeadLetter(payload,error,attempts); ReplayAudit(operator,reason).|Bounded retries > Dead-letter store > Authorized correction > Idempotent replay|Replaying with a new business identity can duplicate an earlier effect.
Customer 9's address change must precede their shipment event, but other customers run concurrently.|Publish(customerId,sequence,event); handle sequence gaps explicitly.|EntityEvent(customer_id,sequence,event_id); consumer last applied sequence.|Entity key > Stable partition > Ordered consumer > Versioned state|Partition order alone does not resolve producers assigning conflicting sequences.
A burst of large uploads creates thumbnail jobs faster than image workers finish.|POST /thumbnail-jobs; GET /jobs/{id} reports queued/running/failed/complete.|ImageJob(object_key,transform,attempt,state,result_key).|Upload complete > Bounded job queue > Image worker pool > Thumbnail objects|Decode size, concurrency and retry limits must protect worker memory.
A customer endpoint returns 500 for an hour and later receives a repeated webhook.|Deliver(eventId,signature,timestamp); retry under a bounded schedule.|WebhookAttempt(event_id,url,status,next_attempt_at); endpoint secret reference.|Stored event > Delivery scheduler > Signed HTTP attempt > Delivery history|A 200 response and actual customer-side processing are separate contracts.
`);
cases('sd-product',`
A recipient reconnects after being offline and must see missed messages once in order.|POST /conversations/{id}/messages; GET /messages?afterSequence=…|Message(id,conversation_id,sequence,sender,body); receipt state.|Sender > Durable message service > Conversation log > Recipient sync|Transport delivery, durable storage and read receipts are different states.
A room has 10,000 members, but only 300 are online.|SendMessage(roomId,clientMessageId); fetch history by room sequence.|RoomMembership; Message(room_id,sequence); session subscriptions.|Room author > Membership check > Room log > Fanout / reconnect sync|Broadcasting every presence update to all members can dominate message traffic.
A celebrity publishes to millions while ordinary accounts have small follower sets.|GET /feed?cursor=…; PublishPost with durable identity.|Post; Follow; FeedEntry(user,post,rank_context).|Post write > Fanout policy > Feed materialization > Read-time merge|Fanout-on-write can make large-publisher writes expensive.
Two offline editors insert characters at the same document position and later reconnect.|Sync(documentId,baseVersion,operations); select and define a convergence model.|Document; operation IDs; causal/version metadata; durable snapshot.|Local operation > Operation sync > Merge / transform engine > Shared document|Last-write-wins for the entire document can erase independent edits.
A user's laptop loses Wi-Fi without sending a disconnect message.|Heartbeat(sessionId); presence expires after a declared lease.|Presence(user_id,session_id,last_seen,expires_at).|Client heartbeat > Presence service > Expiring session record > Presence subscribers|Presence is approximate; absence of a heartbeat is delayed evidence.
A recurring 9 AM meeting crosses daylight-saving changes and invitations are updated.|CreateEvent(localTime,timeZone,recurrence); Respond(invitationVersion).|CalendarEvent(local_rule,zone); Occurrence; Invitation(version,status).|Local recurrence rule > Timezone expansion > Invitations > Versioned responses|Adding a fixed number of UTC hours does not preserve every local recurrence.
A document becomes private after its title already appeared in a feed.|GET /activity checks current access; revocation removes derived visibility.|Activity(resource_id,actor,version); ACL; deletion/revocation checkpoint.|Authoritative action > Activity projection > Access recheck > Visible feed|Cached derived content can leak after permissions change.
A reader posts a reply to a moderated parent comment.|POST /comments with parentId; GET /comments uses stable cursor.|Comment(post_id,parent_id,author_id,status,version); moderation audit.|Author > Comment authorization > Comment records > Moderation view|Parent validation must prevent cross-post links and unbounded nesting.
A learner watches on a phone offline and later opens the same video on a laptop.|SaveCheckpoint(videoId,position,sessionId,version); define conflict policy.|PlaybackCheckpoint(user,video,position,version); completion evidence.|Player session > Local checkpoint > Versioned sync > Resume position|Taking the largest playback position does not prove the content was watched.
A learner submits a second answer while retaining the first for revision.|SubmitAttempt(questionId,text); SaveFeedback(attemptId,source).|Curriculum; immutable Attempt(user,question); Feedback; ReviewDue; Attachment ownership.|Question > Saved attempt > Reviewed feedback > Retrieval schedule|Replacing answer text destroys the evidence needed to compare learning over time.
`);
cases('sd-commerce',`
A cart shows yesterday's price but checkout sees a new catalog price.|QuoteCart(cartVersion); CreateOrder(acceptedQuoteId).|CartLine; Quote(expires_at); OrderLine(unit_price_snapshot).|Editable cart > Current quote > User acceptance > Immutable order lines|Silently changing price after acceptance violates the checkout contract.
Payment succeeds but shipping creation fails after inventory was reserved.|Checkout(operationId); track each step and its recoverability.|Order(state); Reservation; Payment; Shipment; compensation history.|Reserve inventory > Payment operation > Shipping request > Reconcile / compensate|A refund may not undo every fulfillment action already taken.
A guest books Monday through Wednesday, excluding Wednesday night.|ReserveRoom(roomId,arrival,departure); enforce a half-open date range.|RoomNight(room_id,date,availability); Booking; Hold(expiry).|Requested nights > Atomic availability claim > Booking hold > Confirmation|Checking each night separately without one coordination boundary can double-book.
Two buyers click the same airline seat during payment latency.|HoldSeat(flightId,seatId); Confirm(holdId,paymentOperation).|FlightSeat(flight_id,seat_id,state,version); Hold; Ticket UNIQUE seat assignment.|Seat map > Atomic hold > Payment state > Ticket issue|A displayed empty seat is not a reservation.
One million users request a limited batch of products in a flash sale.|JoinAdmissionQueue; Reserve(sku,operationId); expose queue status.|AdmissionToken; Inventory; Reservation; abuse/rate-limit counters.|Admission gate > Bounded queue > Inventory claim > Checkout|A queue buffers demand but cannot create stock or unlimited processing capacity.
A coupon has a global limit of 100 and a per-user limit of one.|Redeem(couponId,userId,operationId) commits all limits together.|Coupon(limit,used); Redemption(coupon,user UNIQUE,operation_key).|Eligibility check > Atomic quota claim > Redemption record > Checkout result|Independent counter updates can violate one of the limits under concurrency.
A renewal charge fails twice and later succeeds through a repeated provider callback.|Renew(subscriptionId,periodId); provider callback is deduplicated.|Subscription; BillingPeriod UNIQUE subscription/period; ChargeAttempt; grace state.|Due billing period > Durable charge request > Provider events > Subscription state|A repeated event must not extend service or charge the period twice.
An order is partially refunded, then the same callback arrives again.|Refund(paymentId,amountMinor,operationId); track cumulative approved refunds.|Refund(operation_key,amount,state); immutable payment/refund ledger.|Refund authorization > Remaining-amount check > Provider request > Ledger reconciliation|Concurrent partial refunds must not exceed the refundable amount.
A product changes price while a search index still contains the old value.|UpdateProduct(expectedVersion); search returns freshness-aware result.|Product; Attribute; PriceVersion(valid_from); index checkpoint.|Catalog write > Versioned history > Search update > Current purchase validation|Search results are a derived view, not the authoritative checkout price.
An operator corrects an order but the original state and reason must remain inspectable.|AppendOrderEvent(orderId,event,actor,reason); restrict history mutation.|OrderEvent(sequence,actor,payload,recorded_at); retention metadata.|Authorized action > Append audit event > Derived order view > Audit reader|Append-only permissions do not by themselves prove cryptographic tamper evidence.
`);
cases('sd-platform',`
A stateful game room moves from instance A to B without accepting two owners.|ClaimRoom(roomId,lease,fence); transfer snapshot and event position.|RoomOwner(epoch,lease_until); room snapshot; event log.|Room routing > Current owner > Durable state > Fenced takeover|A stale owner must be prevented from writing after its lease is replaced.
Two schedulers briefly believe they are leader during a network pause.|AcquireLease(jobGroup); writes carry a monotonic fencing token.|Lease(holder,expires_at,fence); executed job operation key.|Coordination lease > Leader scheduler > Fenced job claim > Worker|Lease expiry without fencing does not stop an old leader's delayed write.
A coordinator session expires while its process is still running.|Create ephemeral sequential candidacy; watch predecessor; fence actual effects.|Candidate sequence; coordination session; resource fencing token.|Candidate registration > Predecessor watch > Leadership decision > Fenced operation|Failure detection can be delayed; conceptual leadership is not sufficient authority to write.
A service instance dies before removing its discovery registration.|Register(instance,lease); clients use cached endpoints with bounded staleness.|ServiceEndpoint(address,lease_until,health,version).|Instance registration > Registry > Client discovery cache > Healthy endpoint|Discovery availability and endpoint health are separate concerns.
An entire availability zone is lost, including one database replica.|Define zone failure contract; verify compute and data dependencies.|ZonePlacement; replica health; dependency map; failover readiness.|Multi-zone ingress > Zone-local compute > Cross-zone data replicas > Failover control|Replicating the API alone leaves shared dependencies as failure points.
A five-person team wants independent services before identifying release bottlenecks.|Define module contracts first; extract a service only for a concrete boundary.|Module ownership; dependency graph; deployment/change history.|Client > Modular application > Module interfaces > Owned persistence|Network boundaries add failure, deployment and data-consistency work.
A bad feature configuration reaches one cohort; revert it without redeploying code.|PublishConfig(version,scope); validate and progressively activate.|ConfigVersion(schema,scope,author); rollout state; last known good value.|Validated config > Canary cohort > Health gate > Wider activation|Cached clients may remain on the previous version; define propagation and rollback behavior.
A database credential rotates while old application instances are still serving.|Issue new credential; refresh clients; verify adoption; revoke old credential.|Secret reference/version; consumer adoption state; rotation audit.|Secret issuer > Trusted secret store > Application refresh > Old-key revocation|Never send a server credential to the browser or log its value.
A canary release passes process health but increases checkout errors.|Promote artifact digest only after user-path and metric gates.|Release(digest,cohort,stage); metric baseline; compatible rollback target.|Immutable artifact > Canary traffic > Business health gate > Promote / rollback|A code rollback can fail if the schema migration is not backward compatible.
A failing downstream service accumulates more pending calls than the API can hold.|Bound concurrency, deadline and queue; reject excess work deliberately.|Dependency budget; circuit state; queue age; rejection counters.|Incoming load > Admission / deadline > Bounded dependency calls > Clear fallback|Retries can amplify overload precisely when the dependency has least capacity.
`);
cases('sd-data',`
A billion-document index must be rebuilt while new documents continue to arrive.|Search(query,cursor); ingest(documentId,version,operation).|Source document; index generation; checkpoint; deletion tombstone.|Source snapshot + changes > Partitioned indexing > Search shards > Query merge|A new index is not ready until it catches up and deletes are represented.
Typing rea should suggest React and related terms without querying every document.|GET /suggest?q=rea&limit=10; define ranking and typo policy.|Prefix index; normalized token; ranking signal; update version.|Typed prefix > Prefix / fuzzy retrieval > Ranking > Bounded suggestions|Personalized or popularity ranking can change ordering and cache behavior.
Thousands of services emit logs; one debug burst must not exhaust ingestion.|Ingest structured log batch with tenant and time; query by correlation fields.|Log(timestamp,service,request_id,level); retention and partition metadata.|Log agent > Bounded ingestion > Indexed storage > Investigator query|High volume or secret-rich payloads require limits and redaction before storage.
A request queues work that finishes minutes after the HTTP response.|Propagate trace context and separate durable business operation ID.|Span(trace_id,parent_id,start,end); operation correlation metadata.|HTTP span > Queue publish span > Worker span / link > Trace viewer|A request trace ID alone may not model a long-lived retried workflow.
Every user ID becomes a metric label and the time-series count explodes.|Define approved label dimensions; aggregate or move detail to logs.|Metric(name,labels,time_bucket,value); cardinality budget.|Instrumented service > Label validation > Aggregation > Metrics store|Unbounded label values increase storage and query cost even with few metric names.
An event arrives two hours late and another event is delivered twice.|Ingest(eventId,eventTime,value); specify correction window.|Event dedup ID; event-time window; watermark; correction version.|Event ingestion > Deduplication > Window aggregation > Late-data correction|Processing time and event time answer different business questions.
A new product has few interactions; start recommendations without a complex model.|GET /recommendations with experiment assignment and feedback event.|Item metadata; consented interaction; experiment cohort; outcome metric.|Baseline candidates > Eligibility filter > Ranking > Measured feedback|A complex model cannot compensate for unclear goals or biased feedback.
A topic trends in a rolling hour but activity is uneven and keys are hot.|GetTopK(windowEnd,k); declare exact or approximate behavior.|Time-bucket counts; topic ID; sketch/error parameters if approximate.|Partitioned counts > Window merge > Top-k selection > Ranked output|Summing overlapping windows or ignoring expiration can inflate counts.
A customer exports millions of records without holding an HTTP request open.|POST /exports returns job ID; GET /exports/{id} returns authorized expiring download.|Export(owner,snapshot_ref,state,object_key,expires_at).|Authorized request > Background snapshot export > Private file > Expiring download|A file URL must not grant unrelated users access to another tenant's data.
A deletion request must remove visible data from the database, cache and search.|RequestDeletion(subjectId); track per-store completion and retention exceptions.|DeletionRequest; per-store checkpoint; tombstone; retention policy.|Verified request > Primary deletion > Derived-store propagation > Completion audit|Backup retention and active-data removal need distinct, honest guarantees.
`);
cases('sd-oop',`
Two cars enter when only one compatible spot remains.|ParkingService.park(vehicle); AllocationStrategy.choose(spots,vehicle).|Vehicle; Spot(type,state); Ticket(entry,spot); Payment record.|ParkingService > AllocationStrategy > Atomic spot repository > Ticket|An in-memory available-spots list does not prevent concurrent double allocation.
Two elevator cars compete for a new hall call while one is in maintenance.|Dispatcher.assign(call); CarController.accept(command) validates state.|HallCall; Car(position,direction,state); Assignment.|Hall call > SchedulingStrategy > CarController > Safety-checked transition|Scheduling optimization must not bypass door, load or maintenance constraints.
A title has three physical copies but a borrower requests a specific unavailable copy.|LendingService.checkout(copyId,borrowerId).|BookTitle; Copy; Borrower; Loan; Reservation queue.|LendingService > LoanPolicy > Copy / loan repository > Checkout result|One active loan per physical copy needs persisted coordination.
A player tries a move that exposes their own king.|Game.tryMove(from,to,promotion); MoveValidator evaluates proposed board.|Board; Piece; Move; Turn; game status.|Player move > Pseudo-legal validation > King-safety check > Committed game state|Movement rules alone do not prove a move is legal.
Three friends split a bill unevenly and rounding leaves one minor unit.|ExpenseService.record(amount,splitPolicy); return balanced ledger entries.|Money(currency,minorUnits); Expense; Share; LedgerEntry.|Validated expense > SplitStrategy > Rounded shares > Balance ledger|Shares must sum exactly to the original amount with an explicit rounding rule.
A notification vendor is replaced without changing business notification rules.|NotificationDispatcher.send(message); ChannelProvider.send(contract).|Notification; ProviderResult; durable delivery job.|Business notification > Dispatcher > Provider interface > Vendor adapter|Retry state belongs in durable orchestration, not hidden inside an unbounded adapter loop.
A machine takes payment but the selected item jams while dispensing.|Machine.handle(event); transition returns state and required action.|State; Inventory; Credit; DispenseAttempt; Refund obligation.|Selection > Payment state > Dispense state > Receipt / refund|Dispense failure must preserve the customer's refund obligation.
A new discount rule conflicts with an existing seasonal discount.|PricingEngine.quote(input); ordered PricingRule.apply(context).|PriceInput; RuleResult; applied-rule trace; total in minor units.|Validated basket > Rule ordering policy > Rule evaluation > Traceable quote|Changing rule order can change the price; make precedence explicit.
An ATM simulator approves withdrawal but the dispenser reports only partial cash delivery.|Session.withdraw(amount); Dispenser returns delivered denominations.|Session; Authorization; CashInventory; WithdrawalAttempt state.|Authorized session > Withdrawal plan > Simulated dispenser > Reconcile delivered cash|Do not model the external debit and physical dispense as one infallible method.
A file search encounters a symlink cycle and a directory without permissions.|SearchService.find(root,predicate,cancel); FileSystemAdapter enumerates entries.|SearchOptions; FileEntry; visited identity set; structured scan errors.|Traversal adapter > Cycle / access checks > Composed predicate > Results|Unbounded recursion through symlinks can loop forever.
`);
cases('sd-functions',`
Adding two units returns a new cart without changing the previous cart.|updateCart(cart,command,catalog) returns cart or validation error.|Cart lines as immutable records; quantities and minor-unit prices.|Command > Pure cart transition > New cart / error > Checkout effect boundary|Mutation of a nested line can leak into the previous state snapshot.
A scheduler chooses due jobs without reading a hidden global clock.|selectDue(jobs,now,limit); claim selected jobs separately.|Job(id,due_at,priority,state,version).|Explicit time + job records > Pure selection > Atomic claims > Job execution|A pure selection function does not stop two workers claiming the same job.
A confirmation password depends on another field and produces an ordered error list.|validateFields(values,rules) returns structured errors.|Rule(field,dependencies,validate); Error(path,code,message).|Input values > Field validators > Cross-field validators > Ordered errors|Asynchronous checks can return after the form values have changed.
An order in cancelled state receives a payment-success event.|transition(order,event) returns nextState/effects or an invalid-transition error.|Tagged OrderState; Event; durable effect ID.|Current state + event > Transition table > Next state + effects > Effect runner|Ignoring an invalid transition can lose a required reconciliation action.
A CSV has a bad row in the middle of a file too large to load entirely.|parseStream → validateRow → transformRow → persistBatch.|ImportJob; row number; validation error; batch checkpoint.|Byte stream > Row parser > Validation / transformation > Bounded persistence|Retrying a partly committed batch needs an import/row identity policy.
A user has an allow rule and an explicit deny rule for one resource.|evaluate(policy,subject,resource,action) returns decision and reasons.|Policy records; attributes; precedence; decision trace.|Subject + resource context > Pure predicates > Precedence resolution > Explainable decision|Untrusted policy text must not execute arbitrary application code.
A bucket has two tokens but a request costs three at the supplied time.|calculateBucket(state,now,cost) returns allowed,nextState,retryAfter.|Bucket(tokens,lastRefill,capacity,rate,version).|Explicit bucket + time > Refill calculation > Consume decision > Atomic state update|Saving the calculated state without a concurrency guard can overspend tokens.
A learner recalls a concept poorly and needs an earlier review without changing past evidence.|scheduleReview(evidence,now,policy) returns dueDate and reason.|Attempt(confidence,time); ReviewState; policy version.|Attempt evidence > Pure scheduling rule > Next due date > Persisted review state|A study streak is not evidence of independent recall.
An editor undoes a change, then makes a different edit.|reduce(history,command) returns new history; define future-branch behavior.|History(past,present,future); bounded snapshots or reversible commands.|Edit command > Immutable transition > History update > Render present|A new edit after undo must deliberately discard or preserve the old redo branch.
Implement the same no-double-booking rule once with objects and once with pure transitions.|BookingService.reserve versus reserve(state,command), both using one atomic persistence boundary.|Booking records; resource uniqueness; expected version.|Shared requirements > OOP / function implementation > Same storage constraint > Compare change cost|Changing programming style does not remove database races.
`);
