type Row=[string,string,string,string];
const rows=(text:string):Row[]=>text.trim().split('\n').map(line=>{const parts=line.split('|').map(part=>part.trim());if(parts.length!==4)throw new Error('Invalid interview content');return parts as Row});
export const expandedInterview:Record<string,Row[]>={
nodejs:rows(`What is Node.js? |Node is a JavaScript runtime used for servers, tools and other non-browser programs. Its libraries expose networking and operating-system facilities.|An HTTP service receives JSON, validates it and calls a database without a browser.|Do not call Node a frontend framework.
Why choose Node for an API? |It fits many concurrent I/O-bound operations and shared JavaScript tooling. CPU-heavy work needs separate capacity planning.|A dashboard aggregates independent service responses; a long video encoder belongs in a worker.|One language does not remove architectural trade-offs.
What does async return? |An async function returns a promise, including when it returns an ordinary value. Thrown errors become rejections.|async function answer(){return 42;} must be awaited or consumed with then to obtain 42.|A promise is not the resolved value.
Promise.all versus allSettled? |all combines fulfillment results but rejects when an input rejects. allSettled describes every final outcome.|Use all for required independent resources; use allSettled for a dashboard where partial results are useful.|Rejection of all does not cancel other operations.
How do you limit concurrent requests? |Use a bounded queue or pool to cap simultaneous work and protect downstream capacity.|Process a thousand URLs with twenty workers rather than firing all at once.|Do not confuse rate per second with concurrent count.
Why use connection pooling? |Reusing a bounded set of database connections avoids repeated setup while limiting database load.|Each API instance gets a pool budget; total connections must account for all instances.|A larger pool can make an overloaded database worse.
How do you implement request validation? |Parse and validate structure, types, size and allowed values at the boundary; enforce business rules deeper in the use case.|Reject a negative quantity before storage and reject an out-of-stock purchase during the business operation.|TypeScript types do not validate incoming JSON at runtime.
What is middleware? |Middleware participates in request processing and can continue, respond or pass an error according to the framework contract.|A request-ID middleware adds context before logging and route execution.|Do not call next after already completing a response accidentally.
What belongs in a controller? |Translate HTTP input to application calls and map outcomes to responses. Keep reusable business logic outside large route handlers.|A controller calls placeOrder; the service applies pricing and inventory rules.|A thin controller still needs correct boundary validation.
How do you structure configuration? |Load environment-specific values centrally, validate them at startup and keep secrets out of source and client responses.|Fail early if the database URL is missing instead of failing on the first purchase.|Do not log full configuration objects containing credentials.
What is npm package-lock for? |It records resolved dependency versions and integrity data for reproducible installs. npm ci uses the lockfile for clean installation.|CI uses the committed lockfile so developers and deployment resolve the same dependency tree.|A lockfile does not guarantee dependencies are vulnerability-free.
What is semantic versioning? |Major, minor and patch versions communicate intended compatibility changes, but actual upgrades still require review.|A patch is intended to fix a bug; a major upgrade can require API changes.|Do not assume every package follows the convention perfectly.
How do you hash passwords? |Use a dedicated password-hashing algorithm with unique salts and suitable cost, through a maintained library.|A login compares a submitted password using the library verifier rather than decrypting stored passwords.|Do not use plain SHA hashing or reversible encryption as password storage.
Session cookies versus bearer tokens? |Cookies can be automatically sent by browsers; bearer tokens are explicitly presented. Each design has storage, CSRF, XSS and revocation trade-offs.|An HttpOnly cookie limits script access, but cookie-authenticated mutations still need a CSRF strategy.|Neither option is automatically secure without the surrounding design.
How do you implement rate limiting? |Choose a key, window or token policy and enforce limits at appropriate boundaries. Distributed servers need coordinated state when limits are global.|Limit login attempts by multiple useful signals without locking every user behind one shared IP.|Do not trust arbitrary forwarded-IP headers from untrusted sources.
What is structured logging? |Record named fields instead of only free-form strings so events can be searched and correlated.|Log requestId, route, duration and safe error category for a failed checkout.|Do not log passwords or authorization headers.
Unit versus API integration checks? |Unit checks isolate business behavior; integration checks exercise routing, serialization, persistence and authorization together.|Verify a discount rule separately, then verify another user cannot read the discounted order.|Mocks alone cannot prove database constraint behavior.
How do you version an API? |Preserve existing contracts or introduce an explicit migration/version policy when incompatible changes are necessary.|Add an optional response field safely; replacing a field type may require a version or migration.|Do not surprise clients with silently changed semantics.
How do you paginate an endpoint? |Bound page size, use deterministic ordering and choose offset or cursor behavior suited to the data.|A feed cursor contains the last timestamp and ID so tied timestamps are handled.|Never return an unbounded collection by default.
How do you validate file uploads? |Limit size, authorize ownership, inspect actual content as appropriate and store files outside executable paths.|Store a generated object key rather than using a supplied filename as a filesystem path.|A browser-provided MIME type is not proof of content.
What is an EventEmitter? |It is an in-process event/listener mechanism. Emitting ordinarily invokes registered listeners synchronously; async listeners need error handling.|A local component publishes a state-change notification to observers.|It is not a durable cross-server message queue.
Why can regular expressions be dangerous? |Some patterns exhibit excessive backtracking on crafted inputs, blocking processing. Bound inputs and use safer patterns or parsers.|A user-submitted long string can consume CPU in a poorly designed validation regex.|Do not assume short regex code means cheap execution.
What is Buffer? |Buffer represents binary bytes in Node. It is useful for files, network data and encoding conversions.|Decode UTF-8 bytes to text only when the payload actually uses that encoding.|Do not treat arbitrary binary data as a JavaScript string.
What does JSON serialization lose? |JSON represents a limited data model, not every JavaScript type or reference relationship.|Dates commonly become strings; object properties with undefined are omitted; BigInt needs an explicit representation.|Circular references cannot be serialized by ordinary JSON.stringify.
How do you handle unhandled rejections? |Attach meaningful error handling at async boundaries and configure process monitoring. Unexpected process-level failures need safe termination/restart policies.|An awaited job failure is recorded with its retry state, not silently abandoned.|Do not rely on one global handler to repair corrupted application state.
What is a timeout budget? |Allocate a bounded end-to-end duration and pass deadlines/cancellation to dependencies where possible.|A two-second API budget cannot safely give each of five sequential calls two seconds independently.|A timeout response does not prove the downstream operation stopped.
What is health versus readiness? |Liveness asks whether a process should be restarted; readiness asks whether it should receive traffic.|During startup the process may be alive but not ready until critical initialization completes.|Do not restart every instance because one optional dependency is slow.
How do you prevent cache stampedes? |Coordinate regeneration and spread expiration so many misses do not all hit storage simultaneously.|A hot product key uses single-flight loading and a bounded stale-response policy.|Do not let expired-cache traffic overwhelm the database.
What is a circular module dependency? |Modules depend back on each other, which can expose partially initialized exports or create confusing initialization behavior.|Extract shared types or contracts instead of having user and order modules import each other's startup code.|Do not fix architecture solely by changing import order.
How do you explain your Node feature? |Describe the requirement, request contract, service rule, persistence, security, failure handling and your contribution.|For saved notes: authenticate, validate text, enforce ownership, upsert, return status and show retry on failure.|Use actual experience rather than claiming every production practice was implemented.`),
react:rows(`What is a component? |A component describes UI from inputs and state; its render should be pure. Composition combines smaller components into screens.|An OrderCard receives an order and renders it without mutating that order.|Do not fetch or mutate external systems directly during render.
Props versus state? |Props are inputs from a parent; state is component-managed memory that schedules renders when updated.|A parent passes product price while a quantity input keeps its current draft in state.|Do not directly mutate incoming props.
Why avoid mutating state? |React relies on update boundaries and identity comparisons; replacing changed objects makes transitions predictable.|Update an item with map and copy its changed fields instead of modifying the existing array.|Shallow copying an array alone does not clone nested objects.
What is lifting state up? |Move shared state to the nearest common owner so related components use one source of truth.|A search field and filtered list read the same parent-owned query.|Do not duplicate the same authoritative state in several children.
What is useRef for? |A ref retains a value across renders without scheduling a render when changed. It can hold a DOM node or mutable handle.|Store a timer ID for cleanup, or focus an input via its ref.|Do not put visible UI state only in a ref and expect rendering.
When useReducer instead of useState? |A reducer centralizes transitions when updates form related actions or rules. It must calculate next state without side effects.|A checkout has addItem, removeItem and applyCoupon actions with explicit transitions.|A reducer does not automatically make state global.
What makes a custom hook useful? |It extracts reusable stateful logic while each caller keeps its own hook state unless shared externally.|useOnlineStatus can encapsulate subscribing and cleanup for network status.|Do not call hooks conditionally inside a custom hook.
Why must hook order stay consistent? |React associates hook calls with their order in a component. Conditional calls can shift that association between renders.|Put an if inside an effect callback rather than conditionally calling the effect.|Only call hooks in supported React functions and contexts.
What does effect cleanup do? |Cleanup undoes the prior synchronization before relevant reruns and when unmounting.|Remove an event listener or close a subscription created by that effect.|Do not register a new listener every render without removing the old one.
Why does Strict Mode repeat some work? |Development checks replay certain rendering/effect behavior to surface impure logic and missing cleanup.|An effect that subscribes twice without cleanup exposes a bug the development replay makes visible.|Do not claim every production effect always runs twice.
What is an error boundary? |It provides fallback UI for supported errors in a descendant component tree. Placement decides how much UI is replaced.|A report widget can fail while the rest of the dashboard remains usable.|Ordinary event-handler and arbitrary async errors need their own handling.
What is Suspense? |Suspense shows a fallback while supported children are not ready, such as lazy code or framework-supported data loading.|A lazily loaded chart can display a loading placeholder without hiding the entire page.|Suspense does not automatically detect every fetch inside an effect.
What does lazy loading improve? |Splitting code can reduce initial download and execution, at the cost of later loading boundaries.|Load a rarely opened diagram editor on demand rather than in the first screen bundle.|Do not split so aggressively that navigation becomes a chain of waterfalls.
What is useTransition useful for? |It marks supported state updates as non-urgent so urgent interaction can remain responsive.|Keep input typing immediate while transitioning a costly results-view update.|It is not a network debounce or a way to control a text input's own urgent value.
What is useDeferredValue? |It lets a consumer use a deferred version of a value while urgent updates progress. It does not imply a fixed delay.|A costly results pane can lag behind the text currently typed into a search field.|It does not by itself prevent repeated network requests.
How do you debounce search? |Wait until input has been quiet for a chosen interval before starting the relevant work; cancel the prior scheduled callback.|Clear the old timeout when the query changes, then issue a request for the settled query.|Debouncing does not solve responses arriving out of order.
How do you handle loading, empty and error states? |Model them explicitly rather than interpreting every missing array as the same condition.|Show a skeleton while loading, no-results guidance after a successful empty response, and retry after failure.|Do not show no results before the first request finishes.
What is optimistic UI? |Display an expected change before confirmation, then reconcile with the server or roll back on failure.|A todo appears checked immediately while its save is pending, with a recoverable failure state.|Do not discard the original state needed for rollback.
How should forms validate? |Validate interactively for usability and always validate again on the server. Associate errors with fields accessibly.|A quantity field explains an invalid range and the API independently enforces it.|Client validation cannot be a security boundary.
How do you make a modal accessible? |Give it a clear name, manage focus, provide keyboard dismissal where appropriate and restore focus on close.|Opening a delete-confirmation dialog moves focus inside; closing returns it to the trigger.|A visually centered div is not automatically an accessible dialog.
What is a portal? |A portal renders children into another DOM container while keeping their React tree relationships.|A tooltip can escape a clipping ancestor by rendering near the document root.|Portal placement does not automatically implement focus trapping.
How do you choose list state ownership? |Keep item identity stable and store state at the level that must survive filtering, sorting or unmounting.|Draft text keyed by item ID can survive a paginated row unmount if its owner is above the row.|Index-based identity can associate drafts with the wrong item.
Why can callbacks cause unnecessary renders? |New function references may defeat a child memo comparison, but the practical impact depends on the child and workload.|Use a stable callback for an expensive memoized row when profiling shows a benefit.|Do not use useCallback as a blanket correctness fix.
What is derived state? |A value computed from existing props/state should often be calculated rather than independently stored.|Compute total from cart items instead of synchronizing a second total state after every change.|Duplicated state can drift out of sync.
How do you reset component state? |Change the component identity intentionally, or implement explicit reset behavior for the desired fields.|Key an editor by document ID when switching documents should start a fresh local draft.|Do not change keys accidentally on every render.
How do you test a React feature? |Focus on observable user behavior, loading/failure handling and accessibility rather than implementation internals.|Enter a query, wait for matching results and verify a retry button when the request fails.|A snapshot alone does not verify meaningful interactions.
What is an external store? |State managed outside a component needs a subscription mechanism so React can observe consistent updates.|Use an appropriate store integration such as useSyncExternalStore for external subscription state.|Reading a global variable in render does not subscribe to changes.
How do you safely render user content? |Render plain text by default; if HTML is required, apply an appropriate trusted sanitization policy.|A saved answer displays as text so an entered script tag is not executed.|Do not pass untrusted content directly to dangerouslySetInnerHTML.
What belongs in a reusable component API? |Expose a small contract that describes behavior and composition without leaking unnecessary internals.|A Button exposes disabled, type and children; a specialized payment action stays in its feature layer.|Do not create a universal component with dozens of unrelated switches.
How do you describe React in an interview? |Explain its component model, state-driven rendering and one concrete user flow, then discuss a trade-off you handled.|For a search page, describe query state, fetch lifecycle, stale responses, stable keys and empty-state handling.|Do not reduce the answer to React is fast because virtual DOM.`),
nextjs:rows(`What problem does Next.js solve? |It adds application routing, rendering and server integration conventions around React. Choose its capabilities according to hosting and product needs.|A content site can generate public pages while a dashboard loads authenticated data.|Do not describe it only as a replacement for React.
App Router versus Pages Router? |They use different routing and rendering conventions. App Router organizes routes with layouts and server/client component boundaries; Pages Router uses page-file conventions.|Identify which router a codebase uses before proposing its data-loading APIs.|Do not mix router-specific APIs without checking compatibility.
What is a route group? |A parenthesized folder organizes routes without adding that folder name to the URL.|Group marketing pages under a shared layout separate from authenticated workspace pages.|A route group is not an authorization rule.
What is a catch-all route? |A catch-all captures multiple path segments as an array; optional catch-all also supports the base path.|A documentation tree can capture guides/auth/setup as several segments.|Validate accepted paths rather than rendering arbitrary unknown topics.
What belongs in a shared layout? |UI shared across related routes, with state ownership and data boundaries chosen deliberately.|Put persistent workspace navigation around changing lesson content.|Do not assume a layout's server data refreshes on every client navigation.
What is streaming rendering? |It lets ready portions of a response arrive before all content finishes, usually through loading boundaries.|Render navigation first while a slow report section shows a fallback.|Streaming does not make a slow query itself execute faster.
What is a loading waterfall? |Dependent sequential work delays completion when some requests could have started together.|Fetch independent profile and product data concurrently instead of waiting for one unnecessarily.|Do not parallelize operations that truly depend on prior results.
How should a server component access data? |Use server-side data access with correct authorization and return only what the client needs.|Read a private order for the verified user and pass a safe DTO to a client widget.|Do not expose database models or credentials merely because code runs on the server.
Why must client props be serializable? |Values crossing the server/client boundary must use representations supported by the framework's serialization model.|Pass an order ID and display fields rather than a database connection object.|Do not assume arbitrary class instances cross unchanged.
What does server-only separation protect? |It helps prevent server modules from being bundled into browser code, but runtime authorization is still required.|Keep database credentials and privileged helpers in explicitly server-owned modules.|A build boundary is not a replacement for permissions.
How do you validate a dynamic parameter? |Treat URL values as untrusted input, check format and authorize the requested resource.|Validate an order identifier, then confirm the caller can read that order.|A syntactically valid ID does not imply ownership.
What is not-found handling? |Return a deliberate missing-resource experience and appropriate route behavior rather than a misleading successful empty page.|An unknown lesson slug should show not found instead of silently opening lesson one.|Do not reveal private resource existence when policy requires concealment.
What are search parameters good for? |They represent shareable view state such as filters, sorting and pagination, distinct from private saved records.|A materials page uses page=2 and filter=revise so back/forward restores the view.|Do not place passwords or private answer text in URLs.
How do you preserve browser navigation? |Use real route URLs and integrate history deliberately so back, forward and open-in-new-tab remain useful.|A topic link has an href even when navigation is handled without full reload.|Do not make navigation depend only on component state.
How do you choose cache invalidation scope? |Invalidate the relevant data/output after a successful mutation while preserving unaffected work.|Updating a product may invalidate its detail and catalog listing, not every user's entire workspace.|Do not globally cache a personalized response.
What is revalidation? |It refreshes cached content according to explicit policy. The mechanism and defaults depend on framework version and configuration.|Public catalog content may tolerate periodic refresh; account balances require a stronger freshness decision.|Do not assume time-based revalidation means every request receives fresh data.
What is the difference between redirect and rewrite? |A redirect tells the client to request another URL. A rewrite serves a different destination while preserving the visible requested URL.|Redirect an old canonical article URL; rewrite a public API path to a backend when hosting supports it.|Do not hide authentication requirements behind a rewrite.
What is request interception used for? |Framework request interception can handle early routing concerns, but should remain bounded and compatible with its runtime.|Apply a locale redirect or coarse access redirect, with final authorization still at data access.|Naming and runtime constraints vary by Next.js version; verify the target version.
How do you handle cookies securely? |Choose appropriate HttpOnly, Secure and SameSite attributes, validate sessions server-side and define expiry/revocation.|A cookie-backed private API verifies identity before returning notes.|HttpOnly does not prevent every CSRF or XSS consequence.
How should image optimization be planned? |Use appropriate dimensions and formats, avoid unnecessary bytes and configure trusted remote sources. Hosting mode affects optimization availability.|Reserve image space to prevent layout shift and lazy-load below-the-fold media.|Static export may need a compatible loader or unoptimized images.
Why use metadata deliberately? |Titles, descriptions and canonical information help navigation, previews and discovery when appropriate.|A public article has topic-specific metadata; a private dashboard should not expose personal details in previews.|Do not add sensitive data to share previews.
How do you improve bundle size? |Inspect dependencies and client boundaries, remove unused heavy code and load rare interactions on demand.|Keep a large editor out of the initial lesson list bundle.|Do not mark the entire application client-only without considering the cost.
How do you handle fonts and layout shift? |Reserve layout space and use a loading strategy consistent with design and performance goals.|A heading should not jump dramatically when its final font becomes available.|Do not assume a fast server removes client layout instability.
What is a serverless deployment constraint? |Request lifetime, filesystem persistence, concurrency and resource limits depend on the platform.|Store uploads in durable object storage instead of relying on a temporary function directory.|Do not assume a serverless process lives forever.
How do you handle background work? |Move durable long-running jobs to an appropriate queue/worker system rather than relying on a finished HTTP request.|A report endpoint returns a job ID and a worker persists progress.|A fire-and-forget promise may be interrupted by the hosting runtime.
How do you manage multiple environments? |Separate configuration, credentials and data for development, preview and production. Validate required settings.|A preview deployment must not accidentally write experimental data into production.|Publicly prefixed environment variables are not secret storage.
How do you investigate a route that works locally but 404s live? |Compare generated paths, hosting mode, trailing-slash behavior and deployment output.|A static topic route must be included in generated parameters and deployed as the expected artifact.|Do not fix missing static routes only with client-side navigation.
How do you design an error page? |Explain what failed safely and offer a useful retry or navigation route while preserving user drafts.|A failed notes save keeps the local draft and clearly shows that cloud sync is pending.|Do not claim Saved when only an optimistic local update happened.
What is a safe mutation response? |Return a bounded, serializable result that distinguishes validation, authorization and unexpected failure states.|A form receives field errors or the created record ID without internal database diagnostics.|Do not expose raw stack traces from server actions.
How would you explain this portal's architecture? |Describe static learning pages, client interactions, authenticated data access and separate privileged backend functions.|Questions can be authored content while user notes persist in Supabase and Gemini credentials stay in an Edge Function.|Do not imply static exported content becomes private merely because the UI has a login screen.`),
sql:rows(`What is a relational table? |A table stores rows with defined columns and constraints; relations between entities are represented through keys.|An orders table links to customers by customer_id instead of repeating every customer attribute.|Row order is not guaranteed without ORDER BY.
DELETE versus TRUNCATE versus DROP? |DELETE removes selected rows, TRUNCATE removes table contents with database-specific behavior, and DROP removes the table definition.|Use a filtered DELETE for one user's draft, not DROP TABLE.|Transaction, trigger and identity behavior vary by engine.
UNION versus UNION ALL? |UNION removes duplicate result rows; UNION ALL preserves them and avoids deduplication work.|Combine two activity streams with ALL when duplicate-looking events are still distinct.|The inputs need compatible column shapes.
EXISTS versus IN? |EXISTS asks whether a correlated result exists; IN compares against a set. Choose based on semantics and the optimizer's plan.|Find customers with any paid order using a correlated EXISTS.|NOT IN can behave unexpectedly when null values are present.
What is a correlated subquery? |It refers to values from an outer query, linking its result to the outer row.|For each customer, check whether an order with that customer's ID exists.|Do not assume every correlated query is necessarily slow; inspect its plan.
What is a CTE? |A common table expression names a query expression for use within a statement and can improve organization.|First define recent_orders, then aggregate it by customer.|Do not assume every CTE is always materialized or always optimized away.
What is a recursive CTE? |It combines a starting result with repeated recursive steps to traverse hierarchical relationships.|Walk an employee-manager hierarchy while guarding against cycles and excessive depth.|Do not allow unbounded recursion over cyclic data.
What is a window function? |It calculates across related rows without collapsing them into one grouped result row.|Show each order alongside its customer's running total.|Window ordering and frame definitions affect the result.
How do you find duplicates? |Group by the business key and retain groups with count greater than one, then decide what a valid survivor means.|GROUP BY normalized_email HAVING COUNT(*) > 1 identifies duplicate email groups.|Do not delete duplicate-looking rows without understanding business identity.
How do you find the second-highest salary? |Clarify whether second means second row or second distinct salary, then choose ranking accordingly.|DENSE_RANK by salary descending and filter rank 2 for the second distinct salary.|Ties change the question's meaning.
What is a CHECK constraint? |It enforces a predicate on inserted/updated data according to the database's semantics.|CHECK(quantity > 0) protects positive quantities; add NOT NULL if missing quantities are invalid.|A check alone may permit null under SQL's unknown semantics.
What does ON DELETE CASCADE do? |It removes dependent rows when the referenced parent is deleted, following the configured relationship.|Deleting a temporary import batch can remove its staging rows automatically.|Do not cascade-delete audit or financial records without a deliberate retention model.
What is a transaction savepoint? |A savepoint marks a position for partial rollback within a transaction where supported.|Rollback one optional operation while preserving earlier valid work in the same transaction.|It is not an independently committed nested transaction.
What is MVCC? |Multi-version concurrency control lets transactions observe appropriate versions of rows while reducing some read/write interference.|A PostgreSQL reader can see a snapshot while another transaction updates a row.|MVCC does not eliminate locks or every serialization conflict.
What is a dirty read? |It observes another transaction's uncommitted change. Isolation semantics determine whether it is possible.|A balance read should not expose a transfer that later rolls back.|Do not assume isolation-level names behave identically across engines.
What is a non-repeatable read? |Reading the same row twice in one transaction can yield different committed values under some isolation levels.|A price changes between two reads while another transaction commits.|A transaction alone does not promise a stable snapshot at every isolation level.
What is a phantom? |Repeating a predicate query can observe a changed set of matching rows due to concurrent changes.|A second query finds an additional booking that now matches the date range.|Locking one existing row may not protect a whole logical range.
When use SELECT FOR UPDATE? |Lock selected rows when a read-modify-write operation requires coordination and the database supports the chosen lock mode.|Reserve an inventory row inside a short transaction before updating its quantity.|Avoid holding database locks while waiting for a slow external API.
What is an upsert? |It inserts or updates according to a unique conflict rule using a database-supported atomic statement.|PostgreSQL INSERT ... ON CONFLICT updates a user's existing preference row.|Define the correct unique key rather than guessing conflicts in application code.
What is a partial index? |It indexes only rows matching a predicate and can help queries focused on that subset.|Index active jobs where status is pending if the workload repeatedly searches that subset.|Queries must be compatible with the index predicate.
What is a covering index? |It can provide the data needed by a query without additional table lookup when engine conditions permit.|Include selected display fields alongside lookup keys for a hot read query.|More index data adds storage and write cost.
Why can a function on a column hurt index use? |Wrapping a search column can prevent a simple index from matching the predicate unless a suitable expression index or rewrite is used.|Prefer a timestamp range over extracting a date from every row when appropriate.|Verify with the plan rather than assuming every function disables every index.
What is an execution plan? |It shows how the optimizer expects to access, join, sort and aggregate data.|Unexpected large scans or poor row estimates suggest where to investigate.|A sequential scan can be correct for a small table or large result fraction.
What is connection exhaustion? |Too many concurrent or leaked connections consume database capacity before useful work can complete.|Several autoscaled API instances each creating a large pool can exceed the database limit.|A longer connection timeout does not fix the capacity mismatch.
Why use decimal for money? |Exact decimal representations avoid many binary floating-point rounding surprises for fixed decimal amounts.|Store a currency code and an appropriately scaled numeric amount or defined minor-unit integer.|Currency rounding rules still require a business decision.
How should timestamps be handled? |Define whether a value represents an instant or local wall time and store/convert consistently.|Store event instants using an appropriate timezone-aware type and present them in the user's zone.|A calendar appointment may need its original timezone as well as an instant.
JSON versus relational columns? |JSON is useful for flexible data, while explicit columns support clear constraints and common queries.|Store optional metadata as JSON but keep frequently joined owner_id as a constrained column.|Do not move the entire schema into JSON to avoid modeling.
What is database partitioning? |It divides a logical table into physical partitions using a key/range strategy to support relevant workloads and maintenance.|Monthly event partitions can support retention and date-filtered access.|Partitioning is not automatically cross-server sharding.
What is a materialized view? |It stores a query result for later reads and must be refreshed or maintained according to its semantics.|A reporting summary trades freshness and maintenance cost for faster reads.|Do not assume it always reflects the latest transaction.
How do you migrate data safely? |Plan compatibility, backfills, validation and rollback or forward-fix before changing production data.|Add a nullable column, backfill in bounded batches, validate and then enforce stricter rules.|Do not lock a large live table unexpectedly with an unreviewed migration.`),
aws:rows(`What is the shared responsibility model? |AWS and the customer own different security responsibilities depending on the service. Customers still manage identities, data and relevant configuration.|A managed database removes some server work but not the need for safe access permissions.|Managed does not mean every security choice is handled for you.
IAM policy versus trust policy? |A permissions policy describes allowed actions/resources; a role trust policy describes who can assume the role.|A worker role trusts its compute service and has only required storage permissions.|Granting actions does not automatically grant the right to assume a role.
What is least privilege in practice? |Start from the workload's required actions, resources and conditions and avoid broad wildcard permissions.|A thumbnail worker can read its input prefix and write its output prefix.|Do not use administrator access as a permanent debugging fix.
What is a VPC? |A VPC is an isolated virtual network with subnets, routing and traffic controls.|Place application and database resources according to their required communication paths.|A VPC alone does not imply every resource is private.
Public versus private subnet? |Public routing commonly includes an internet-gateway route; private subnets lack that direct route. Actual reachability also depends on addresses and controls.|A private database should not be made publicly reachable just for app connectivity.|A subnet name is not evidence of its routing behavior.
What is a NAT gateway used for? |It enables supported outbound connectivity from private subnet resources without allowing arbitrary inbound initiation through it.|A private worker downloads an external dependency through its configured egress route.|NAT has cost and availability implications; it is not free magic internet access.
What is a VPC endpoint? |It provides a service-specific private connectivity path that can reduce the need for public internet routes depending on endpoint type.|Private workloads can reach supported AWS services through an appropriately configured endpoint.|Policies, DNS and route/security settings still matter.
EBS versus EFS versus S3? |EBS is block storage, EFS is a managed shared file system, and S3 is object storage with different access semantics.|A VM disk, shared POSIX files and uploaded images have different storage needs.|Do not treat them as interchangeable folders.
What does S3 versioning help with? |It retains object versions so some overwrites/deletions can be recovered under the configured behavior.|Restore an earlier uploaded document version after an accidental overwrite.|Versioning is not a substitute for permissions and retention planning.
What are S3 lifecycle rules? |They transition or expire objects according to configured criteria to manage storage over time.|Move old logs to an appropriate archive class and expire them after the retention period.|Archive retrieval time and charges must match the use case.
What is a presigned URL? |It grants time-bounded access to a specific signed operation under the signing identity's permissions.|A user uploads one authorized object without receiving the server's credentials.|Anyone possessing the URL may be able to use it until expiry; avoid leaking it.
CloudFront versus S3? |CloudFront distributes content through an edge network; S3 stores origin objects. They solve different parts of content delivery.|Cache public static assets near users while controlling access to the origin.|Private content requires deliberate authorization and cache-key choices.
What is Route 53 used for? |It provides DNS and related traffic-routing/health-check capabilities under configured policies.|Map an application domain to the appropriate load-balancer or CDN endpoint.|DNS changes are affected by caching; failover is not instantaneous everywhere.
What is an ALB target group? |It groups destinations and defines health-check behavior used for routing traffic.|Route API requests to healthy application instances or supported container targets.|A successful shallow health check may not prove the full user flow works.
What is an Auto Scaling cooldown/stabilization concern? |Scaling policies must avoid reacting so aggressively that capacity repeatedly oscillates.|Allow new instances time to initialize before interpreting remaining high load as another full shortage.|Scaling in too quickly can interrupt useful work.
What is a Lambda cold start? |Initialization work can add latency when a new execution environment is needed.|Large dependencies or expensive startup code can make occasional requests slower.|Do not assume every invocation starts from scratch or that warm state is durable.
What is Lambda concurrency? |It is the number of simultaneous in-flight function invocations. Limits and reservations affect capacity and downstream pressure.|A burst of invocations can exhaust database connections unless bounded.|High concurrency does not guarantee higher end-to-end throughput.
Why use an RDS proxy or connection strategy? |It helps manage database connections for suitable workloads, especially bursty clients, but has its own constraints.|Many short-lived function invocations need controlled database connection usage.|It does not fix inefficient queries or every transaction bottleneck.
RDS Multi-AZ versus read replicas? |Multi-AZ targets availability; replicas can offload reads. Capabilities differ between classic Multi-AZ instances and Multi-AZ clusters.|A classic standby does not serve reads; some cluster reader instances do. Async read replicas can lag.|Do not state all Multi-AZ secondaries are readable or all are unreadable.
What are RPO and RTO? |RPO describes tolerable data loss measured in time; RTO describes tolerable restoration time.|A reporting service may tolerate a longer recovery than payment processing.|A backup existing does not prove the required recovery time is achievable.
Why test restores? |Recovery depends on usable backups, credentials, procedures and application compatibility, not just successful backup jobs.|Restore into an isolated environment and validate representative data and service behavior.|Do not discover missing recovery permissions during an outage.
What is DynamoDB partition-key design? |The key should distribute workload and support planned access patterns; concentrated traffic can create hot keys.|Using one shared partition key for all active events can concentrate work.|Do not design keys without knowing read/write patterns.
What is a conditional write? |It applies a change only when a defined condition holds, supporting concurrency control and idempotent state transitions.|Create a job only if its request key does not already exist.|Read-then-write without a condition can race.
SQS visibility timeout? |A received message becomes temporarily hidden while a consumer processes it; lack of successful deletion can permit redelivery.|Set or extend visibility to suit a bounded processing duration.|It is not a guarantee that a message can never be delivered twice.
What is a dead-letter queue? |It isolates messages that repeatedly fail so they can be investigated and deliberately redriven.|A malformed order event is inspected rather than retried forever.|A DLQ without alarms and ownership only hides failures.
Secrets Manager versus hardcoded secrets? |A managed secret store supports controlled access and rotation workflows; applications must still retrieve and use secrets safely.|A service role retrieves its database secret at runtime under scoped permission.|Do not copy the retrieved secret into logs.
KMS encryption versus authorization? |Encryption protects data under keys; authorization determines who may use data and keys. Both are needed.|A storage object can be encrypted yet accessible to an overly broad identity.|Encrypted does not mean nobody can read it.
CloudWatch versus CloudTrail? |CloudWatch supports operational monitoring; CloudTrail records relevant API/account activity for audit according to configuration.|Investigate latency in metrics/traces and permission-changing API activity in audit records.|Do not assume either contains every signal without configuration.
What is infrastructure as code? |Infrastructure definitions are versioned and reviewed so changes are reproducible and differences are inspectable.|Review a proposed security-group change before applying it through a deployment workflow.|State and credentials used by tooling also need protection.
How do you explain an AWS project without exaggerating? |Name the services you actually used, their responsibilities, one failure consideration and your specific contribution.|I deployed an API behind a load balancer and configured logs; I have studied multi-region failover but not operated it.|Do not list every AWS service as production experience.`),
'system-design':rows(`What are functional requirements? |They describe operations the system must support, separate from quality goals.|A chat service sends messages, lists history and indicates delivery state.|Do not substitute scale numbers for user behavior.
What are non-functional requirements? |They describe constraints such as latency, durability, availability, security and maintainability.|A checkout may need stronger correctness guarantees than a view counter.|Do not demand maximum guarantees everywhere without cost trade-offs.
How do you estimate traffic? |State assumptions, estimate average load and account for peak/burst behavior. Use estimates to identify likely bottlenecks.|One million daily actions is roughly twelve per second on average, but peaks may be much higher.|Do not confuse average traffic with required peak capacity.
Latency versus throughput? |Latency is time per operation; throughput is completed work per unit time. Improving one may affect the other.|Batching can improve throughput while making an individual item wait longer.|High throughput does not imply low tail latency.
Why discuss p95 or p99? |Tail percentiles show slow experiences hidden by the average and matter when operations compose.|A page calling several services may often wait for the slowest dependency.|Do not optimize only the average response time.
Vertical versus horizontal scaling? |Vertical scaling increases one machine's resources; horizontal scaling adds machines and coordination needs.|Add API instances behind a load balancer, but move shared session state out of local memory.|More machines do not automatically remove a shared storage bottleneck.
What is a stateless service? |It does not depend on request-specific durable state held only in one instance's memory.|Any API instance can serve the next request using shared authoritative storage.|Stateless does not mean the entire application has no state.
What does a reverse proxy do? |It receives requests on behalf of servers and can route, terminate TLS and apply configured controls.|A proxy forwards /api traffic to backend instances while serving another origin for assets.|Do not confuse it with a client's forward proxy.
What is consistent hashing useful for? |It can reduce key reassignment when nodes change in a distributed partitioning scheme.|A cache cluster assigns keys across virtual nodes and redistributes part of the keyspace after a change.|It does not eliminate hotspots or all rebalancing work.
What is a hot partition? |One partition receives disproportionate traffic or data, limiting the whole system.|A celebrity account may overload a naive user-keyed feed partition.|Uniform record counts do not guarantee uniform traffic.
Strong versus eventual consistency? |Strong guarantees constrain what reads can observe; eventual consistency permits temporary divergence that converges under stated assumptions.|A product recommendation can tolerate lag more easily than a funds check.|Eventually does not specify a bounded delay by itself.
What is read-your-writes consistency? |A client sees its own acknowledged changes in subsequent reads under the promised scope.|After editing a profile, route the user to a source that reflects the write rather than a lagging replica.|Global linearizability is stronger than this session-oriented guarantee.
What is the transactional outbox? |Write business data and an outgoing event record in one local transaction; a relay publishes the event later.|An order and order-created event are committed together, avoiding an unrecorded event after a crash.|The relay can publish duplicates, so consumers still need idempotency.
What is a saga? |A multi-step workflow coordinates local transactions and compensating actions instead of one cross-service database transaction.|Reserve stock, request payment, then release stock if payment fails according to policy.|A compensation is a business action, not guaranteed time reversal.
What is a circuit breaker? |It temporarily stops repeated calls to an unhealthy dependency and probes recovery under a policy.|A failing recommendation service is bypassed while checkout continues without recommendations.|It is not a substitute for timeouts and capacity limits.
What is a bulkhead? |It isolates resource pools so one failing workload does not consume all shared capacity.|Separate report workers from latency-sensitive purchase processing.|Isolation boundaries still need correctly chosen limits.
Why use exponential backoff and jitter? |They spread retries over time to avoid synchronized pressure after a shared failure.|Many clients wait different bounded delays before retrying a temporary outage.|Do not retry invalid requests or unsafe writes without idempotency.
What is graceful degradation? |Preserve essential behavior while reducing optional functionality under failure or load.|Show a product page without personalized recommendations when that dependency is down.|Do not silently degrade correctness of critical financial operations.
How do you design a rate limiter? |Clarify scope, fairness, bursts and distributed accuracy, then choose an algorithm and shared-state approach.|A token bucket allows controlled bursts while limiting sustained usage.|Per-instance counters multiply a supposed global limit across servers.
How do you design file uploads? |Authorize, bound size/type, store objects durably and process asynchronously when expensive.|The API creates a scoped upload target; a worker scans/processes it and persists status.|Do not trust the file extension as proof of safe content.
How do you design a notification service? |Separate intent, channel delivery, retry state and user preferences. Track delivery semantics per channel.|Store a notification job, deduplicate its business event and retry transient email-provider failures.|Provider acceptance does not prove the user read the message.
How do you design a feed? |Clarify freshness, fan-out scale and ranking before choosing push, pull or a hybrid.|Precompute feeds for ordinary accounts while handling high-fanout publishers differently.|Do not assume one write fan-out strategy fits every account.
How do you design search? |Separate source-of-truth writes from searchable indexes and define indexing lag, relevance and access filtering.|An event updates a document index; search results enforce the user's visibility rules.|A search index is not automatically transactionally current.
How do you design a booking system? |Define the reservable resource and enforce exclusivity with atomic storage rules, locks or constraints.|A seat reservation has an expiry and a transaction that prevents two confirmed owners.|A green button in the browser cannot prevent a booking race.
What is LLD encapsulation in practice? |Objects or modules expose valid operations while protecting invariants and hiding representation.|A Reservation.confirm operation rejects an expired hold instead of allowing arbitrary status assignment.|Private fields alone do not create a useful domain model.
What is the strategy pattern? |It supplies interchangeable behavior behind a contract when an algorithm varies independently.|Checkout uses one of several pricing policies without hardcoding each policy into the controller.|Do not add a pattern when a simple function is sufficient.
What is the observer pattern? |Subscribers are notified about changes through an event relationship.|A local model notifies UI observers when its state changes.|An in-process observer is not a durable distributed event bus.
When choose a modular monolith? |It preserves clear module boundaries within one deployment and can be simpler for a small team.|Separate orders and billing internally before paying the operational cost of separate services.|Microservices are not a prerequisite for good architecture.
How do you choose a partition key? |Choose from access patterns, distribution, growth and cross-partition operation requirements.|Tenant ID is convenient, but large tenants may need additional partitioning.|Do not ignore skew and cross-tenant reporting.
How do you conclude a design interview? |Summarize the normal flow, main trade-off, biggest bottleneck and next improvement under changed requirements.|The first version uses one relational store; if reads dominate, add measured caching before sharding.|Do not add new components at the end without explaining their purpose.`),
dsa:rows(`What is Big O? |It describes growth of work or space as input size increases, abstracting constants under a stated model.|A full scan grows linearly; nested scans over all pairs usually grow quadratically.|Do not label complexity only by counting written loops.
What is auxiliary space? |It is extra working memory beyond the input, with output-space conventions stated separately.|A hash-based duplicate check stores up to n distinct items.|Recursion call stacks also consume space.
Array versus linked list? |Arrays support direct indexing; linked lists follow references and can relink known nodes cheaply.|Accessing the tenth array item is direct; a singly linked list must traverse from its known start.|Finding the insertion point can dominate linked-list insertion cost.
What is a linked-list node? |It stores a value and reference to the next node, with optional extra links depending on the structure.|A -> B -> C -> null is a simple singly linked chain.|An array index and a node reference are not interchangeable.
How do you reverse a linked list? |Track previous, current and next; redirect the current link only after saving the next node.|For A -> B -> null, save B before pointing A to null, then continue.|Losing the next pointer loses access to the rest of the list.
How do you detect a linked-list cycle? |Use slow and fast pointers; if they meet before reaching null, a cycle exists.|Slow advances one link and fast advances two within the same chain.|Check fast and its next link before advancing twice.
Why use a dummy node? |It simplifies operations that may change the head by giving the head a stable predecessor.|Remove matching nodes after a sentinel instead of special-casing each head removal.|Return dummy.next rather than the dummy node.
What is a queue? |A queue processes items first-in-first-out and fits level-order or arrival-order work.|BFS enqueues discovered neighbors and processes earlier discoveries first.|Repeated array shift can be costly; an index or deque avoids it.
What is a deque? |It supports operations at both ends and is useful when candidates enter/leave from either side.|A monotonic deque keeps useful candidates for sliding-window maximum.|Track indices so expired candidates can be removed.
What is a heap? |A heap maintains a priority property, supporting efficient insertion and extraction of an extreme element.|A min-heap exposes the smallest pending job priority without fully sorting all jobs.|A heap is not a fully sorted array.
How do you solve top K? |Choose sorting, selection or a bounded heap based on input size and whether streaming matters.|A size-k min-heap retains the largest k values in O(n log k) time.|Clarify how ties and output ordering should be handled.
What is a binary search tree? |It organizes values by an ordering rule across left/right subtrees. Balance determines operation depth.|Lookup descends left or right rather than exploring both subtrees.|An unbalanced BST can degrade to linear time.
Preorder, inorder and postorder? |Preorder visits node before children, inorder between children, and postorder after children.|Inorder yields sorted order for a BST that follows the corresponding duplicate policy.|Traversal order names do not imply breadth-first search.
How do you traverse a tree by levels? |Use a queue and process the current queue length as one level.|Start with root, emit its value, then enqueue children for the next level.|Handle an empty root before enqueueing it.
How do you find tree height? |Combine child heights recursively or track levels iteratively, defining whether height counts edges or nodes.|For node-count height, an empty tree has zero and a leaf has one.|Do not mix edge-count and node-count definitions.
What is an adjacency list? |It stores each graph vertex's neighbors and is efficient for many sparse-graph traversals.|Map each city ID to reachable neighboring city IDs.|Directed and undirected edges require different insertion rules.
What is a topological ordering? |It orders a directed acyclic graph so prerequisites precede dependent nodes.|Use indegrees and a queue to schedule courses whose prerequisites are satisfied.|If not all vertices are processed, a directed cycle may prevent an ordering.
When use Dijkstra? |Use it for shortest paths with non-negative edge weights, usually with a priority queue.|Find a cheapest route when every edge cost is zero or positive.|Ordinary Dijkstra is not valid with arbitrary negative edges.
What is union-find? |It tracks disjoint sets with find and union operations, often using path compression and rank/size heuristics.|Detect whether adding an undirected edge connects vertices already in the same component.|It does not directly maintain arbitrary shortest paths.
When use a trie? |It organizes strings by prefixes, supporting prefix-oriented lookup and traversal.|An autocomplete dictionary follows character edges for the typed prefix.|Memory cost can be high relative to a simple hash set.
What is XOR useful for? |XOR cancels equal bit patterns and combines differing bits; under exact pairing assumptions it can reveal an unpaired value.|For values where every number appears twice except one, XOR of all values returns the singleton.|This does not solve arbitrary frequency patterns.
Bitwise versus logical operators? |Bitwise operators act on bit representations; logical operators operate on truthiness/boolean logic with language-specific behavior.|A bit mask checks whether a feature bit is set; a logical AND guards a condition.|JavaScript number bitwise operations use 32-bit integers, which affects large values.
What is a frequency map? |It counts occurrences so the algorithm can compare multiplicities rather than only membership.|Anagram checking increments counts for one string and decrements for the other.|A Set loses repeated-character information.
How do you group anagrams? |Choose a canonical representation shared by words with the same character counts.|Sorting letters gives eat and tea the same key, with O(k log k) work per word.|Define normalization and character set assumptions.
How do you merge intervals? |Sort by start, then extend the current interval when the next overlaps; otherwise emit and start a new one.|[1,3] and [2,4] become [1,4]. Sorting costs O(n log n).|Clarify whether touching boundaries count as overlap.
What is a greedy algorithm? |It chooses a locally best action with a proof that the choice preserves an optimal solution.|Choosing the earliest finishing compatible interval maximizes the number of non-overlapping intervals.|A plausible local rule is not enough without a correctness argument.
How do you use backtracking safely? |Choose, recurse and undo state; prune only branches proven unable to produce valid results.|Generate subsets by including or excluding each position and copying completed outputs.|Do not keep references to a mutable working array as final results.
Memoization versus tabulation? |Memoization caches recursive subproblems on demand; tabulation fills states in a valid dependency order.|Fibonacci can use either, but two previous values suffice when only the final number is needed.|Recursion overhead and stack depth still matter with memoization.
What is Kadane's algorithm? |Track the best subarray ending at the current position and the best overall, choosing whether to extend or restart.|For [-2,3,-1,2], the best non-empty sum is 4 from [3,-1,2].|Initialize carefully so all-negative input does not incorrectly return zero.
How do you debug an off-by-one error? |Write the interval convention and trace minimal boundary inputs before changing inequalities.|For a half-open range [lo,hi), an empty range has lo == hi.|Do not change several loop bounds simultaneously without restoring the invariant.`),
mern:rows(`What is MERN? |MERN combines MongoDB, Express, React and Node.js for a full-stack application. Each part has a different responsibility.|React renders the UI, Express routes API requests on Node, and MongoDB stores application data.|Do not describe MongoDB as the backend server itself.
How do you introduce your MERN experience? |State your actual experience, feature ownership, stack and one result, then connect it to the role.|I built [real feature] with React and an API; I owned [actual part] and improved [verified outcome].|Replace placeholders honestly; do not invent impact numbers.
How do you explain project architecture? |Start with the user flow and explain UI, API, business logic, storage, authentication and deployment.|A notes form sends a validated request; the API verifies the owner, persists the note and returns its ID.|Do not begin by listing every installed package.
How does a React request reach MongoDB? |The client calls a backend endpoint; the server validates and authorizes before querying MongoDB and serializing a safe response.|GET /orders returns only the signed-in user's permitted order fields.|Do not connect a browser directly with privileged database credentials.
Why separate routes, services and data access? |Different concerns become easier to reason about and change without tying every rule to HTTP details.|An order route translates input while a service decides whether an order can be cancelled.|Do not create empty layers that add no useful boundary.
What is a MongoDB document? |It stores structured BSON data with fields, nested objects and arrays rather than a fixed relational row shape.|A profile can contain a bounded embedded address object.|Flexible schema does not mean validation is unnecessary.
Embed or reference related data? |Choose based on access patterns, growth and consistency. Embedding suits bounded related data read together; references suit independent or growing relationships.|Embed an order's purchase-time address snapshot; reference an independently managed customer record.|Avoid arrays that grow without a practical bound.
What is Mongoose? |It is an object-modeling library that can add schemas, validation and query conveniences on top of MongoDB.|A User schema describes expected fields while the database remains responsible for configured database constraints.|Do not confuse ODM validation with full authorization.
Mongoose validation versus a unique index? |Validation checks values through the library's path; a database unique index arbitrates duplicates under concurrent writes.|Two signup requests can race, so catch the duplicate-key result even after a pre-check.|A uniqueness pre-check alone is not safe.
What is populate? |It loads referenced related data through ODM behavior, which can add query cost and payload size.|Load an author's display name for an article when that field is needed.|Do not populate every relationship automatically.
What is an aggregation pipeline? |It processes documents through stages such as filtering, grouping and projection for a query/report.|Filter paid orders, group by customer and sum amounts for a spending report.|Stage order affects semantics and performance.
Why create MongoDB indexes? |Indexes support chosen lookup/order patterns at a write/storage cost. Design them from real queries.|An ownerId plus createdAt index can support a user's chronological notes list.|Do not assume the _id index optimizes every filter.
How do you inspect a Mongo query? |Use explain information and workload measurements to examine examined documents, index use and result size.|A query returning ten rows but scanning a million documents deserves investigation.|Small result size does not imply cheap execution.
What is atomic in MongoDB? |A single-document write is atomic; multi-document business operations may need transactions or a redesigned data model.|Update related fields of one order together; coordinate inventory and payment records deliberately.|Do not assume several separate updates form one transaction.
How do you handle identifiers? |Validate format, parse safely and authorize the requested resource independently of the identifier's shape.|Reject malformed ObjectId input and still check that a valid order belongs to the caller.|An unguessable ID is not a permission system.
How do you implement signup? |Validate input, normalize where appropriate, hash passwords safely and enforce unique identity constraints.|Store a password hash, not the raw password; return safe errors without exposing internal data.|Do not log submitted passwords.
How do you implement login? |Verify credentials securely, issue/manage a session and define expiry, refresh and revocation behavior.|A successful login creates a session whose identity is validated on private requests.|Do not treat a user ID returned by the client as proof of login.
How do you implement logout? |Clear client credentials and invalidate server-side session/refresh state according to the design.|Removing a cookie plus revoking the corresponding session prevents its intended reuse.|Deleting a UI variable may leave other valid tokens active.
How do you protect roles and ownership? |Authorize on the server for the operation and specific resource, using trusted identity and policy data.|An admin endpoint checks an admin permission; a note endpoint checks the note's owner.|Do not accept isAdmin directly from an update DTO.
How do you prevent NoSQL injection? |Validate input types, allow only intended query fields/operators and construct queries explicitly.|An email lookup accepts a string, not an arbitrary object containing query operators.|Do not spread untrusted request objects into database filters.
How do you paginate Mongo results? |Use bounded pages with stable ordering; cursor/keyset designs fit large sequential feeds.|Continue after createdAt plus _id rather than using an ambiguous timestamp alone.|Large skip values can become expensive.
How do you implement search? |Clarify prefix, exact, text or relevance requirements and choose an indexed query or search system accordingly.|A simple exact-email lookup differs from multilingual ranked document search.|Do not use an unbounded user regex over all documents.
How do you manage API errors in React? |Keep loading, success and failure states distinct and preserve unsaved input when possible.|A failed note submission shows retry without clearing the user's text.|Do not report success before the server confirms persistence.
How do you handle duplicate form submission? |Disable repeated UI actions for usability and implement server idempotency where duplicate effects matter.|An order request includes a persisted idempotency key so a retry after timeout does not create another order.|A disabled button cannot prevent all duplicate HTTP requests.
How do you handle uploads in MERN? |Authorize an upload, limit and validate it, store the object appropriately and save metadata/ownership in the database.|Store an image in object storage and its key on the note document.|Do not accept arbitrary filesystem paths from a client.
How do you use WebSockets in a MERN app? |Authenticate connections, authorize channels and define reconnect, missed-message and delivery behavior.|A chat UI reloads messages after the last acknowledged message ID when reconnecting.|Joining a room name is not proof of permission.
How do you cache a MERN API? |Cache measured expensive reads with clear ownership boundaries, expiration and invalidation rules.|A shared catalog cache differs from a private user's note cache key.|Do not leak personalized data through a shared cache.
How do you deploy frontend and backend separately? |Configure API origins, HTTPS, authentication, environment values and observable deployment health across both services.|The static React site calls a versioned HTTPS API whose allowed origins match the deployment.|Do not hardcode localhost in a production bundle.
What is CORS in this architecture? |It controls browser cross-origin access according to the server's response policy, not who can call the API in general.|Allow a known frontend origin and configure credential behavior deliberately.|A CORS error is not solved safely by enabling every origin and credential combination.
How do you manage secrets? |Keep database and provider credentials on the server with controlled access and rotation practices.|The backend retrieves an AI key from environment secrets while React calls only the authorized backend.|Frontend environment variables shipped in a bundle are visible.
How do you test a full user flow? |Verify UI behavior, API contract, authorization and persistence together at appropriate boundaries.|Create a note, reload it, edit it and confirm another account cannot access it.|A successful happy-path click does not verify isolation.
How do you investigate a slow MERN page? |Measure frontend rendering, network payloads, API timing and database plans to find the actual bottleneck.|A slow list may be over-fetching documents rather than suffering from React rendering cost.|Do not add memoization before checking the network and query.
How do you handle schema evolution? |Plan backward-compatible reads/writes, migration of old documents and rollout sequencing.|Add an optional preference field with a safe default, backfill if needed, then enforce stricter rules later.|Old documents do not automatically change when a schema definition changes.
How do you represent money? |Use a deliberately exact representation and define currency/rounding rules across frontend and backend.|An integer minor-unit amount with a currency code can avoid floating-point arithmetic for supported currencies.|Not every currency uses two decimal places.
How do you handle timezones? |Separate stored instants from local calendar meaning and convert intentionally at display boundaries.|A completion timestamp is an instant; a course start date may be a local calendar date.|Do not parse every date-only value as a UTC instant accidentally.
How do you explain a production bug? |Use situation, diagnosis, your action, verification and prevention, with evidence from the actual incident.|A generic example is stale search results fixed by rejecting outdated responses; use it only if it matches your experience.|Do not claim a hypothetical story happened to you.
How do you explain a technical disagreement? |State the shared goal, compare evidence and trade-offs, propose a small experiment and describe the decision respectfully.|Compare embedding versus references using growth and query patterns instead of personal preference.|Do not blame teammates or present opinion as measurement.
How do you answer when .NET is new to you? |Be honest about your current stack and connect transferable concepts such as HTTP, authentication, transactions and testing.|I have built APIs in Node; I am learning ASP.NET Core DI and middleware and can explain the same request lifecycle.|Do not pretend equivalent concepts mean identical framework behavior.
What would you improve in your project? |Choose one measured or clearly reasoned limitation, describe a bounded improvement and explain validation.|I would add request tracing to locate latency before deciding whether caching is needed.|Do not propose a total rewrite as the default improvement.
How do you end a MERN interview answer? |Summarize your choice and one trade-off, then invite a focused follow-up rather than continuing indefinitely.|I chose references because children grow independently; the trade-off is additional lookup work. I can explain the query next.|Do not memorize a long speech that ignores the actual question.`),
};
