const NAME='quest90-learning';
import type {LocalCheckpoint} from './recovery';
async function db(){return new Promise<IDBDatabase>((resolve,reject)=>{const r=indexedDB.open(NAME,1);r.onupgradeneeded=()=>{r.result.createObjectStore('records');r.result.createObjectStore('images',{keyPath:'id'})};r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error);});}
export async function localGet<T>(key:string):Promise<T|undefined>{const d=await db();return new Promise((resolve,reject)=>{const tx=d.transaction('records','readonly'),r=tx.objectStore('records').get(key);r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error);tx.oncomplete=()=>d.close()})}
export async function localSet(key:string,value:unknown){const d=await db();return new Promise<void>((resolve,reject)=>{const tx=d.transaction('records','readwrite');tx.objectStore('records').put(value,key);tx.oncomplete=()=>{d.close();resolve()};tx.onerror=()=>{d.close();reject(tx.error)};tx.onabort=()=>reject(tx.error)})}
// Both the newest draft and periodic previous copies are committed atomically.
export async function saveCheckpoint(key:string,value:LocalCheckpoint,forceArchive=false){const d=await db();return new Promise<void>((resolve,reject)=>{const tx=d.transaction('records','readwrite'),store=tx.objectStore('records');const get=store.get(key);get.onsuccess=()=>{const old=get.result as LocalCheckpoint|undefined;const history=store.get(key+':history');history.onsuccess=()=>{const copies=(history.result||[]) as LocalCheckpoint[];if(old&&(forceArchive||!copies.length||Date.parse(old.savedAt)-Date.parse(copies[0].savedAt)>60000)&&JSON.stringify(old.progress)!==JSON.stringify(value.progress)){store.put([old,...copies].slice(0,12),key+':history');}store.put(value,key);};};tx.oncomplete=()=>{d.close();resolve()};tx.onerror=()=>{d.close();reject(tx.error)};tx.onabort=()=>{d.close();reject(tx.error)}})}
export type Screenshot={id:string;context_id:string;user_id:string;name:string;data_url:string;created_at:string};
export async function localImages(context?:string):Promise<Screenshot[]>{const d=await db();return new Promise((resolve,reject)=>{const tx=d.transaction('images','readonly'),r=tx.objectStore('images').getAll();r.onsuccess=()=>resolve((r.result as Screenshot[]).filter(x=>!context||x.context_id===context));r.onerror=()=>reject(r.error);tx.oncomplete=()=>d.close()})}
export async function localImageSave(img:Screenshot){const d=await db();return new Promise<void>((resolve,reject)=>{const tx=d.transaction('images','readwrite');tx.objectStore('images').put(img);tx.oncomplete=()=>{d.close();resolve()};tx.onerror=()=>reject(tx.error)})}
export async function localImageDelete(id:string){const d=await db();return new Promise<void>((resolve,reject)=>{const tx=d.transaction('images','readwrite');tx.objectStore('images').delete(id);tx.oncomplete=()=>{d.close();resolve()};tx.onerror=()=>reject(tx.error)})}
