import type {ReadingLesson} from './commute-guides';
export const patternNames=['Map','Set','Two pointers','Sliding window','Stack','Breadth-first search','Binary search','Prefix sums'] as const;
export type Pattern=typeof patternNames[number];
export type PatternCase={id:string;title:string;prompt:string;input:string;output:string;pattern:Pattern;cue:string;why:string;trap:string;flow:string[];cost:string;transfer:string};
const c=(id:string,title:string,pattern:Pattern,prompt:string,input:string,output:string,cue:string,why:string,trap:string,flow:string[],cost:string,transfer:string):PatternCase=>({id,title,pattern,prompt,input,output,cue,why,trap,flow,cost,transfer});
export const patternCases:PatternCase[]=[
 c('pair-indices','Find the two positions','Map','Return two distinct indices adding to a target in an unsorted array. Aim for expected linear time.','[2,7,11,15], target=9','[0,1]','You need an earlier value AND its index.','Remember value → index, look for target-current before storing the current value.','Set alone forgets original indices. Sorted two pointers would need index bookkeeping.',['i=0, value=2: need 7','7 absent → store 2 → 0','i=1, value=7: need 2','get(2)=0 → return [0,1]'],'Expected O(n) time, O(n) extra space','If the array were already sorted and only values were needed, consider two pointers.'),
 c('frequencies','Count every vote','Map','Count occurrences of every string while scanning once.','["js","py","js"]','js → 2; py → 1','The answer needs a count for each key.','Initialize a missing count to zero, then increment it.','Set can tell you distinct languages, but loses how many votes each received.',['Read js → count 1','Read py → count 1','Read js → count 2','Return both key/count entries'],'Expected O(n) time, O(k) space for k keys','If you only need the number of different languages, a Set is enough.'),
 c('earliest-unique','Find a value used once','Map','Return the first value appearing exactly once, preserving original order.','[4,2,4,3,2]','3','Both frequency and original order matter.','Count values first, then scan the original input for count 1.','Returning the first new value during the initial scan ignores later duplicates.',['Counts after scan: 4→2, 2→2, 3→1','Check 4: count 2','Check 2: count 2','Check 3: count 1 → return 3'],'Expected O(n) time, O(k) space','If order no longer matters, you can search the frequency entries directly.'),
 c('repeated-id','Have we seen this ID?','Set','Detect whether any numeric ID repeats. Only a Boolean is needed.','[8,3,8]','true','Membership is enough; no count or index is requested.','Check has(id), then add(id) if absent.','Adding before checking would report every value as a repeat.',['Read 8: absent → {8}','Read 3: absent → {8,3}','Read 8: already present','Return true'],'Expected O(n) time, O(k) space','For repeated object IDs, store record.id, not the whole object.'),
 c('distinct-tags','Collect unique tags','Set','Keep each exact tag string once, in first appearance order.','["react","sql","react"]','["react","sql"]','Duplicates should collapse into one membership entry.','Set iteration follows insertion order for these strings.','Case-sensitive tags stay different unless you normalize them first.',['Add react → {react}','Add sql → {react,sql}','Add react → unchanged','Convert Set to array'],'Expected O(n) time, O(k) output/storage','If you need a count for each tag, use a Map.'),
 c('blocked-values','Remove banned values','Set','Filter banned numbers from a list, keeping remaining duplicates and order.','values=[1,2,1,3], banned=[2]','[1,1,3]','Many membership checks against the same banned list.','Build a Set of banned values, then append every allowed occurrence.','Do not put the output into a Set: both allowed 1s must remain.',['Banned lookup = {2}','1 allowed → [1]','2 rejected; next 1 allowed → [1,1]','3 allowed → [1,1,3]'],'Expected O(n+b) time, O(b) lookup plus output','One banned value only? A simple equality check may be sufficient.'),
 c('sorted-pair','Find a pair in sorted values','Two pointers','Find two values summing to 10 in an ascending array using constant extra space.','[1,3,4,7,9]','[1,9]','Sorted order tells you which endpoint to move.','If sum is too small move left forward; if too large move right backward.','This decision rule fails on an unsorted array.',['left=0 (1), right=4 (9)','sum=10','Target reached','Return [1,9]'],'O(n) time, O(1) extra space','If unsorted and original indices matter, consider a Map.'),
 c('palindrome','Read from both ends','Two pointers','Check whether an exact string is a palindrome without constructing its reverse.','"level"','true','Symmetric positions must match.','Compare ends, move inward, stop on mismatch.','If punctuation or case should be ignored, that must be part of the contract.',['l matches l','e matches e','Pointers meet at v','Return true'],'O(n) time, O(1) extra space','For a normalized sentence, skip nonletters deliberately rather than assuming exact comparison.'),
 c('merge-heads','Merge two sorted lists','Two pointers','Merge ascending arrays, preserving duplicates, without sorting the combined input.','a=[1,4], b=[2,4]','[1,2,4,4]','Each input exposes its smallest remaining value at the head.','Advance only the pointer whose value you append.','A pair of unsorted inputs does not satisfy this invariant.',['Take a[0]=1','Take b[0]=2','Take a[1]=4','Append remaining b[1]=4'],'O(n+m) time, O(n+m) output space','For linked lists the same idea advances node references instead of array indices.'),
 c('fixed-sum','Best run of three','Sliding window','Find the maximum sum of exactly three consecutive values.','[2,1,5,1,3,2], k=3','9','Fixed-length consecutive windows differ by one outgoing and one incoming value.','Keep the current sum and update it by subtracting the outgoing value and adding the incoming one.','This is a contiguous window, not any three values.',['First window [2,1,5] → 8','Remove 2, add 1 → 7','Remove 1, add 3 → 9','Remove 5, add 2 → 6; best 9'],'O(n) time, O(1) extra space','Negative values are fine for a fixed-size sum window.'),
 c('unique-window','Longest substring without repeats','Sliding window','Find the length of the longest contiguous substring with no repeated character.','"abba"','2','Expand a contiguous interval, shrinking it until uniqueness holds.','Use a Set or counts to maintain membership inside a sliding window.','Patterns can combine: the Set supports the window rather than replacing it.',['Add a,b → length 2','Next b repeats; remove a then old b','Window b; append a → ba','Best length remains 2'],'Expected O(n) time, O(k) space','If the problem asks for a subsequence instead, contiguity-based window reasoning no longer applies.'),
 c('positive-target','Shortest window reaching a sum','Sliding window','For strictly positive integers, find the shortest contiguous interval with sum at least 7.','[2,3,1,2,4,3]','2','Positivity makes expanding increase and shrinking decrease the sum.','Expand until the target is reached, then shrink while valid to improve the length.','Arbitrary negative values break this monotonic sum argument.',['[2,3,1,2] sums to 8, length 4','Shrink/expand → [3,1,2,4], then [1,2,4]','Append 3 and shrink → [4,3]','Sum 7, length 2'],'O(n) time, O(1) extra space','With negative values, investigate prefix sums and other structures instead.'),
 c('brackets','Match nested brackets','Stack','Validate correctly nested (), [] and {} pairs.','"([])"','true','The latest unmatched opening bracket must close first.','Push openings; each closing bracket must match the top.','Counting equal numbers of opens and closes does not prove correct nesting.',['Push (','Push [','Read ] → pop [','Read ) → pop (; stack empty'],'O(n) time, O(n) space','For "([)]", counts match but the stack detects a nesting error.'),
 c('undo','Undo the latest edit','Stack','Support undoing edits in reverse order of application.','type A; type B; undo','A','Last action in is the first action out.','Store previous states or reversible commands in a stack.','A FIFO queue would undo the oldest action first.',['Start ""','Type A; remember ""','Type B; remember "A"','Undo restores "A"'],'O(1) push/pop; full snapshot copying adds state-size costs','Redo generally uses a second stack; new edits clear its obsolete branch.'),
 c('next-warmer','Find the next warmer day','Stack','For each temperature, count days until a strictly warmer temperature.','[70,72,71,75]','[1,2,1,0]','Unresolved earlier indices wait for a warmer value.','Keep a monotonic stack of unresolved indices; pop colder entries when a warmer day arrives.','Equal temperature does not satisfy strictly warmer.',['Day 0: push 70','72 resolves 70: wait 1','71 waits under 72','75 resolves 71:1 and 72:2'],'O(n) time, O(n) space','A repeated scan to the right is a simpler but quadratic baseline.'),
 c('fewest-hops','Fewest links between services','Breadth-first search','Find the minimum number of edges from A to D in an unweighted graph.','A→B,C; B→D; C→E; E→D','2','All edges have equal cost; layers correspond to hop counts.','Explore a FIFO frontier, marking nodes visited when enqueued.','DFS finds a path but not necessarily the fewest hops.',['Layer 0: A','Layer 1: B,C','Expand B → D at layer 2','Return 2 edges'],'O(V+E) time, O(V) space','For unequal positive edge weights, consider Dijkstra instead.'),
 c('tree-levels','Read a tree level by level','Breadth-first search','Return binary-tree values grouped by depth.','root 1; children 2,3; child of 2 is 4','[[1],[2,3],[4]]','The required output is organized by levels.','Process the current queue length as one level, appending children for the next.','Do not let newly enqueued children extend the current level.',['Queue [1] → output [1]','Queue [2,3] → output [2,3]','Queue [4] → output [4]','Queue empty → done'],'O(n) time, O(w) frontier plus output','Recursive traversal with a depth parameter is another valid approach; BFS makes layers explicit.'),
 c('nearest-exit','Shortest grid escape','Breadth-first search','Find the fewest four-direction moves from S to E. # cells are blocked; moves have equal cost.','S . #\n# . E','3','Cells are graph nodes, and each move costs one.','Explore reachable cells by distance layers with a visited set.','Diagonal movement is not allowed by this contract.',['Distance 0: (0,0)','Distance 1: (0,1)','Distance 2: (1,1)','Distance 3: exit (1,2)'],'O(rows×cols) time and space','A weighted terrain problem needs a different shortest-path strategy.'),
 c('sorted-target','Search a sorted array','Binary search','Find target 7 in an ascending array in logarithmic time.','[1,3,5,7,9]','index 3','A midpoint comparison rules out an entire ordered half.','Maintain an inclusive candidate interval and remove the midpoint after a miss.','Not moving past midpoint can create an infinite loop.',['lo=0, hi=4, mid=2 → 5','5<7 → lo=3','mid=3 → 7','Return index 3'],'O(log n) time, O(1) space','For unsorted data, this elimination rule does not hold.'),
 c('first-true','Find a transition','Binary search','Find the first failing build when all builds after the first failure also fail.','[false,false,true,true,true]','index 2','A monotonic predicate switches once from false to true.','Keep the true side as a candidate and search left for an earlier true.','If builds can recover later, the monotonic assumption is false.',['mid=2 → true, remember 2','Search [0,1]; mid=0 false','mid=1 false','First true is 2'],'O(log n) predicate checks, O(1) space','The same idea locates an insertion boundary in sorted values.'),
 c('insert-position','Find an insertion boundary','Binary search','Return the first position whose value is at least target 4, or length if none.','[1,3,3,7]','3','The predicate value>=target is monotonic.','Use lower-bound search on a half-open interval [lo,hi).','Finding any equal element is not enough when duplicates exist.',['[0,4), mid=2 → 3<4','[3,4), mid=3 → 7>=4','hi=3 equals lo','Return 3'],'O(log n) time, O(1) space','For target 3, the first valid index is 1, not 2.'),
 c('range-queries','Many range-sum queries','Prefix sums','Preprocess a static array so each half-open range sum [l,r) takes constant time.','[2,-1,4], query [1,3)','3','Many sums reuse the same prefixes.','Store prefix[0]=0; range sum is prefix[r]-prefix[l].','If updates are frequent, static prefix sums need expensive rebuilding.',['prefix [0]','After 2,-1,4 → [0,2,1,5]','query [1,3): 5-2','Return 3'],'O(n) preprocessing, O(1) query, O(n) space','For frequent updates, consider Fenwick or segment trees.'),
 c('balance-index','Balance left and right sums','Prefix sums','Find an index whose strict left sum equals its strict right sum.','[1,7,3,6,5,6]','3','A total and a running prefix let you derive the right sum.','At index i: right=total-left-nums[i]; compare before adding current to left.','Including the pivot in either side violates the contract.',['Total 28; left starts 0','Before i=3: left=11','right=28-11-6=11','Return index 3'],'O(n) time, O(1) extra space using a running prefix','If no pivot matches, return the contract’s missing-result sentinel.'),
 c('negative-subarray','Count target-sum subarrays','Prefix sums','Count contiguous subarrays summing to 2, allowing negative values, in expected linear time.','[1,-1,2]','2','A subarray sum is the difference of two prefix sums.','Use a Map of earlier prefix frequencies, initialized with 0→1. Count prefix-target before storing the new prefix.','A positive-only sliding-window rule fails with negative numbers; Map supports the prefix technique.',['prefix=1: need -1, 0 matches','prefix=0: need -2, 0 matches; 0 count becomes 2','prefix=2: need 0, 2 matches','Return 2 subarrays'],'Expected O(n) time, O(n) space','If only one static range is queried, just scan that range.'),
];
export const patternLessons:ReadingLesson[]=patternCases.map(x=>({id:`pattern-reading-${x.id}`,title:x.title,category:'Pattern recognition',topic:'Choose an approach before coding',format:'Visual guide',minutes:4,explanation:'First predict the best-fit approach for this contract and explain your reason in the practice panel. Then follow the reference flow below. Multiple algorithms may work; focus on the stated constraints.',example:`${x.prompt}\nInput: ${x.input}\nExpected: ${x.output}`,steps:x.flow.map((state,i)=>({title:`Trace ${i+1}`,detail:i===0?x.cue:i===x.flow.length-1?x.why:'Follow the state change for this concrete input.',state})),pitfall:x.trap,interview:`I choose ${x.pattern} because ${x.why} ${x.cost}.`,recall:x.prompt,answer:`${x.pattern}. ${x.why}`,useWhen:x.cue,questions:[{question:'Why this pattern?',answer:x.why},{question:'When would you choose differently?',answer:x.transfer}],hinglish:'Pehle output aur constraints samjho. Kaunsi information yaad rakhni hai? Sirf keyword dekh kar pattern mat chuno.'}));
