import {Progress,dateKey,dayDate,emptyDay,updateDay} from './progress';
import {quests} from './curriculum';
export const groups=[{id:'learn',label:'Learn & investigate',steps:['recall','investigate','learn'],minutes:60},{id:'practice',label:'Practice & explain',steps:['dsa','explain'],minutes:60},{id:'build',label:'Build & reflect',steps:['build','reflect'],minutes:60}];
export type PlanChange={at:string;dueDate:string;status:'active'|'deferred'|'skipped';reason:string};
export type PlanItem={dueDate:string;status:PlanChange['status'];reason:string;priority:'high'|'normal'|'low';minutes:number;updatedAt:string;history:PlanChange[]};
export type Planning={items:Record<string,PlanItem>;dailyBudget:number};
export type Submission={id:string;at:string;status:'complete'|'partial'|'not-started';reason:string;minutes:number;steps:string[];answers:Record<string,{text:string;feedback:string}>;notes:string};
export type ManagedTask={id:string;day:number;label:string;title:string;dueDate:string;originalDate:string;done:boolean;status:PlanItem['status'];reason:string;priority:PlanItem['priority'];minutes:number;personal:boolean;updatedAt:string;history:PlanChange[]};
export function managedTasks(p:Progress):ManagedTask[]{const list=quests.flatMap(q=>groups.map(g=>({id:`quest-${q.day}-${g.id}`,day:q.day,label:g.label,title:q.title,done:g.steps.every(s=>p.days[q.day]?.steps.includes(s)),minutes:g.minutes,personal:false}))).concat(p.todos.map(t=>({id:`todo-${t.id}`,day:t.day,label:t.text,title:'Personal task',done:t.done,minutes:30,personal:true})));return list.map(t=>{const item=p.planning?.items[t.id],originalDate=dayDate(p.startDate,t.day-1);return {...t,originalDate,dueDate:item?.dueDate||originalDate,status:item?.status||'active',reason:item?.reason||'',priority:item?.priority||'normal',minutes:item?.minutes??t.minutes,updatedAt:item?.updatedAt||'',history:item?.history||[]}})}
export function changePlan(p:Progress,id:string,patch:Pick<PlanItem,'dueDate'|'status'|'reason'|'priority'|'minutes'>,now=new Date()):Progress{const t=managedTasks(p).find(t=>t.id===id);if(!t)throw new Error('Task no longer exists.');if(!/^\d{4}-\d{2}-\d{2}$/.test(patch.dueDate)||dateKey(new Date(patch.dueDate+'T12:00:00'))!==patch.dueDate)throw new Error('Choose a valid date.');if(!Number.isInteger(patch.minutes)||patch.minutes<5||patch.minutes>480)throw new Error('Estimate must be 5–480 minutes.');if((patch.status!=='active'||patch.dueDate!==t.dueDate)&&!patch.reason.trim())throw new Error('Add a reason for deferring, skipping, or rescheduling.');const at=now.toISOString();return {...p,updatedAt:at,planning:{dailyBudget:p.planning?.dailyBudget||180,items:{...p.planning?.items,[id]:{...patch,updatedAt:at,history:[...t.history,{at,dueDate:patch.dueDate,status:patch.status,reason:patch.reason}]}}}}}
export function moveDueTo(p:Progress,target:string,reason:string,today=dateKey()){let next=p;for(const t of managedTasks(p).filter(t=>!t.done&&t.status!=='skipped'&&t.dueDate<=today))next=changePlan(next,t.id,{dueDate:target,status:'deferred',reason,priority:t.priority,minutes:t.minutes});return next}
export function shiftRemaining(p:Progress,days:number,reason:string,today=dateKey()){if(!Number.isInteger(days)||days<1||days>90)throw new Error('Choose a break of 1–90 days.');let next=p;for(const t of managedTasks(p).filter(t=>!t.done&&t.status!=='skipped'))next=changePlan(next,t.id,{dueDate:dayDate(t.dueDate<today?today:t.dueDate,days),status:'deferred',reason,priority:t.priority,minutes:t.minutes});return next}
export function submitQuest(p:Progress,day:number,status:Submission['status'],reason:string,minutes:number,now=new Date()):Progress{const d=p.days[day]||emptyDay(),q=quests[day-1];if(!q)throw new Error('Unknown quest.');if(!Number.isInteger(minutes)||minutes<0||minutes>1440)throw new Error('Actual time must be 0–1440 minutes.');if(status==='complete'&&!q.steps.every(s=>d.steps.includes(s.id)))throw new Error('Finish every checklist step before submitting as complete. You can submit partial work now.');if(status==='not-started'&&(d.steps.length>0||Object.values(d.answers).some(a=>a.text.trim())))throw new Error('This quest already has work. Choose partial instead.');if(status!=='complete'&&!reason.trim())throw new Error('Add a reason or your next step.');const submission:Submission={id:crypto.randomUUID(),at:now.toISOString(),status,reason,minutes,steps:[...d.steps],answers:Object.fromEntries(Object.entries(d.answers).map(([id,a])=>[id,{text:a.text,feedback:a.feedback}])),notes:d.notes};return updateDay(p,day,{submissions:[...(d.submissions||[]),submission]},now)}
