export type QuestionExample={answer:string;example:string;code:string;output:string;hint:string;trap:string};
export const questionExamples:Record<string,QuestionExample>={};
function group(prefix:string,rows:QuestionExample[]){rows.forEach((r,i)=>{questionExamples[`${prefix}-${String(i+1).padStart(2,'0')}`]=r})}
group('int-js',[
 {answer:'var is function-scoped and initialized to undefined before its declaration runs. let and const are block-scoped and cannot be accessed before initialization. let permits reassignment; const prevents reassignment of the binding, not mutation of its object.',example:'An inner block can shadow an outer let without changing it.',code:'let n = 1;\n{ let n = 2; console.log(n); }\nconsole.log(n);',output:'2\n1',hint:'Draw a separate binding box for each block.',trap:'Do not describe const as deep immutability.'},
 {answer:'A closure retains access to bindings in its lexical environment. A factory call can create private state shared by the functions returned from that call.',example:'Two factory calls create independent counts.',code:'function counter() { let n = 0; return () => ++n; }\nconst a = counter(), b = counter();\nconsole.log(a(), a(), b());',output:'1 2 1',hint:'Track the environment created by each call, not just the returned function.',trap:'A closure sees the binding; it is not a frozen snapshot.'},
 {answer:'const restricts assignment to the variable. It does not make the referenced object immutable. Property writes still operate on that object.',example:'Mutate a field without replacing the object.',code:'const user = {name: "Ada"};\nuser.name = "Grace";\nconsole.log(user.name);',output:'Grace',hint:'Separate the variable-to-object arrow from the object’s properties.',trap:'Object.freeze is shallow and has different semantics from const.'},
 {answer:'Strict equality does not coerce values to another type. Loose equality follows coercion rules. Both compare object identity rather than recursively comparing fields.',example:'Numeric strings can compare loosely equal to numbers, but separate objects do not become equal.',code:'console.log("0" == 0, "0" === 0);\nconsole.log({x:1} === {x:1});',output:'true false\nfalse',hint:'First determine operand types, then apply the comparison rule.',trap:'Strict equality still has special numeric behavior: NaN is not strictly equal to itself.'},
 {answer:'Object.is considers NaN equal to NaN and distinguishes +0 from -0. It still compares objects by identity.',example:'Compare the two numeric cases where Object.is differs from ===.',code:'console.log(Object.is(NaN,NaN), NaN === NaN);\nconsole.log(Object.is(0,-0), 0 === -0);',output:'true false\nfalse true',hint:'Check NaN and signed zero separately.',trap:'Object.is is not a deep object comparison.'},
 {answer:'A lexical binding is in scope before its declaration is evaluated but remains uninitialized. Reading it during this temporal dead zone throws ReferenceError, including through typeof.',example:'The inner x shadows the outer binding throughout its block.',code:'let x = 1;\ntry {\n  { console.log(x); let x = 2; }\n} catch (error) { console.log(error.name); }',output:'ReferenceError',hint:'Resolve which x the read refers to before evaluating its value.',trap:'The read does not fall back to the outer x.'},
 {answer:'Function declarations are initialized early in their scope. var bindings exist with undefined until assignment executes. let/const bindings remain uninitialized until their declarations execute.',example:'Calling a function declaration succeeds before its textual declaration.',code:'console.log(twice(3));\nconsole.log(n);\nvar n = 7;\nfunction twice(x) { return x * 2; }',output:'6\nundefined',hint:'Distinguish declaration initialization from later assignment.',trap:'A function expression assigned to var cannot be called while its value is undefined.'},
 {answer:'For a regular function, the call form determines this. Method invocation supplies its receiver; call/apply/bind supply one explicitly; new creates a receiver. A plain strict-mode call has undefined this.',example:'Detaching a method loses the original receiver.',code:'"use strict";\nconst obj = {n:7, read(){ return this?.n; }};\nconst read = obj.read;\nconsole.log(obj.read(), read());',output:'7 undefined',hint:'Look immediately to the left of the call, not where the function was written.',trap:'Passing a method as a callback does not automatically bind its receiver.'},
 {answer:'An arrow function captures this from its surrounding lexical context. call/apply/bind cannot replace that captured this, and arrows cannot be constructors.',example:'An arrow returned by a method keeps that method call’s receiver.',code:'const obj = {n:7, make(){ return () => this.n; }};\nconst read = obj.make();\nconsole.log(read.call({n:99}));',output:'7',hint:'Find the enclosing regular function’s this.',trap:'An arrow stored directly as an object property does not acquire the object as this.'},
 {answer:'call invokes a function with this and separate arguments. apply invokes with this and an array-like argument list. bind returns a new callable with a receiver and optional initial arguments.',example:'Reuse one function against a different receiver.',code:'function add(x,y){ return this.base+x+y; }\nconst obj={base:10};\nconsole.log(add.call(obj,1,2));\nconsole.log(add.apply(obj,[1,2]));\nconsole.log(add.bind(obj,1)(2));',output:'13\n13\n13',hint:'Ask whether the method invokes immediately or returns a function.',trap:'Arrow functions do not accept a replacement lexical this.'},
 {answer:'Property lookup checks own properties first, then follows the prototype chain until it finds the key or reaches null. An own property can shadow an inherited one.',example:'Deleting a shadow reveals the inherited value again.',code:'const parent={x:1};\nconst child=Object.create(parent);\nchild.x=2; console.log(child.x);\ndelete child.x; console.log(child.x);',output:'2\n1',hint:'Draw child → parent → Object.prototype → null.',trap:'Writing child.x normally creates or changes an own property; it does not necessarily edit the parent.'},
 {answer:'An own property belongs directly to an object. Object.hasOwn checks this directly; the in operator also checks inherited properties.',example:'An inherited name is present but not owned by the child.',code:'const child=Object.create({name:"Ada"});\nchild.id=7;\nconsole.log(Object.hasOwn(child,"name"), "name" in child);\nconsole.log(Object.hasOwn(child,"id"));',output:'false true\ntrue',hint:'Compare storage on the object with lookup along the chain.',trap:'Calling obj.hasOwnProperty can fail if that name was overwritten or no prototype exists.'},
 {answer:'A shallow copy creates a new outer container while nested object references remain shared. Copy each changed level to update nested state independently.',example:'Spread alone does not clone settings.',code:'const a={settings:{dark:false}};\nconst b={...a}; b.settings.dark=true;\nconsole.log(a.settings.dark, a===b);',output:'true false',hint:'Draw two outer boxes pointing at the same nested box.',trap:'Deep cloning every update may be unnecessary and may not support every value type.'},
 {answer:'JSON cloning serializes a restricted data representation: unsupported object values can be omitted, dates become strings, and cycles fail. It does not preserve arbitrary JavaScript values or prototypes.',example:'An undefined object field disappears during JSON serialization.',code:'const a={x:undefined,n:1};\nconst b=JSON.parse(JSON.stringify(a));\nconsole.log(Object.hasOwn(b,"x"),b.n);',output:'false 1',hint:'Think about the serialization format’s allowed value types.',trap:'structuredClone supports more types, but still is not a universal clone for functions and all resources.'},
 {answer:'map produces one transformed output per present element. filter keeps elements that satisfy a predicate. reduce combines elements into an accumulator; supplying an initial value defines empty-input behavior.',example:'Transform, select and total the same array.',code:'const a=[1,2,3];\nconsole.log(a.map(x=>x*2));\nconsole.log(a.filter(x=>x>1));\nconsole.log(a.reduce((sum,x)=>sum+x,0));',output:'[2,4,6]\n[2,3]\n6',hint:'Describe the output shape before choosing the method.',trap:'Array.map and the Map key-value data structure are unrelated APIs.'},
 {answer:'undefined commonly signals a missing property, uninitialized variable or omitted return value. null is often an explicit empty value chosen by an API. The contract determines their meaning.',example:'A missing field differs from an explicitly empty field.',code:'const user={manager:null};\nconsole.log(user.manager,user.nickname);',output:'null undefined',hint:'Ask whether absence is intentional and how the API serializes it.',trap:'typeof null returns object for historical reasons; null is not an ordinary object.'},
 {answer:'Optional chaining short-circuits on null or undefined along the optional chain. It does not catch arbitrary exceptions or make a non-callable existing property callable.',example:'A missing nested field yields undefined; an invalid call still throws.',code:'console.log(({user:null}).user?.name);\ntry { ({run:7}).run?.(); }\ncatch (error) { console.log(error.name); }',output:'undefined\nTypeError',hint:'Check nullish absence separately from wrong value type.',trap:'Accessing a completely undeclared root variable still throws.'},
 {answer:'?? uses its fallback only for null or undefined. || falls back for any falsy value, including zero, false and an empty string.',example:'Preserve a valid zero setting.',code:'const volume=0;\nconsole.log(volume ?? 50, volume || 50);',output:'0 50',hint:'Decide whether zero is a valid value or means missing.',trap:'Do not substitute || for ?? when false and empty strings are meaningful.'},
 {answer:'Visit each input element. Recurse into arrays and append scalar values to an output accumulator. For an acyclic array, time is proportional to visited elements; recursion depth follows nesting.',example:'Flatten a nested number array while preserving order.',code:'function flatten(values,out=[]) {\n  for(const v of values) {\n    if(Array.isArray(v)) flatten(v,out); else out.push(v);\n  }\n  return out;\n}\nconsole.log(flatten([1,[2,[3]],4]));',output:'[1,2,3,4]',hint:'Use one output accumulator rather than repeatedly concatenating large arrays.',trap:'Specify a cycle policy and consider an explicit stack for deeply nested input.'},
 {answer:'Compute a key for each item, find or create its group, and append the item. Map supports arbitrary keys and avoids object prototype property collisions.',example:'Group two developers in the same team.',code:'const groups=new Map();\nfor(const item of [{name:"Ada",team:"web"},{name:"Grace",team:"web"}]) {\n  if(!groups.has(item.team)) groups.set(item.team,[]);\n  groups.get(item.team).push(item.name);\n}\nconsole.log(groups.get("web"));',output:'["Ada","Grace"]',hint:'Maintain one array per group key.',trap:'Choose whether keys are strings, normalized values or object identities.'},
]);
