export const puzzles=[
{id:'closure',title:'The counter that starts over',code:'function counter() {\n  let value = 0;\n  return () => ++value;\n}\nconsole.log(counter()(), counter()());',question:'What does it print?',choices:['1 1','1 2','0 1'],correct:0,why:'Each call to counter creates a separate environment. Reuse one returned function to share its count.',hints:['Count factory calls, not just increments.','Each counter() creates a new value binding.','const next = counter(); next(); next();','Separate factories: 1,1. Shared function: 1,2.'],changed:'const next = counter();\nconsole.log(next(), next());',changedCorrect:1,steps:['Create environment A: value=0','Call A: value becomes 1','Create environment B: value=0','Call B: value becomes 1'],lesson:'Closure lifetime'},
{id:'event-loop',title:'The timer that does not run first',code:"console.log('A');\nsetTimeout(() => console.log('B'), 0);\nPromise.resolve().then(() => console.log('C'));\nconsole.log('D');",question:'What is the order in a browser?',choices:['A B C D','A D C B','A D B C'],correct:1,why:'The script finishes first, then the Promise reaction runs at the microtask checkpoint, then the timer task.',hints:['Separate registering a callback from running it.','Synchronous A and D finish first.','script → microtask checkpoint → later timer task','A D C B'],changed:"console.log('A');\nsetTimeout(() => console.log('C'), 0);\nPromise.resolve().then(() => console.log('B'));\nconsole.log('D');",changedCorrect:2,steps:['Stack: script → output A','Register timer B','Queue Promise reaction C','Output D; script returns','Run microtask C','Run later timer B'],lesson:'Tasks and microtasks'},
{id:'copy',title:'The copy that changes the original',code:'const original = { settings: { dark: false } };\nconst copy = { ...original };\ncopy.settings.dark = true;\nconsole.log(original.settings.dark);',question:'What is printed?',choices:['false','true','undefined'],correct:1,why:'The outer object is copied, but both objects point to the same nested settings object.',hints:['Draw two outer objects.','Where does each settings reference point?','Copy the nested level before changing it.','{...original, settings: {...original.settings}} isolates this level.'],changed:'const original = { settings: { dark: false } };\nconst copy = { ...original, settings: {...original.settings} };\ncopy.settings.dark = true;\nconsole.log(original.settings.dark);',changedCorrect:0,steps:['original → settings object S','copy → same settings object S','Write S.dark = true','Both references observe true'],lesson:'Object identity'},
{id:'two-sum',title:'The pair that uses one index twice',code:'const nums = [3]; const target = 6;\nconst seen = new Map();\nfor (let i=0; i<nums.length; i++) {\n  seen.set(nums[i], i);\n  if (seen.has(target-nums[i])) {\n    console.log([seen.get(target-nums[i]), i]);\n  }\n}',question:'What is wrong with the reported pair?',choices:['It reports [0,0], reusing one index','Map cannot store numbers','There is no problem'],correct:0,why:'Insertion happens before lookup. A valid Two Sum pair must use distinct indices; look for earlier values before inserting this value.',hints:['At lookup, is the current index already in seen?','target-current equals current in this input.','lookup complement; if found return; then insert current','Move seen.set below the lookup.'],changed:'const nums = [3,3];\n// Correct algorithm: lookup first, then insert.\n// It returns [0,1].',changedCorrect:2,steps:['i=0, current=3','Insert seen[3]=0','Need target-3 = 3','Lookup returns current index 0: invalid pair'],lesson:'Hash-map invariants'},
{id:'null',title:'The missing rows in SQL',code:'SELECT name FROM users WHERE salary = NULL;',question:'What is the bug?',choices:['Use IS NULL instead of = NULL','NULL must be quoted','All salaries are selected'],correct:0,why:'Equality with NULL produces UNKNOWN. WHERE retains only TRUE. IS NULL is the missing-value predicate.',hints:['SQL has three-valued logic.','NULL equality is not a normal boolean comparison.','SELECT name FROM users WHERE salary IS NULL;','Use IS NULL or IS NOT NULL.'],changed:'SELECT name FROM users WHERE salary IS NULL;\n-- What was the necessary correction?',changedCorrect:0,steps:['Read row','Evaluate salary = NULL → UNKNOWN','WHERE rejects UNKNOWN','No rows pass this predicate'],lesson:'SQL NULL'},
{id:'async',title:'The async work that freezes the UI',code:'async function work() {\n  for (let i=0; i<1e9; i++) { /* CPU work */ }\n  return 1;\n}\nwork();',question:'Why can the UI freeze?',choices:['Async means CPU work runs on another thread','The synchronous loop still blocks its thread','The returned Promise is always rejected'],correct:1,why:'async changes the return contract, not the execution resource. Long synchronous work blocks until it completes or yields.',hints:['Where does the function yield?','There is no await in this body.','Use a worker for suitable CPU work; keep main-thread chunks bounded.','Move computation to a Worker or redesign/chunk the work.'],changed:'// Move the CPU computation to a Web Worker.\n// Why was async alone insufficient?',changedCorrect:1,steps:['Call work on main thread','Execute loop synchronously','UI events wait','Resolve returned Promise after loop'],lesson:'Concurrency versus parallelism'},
];
export const incidents=[
{id:'slow-api',title:'Checkout latency after release',logs:['09:00 deploy v42','09:03 p95 /checkout: 240ms → 4200ms','09:04 trace: 80 sequential SELECT inventory calls/request','09:05 CPU 25%; database round-trip 45ms'],clue:'The number of database calls grows with cart size.',options:['Increase API replicas immediately','Batch the inventory read and verify query count','Disable authentication'],correct:1,explain:'The trace supports an N+1 round-trip problem. Batch the read, preserve consistency requirements, and compare query count and p95 with the same workload.',interrupt:'What if the batch query locks too many rows?',follow:'Limit batch size, inspect the plan/lock duration, and choose transaction boundaries intentionally.'},
{id:'duplicate-payment',title:'A timeout followed by two charges',logs:['op=pay-18 received','provider: charge ch_1 accepted','gateway: response timed out','client retries with new op=pay-19','provider: charge ch_2 accepted'],clue:'A timeout does not prove the first side effect failed.',options:['Retry every timeout with a new operation ID','Never allow retries','Reuse an idempotency key and reconcile ambiguous outcomes'],correct:2,explain:'Preserve one operation identity across retries and store/reuse its result at the correct boundary. Reconcile uncertain provider outcomes before another charge.',interrupt:'The provider does not support idempotency. Now what?',follow:'Describe durable operation tracking, reconciliation and the remaining failure window; do not promise exactly-once external effects.'},
{id:'deploy',title:'Healthy process, failing release',logs:['deploy v9 process started','GET /health returns 200','POST /orders returns 500','database: column delivery_window does not exist','migration job: not executed'],clue:'Process liveness differs from feature readiness.',options:['Investigate migration compatibility; pause rollout and recover','Increase health-check timeout','Delete the orders table'],correct:0,explain:'Stop widening impact, inspect the missing migration, and select a compatible rollback or forward fix. Validate the user path and use expand/contract migrations.',interrupt:'A rollback uses an older schema shape. Is it safe?',follow:'Check backward compatibility and changed data before rolling back; process version alone is not enough.'},
{id:'cache',title:'The cache expires all at once',logs:['cache TTL: 300 seconds on all popular keys','12:05 hit rate: 96% → 3%','database pool wait: 5ms → 2400ms','many concurrent reads of identical keys'],clue:'Concurrent cache misses amplify database work.',options:['Set every TTL to zero','Add TTL jitter and coordinate hot-key refills','Make all keys permanent'],correct:1,explain:'Stagger expiration and coalesce concurrent refills where appropriate. Bound staleness and measure database pressure; permanent caching may be incorrect.',interrupt:'Can you serve stale data during refill?',follow:'Only for operations whose freshness requirements allow it; distinguish product browsing from checkout.'},
];
export const comparisons=[
{title:'WHERE vs HAVING',left:'WHERE filters input rows before grouping.',right:'HAVING filters aggregate groups.',example:"WHERE status='paid' → GROUP BY user_id → HAVING SUM(total)>100",decision:'Use WHERE for row predicates and HAVING for aggregate predicates.'},
{title:'useMemo vs useCallback',left:'useMemo caches the result of a pure calculation.',right:'useCallback caches a function identity.',example:'useMemo(() => filter(items), [items]) versus useCallback(() => save(id), [id])',decision:'Measure the need; complete dependencies matter in both. Neither is durable storage.'},
{title:'SQL vs document database',left:'Relational tables express relationships and constraints; joins combine data.',right:'Documents group data read together; cross-document relationships need deliberate handling.',example:'Orders with many cross-entity reports versus self-contained catalog documents.',decision:'Choose from access patterns, consistency and operations, not from a claim that one category never scales.'},
{title:'Inheritance vs composition',left:'Inheritance specializes an existing type and must preserve substitutability.',right:'Composition delegates work to collaborators with explicit contracts.',example:'Checkout has a PaymentGateway; it is not a type of PaymentGateway.',decision:'Use inheritance for a genuine behavioral subtype; use composition to combine capabilities.'},
{title:'Monolith vs microservices',left:'One deployable application can still have strong internal modules.',right:'Independently deployed services introduce network and operational boundaries.',example:'A small team may iterate faster with a modular monolith; isolated scaling may later justify extracting a service.',decision:'Weigh ownership, release coupling, failure modes, observability and operational cost.'},
];
export const followups=[
{topic:'Closures',questions:['What is a closure?','Show a concrete use in code.','What can a long-lived callback retain?','How would you clean up a subscription?']},
{topic:'React performance',questions:['How would you investigate a slow screen?','What did profiling show?','When would useMemo help?','How can changing object identity defeat memoization?']},
{topic:'SQL',questions:['When do you choose an index?','What does the query plan show?','What is the cost on writes?','How would you investigate a slow join?']},
{topic:'System design',questions:['What requirements would you clarify first?','Which operation needs strong consistency?','What is your first bottleneck?','What happens when the database times out after committing?']},
];
export const speakingLadder=['Record a 20-second sentence privately','Explain a concept to a willing friend','Ask a teammate one focused clarification','Give a concise update in a meeting','Complete a mock interview with a willing partner'];
export const listeningPrompts=['Explain the difference between WHERE and HAVING with a small example.','A payment request times out. How would you decide whether retrying is safe?','Tell me about a bug you owned, the evidence you used, and what changed.'];
export const stackExamples={
Node:`// Express route; simplified in-memory example\napp.post('/tasks', (req, res) => {\n  const title = typeof req.body?.title === 'string' ? req.body.title.trim() : ''; \n  if (!title) return res.status(400).json({error:'Title required'});\n  const task = {id: crypto.randomUUID(), title, done:false};\n  tasks.push(task);\n  return res.status(201).json(task);\n});`,
'.NET':`// ASP.NET Core minimal API; simplified in-memory example\napp.MapPost("/tasks", (CreateTask input) => {\n  if (string.IsNullOrWhiteSpace(input.Title))\n    return Results.BadRequest(new { error = "Title required" });\n  var task = new TaskItem(Guid.NewGuid(), input.Title.Trim(), false);\n  tasks.Add(task);\n  return Results.Created($"/tasks/{task.Id}", task);\n});\nrecord CreateTask(string Title);\nrecord TaskItem(Guid Id, string Title, bool Done);`,
Python:`# FastAPI route; simplified in-memory example\nclass CreateTask(BaseModel):\n    title: str\n\n@app.post('/tasks', status_code=201)\ndef create_task(body: CreateTask):\n    title = body.title.strip()\n    if not title:\n        raise HTTPException(400, 'Title required')\n    task = {'id': str(uuid4()), 'title': title, 'done': False}\n    tasks.append(task)\n    return task`
};
export const sqlExercises=[
{id:'filter',title:'Filter salary',task:'Return name and salary for salaries above 50000.',starter:'SELECT name, salary FROM employees WHERE salary > 50000;',expected:[['Asha',70000],['Leena',60000]]},
{id:'join',title:'Join orders to people',task:'Return employee name and paid order total. Keep one row per paid order.',starter:"SELECT e.name, o.total FROM employees e JOIN orders o ON e.id=o.employee_id WHERE o.status='paid';",expected:[['Asha',40],['Asha',70],['Ravi',30]]},
{id:'group',title:'Filter groups',task:'Return employee_id and SUM(total) for paid totals above 100.',starter:"SELECT employee_id, SUM(total) FROM orders WHERE status='paid' GROUP BY employee_id HAVING SUM(total)>100;",expected:[[1,110]]},
{id:'null',title:'Find missing data',task:'Return names whose salary is unknown.',starter:'SELECT name FROM employees WHERE salary IS NULL;',expected:[['Mina']]},
{id:'rank',title:'Rank known salaries',task:'Return name and dense salary rank, highest salary first. Exclude unknown salaries.',starter:'SELECT name, DENSE_RANK() OVER (ORDER BY salary DESC) FROM employees WHERE salary IS NOT NULL ORDER BY salary DESC, name;',expected:[['Asha',1],['Leena',2],['Ravi',3]]},
];
export const sqlSeed=`CREATE TABLE employees(id INTEGER PRIMARY KEY,name TEXT,department TEXT,salary INTEGER);
INSERT INTO employees VALUES (1,'Asha','Engineering',70000),(2,'Ravi','Support',45000),(3,'Mina','Engineering',NULL),(4,'Leena','Engineering',60000);
CREATE TABLE orders(id INTEGER PRIMARY KEY,employee_id INTEGER,total INTEGER,status TEXT);
INSERT INTO orders VALUES (1,1,40,'paid'),(2,1,70,'paid'),(3,2,200,'pending'),(4,2,30,'paid');`;
