import {puzzles} from './studio-content';
import {questionExamples} from './question-examples';
export type PuzzleMode='bug'|'predict'|'change'|'hints'|'trace';
export type Puzzle=typeof puzzles[number];
const wrong=[['1 2','2 2'],['1 2 3','1 1 1'],['Ada','TypeError'],['false false\nfalse','true true\ntrue'],['false false\ntrue true','true true\nfalse false'],['1','undefined'],['6\n7','ReferenceError'],['7 7','undefined undefined'],['99','undefined'],['13\n13\nNaN','TypeError'],['2\n2','1\n1'],['true true\ntrue','false false\nfalse'],['false false','true true'],['true 1','undefined 1'],['[1,2,3]\n[1]\n0','TypeError'],['undefined null','null null'],['undefined\nundefined','ReferenceError'],['50 50','0 0'],['[1,2,[3],4]','[4,3,2,1]'],['["Grace"]','undefined']];
const predictions:Puzzle[]=Object.entries(questionExamples).map(([id,e],i)=>{
 const choices=[...wrong[i]];const correct=i%3;choices.splice(correct,0,e.output);
 return {id:'js-'+id,title:e.example,lesson:'JavaScript reasoning',code:e.code,question:'Predict the observable output, then explain the mechanism.',choices,correct,why:e.answer+' '+e.trap,hints:[e.hint,'Track each binding, object identity and call separately.',e.answer,e.output],changed:e.code,changedCorrect:correct,steps:[e.example,e.hint,e.answer,'Expected output: '+e.output]};
});
const extra:Puzzle[]=[
{id:'map-zero',title:'The stored index that disappears',lesson:'Map membership',code:'const seen = new Map([[2, 0]]);\nconsole.log(Boolean(seen.get(2)));',question:'What does this print?',choices:['true','false','undefined'],correct:1,why:'get(2) returns the stored index 0. Boolean(0) is false; use has for membership.',hints:['What is the value at key 2?','Zero is falsy.','Use seen.has(2) when checking existence.','Original prints false; has prints true.'],changed:'const seen = new Map([[2, 0]]);\nconsole.log(seen.has(2));',changedCorrect:0,steps:['Store key 2 → index 0','get(2) returns 0','Convert 0 to false','Membership and value truthiness are different']},
{id:'numeric-sort',title:'The smallest number is not first',lesson:'Array sorting',code:'console.log([10, 2, 1].sort().join(","));',question:'What is printed?',choices:['1,2,10','10,2,1','1,10,2'],correct:2,why:'Default array sorting compares string representations. Supply a numeric comparator for ascending numeric order.',hints:['No comparator is provided.','Compare "10" with "2" as strings.','sort((a,b) => a-b)','Original: 1,10,2. Numeric: 1,2,10.'],changed:'console.log([10, 2, 1].sort((a,b) => a-b).join(","));',changedCorrect:0,steps:['Convert ordering comparisons to strings','"1" comes before "10"','"10" comes before "2"','Join gives 1,10,2']},
{id:'filter-zero',title:'The filter removes valid data',lesson:'Truthy filtering',code:'console.log([0, 1, null, 2].filter(Boolean).join(","));',question:'What remains?',choices:['0,1,2','1,2','0,1,null,2'],correct:1,why:'Boolean filtering removes all falsy values, including a legitimate zero. Use a null-specific predicate when zero is valid.',hints:['Evaluate Boolean for each item.','Both 0 and null are falsy.','filter(x => x !== null)','Original retains 1,2; changed retains 0,1,2.'],changed:'console.log([0, 1, null, 2].filter(x => x !== null).join(","));',changedCorrect:0,steps:['0 fails Boolean predicate','1 passes','null fails','2 passes → 1,2']},
{id:'fallback-zero',title:'A zero-volume setting turns loud',lesson:'Default values',code:'const volume = 0;\nconsole.log(volume || 50);',question:'Which volume is chosen?',choices:['0','undefined','50'],correct:2,why:'Logical OR selects the fallback for any falsy value. Nullish coalescing keeps zero.',hints:['Is 0 truthy?','OR uses truthiness, not just null checks.','volume ?? 50','Original 50; changed 0.'],changed:'const volume = 0;\nconsole.log(volume ?? 50);',changedCorrect:0,steps:['Read volume 0','OR sees a falsy left operand','Evaluate fallback 50','Return 50 instead of the intended zero']},
{id:'set-identity',title:'Equal-looking users are still duplicated',lesson:'Set identity',code:'const users = [{id:7}, {id:7}];\nconsole.log(new Set(users).size);',question:'How many Set entries exist?',choices:['1','2','0'],correct:1,why:'Separate object references are distinct Set values. Map to the chosen identity field if deduplication means equal user IDs.',hints:['Count object allocations.','Set does not deeply compare object fields.','new Set(users.map(x => x.id))','Original size 2; IDs size 1.'],changed:'const users = [{id:7}, {id:7}];\nconsole.log(new Set(users.map(x => x.id)).size);',changedCorrect:0,steps:['Allocate object A with id 7','Allocate object B with id 7','A and B have different identities','Set retains both']},
{id:'reduce-empty',title:'An empty cart crashes the total',lesson:'Reduction boundaries',code:'try { console.log([].reduce((a,b) => a+b)); }\ncatch(e) { console.log(e.name); }',question:'What is printed?',choices:['undefined','0','TypeError'],correct:2,why:'Without an initial accumulator, reduce needs a present element to start. An empty array has none.',hints:['Where does the accumulator start?','No initial value was supplied.','reduce((a,b) => a+b, 0)','Original TypeError; changed 0.'],changed:'try { console.log([].reduce((a,b) => a+b, 0)); }\ncatch(e) { console.log(e.name); }',changedCorrect:1,steps:['Array has no elements','No initial accumulator supplied','Reduction cannot start','Catch prints TypeError']},
{id:'loop-binding',title:'Three callbacks read the final index',lesson:'Loop scope',code:'const callbacks=[];\nfor(var i=0;i<3;i++) callbacks.push(() => i);\nconsole.log(callbacks.map(f=>f()).join(","));',question:'What is printed after the loop?',choices:['0,1,2','3,3,3','1,2,3'],correct:1,why:'var uses one binding shared by these callbacks. let creates per-iteration bindings for this loop.',hints:['Callbacks are invoked after the loop.','All callbacks read the same var binding.','Replace var with let.','Original 3,3,3; changed 0,1,2.'],changed:'const callbacks=[];\nfor(let i=0;i<3;i++) callbacks.push(() => i);\nconsole.log(callbacks.map(f=>f()).join(","));',changedCorrect:0,steps:['Create callbacks closing over i','Loop increments shared i to 3','Invoke callbacks after loop','Each reads current i=3']},
{id:'map-overwrite',title:'Repeated keys replace earlier values',lesson:'Map updates',code:'const m=new Map();\nm.set("a",1); m.set("a",2);\nconsole.log(m.size, m.get("a"));',question:'What is printed?',choices:['2 2','1 2','2 1'],correct:1,why:'Setting an existing key replaces its value without increasing size. Separate keys create separate entries.',hints:['How many unique keys exist?','The second set replaces the value for a.','Inspect size and value separately.','One key, latest value 2.'],changed:'const m=new Map();\nm.set("a",1); m.set("b",2);\nconsole.log(m.size, m.get("a"));',changedCorrect:2,steps:['Insert a → 1','Replace a → 2','Map still has one key','size 1; get(a) 2']},
];
export const puzzleCatalog:Record<PuzzleMode,Puzzle[]>={
 predict:[...predictions,...puzzles,...extra],
 bug:[...extra,...puzzles],
 change:[...extra,...puzzles.filter(q=>['closure','event-loop','copy'].includes(q.id))],
 hints:[puzzles[3],...extra,...puzzles.filter(q=>q.id!=='two-sum')],
 trace:[puzzles[1],...extra,...predictions,...puzzles.filter(q=>q.id!=='event-loop')],
};
