import type {Question} from './bank/core';

export const designLevels={
 Easy:{minutes:25,focus:'One bounded use case, clear ownership, a simple design and one failure path.'},
 Medium:{minutes:40,focus:'Multiple components, explicit consistency, estimates, retries and a justified tradeoff.'},
 Hard:{minutes:60,focus:'Concurrent or distributed failures, recovery, scale limits and a defensible alternative.'},
} as const;

export const designSections=[
 ['Problem & scope','Who uses it? What must it do? What is explicitly out of scope?'],
 ['Requirements & assumptions','List functional needs and measurable latency, availability, privacy and durability goals. Label assumptions.'],
 ['Scale or invariants','HLD: estimate traffic, peak factor and storage with units. LLD: define valid states, ownership and concurrency invariants.'],
 ['Contracts','Show API requests/responses or method/function signatures, errors and authorization boundaries.'],
 ['Data model','Name keys, relationships, indexes, uniqueness rules and retained history.'],
 ['Diagram & responsibilities','Draw only the components or objects you need. Label arrows and explain each responsibility.'],
 ['Happy path','Walk through one concrete input from acceptance to a durable result and response.'],
 ['Failures & security','Trace a timeout, duplicate or concurrent request; define recovery, access control and useful telemetry.'],
 ['Tradeoffs & next iteration','Compare a simpler alternative, identify the first bottleneck and explain when you would change the design.'],
] as const;

type Blueprint={name:string;clarify:string[];nodes:string[];flows:string[];contract:string;data:string;failure:string;tradeoff:string};
const blueprints:Record<string,Blueprint>={
 'sd-routing':{name:'Request routing example',clarify:['What endpoint and traffic shape are in scope?','Where are identity and resource access checked?','What is the total request deadline?'],nodes:['Client','Edge / proxy','Application','Owned data store'],flows:['TLS + request','Route with deadline','Authorized read/write'],contract:'GET /resources/{id} → 200 resource, 401 unauthenticated, 403 forbidden, 404 absent; request ID propagated.',data:'Resource(id, owner_id, version, payload); choose indexes from the actual lookup path.',failure:'An upstream timeout is an unknown result for a write. Retry only with a defined operation identity and recovery policy.',tradeoff:'Start with a simple proxy and application. Add caching or regional routing only for a stated requirement.'},
 'sd-storage':{name:'Partitioned storage example',clarify:['Which reads and writes dominate?','What key distributes load while preserving useful locality?','What acknowledgment and recovery guarantees are required?'],nodes:['Caller','Partition router','Owning partition','Replica / recovery log'],flows:['Keyed operation','Resolve ownership','Replicate by policy'],contract:'put(key, value, expectedVersion) → version or conflict; get(key, minVersion?) → value/version or unavailable.',data:'Record(key, version, value, expires_at); ownership metadata is separate from user data.',failure:'After failover, fence the old writer. Define whether an acknowledged write can be lost under the chosen replication policy.',tradeoff:'Co-location simplifies related reads; distributing keys may improve balance but makes cross-partition operations harder.'},
 'sd-consistency':{name:'Concurrent workflow example',clarify:['Which business invariant may never be violated?','What belongs in one local transaction?','How will an ambiguous external outcome be reconciled?'],nodes:['Caller + operation ID','Workflow service','Durable operation state','External dependency'],flows:['Submit / retry','Commit local transition','Perform / reconcile effect'],contract:'POST /operations with Idempotency-Key → stable operation ID; GET /operations/{id} → pending/succeeded/failed/unknown.',data:'Operation(owner_id, key UNIQUE per owner, payload_hash, state, result); append transition history.',failure:'Persist intent before an external effect. A crash after the effect but before recording its result requires reconciliation.',tradeoff:'A local transaction protects local invariants; it does not atomically commit an unrelated provider side effect.'},
 'sd-messaging':{name:'Durable job example',clarify:['Is ordering needed globally or only per entity?','What is the maximum acceptable delay?','How are duplicates, poison jobs and provider responses represented?'],nodes:['Producer + outbox','Broker / queue','Consumer + dedup store','Destination'],flows:['Retry publish','Lease / consume','Apply effect + record outcome'],contract:'POST /jobs → 202 job ID; GET /jobs/{id} → accepted/processing/retrying/failed/provider-accepted.',data:'Job(id, entity_id, state, attempts, next_attempt_at); deduplication keyed by the business effect.',failure:'A worker can crash between effect and acknowledgment. Make the effect retry-safe, and expose bounded retries and dead-letter recovery.',tradeoff:'Asynchronous work absorbs bursts but adds delay, state tracking and operational effort.'},
 'sd-product':{name:'Product write and derived-view example',clarify:['What user journey matters first?','Who can read or edit each resource?','How should offline or concurrent edits behave?'],nodes:['Authorized user','Product API','Authoritative records','Derived / live view'],flows:['Command + version','Commit owned data','Update with defined lag'],contract:'POST /resources → ID/version; PATCH /resources/{id} with expected version → new version or 409 conflict.',data:'Resource(id, owner_id, version); Membership(resource_id, user_id, role); ordered changes where required.',failure:'A derived view can lag or contain revoked data. Recheck authorization and define repair and deletion propagation.',tradeoff:'A separate view speeds reads but adds freshness and repair work. Begin with authoritative reads if sufficient.'},
 'sd-commerce':{name:'Checkout lifecycle example',clarify:['When is price fixed?','What constitutes a reservation rather than availability?','What happens if payment finishes after a hold expires?'],nodes:['Cart / quote','Order + reservation','Payment boundary','Fulfillment / reconciliation'],flows:['Validate + snapshot','Authorize one operation','Confirm or compensate'],contract:'POST /orders with operation key → order ID/state; callback repeats must not create another business effect.',data:'Order + OrderLine(price_snapshot, quantity); Reservation(expires_at, state); Payment(operation_key, provider_id, state).',failure:'A payment success and inventory expiry can race. Choose explicit state transitions and a reconciliation or refund path.',tradeoff:'Strict coordination protects scarce inventory but costs availability and throughput; separate browsing from committing stock.'},
 'sd-platform':{name:'Controlled service rollout example',clarify:['Which failure domain must be tolerated?','What makes an instance ready for real user traffic?','Which state must survive a process or leader change?'],nodes:['Control / deployment','Readiness gate','Serving instance','Durable shared dependency'],flows:['Versioned change','Admit / drain traffic','Bounded dependency calls'],contract:'Liveness proves process health; readiness checks the serving contract. Record artifact and configuration versions.',data:'Deployment(version, stage, health); leases need expiry plus fencing when ownership can overlap.',failure:'A process can be alive while its user path fails. Stop rollout, inspect compatibility, and choose a safe rollback or forward fix.',tradeoff:'More replicas add cost and do not remove a shared database, network or control-plane failure.'},
 'sd-data':{name:'Derived data pipeline example',clarify:['How stale may results be?','Can source changes be replayed?','How are deletes, duplicates and late events handled?'],nodes:['Authoritative source','Durable change stream','Indexer / aggregator','Query view'],flows:['Versioned change','Partition + replay','Publish queryable state'],contract:'Ingest(event_id, entity_id, version, payload) with deduplication; query returns data with a defined freshness contract.',data:'Source version, processing checkpoint and derived record version; retain enough information to repair or replay.',failure:'A consumer restart can replay old events. Prevent an older version from replacing a newer result; propagate deletion tombstones.',tradeoff:'Derived views optimize queries at the cost of lag, duplicate handling, retention and rebuilding.'},
 'sd-oop':{name:'OOP collaboration example',clarify:['Which use cases and state transitions are in scope?','Which object owns the invariant?','Which policy should vary independently?'],nodes:['Use-case service','Domain entity','Policy interface','Repository / adapter'],flows:['Ask for transition','Delegate variable rule','Persist or perform I/O'],contract:'UseCase.execute(command) → Result; Entity.transition(event) validates state; inject a policy and repository contract.',data:'Entities have stable identity. Value objects represent validated values. Persisted uniqueness must enforce concurrent invariants.',failure:'An object diagram alone cannot prevent two processes reserving the same resource. Define the database coordination boundary.',tradeoff:'Composition separates changing policies; inheritance requires a real substitutable subtype, not merely shared code.'},
 'sd-functions':{name:'Functional collaboration example',clarify:['What is the immutable state shape?','Which events are valid in each state?','Which I/O and clock boundaries must be explicit?'],nodes:['Command handler','Pure transition','Effect runner','Persisted state'],flows:['Validate input','Return next state + effects','Commit with version check'],contract:'transition(state, event) → {nextState, effects} | error; effects are executed separately and confirmed as later events.',data:'Tagged states/events, explicit version, immutable values and durable effect IDs where retry is possible.',failure:'Computing a correct next state is insufficient under concurrency. Persist with an expected version and handle conflicts.',tradeoff:'Pure transitions are easy to reason about; orchestration must still handle retries, persistence and effect lifecycles.'},
};

export type WorkedDesign=Blueprint & {scope:string;requirements:string[];estimate:string;walkthrough:string[];implementation:string[]};
export const workedDesigns:Record<string,WorkedDesign>={
 'sd-product-08':{name:'Comments with moderation',scope:'One application, paginated comments, replies and moderator review; no live collaborative editing.',requirements:['Only authorized users can comment on a resource.','Bound nesting depth and use stable cursor pagination.','Hide moderated content without losing the audit trail.'],estimate:'Illustrative assumption: 10,000 comments/day × 1 KB ≈ 10 MB/day before indexes, replicas and history. Measure peak reads separately.',clarify:['Can an author edit or delete a reply?','How deep can replies nest?','Are deleted parents shown as placeholders?'],nodes:['Reader / author','Comment service','SQL comment records','Moderator audit'],flows:['Read / submit','Authorize + persist','Record moderation'],contract:'POST /posts/{id}/comments {body,parentId?} → 201; GET /posts/{id}/comments?cursor=… → items,nextCursor.',data:'Comment(id, post_id, parent_id?, author_id, body, status, created_at, version). Index (post_id, created_at, id); validate parent belongs to the same post.',failure:'Retrying creation can duplicate a comment; accept a caller-scoped operation key. Recheck permissions when reading and moderating.',tradeoff:'Start with SQL reads. A cached count or search index adds freshness and deletion work.',walkthrough:['Authorize the author against the post.','Validate body, parent and depth; create a comment once.','Return its ID; the next page uses a stable cursor.','A moderator changes visibility and appends an audit event.'],implementation:['Build create/read with ownership checks.','Add pagination and parent validation.','Add optimistic edits and moderation history.']},
 'sd-functions-01':{name:'Immutable shopping-cart engine',scope:'Pure cart logic with explicit price input; payment and inventory I/O are outside the transition function.',requirements:['Quantities must be positive integers.','Use integer minor currency units and reject mixed currencies.','Do not mutate the original cart; revalidate prices at checkout.'],estimate:'For n lines, a simple update scans O(n) and copies O(n) data. Optimize only if cart size justifies it.',clarify:['Are duplicate products merged?','How are discounts ordered and rounded?','What happens when the quote changes?'],nodes:['Cart command','Pure reducer','New cart / error','Checkout adapter'],flows:['Validate intent','Compute without mutation','Perform explicit I/O'],contract:'updateCart(cart, command, catalog) → {ok:true,cart} | {ok:false,error}; commands include Add, SetQuantity and Remove.',data:'Cart {currency, lines:[{productId,quantity,unitPriceMinor}]}; immutable return values; order snapshots are separate.',failure:'Reject missing products or invalid quantities without changing state. Checkout must detect outdated prices and stock.',tradeoff:'Arrays are easy to inspect for small carts; keyed maps improve lookup but complicate serialization and ordering.',walkthrough:['Start with quantity 1 at 1,000 minor units.','Set quantity to 2 and compute 2,000 before discounts.','Return a new cart; the old quantity remains 1.','Checkout validates the quote before a durable order is created.'],implementation:['Define tagged commands and result types.','Write validation and pure transitions.','Inject pricing rules and isolate checkout effects.']},
 'sd-oop-03':{name:'Library lending with OOP',scope:'Physical copies, checkout, return and reservation queue. A title is not the same entity as a copy.',requirements:['A physical copy has at most one active loan.','A borrower must meet the lending policy.','Returning a copy can make it available to the next reservation.'],estimate:'Focus on invariant ownership: two simultaneous checkouts of one copy must not both succeed.',clarify:['What is the borrowing limit?','Can a user renew when another user has reserved?','How are lost copies handled?'],nodes:['LendingService','Copy + Loan entities','LoanPolicy interface','LoanRepository'],flows:['Execute checkout','Validate invariant / policy','Atomic persistence'],contract:'checkout(copyId, borrowerId) → Loan | error; returnCopy(loanId) → result. Inject repository and policy contracts.',data:'BookTitle(id); Copy(id,title_id,status,version); Loan(id,copy_id,borrower_id,returned_at?). Enforce one active loan per copy in storage.',failure:'A transaction or conditional update must reject the second concurrent checkout. A copied in-memory object is not a lock.',tradeoff:'A composed policy changes lending rules without a borrower-subclass hierarchy. Keep persistence behind an explicit interface.',walkthrough:['LendingService loads borrower eligibility and copy state.','LoanPolicy approves or returns a reason.','Atomically create the loan and change copy state.','Return the loan ID; a concurrent loser receives a conflict.'],implementation:['Define entities, value objects and policy/repository interfaces.','Implement checkout and return sequences.','Enforce storage invariants and document failure results.']},
 'sd-routing-05':{name:'Read-heavy URL shortener',scope:'Create a short link and redirect; custom aliases and detailed analytics are optional extensions.',requirements:['Short codes uniquely identify a destination.','Validate destinations and define abuse/expiry policy.','Support the stated ten million reads and one million writes per day.'],estimate:'10M/86,400 ≈ 116 reads/s average; 1M/86,400 ≈ 12 writes/s. An assumed 10× peak gives about 1,160 reads/s and 120 writes/s. At an assumed 500 B/link, raw new records are about 500 MB/day, excluding indexes and replicas.',clarify:['May links change destination?','What redirect cache behavior is acceptable?','Must expired or revoked links stop immediately?'],nodes:['Browser','Redirect API','Cache (optional)','Link database'],flows:['GET /{code}','Lookup cached mapping','Read on miss'],contract:'POST /links {url,expiresAt?} → 201 {code}; GET /{code} → chosen 3xx + Location; unknown/expired codes follow a defined 404/410 policy.',data:'Link(code PRIMARY KEY, destination, owner_id, created_at, expires_at). A unique constraint resolves random-code collisions with a bounded retry.',failure:'On cache miss, read the database. Cache TTL must respect expiry; define invalidation and revocation policy. Do not silently redirect using data beyond the allowed staleness.',tradeoff:'Start without a cache if measurements allow. Caching hot reads reduces database load but complicates updates and abuse takedowns.',walkthrough:['Validate and authorize link creation.','Generate a code and insert under a uniqueness constraint.','On redirect, check the mapping and its expiry.','Return Location; queue optional analytics separately from the redirect.'],implementation:['Create the link schema and create/redirect contracts.','Implement collision and expiry handling.','Measure load, then add bounded caching and abuse controls.']},
 'sd-messaging-01':{name:'Multi-channel notification delivery',scope:'Email, push and in-app delivery with preferences and visible status; provider acceptance is not proof of reading.',requirements:['Honor channel preferences and opt-outs.','Persist delivery intent before acknowledging acceptance.','Handle provider outages and retries without uncontrolled duplication.'],estimate:'Illustrative: 1M notifications/day ≈ 12/s average. At 10× peak, plan for about 120/s before channel fanout; measure provider limits and handler duration.',clarify:['Is delivery urgent or can it be delayed?','Which states can each provider actually confirm?','What is the maximum retry age?'],nodes:['API + job/outbox DB','Durable queue','Channel worker','Provider / in-app store'],flows:['Publish durable intent','Consume + check preference','Send with operation ID'],contract:'POST /notifications with operation key → 202 job ID; GET /notifications/{id} → per-channel state.',data:'Notification(id, user_id, template, operation_key); Delivery(id, notification_id, channel, state, attempts, provider_id).',failure:'A crash after provider acceptance but before acknowledgment makes the outcome uncertain. Use supported provider idempotency or reconcile; do not promise exactly-once delivery.',tradeoff:'A queue isolates slow providers but adds lag and retry management. A simple durable job table may be enough initially.',walkthrough:['Validate request and persist job plus outbox atomically.','Publish with retry; consumers expect possible duplicates.','Check preferences, invoke the channel adapter and record its outcome.','Retry transient failures with bounded backoff; expose exhausted jobs for review.'],implementation:['Define job and per-channel state machines.','Implement one provider adapter and durable attempts.','Add deduplication, retry bounds, opt-outs and operational views.']},
 'sd-consistency-04':{name:'Idempotent payment request',scope:'Prevent a repeated logical request from intentionally creating another charge, while handling uncertain provider outcomes.',requirements:['The same scoped key and payload returns the same operation.','The same key with a different payload is rejected.','An ambiguous outcome remains visible and is reconciled before another charge.'],estimate:'Correctness first: key uniqueness is scoped to caller/tenant and operation type. Choose retention from the retry and audit contract; no universal TTL is assumed.',clarify:['Does the provider support idempotency and lookup?','How long may clients retry?','How are webhooks authenticated and deduplicated?'],nodes:['Caller + stable key','Payment service','Operation ledger','Payment provider'],flows:['Submit / retry','Claim durable operation','Call / reconcile'],contract:'POST /payments with Idempotency-Key {amountMinor,currency} → operation ID/state; a key/payload mismatch → 409. GET /payments/{id} reports pending/succeeded/failed/unknown.',data:'PaymentOperation(tenant_id,key UNIQUE per tenant,payload_hash,state,provider_id,result). Store intent and transition history; avoid storing sensitive card data in the app.',failure:'The provider may charge before the service loses its response. Keep the operation unknown/pending and reconcile via provider identity, lookup or verified callback.',tradeoff:'Local deduplication alone cannot eliminate an external failure window. Provider capabilities and reconciliation determine the actual guarantee.',walkthrough:['Authorize and hash the normalized business payload.','Atomically claim the scoped operation key; replay an existing result or reject mismatch.','Call the provider with a stable identity where supported.','Persist a known result; reconcile uncertain outcomes without creating a new logical payment.'],implementation:['Implement unique operation keys and payload comparison.','Model pending, unknown and terminal outcomes.','Add authenticated callbacks, reconciliation and auditable recovery.']},
 'sd-data-01':{name:'Search over one billion documents',scope:'A derived text index with incremental updates, deletion and safe reindexing. Ranking details require separate product requirements.',requirements:['Document identity and version come from an authoritative source.','Define acceptable indexing lag and query latency.','Support updates, deletes and rebuilding without discarding ongoing changes.'],estimate:'Illustrative: 1B × 2 KB text ≈ 2 TB raw text. Index expansion, replicas, metadata and headroom must be measured; do not infer shard count from document count alone.',clarify:['What fields and languages are searched?','How frequent are updates and deletes?','Which queries and access controls must be supported?'],nodes:['Versioned source','Change stream','Partitioned indexer','Search shards + query API'],flows:['Capture changes','Consume + replay','Index / fan out queries'],contract:'Search(q, filters, cursor) → results; ingestion carries document ID, version and operation type, including delete.',data:'Document(id, version, owner/ACL); indexed fields and source checkpoints; tombstones or version tracking prevent resurrection by stale events.',failure:'On restart, replay from a durable checkpoint and reject older versions. Build a new index from a snapshot plus changes; cut over only after verification.',tradeoff:'More shards increase parallelism but also coordination, query fanout and operating cost. Compare routing by tenant with balanced shared shards.',walkthrough:['Capture a source change with its version.','Route to a partition and apply only a newer update/delete.','Query relevant shards and merge ranked results with authorization enforced.','Monitor lag and repair missing or stale records; reindex into a new generation.'],implementation:['Build a small index and measure representative queries.','Add versioned incremental updates and deletes.','Exercise replay, reindex catch-up and index-generation cutover.']},
};

export function designGuide(q:Question){
 const example=workedDesigns[q.id];
 const blueprint=example||blueprints[q.lessonId]||blueprints['sd-product'];
 const mode=q.lessonId==='sd-oop'?'Low-level design · OOP':q.lessonId==='sd-functions'?'Low-level design · functions':'High-level design';
 return {mode,example,blueprint,...designLevels[q.difficulty]};
}
export function designTemplate(q:Question){
 const g=designGuide(q);
 return `# ${q.title}\n\n${q.difficulty} · ${g.mode}\n\n${designSections.map(([title,prompt],i)=>`## ${i+1}. ${title}\n${prompt}\n\nMy answer: \n`).join('\n')}\n## Final interview summary\nI chose ___ because ___. The main risk is ___. I would change ___ when ___.`;
}
export function designBrief(q:Question){const g=designGuide(q);return `${q.prompt}\nDesign type: ${g.mode}. Difficulty: ${q.difficulty}.\nClarify:\n${g.blueprint.clarify.map(x=>'- '+x).join('\n')}\nAnswer structure:\n${designSections.map(([title,prompt],i)=>`${i+1}. ${title}: ${prompt}`).join('\n')}\nQuestion-specific focus: ${q.logic}`;}
