'use client';
import {useState} from 'react';
import {readingLibrary} from '@/lib/commute';
import {readingPractice} from '@/lib/learning-links';
import {dateKey,dayDate} from '@/lib/progress';
import {useStudio,Field,Attempts} from './StudioContext';
export function EveningBridgeAction({lessonId}:{lessonId:string}){const {get,patch,notice}=useStudio(),id=`bridge-${lessonId}`,r=get(id);return <button className="secondary" onClick={()=>{patch(id,{lesson:lessonId,plannedAt:dateKey(),due:r.fields.due||dayDate(dateKey(),1),recalled:'no'});patch('bridge-preference',{lesson:lessonId});notice('Added to Commute to practice. Tomorrow’s recall appears on Today.');}}>Save for evening practice →</button>}
export default function CommutePracticeBridge(){
 const {p,get,patch,submit,notice,read,practice}=useStudio(),[chosen,setChosen]=useState('');
 const recent=[...readingLibrary].sort((a,b)=>(p.reading?.[b.id]?.visitedAt||'').localeCompare(p.reading?.[a.id]?.visitedAt||'')),saved=get('bridge-preference').fields.lesson,lesson=readingLibrary.find(l=>l.id===(chosen||saved))||recent[0],id=`bridge-${lesson.id}`,r=get(id),linked=readingPractice(lesson);
 const due=Object.entries(p.studio||{}).filter(([id,r])=>id.startsWith('bridge-')&&id!=='bridge-preference'&&r.fields.due&&r.fields.due<=dateKey()&&r.fields.recalled!=='yes');
 return <section className="card"><h2>Commute → evening attempt → morning recall</h2><p>Choose a lesson, attempt a related problem without looking at the guide, then return tomorrow to explain the idea from memory.</p>{due.length>0&&<div className="info-box"><strong>{due.length} recalls due</strong>{due.map(([key,r])=><button className="secondary" key={key} onClick={()=>setChosen(r.fields.lesson||key.slice(7))}>{readingLibrary.find(l=>l.id===(r.fields.lesson||key.slice(7)))?.title||'Earlier lesson'} →</button>)}</div>}<label>Lesson<select value={lesson.id} onChange={e=>setChosen(e.target.value)}>{recent.map(l=><option key={l.id} value={l.id}>{l.title}{p.reading?.[l.id]?.readAt?' · read':''}</option>)}</select></label><div className="studio-flow"><span>Read / listen</span><span>Attempt without notes</span><span>Recall tomorrow</span></div><h3>{lesson.title}</h3><div className="button-row"><button className="secondary" onClick={()=>read(lesson.id)}>Read this lesson</button>{linked&&<button className="primary" onClick={()=>practice(linked.id)}>Related problem: {linked.title}</button>}</div><p>{linked?'Read the coding problem’s own contract carefully; it may differ from the lesson example.':`Evening task: ${lesson.exercise?.task||lesson.recall}`}</p><Field id={id} name="application" label="Evening: write your independent approach, result, and what got stuck"/><label>Recall date<input type="date" value={r.fields.due||dayDate(dateKey(),1)} onChange={e=>patch(id,{due:e.target.value})}/></label><button className="primary" onClick={()=>{if(!get(id).fields.application?.trim()){notice('Record your evening attempt first. Partial reasoning is welcome.');return}patch(id,{lesson:lesson.id,due:r.fields.due||dayDate(dateKey(),1),recalled:'no'});submit(id,'Evening practice saved; recall scheduled');}}>Save evening attempt</button><h3>Morning: close the reference first</h3><Field id={id} name="recall" label="Explain the approach, one example, and when it would fail"/><button className="primary" onClick={()=>{if(!get(id).fields.recall?.trim()){notice('Write what you recalled before completing the recall.');return}patch(id,{recalled:'yes',recalledAt:new Date().toISOString()});if(!submit(id,'Morning recall self-reviewed'))patch(id,{recalled:'no'});}}>Save morning recall</button><Attempts id={id}/></section>;
}
