'use client';
import {useState} from 'react';
import {dateKey,dayDate} from '@/lib/progress';
import {useStudio,Field,Attempts} from './StudioContext';
export default function MistakeRevisions(){
 const {p,get,patch,submit,notice}=useStudio(),[selected,setSelected]=useState(''),[filter,setFilter]=useState('All');
 const all=Object.entries(p.studio||{}).filter(([id])=>id.startsWith('mistake-')),active=all.filter(([,r])=>r.fields.deleted!=='yes'),due=active.filter(([,r])=>r.fields.resolved!=='yes'&&r.fields.retry&&r.fields.retry<=dateKey()),visible=filter==='Due'?due:active,id=visible.some(([key])=>key===selected)?selected:visible[0]?.[0]||'',r=id?get(id):null;
 function revise(days:number,resolved=false){if(!get(id).fields.retryAnswer?.trim()){notice('Write a fresh retry before rating your recall.');return}patch(id,{retry:dayDate(dateKey(),days),resolved:resolved?'yes':'no',lastRating:resolved?'Independent':`${days}-day retry`});if(!submit(id,'Mistake recall rated'))patch(id,{retry:r?.fields.retry||'',resolved:r?.fields.resolved||'no',lastRating:r?.fields.lastRating||''});}
 return <section className="card"><h2>Mistake notebook · {due.length} due</h2><p>Record the wrong assumption, correct it, then retrieve the idea later. Your old notes and attempts stay available.</p><div className="button-row"><button className="primary" onClick={()=>{const key=`mistake-${crypto.randomUUID()}`;patch(key,{title:'New learning mistake',retry:dayDate(dateKey(),1),resolved:'no'});setFilter('All');setSelected(key)}}>Add mistake</button><select aria-label="Mistake filter" value={filter} onChange={e=>setFilter(e.target.value)}><option>All</option><option>Due</option></select></div>{!visible.length&&<p>No mistakes match this view.</p>}{r&&<><label>Mistake<select value={id} onChange={e=>setSelected(e.target.value)}>{visible.map(([key,r])=><option key={key} value={key}>{r.fields.title} · {r.fields.resolved==='yes'?'resolved':r.fields.retry||'unscheduled'}</option>)}</select></label><Field id={id} name="title" label="Title" rows={1}/><Field id={id} name="cause" label="Where did I get stuck?"/><Field id={id} name="assumption" label="What incorrect assumption did I make?"/><details><summary>Show my correction and source after trying</summary><Field id={id} name="correction" label="Correct reasoning / implementation"/><Field id={id} name="source" label="Question, lesson or source" rows={2}/></details><Field id={id} name="retryAnswer" label="Fresh retry without reading the correction"/><label>Next retry<input type="date" value={r.fields.retry||''} onChange={e=>patch(id,{retry:e.target.value,resolved:'no'})}/></label><div className="button-row"><button className="secondary" onClick={()=>revise(1)}>Again · tomorrow</button><button className="secondary" onClick={()=>revise(3)}>With help · 3 days</button><button className="secondary" onClick={()=>revise(7)}>Good · 7 days</button><button className="secondary" onClick={()=>revise(14)}>Confident · 14 days</button><button className="secondary" onClick={()=>revise(14,true)}>Resolve · explained independently</button><button className="primary" onClick={()=>{if(!get(id).fields.cause?.trim()||!get(id).fields.correction?.trim()){notice('Add the cause and correction before saving a revision.');return}submit(id,'Mistake revision saved')}}>Save revision</button><button className="secondary" onClick={()=>patch(id,{deleted:'yes'})}>Archive</button></div><small>Ratings are self-assessed. A resolved mistake leaves the due queue; change its retry date to reopen it.</small><Attempts id={id}/></>}<details><summary>Archived mistakes</summary>{all.filter(([,r])=>r.fields.deleted==='yes').map(([id,r])=><button className="secondary" key={id} onClick={()=>{patch(id,{deleted:'no'});setFilter('All');setSelected(id)}}>Restore {r.fields.title}</button>)}</details></section>;
}
