'use client';
import {useEffect,useState} from 'react';
import {patternCases,patternNames,type PatternCase} from '@/lib/patterns';
import {dateKey,dayDate} from '@/lib/progress';
import {patternPractice} from '@/lib/learning-links';
import {useStudio,Field,Attempts} from './StudioContext';
import PatternGuide from './PatternGuide';

export default function PatternCoach({initialId,embedded=false}:{initialId?:string;embedded?:boolean}){
 const {get}=useStudio();const [selected,setSelected]=useState(initialId||patternCases.find(x=>!get(`pattern-${x.id}`).attempts.length)?.id||patternCases[0].id),[filter,setFilter]=useState('All'),[mode,setMode]=useState<'practice'|'learn'>('practice'),[guidePattern,setGuidePattern]=useState<(typeof patternNames)[number]>('Map');
 const x=patternCases.find(x=>x.id===selected)||patternCases[0],items=patternCases.filter(x=>filter==='All'||!get(`pattern-${x.id}`).attempts.length);
 return <div className="learning-coach"><section className="card"><span className="eyebrow">PATTERN DETECTIVE · THINK BEFORE CODING</span><h2>Which approach fits the constraints?</h2><p>{patternCases.length} scenarios across {patternNames.length} patterns. Learn with real-life examples and animated code walkthroughs, or choose an approach before revealing the reference. Some solutions combine patterns; a label alone does not prove understanding.</p>{!embedded&&<><label>Show<select value={filter} onChange={e=>setFilter(e.target.value)}><option>All</option><option>Unanswered</option></select></label><label>Scenario<select value={selected} onChange={e=>setSelected(e.target.value)}>{!items.some(i=>i.id===selected)&&<option value={selected}>{x.title} · current</option>}{items.map(c=><option key={c.id} value={c.id}>{c.title}{get(`pattern-${c.id}`).attempts.length?' · attempted':''}</option>)}</select></label></>}</section><div className="button-row pattern-mode"><button className="secondary" aria-pressed={mode==='practice'} onClick={()=>setMode('practice')}>Practice recognition</button><button className="secondary" aria-pressed={mode==='learn'} onClick={()=>{setGuidePattern(x.pattern);setMode('learn')}}>Learn why & when · visual guides</button></div>{mode==='learn'?<section className="card"><label>Explore a pattern<select value={guidePattern} onChange={e=>setGuidePattern(e.target.value as typeof guidePattern)}>{patternNames.map(name=><option key={name}>{name}</option>)}</select></label><PatternGuide key={guidePattern} pattern={guidePattern}/></section>:<PatternRound key={x.id} x={x} embedded={embedded}/>}{!embedded&&mode==='practice'&&<button className="primary" onClick={()=>{const at=patternCases.indexOf(x),rotated=[...patternCases.slice(at+1),...patternCases.slice(0,at)];setSelected((rotated.find(c=>!get(`pattern-${c.id}`).attempts.length)||rotated[0]).id)}}>Next scenario →</button>}</div>;
}
function PatternRound({x,embedded}:{x:PatternCase;embedded:boolean}){
 const {get,patch,submit,notice,read,practice}=useStudio(),id=`pattern-${x.id}`,r=get(id);
 const [reveal,setReveal]=useState(false),[hint,setHint]=useState(false),[step,setStep]=useState(0),[playing,setPlaying]=useState(false);
 useEffect(()=>{if(!playing)return;if(step===x.flow.length-1){setPlaying(false);return}const t=setTimeout(()=>setStep(n=>n+1),2500);return()=>clearTimeout(t)},[playing,step,x.flow.length]);
 const linked=patternPractice(x.pattern);
 function check(){if(!r.fields.choice||!r.fields.reason?.trim()){notice('Choose an approach and write why before checking.');return}patch(id,{question:x.prompt,input:x.input,reference:x.pattern});if(submit(id,r.fields.choice===x.pattern?'Matches reference choice; reasoning needs self-review':'Compare your alternative with the reference',hint||reveal?1:0))setReveal(true);}
 return <section className="card"><h3>{x.title}</h3><p>{x.prompt}</p><pre>Input: {x.input}{'\n'}Expected output: {x.output}</pre><fieldset><legend>Your best-fit approach</legend><div className="pattern-choices">{patternNames.map(name=><label key={name}><input type="radio" name={id} checked={r.fields.choice===name} onChange={()=>patch(id,{choice:name})}/>{name}</label>)}</div></fieldset><Field id={id} name="reason" label="Which constraint is the clue? What will you remember?" rows={3}/><div className="button-row"><button className="primary" onClick={check}>Save choice & reveal</button><button className="secondary" onClick={()=>setHint(true)}>One clue</button></div>{hint&&<p className="info-box">{x.cue}</p>}{reveal&&<><h3>Reference: {x.pattern}</h3><p><strong>The clue in this question:</strong> {x.cue}</p><p>{x.why}</p><p><strong>Boundary / alternative:</strong> {x.transfer}</p><p><strong>Trap:</strong> {x.trap}</p><p>{x.cost}</p><div className="pattern-trace"><div className="array-story-track" aria-hidden="true"><span style={{left:`${step/(x.flow.length-1)*100}%`}}>🕵️</span></div><ol>{x.flow.map((text,i)=><li key={i} aria-current={step===i?'step':undefined}><button onClick={()=>{setPlaying(false);setStep(i)}}>{i+1}. {text}</button></li>)}</ol></div><div className="button-row"><button className="secondary" disabled={!step} onClick={()=>{setPlaying(false);setStep(n=>n-1)}}>Previous</button><button className="secondary" onClick={()=>{if(step===x.flow.length-1)setStep(0);setPlaying(v=>!v)}}>{playing?'Pause':'Play trace'}</button><button className="secondary" disabled={step===x.flow.length-1} onClick={()=>{setPlaying(false);setStep(n=>n+1)}}>Next</button></div><small>Illustrated state sequence; your code is not executed here.</small><details className="pattern-deep-dive"><summary>Why this pattern? Methods, real-life example & animated code</summary><PatternGuide key={x.pattern} pattern={x.pattern}/></details><Field id={id} name="transfer" label="Change one constraint. Would your approach still work?"/><button className="secondary" onClick={()=>{if(get(`mistake-pattern-${x.id}`).updatedAt){notice('This scenario is already in Mistake notebook. Its existing notes were kept.');return}patch(`mistake-pattern-${x.id}`,{title:x.title,source:`Pattern detective: ${x.id}`,cause:r.fields.reason||'',assumption:r.fields.choice||'',correction:x.why,retry:dayDate(dateKey(),1),resolved:'no',deleted:'no'});notice('Added to Mistake notebook with a retry tomorrow. Existing attempt history is kept.')}}>Add this to my mistake notebook</button></>}{!embedded&&<button className="secondary" onClick={()=>read(`pattern-reading-${x.id}`)}>Read this on my commute</button>}{linked&&<button className="secondary" onClick={()=>practice(linked.id)}>Related coding practice: {linked.title}</button>}<Attempts id={id}/></section>;
}
