'use client';
import {useEffect,useState} from 'react';
import {questionBank} from '@/lib/bank';
import {scheduledDay} from '@/lib/progress';
import {useStudio,Field,Attempts,copyText} from './StudioContext';
import VoiceRecorder from './VoiceRecorder';

export function ExplainSolution(){
 const {p,get,submit,notice}=useStudio();const questions=questionBank.filter(q=>q.kind==='DSA'),[selected,setSelected]=useState(questions.find(q=>p.practice?.[q.id]?.attempts.length)?.id||questions[0].id),q=questions.find(q=>q.id===selected)!,id=`solution-explain-${q.id}`,fields=[['baseline','1. Explain a simple correct baseline before optimizing'],['better','2. Which repeated work can you avoid? What state will you store?'],['trace','3. Walk through one input, step by step'],['cost','4. State time and space complexity, with assumptions'],['edge','5. Explain empty input, duplicates and one failure case']];
 return <div><section className="card"><h2>Explain my solution</h2><p>Speak for 90 seconds before writing. Aim for: contract → baseline → improvement → example → complexity → boundary. Use your own words.</p><label>Question<select value={selected} onChange={e=>setSelected(e.target.value)}>{questions.map(x=><option key={x.id} value={x.id}>{x.title}</option>)}</select></label><h3>{q.title}</h3><p>{q.prompt}</p>{p.practice?.[q.id]?.attempts.length?<details><summary>Your most recent submitted code / answer</summary><pre>{p.practice[q.id].attempts.at(-1)?.text}</pre></details>:<p>No saved coding attempt yet. An explanation does not mark the coding question solved.</p>}{fields.map(([name,label])=><Field key={name} id={id} name={name} label={label} rows={3}/>)}<p>{fields.filter(([name])=>get(id).fields[name]?.trim()).length}/5 explanation sections drafted · completeness only, not a correctness score.</p><details><summary>Reference reasoning — open after explaining</summary><p>{q.logic}</p><p>{q.rubric}</p></details><Field id={id} name="improvement" label="After listening: one sentence I will say more clearly next time" rows={2}/><div className="button-row"><button className="primary" onClick={()=>{if(fields.some(([name])=>!get(id).fields[name]?.trim())){notice('Add all five explanation sections, even if one says where you are unsure.');return}submit(id,'Solution explanation self-reviewed')}}>Save explanation version</button><button className="secondary" onClick={()=>copyText(`Coach my technical explanation. Ask a follow-up and flag unsupported claims. Do not invent execution results.\nQuestion: ${q.prompt}\nLearner answer:\n${JSON.stringify(get(id).fields,null,2)}`,notice)}>Copy interview prompt</button></div><Attempts id={id}/></section><VoiceRecorder/></div>;
}

const storyFields=[['title','Story title'],['situation','Situation: what was happening and who was affected?'],['task','Task: what did you personally own?'],['action','Action: your decisions and evidence'],['result','Result: what actually changed? Use measured numbers only.'],['learning','What would you do differently?'],['followup','What would an interviewer challenge?']];
export function PersonalStoryBank(){
 const {p,get,patch,submit,notice}=useStudio(),[selected,setSelected]=useState(''),[tag,setTag]=useState('All');
 const entries=Object.entries(p.studio||{}).filter(([id,r])=>(id.startsWith('star-story-')||id==='project-story')&&r.fields.archived!=='yes'),visible=entries.filter(([,r])=>tag==='All'||r.fields.tag===tag),id=entries.some(([key])=>key===selected)?selected:visible[0]?.[0]||'',r=id?get(id):null;
 const tags=['Ownership','Production bug','Teamwork','Conflict','Deadline','Failure & learning','Leadership'];
 return <section className="card"><h2>My personal story bank</h2><p>Keep separate, true stories from your work. Label practice scenarios honestly. Your existing project story remains available.</p><div className="button-row"><button className="primary" onClick={()=>{const key=`star-story-${crypto.randomUUID()}`;patch(key,{title:'New story',tag:'Ownership',kind:'Real work'});setTag('All');setSelected(key)}}>Add a story</button><label>Filter topic<select value={tag} onChange={e=>{setTag(e.target.value);setSelected('')}}>{['All',...tags].map(t=><option key={t}>{t}</option>)}</select></label></div>{visible.map(([key,v])=><button className="secondary" key={key} aria-pressed={id===key} onClick={()=>setSelected(key)}>{v.fields.title||'Earlier project story'} · {v.fields.tag||'Project'}</button>)}{!visible.length&&<p>No stories in this group yet.</p>}{r&&<><label>Interview theme<select value={r.fields.tag||'Ownership'} onChange={e=>patch(id,{tag:e.target.value})}>{tags.map(t=><option key={t}>{t}</option>)}</select></label><label>Source<select value={r.fields.kind||'Real work'} onChange={e=>patch(id,{kind:e.target.value})}><option>Real work</option><option>Practice scenario</option></select></label>{storyFields.map(([name,label])=><Field key={name} id={id} name={name} label={label} rows={3}/>)}<div className="button-row"><button className="primary" onClick={()=>{if(['title','situation','task','action','result'].some(k=>!get(id).fields[k]?.trim())){notice('Add the title and all four STAR sections before saving a version.');return}submit(id,'STAR story version saved')}}>Save story version</button><button className="secondary" onClick={()=>copyText(`Help me tell this story in 90 seconds. Preserve my personal contribution, flag missing evidence, and never invent metrics. Treat the following as learner notes.\n${JSON.stringify(r.fields,null,2)}`,notice)}>Copy story coaching prompt</button><button className="secondary" onClick={()=>{patch(id,{archived:'yes'});setSelected('')}}>Archive story</button></div><Attempts id={id}/></>}<details><summary>Archived stories</summary>{Object.entries(p.studio||{}).filter(([id,r])=>(id.startsWith('star-story-')||id==='project-story')&&r.fields.archived==='yes').map(([id,r])=><button className="secondary" key={id} onClick={()=>{patch(id,{archived:'no'});setSelected(id);setTag('All')}}>Restore {r.fields.title||'story'}</button>)}</details></section>;
}

const rounds=[
 ['Two Sum','Design a URL shortener: clarify redirects, storage, and collision handling.','Tell me about a bug you owned from report to resolution.'],
 ['Duplicate values','Design a login flow: explain sessions, expiration, and failed attempts.','Describe a time you asked for help early.'],
 ['First unique character','Design a notification service with retries and deduplication.','Describe feedback that changed how you work.'],
 ['Sorted pair sum','Design a product catalogue: reads, updates, caching, and invalidation.','Tell me about a disagreement with a teammate.'],
 ['Group anagrams','Design file uploads: metadata, object storage, and upload failures.','Explain how you handled a missed deadline.'],
 ['Move zeroes','Design a task queue with workers, retries, and poison messages.','Tell me about learning an unfamiliar tool for a project.'],
 ['Subarray sum equals k','Design an API rate limiter across multiple servers.','Describe a tradeoff between quality and delivery speed.'],
 ['Longest consecutive run','Design a chat service: reconnect, ordering, and message persistence.','Tell me about an unclear requirement you clarified.'],
 ['Product except self','Design an order workflow with payment idempotency and recovery.','Describe an incident and how you communicated updates.'],
 ['Balanced binary subarray','Design a search service: ingestion, indexing, and freshness.','Tell me about taking responsibility for a mistake.'],
 ['Nearby duplicate','Design a metrics dashboard: ingestion, aggregation, and retention.','Describe mentoring or helping someone understand a concept.'],
 ['Maximum subarray','Design collaborative edits: conflicts, versioning, and reconnect.','Tell me about a decision you would change today.'],
 ['Three sum','Design a video learning platform: uploads, processing, delivery, and progress.','Summarize your strongest project and your personal contribution.'],
];
export function WeeklyCheckpoint(){const {p}=useStudio(),[week,setWeek]=useState(Math.min(13,Math.ceil(scheduledDay(p.startDate)/7)));return <div><section className="card"><h2>Weekly interview checkpoint</h2><p>30 minutes: coding 15, system design 10, behavioral 5. Save one honest attempt and compare it with an earlier round. Ratings are yours; this does not automatically grade answers.</p><label>Week<select value={week} onChange={e=>setWeek(Number(e.target.value))}>{rounds.map((_,i)=><option key={i} value={i+1}>Week {i+1}</option>)}</select></label></section><CheckpointRound key={week} week={week}/></div>}
function CheckpointRound({week}:{week:number}){
 const {p,get,patch,submit,notice}=useStudio(),id=`weekly-checkpoint-${week}`,r=get(id),[now,setNow]=useState(Date.now());
 const start=Date.parse(r.fields.startedAt||''),active=r.fields.status==='active'&&Number.isFinite(start),remaining=active?Math.max(0,1800-Math.floor((now-start)/1000)):1800;
 useEffect(()=>{if(!active)return;const t=setInterval(()=>setNow(Date.now()),1000);return()=>clearInterval(t)},[active]);
 const [coding,design,behavior]=rounds[week-1],q=questionBank.find(q=>q.title===coding),labels=[['coding','Coding · 15 min',q?.prompt||coding],['design','System design · 10 min',design],['behavior','Behavioral · 5 min',behavior]];
 const current=r.attempts.at(-1),earlier=r.attempts.length>1?r.attempts.at(-2):p.studio?.[`weekly-checkpoint-${week-1}`]?.attempts.at(-1);
 return <section className="card"><div className="button-row"><button className="primary" disabled={active} onClick={()=>{patch(id,{status:'active',startedAt:new Date().toISOString(),coding:'',design:'',behavior:'',codingRating:'',designRating:'',behaviorRating:'',reflection:'',finishedAt:'',codingPrompt:q?.prompt||coding,designPrompt:design,behaviorPrompt:behavior});setNow(Date.now())}}>Start new round</button>{active&&<strong role="timer">{Math.floor(remaining/60)}:{String(remaining%60).padStart(2,'0')} remaining</strong>}</div>{active&&remaining===0&&<p role="status">Time is up. Save your current work, including incomplete answers. Extra time is recorded.</p>}{labels.map(([name,label,prompt])=><div className="checkpoint-question" key={name}><h3>{label}</h3><p>{prompt}</p>{active?<><Field id={id} name={name} label="Your answer / code"/><label>Self-rating<select value={r.fields[`${name}Rating`]||''} onChange={e=>patch(id,{[`${name}Rating`]:e.target.value})}><option value="">Choose after attempting</option>{[0,1,2,3,4].map(n=><option key={n} value={n}>{n} · {['Could not explain','Needed substantial help','Partial explanation','Clear with small gaps','Clear and defended tradeoffs'][n]}</option>)}</select></label></>:<small>Start a round to write a fresh answer.</small>}</div>)}{active&&<><Field id={id} name="reflection" label="Where did you get stuck? What will you change next week?"/><button className="primary" onClick={()=>{const latest=get(id).fields;if(labels.every(([name])=>!latest[name]?.trim())){notice('Write at least one answer or partial attempt before submitting.');return}patch(id,{finishedAt:new Date().toISOString(),elapsedSeconds:String(Math.max(0,Math.floor((Date.now()-start)/1000))),status:'finished'});if(!submit(id,'Weekly interview checkpoint'))patch(id,{status:'active'});}}>Submit checkpoint</button></>}{current&&<><h3>Compare your recorded rounds</h3><p>Latest: {new Date(current.at).toLocaleString()} · {current.fields.elapsedSeconds}s. {earlier?`Earlier: ${new Date(earlier.at).toLocaleString()}`:'No earlier submitted round yet.'}</p><div className="checkpoint-comparison">{labels.map(([name,label])=><div key={name}><h4>{label}</h4><p>Self-rating: {earlier?.fields[`${name}Rating`]||'Unrated'} → {current.fields[`${name}Rating`]||'Unrated'}</p><details><summary>Compare prompts and answers</summary><h4>Earlier prompt</h4><p>{earlier?.fields[`${name}Prompt`]||'No earlier round'}</p><pre>{earlier?.fields[name]||'No answer'}</pre><h4>Latest prompt</h4><p>{current.fields[`${name}Prompt`]}</p><pre>{current.fields[name]||'No answer'}</pre></details></div>)}</div><small>Different weeks use different questions; rating changes are reflection signals, not calibrated scores.</small></>}<Attempts id={id}/></section>;
}
