'use client';
import {dateKey,dayDate} from '@/lib/progress';
import {memo,useCallback,useEffect,useMemo,useRef,useState} from 'react';
import {incidents,comparisons,sqlExercises,sqlSeed} from '@/lib/studio-content';
import {useStudio,Field,Attempts} from './StudioContext';

export {default as PuzzleLab} from './PuzzleWorkbench';

type SqlResult={columns:string[];rows:(string|number|null)[][];truncated:boolean;error?:string};
export function SqlPlayground(){const {get,patch,submit}=useStudio(),[exercise,setExercise]=useState(0),[result,setResult]=useState<SqlResult|null>(null),[running,setRunning]=useState(false);const worker=useRef<Worker|null>(null),timeout=useRef<ReturnType<typeof setTimeout>|null>(null),q=sqlExercises[exercise],id=`sql-lab-${q.id}`,r=get(id),query=r.fields.query??'SELECT * FROM employees;';
 function stop(){worker.current?.terminate();worker.current=null;if(timeout.current)clearTimeout(timeout.current);setRunning(false)}
 useEffect(()=>()=>{worker.current?.terminate();if(timeout.current)clearTimeout(timeout.current)},[]);
 function run(){stop();setResult(null);setRunning(true);let w:Worker;try{w=new Worker('/sql-worker.js')}catch{setRunning(false);setResult({columns:[],rows:[],truncated:false,error:'This browser could not start the SQL worker.'});return}worker.current=w;timeout.current=setTimeout(()=>{stop();setResult({columns:[],rows:[],truncated:false,error:'Query stopped after 8 seconds. Simplify it and retry.'})},8000);w.onerror=()=>{stop();setResult({columns:[],rows:[],truncated:false,error:'Unable to load the local SQL engine. Reload and try again.'})};w.onmessage=e=>{const data=e.data as SqlResult;stop();setResult(data);if(!data.error){const normalize=(rows:unknown[][])=>rows.map(row=>JSON.stringify(row)).sort().join('\n'),matched=!data.truncated&&(q.id==='rank'?JSON.stringify(data.rows)===JSON.stringify(q.expected):normalize(data.rows)===normalize(q.expected));patch(id,{query,lastResult:JSON.stringify(data),matched:String(matched)});submit(id,matched?'Sample rows match':'Query executed; sample rows differ',Number(r.fields.solution==='yes'))}};w.postMessage({sql:query,seed:sqlSeed})}
 return <section className="card"><h2>SQL playground</h2><p>Real SQLite execution in an isolated browser worker. Fresh sample data on each run; your Supabase database is never queried here. PostgreSQL-specific syntax may differ.</p><label className="studio-field">Exercise<select value={exercise} disabled={running} onChange={e=>{setExercise(Number(e.target.value));setResult(null)}}>{sqlExercises.map((x,i)=><option key={x.id} value={i}>{x.title}</option>)}</select></label><p>{q.task}</p><details><summary>Sample tables and seed data</summary><pre>{sqlSeed}</pre></details><label className="studio-field">Your SQL<textarea disabled={running} value={query} maxLength={10000} rows={7} onChange={e=>patch(id,{query:e.target.value})}/></label><div className="button-row"><button className="primary" disabled={running} onClick={run}>{running?'Running…':'Run query'}</button>{running&&<button className="secondary" onClick={stop}>Stop</button>}<button className="secondary" disabled={running} onClick={()=>patch(id,{solution:'yes'})}>Reveal example query</button></div>{r.fields.solution==='yes'&&<pre>{q.starter}</pre>}<details><summary>Expected rows</summary><pre>{JSON.stringify(q.expected,null,2)}</pre></details>{result?.error&&<p role="alert">{result.error}</p>}{result&&!result.error&&<><p role="status">{r.fields.matched==='true'?'Sample rows match. Explain why your query works.':'Rows differ from the exercise target. Compare columns, duplicates and filters.'}{result.truncated?' Output limited to 200 rows.':''}</p><div className="studio-table"><table><thead><tr>{result.columns.map((c,i)=><th key={i}>{c}</th>)}</tr></thead><tbody>{result.rows.map((row,i)=><tr key={i}>{row.map((v,j)=><td key={j}>{v===null?'NULL':String(v)}</td>)}</tr>)}</tbody></table></div></>}<Field id={id} name="explanation" label="Explain the filter, join cardinality or grouping"/><Attempts id={id}/></section>;
}

const RenderChild=({count,options,onCommit}:{count:number;options:{query:string};onCommit:(s:string)=>void})=>{
 // Effects run after a committed render in production too; Profiler callbacks
 // are disabled in standard production React bundles.
 useEffect(()=>{onCommit(`Committed child: count=${count}, query=${options.query}`)});
 return <div className="studio-render-child">Child UI: count {count} · query “{options.query}”</div>;
};
const MemoChild=memo(RenderChild);
const RenderSandbox=memo(function RenderSandbox({onCommit}:{onCommit:(s:string)=>void}){const [count,setCount]=useState(0),[theme,setTheme]=useState(0),[query,setQuery]=useState('apple'),[memoized,setMemoized]=useState(true),[stable,setStable]=useState(true);const stableOptions=useMemo(()=>({query}),[query]),options=stable?stableOptions:{query};const Child=memoized?MemoChild:RenderChild;return <div><div className="studio-controls"><label><input type="checkbox" checked={memoized} onChange={e=>setMemoized(e.target.checked)}/>React.memo child</label><label><input type="checkbox" checked={stable} onChange={e=>setStable(e.target.checked)}/>Stable options object</label><label>Query<input value={query} onChange={e=>setQuery(e.target.value)}/></label></div><div className="button-row"><button className="secondary" onClick={()=>setTheme(t=>t+1)}>Unrelated parent update ({theme})</button><button className="primary" onClick={()=>setCount(c=>c+1)}>Change child count</button></div><Child count={count} options={options} onCommit={onCommit}/></div>});
export function RenderExplorer(){const [logs,setLogs]=useState<string[]>([]),report=useCallback((s:string)=>setLogs(old=>[s,...old].slice(0,20)),[]);const {submit}=useStudio();return <section className="card"><h2>React render explorer</h2><p>Actual React components with an effect log after committed child renders. Try an unrelated update with stable props, then create a new options object. Development mode and remounts can add events; memoization is not a correctness guarantee.</p><RenderSandbox onCommit={report}/><h3>Child effect log</h3><pre>{logs.join('\n')||'No commits recorded yet.'}</pre><Field id="render-explorer" name="prediction" label="Before clicking: which child update do you expect?"/><Field id="render-explorer" name="finding" label="What changed when object identity changed?"/><button className="primary" onClick={()=>submit('render-explorer','Observed React experiment')}>Save experiment</button><Attempts id="render-explorer"/></section>}

export function RequestJourney(){const {get,patch,submit}=useStudio(),id='request-journey',r=get(id),[step,setStep]=useState(0);const failure=r.fields.failure||'none',stages=['Client','Validate','Authenticate','Authorize','Business rule','Database','Response'],failAt:Record<string,number>={invalid:1,expired:2,forbidden:3,timeout:5},blocked=failAt[failure];const current=blocked!==undefined?Math.min(step,blocked):step;return <section className="card"><h2>Follow a backend request</h2><p>Illustrated POST /orders. This traces a supplied scenario; it does not send a request.</p><label className="studio-field">Change one boundary<select value={failure} onChange={e=>{patch(id,{failure:e.target.value});setStep(0)}}><option value="none">Valid request</option><option value="invalid">Invalid quantity</option><option value="expired">Expired token</option><option value="forbidden">Wrong resource owner</option><option value="timeout">Database response timeout</option></select></label><div className="studio-flow">{stages.map((s,i)=><span className={i===current?'chosen':''} key={s}>{i+1}. {s}</span>)}</div><pre>{JSON.stringify({requestId:'demo-42',body:{quantity:failure==='invalid'?-1:2},stage:stages[current],status:blocked===current?({invalid:400,expired:401,forbidden:403,timeout:504}[failure]||500):current===6?201:'processing'},null,2)}</pre>{blocked===current&&<p className="studio-callout">{failure==='timeout'?'The response timed out. The write may have committed; reconcile using the operation identity before retrying.':'Stop here and return the defined error. Do not continue to the write.'}</p>}<button className="primary" disabled={current===6||blocked===current} onClick={()=>setStep(s=>s+1)}>Next boundary</button><Field id={id} name="explanation" label="Explain what crosses each boundary and what must not be logged"/><button className="secondary" onClick={()=>submit(id,'Request flow explained')}>Save explanation</button><Attempts id={id}/></section>}

export function IncidentRoom(){const {get,patch,submit}=useStudio(),[n,setN]=useState(0),q=incidents[n],id=`incident-${q.id}`,r=get(id);return <section className="card"><h2>Production incident room</h2><label className="studio-field">Supplied scenario<select value={n} onChange={e=>setN(Number(e.target.value))}>{incidents.map((x,i)=><option key={x.id} value={i}>{x.title}</option>)}</select></label><pre>{q.logs.join('\n')}</pre><Field id={id} name="hypothesis" label="What does the evidence support? What remains unknown?"/><div className="studio-choices">{q.options.map((x,i)=><label key={i}><input type="radio" name={id} checked={r.fields.choice===String(i)} onChange={()=>patch(id,{choice:String(i),revealed:''})}/>{x}</label>)}</div><button className="primary" disabled={!r.fields.choice} onClick={()=>{patch(id,{revealed:'yes'});submit(id,r.fields.choice===String(q.correct)?'Evidence-based action selected':'Action needs revision',Number(r.fields.clue==='yes'))}}>Submit investigation</button><details onToggle={e=>{if(e.currentTarget.open&&r.fields.clue!=='yes')patch(id,{clue:'yes'})}}><summary>Need a clue?</summary><p>{q.clue}</p></details>{r.fields.revealed&&<div className="studio-callout"><p>{q.explain}</p><h3>Interviewer interruption</h3><p>{q.interrupt}</p><Field id={id} name="followup" label="Adapt your recovery plan"/><details><summary>Compare your reasoning</summary><p>{q.follow}</p></details></div>}<Attempts id={id}/></section>}

export function CompareLab(){const {submit}=useStudio(),[n,setN]=useState(0),q=comparisons[n],id=`compare-${n}`;return <section className="card"><h2>Compare concepts</h2><select aria-label="Concept comparison" value={n} onChange={e=>setN(Number(e.target.value))}>{comparisons.map((x,i)=><option key={x.title} value={i}>{x.title}</option>)}</select><div className="studio-columns"><div className="studio-callout"><p>{q.left}</p></div><div className="studio-callout"><p>{q.right}</p></div></div><p>{q.example}</p><Field id={id} name="decision" label="Which would you choose in your project, and why?"/><details><summary>Decision guide</summary><p>{q.decision}</p></details><button className="primary" onClick={()=>submit(id,'Tradeoff explained')}>Save comparison</button><Attempts id={id}/></section>}
