'use client';
import {useState} from 'react';
import {useStudio,Field,Attempts} from './StudioContext';
const concepts=[
{title:'Closure',simple:'A function can keep using variables from where it was created.',analogy:'Think of a function holding a key to its original workroom. The room’s contents can change; the key is not a frozen photograph.',example:'A counter factory creates count=0 and returns increment/read functions. Functions from one call share that count. Another factory call has a separate count.',question:'If two functions come from the same factory call, do they share its count?',answer:'Yes. They share that call’s lexical binding.'},
{title:'useMemo',simple:'React can reuse a calculation result when its dependencies have not changed.',analogy:'Keep a previous calculation beside its input labels. If the labels change, calculate again; never rely on the note as permanent storage.',example:'Filtering the same items array with the same query may reuse a result. Creating a new dependency object on every render can prevent reuse.',question:'Does useMemo stop the component itself from rendering?',answer:'No. It reuses a calculation within rendering; it is a performance optimization.'},
{title:'SQL WHERE',simple:'Keep rows whose condition is TRUE.',analogy:'A filter admits each row only if it passes its rule. An unknown answer does not count as a pass.',example:'For salaries 70000, 45000 and NULL, salary > 50000 keeps only 70000.',question:'Why does salary = NULL not find missing salaries?',answer:'Equality with NULL is UNKNOWN. Use salary IS NULL.'},
{title:'ACID',simple:'A transaction groups changes and defines how committed work behaves under concurrency and failures.',analogy:'A transfer needs a debit and a credit to belong to one operation. Keeping only half breaks the intended rule.',example:'Move 20 from A to B: commit both changes or roll back both. Choose an isolation strategy for concurrent transfers.',question:'Does a transaction automatically check sufficient funds?',answer:'No. Business invariants still need appropriate checks and constraints.'},
{title:'Two Sum',simple:'For each number, ask whether you already saw the number needed to reach the target.',analogy:'Keep a notebook of earlier values rather than rereading the whole list every time.',example:'Target 9: record 2 at index 0. At 7, the needed 2 is already recorded, so return [0,1].',question:'Why check the map before inserting the current item?',answer:'To avoid returning the current index twice.'},
];
export default function UnderstandingCoach(){const {get,patch,submit}=useStudio(),[index,setIndex]=useState(0),[level,setLevel]=useState(0),q=concepts[index],id=`understand-${index}`,r=get(id);return <section className="card"><h2>I don’t understand yet</h2><p>Choose where you got stuck. Work through one small explanation, then answer one guiding question.</p><label className="studio-field">Concept<select value={index} onChange={e=>{setIndex(Number(e.target.value));setLevel(0)}}>{concepts.map((q,i)=><option key={q.title} value={i}>{q.title}</option>)}</select></label><div className="studio-flow">{['Simpler explanation','Everyday analogy','Small example','Guiding question'].map((title,i)=><button key={title} className={level===i?'chosen':''} onClick={()=>setLevel(i)}>{i+1}. {title}</button>)}</div><p className="studio-callout">{[q.simple,q.analogy,q.example,q.question][level]}</p><button className="secondary" disabled={level===3} onClick={()=>setLevel(n=>n+1)}>Next small step</button><Field id={id} name="answer" label="Explain it in your own words"/><button className="primary" disabled={!r.fields.answer?.trim()} onClick={()=>{patch(id,{revealed:'yes'});submit(id,'Simplified concept attempted',level)}}>Save explanation</button>{r.fields.revealed&&<p>{q.answer}</p>}<Attempts id={id}/></section>}
